### ISSUE TITLE
Multiple step support for CLI

### ISSUE THREAD

**Issue by ccpandhare** [publiclab/image-sequencer#100]
## First Timers Only

Hi, this is a first-timers-only issue. This means this has been worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before.**

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/image-sequencer/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3A%22help%20wanted%22%20) issues. Thanks!

## The Problem

We recently added a basic Command Line Interface (CLI) to Image Sequencer, but it isn't complete yet. Currently there is no way for the user to specify multiple steps, which is abd, because that's Image Sequencer's main function! To process image sequenctially in multiple steps.

## The Solution

An ideal solution would be to accept a string of spaced steps.

Currently this is how the steps are added:

```
$ ./index.js -i [PATH_TO_IMAGE] -s step-name
```

If we do this:

```
$ ./index.js -i [PATH_TO_IMAGE] -s step-name-1 step-name-2 ...
```

We can parse `program.step` (Which would basically be "step-name-1 step-name-2") into an array of steps `["step-name-1","step-name-2"]`.

Then, redefine `program.step` as this array.

Image Sequencer accepts an array of steps as an input, so everything will work fine.

## Further work which would be required

So far, so good. Now we'll also have to identify how we shall pass in the inputs for different steps using this method!

Have a look at #97 for more details!

## Steps to Fix
- [ ] Claim this issue with a comment here, and ask for any issues/clarifications.
- [ ] Clone this repository locally.
- [ ] Try to fix the issue as described above, but even before you have completed doing so, you can:
- [ ] Commit your work and initiate a Pull Request (Mark it as `work-needed` if you haven't completed the work on the issue)

**Comment by ROODAY** [comment]
Claimed!

**Comment by ccpandhare** [comment]
I think the user input breaks for multiple steps.

```
➜  image-sequencer git:(master) ./index.js -i examples/images/IS-QR.png -s crop
crop : x : X-position (measured from left) from where cropping starts
crop : Enter a value for x : 0
crop : y : Y-position (measured from top) from where cropping starts
crop : Enter a value for y : 0
crop : w : Width of crop
crop : Enter a value for w : 100
crop : h : Height of crop
crop : Enter a value for h : 100
Files will be exported to "./output/"
➜  image-sequencer git:(master) ./index.js -i examples/images/IS-QR.png -s decode-qr crop
Files will be exported to "./output/"
[decode-qr]: qrval = http://github.com/publiclab/image-sequencer
```

Maybe the UI could be better, with less clutter, and also telling the user about default input values

Somewhat like this:

```
➜  image-sequencer git:(master) ./index.js -i examples/images/IS-QR.png -s crop
[crop]: x: __DESC__
            y: __DESC__
            w: __DESC__
            h: __DESC__
[crop]: Enter a value for x : (integer, default: 0) __
[crop]: Enter a value for y : (integer, default: 0) __
[crop]: Enter a value for w : (integer, default: half of image width) __
[crop]: Enter a value for h : (integer, default: half of image height) __

Would you like to take this up?
```

**Comment by ROODAY** [comment]
Will do!
