### ISSUE TITLE
Writing more UI tests (with guidance)

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#1000]
We need more UI tests to protect and stabilize the UI behaviors of the demo, so that we know when refactors and new features break things. This will build overall stability in the system and let us do more advanced work without chasing bugs. Bugs are natural! No worries! But we can catch them before they get published using more tests. 

Our UI tests can be found here: https://github.com/publiclab/image-sequencer/tree/main/test/ui/spec

Instead of testing core functions with unit tests, they set up an HTML environment and simulate someone actually using the buttons and UI. 

So in one of these test files, or a new one, we should be able to begin interacting with a full Sequencer UI, by selecting things in the Add Modules select, clicking buttons with `$('.btn .uniqueClass').trigger('click');` (or something like that) and then using assertions to test that things really happened, something like this:

```js
    expect($('.step').length).toBe(10); // number of steps shown has changed
```

This way, we can have more confidence in the UI not breaking. We'd love help with this! I know @Harshithpabbati asked a bit about how this might work. Want to try it out? 

Once we have one simple test like this, we can use it as a model to add more like it, and get to higher test coverage of our UI code!

**Comment by jywarren** [comment]
For example, we should be able to input settings using something like `$('.step .step-2 input.brightness').val(24)` -- 

But first, we'll need to add more unique CSS classnames so that we can make calls like that in jQuery. Right now, they're too generic:

```html
<div class="panel-body cal collapse in">
            <div class="row step">
                <div class="col-md-4 details">
                  <h3><span class="load-spin" style="display:none;"><i class="fa fa-circle-o-notch fa-spin"></i></span></h3>
                  <div class="cal collapse in"><p><i>Change the contrast of the image by given value</i></p></div>
                <div class="row" name="contrast">
                    <div class="det cal collapse in">
                           <label for="contrast">contrast for the new image, typically -100 to 100</label>
                           <input class="form-control target" type="range" name="contrast" value="70" placeholder="" min="-100" max="100" step="1">
```

**Comment by VibhorCodecianGupta** [comment]
I'd like to take this up. This would be kind of a quest, adding UI tests as we go deeper into implementing more features for IS. Would like to start with some basic tests

**Comment by jywarren** [comment]
:-) great! And love the idea of a test-quest! You might like this fun
project i once did:

http://pxlqst.com/test (https://github.com/jywarren/pxlqst)

**Comment by VibhorCodecianGupta** [comment]
Nice! I'll get on with improving some tests I already wrote while setting up the UI testing harness.
Rendering of buttons and steps should be a nice starting point.

Also, apologies for shamelessly plugging in my proposal, but trying to make it as comprehensive as possible. What are the chances I'll get reviewed, should I submit one in a couple of hours? Thanks!

**Comment by jywarren** [comment]
It's very close to the deadline - we will read it for sure, but not sure if
it'll be in time to file a revision! But thank you!!!

**Comment by HarshKhandeparkar** [comment]
Hi. Can someone help with the testing of the `$step` method? See #833 for reference

@publiclab/is-reviewers @jywarren

**Comment by Divy123** [comment]
Hi Harsh! I want to work on UI testing and would love to look into!!

**Comment by VibhorCodecianGupta** [comment]
@jywarren again, apologies for the plug, I sent over the commentable link to my proposal to you on Gitter. My proposal on publiclab.org says I'll be notified via mail once my proposal gets published. It is way too late for reviews, but the link is on Gitter for your reference. Thanks!

**Comment by blurry-x-face** [comment]
I would love to work on this issue

**Comment by HarshKhandeparkar** [comment]
sure go ahead

**Comment by Divy123** [comment]
Yes please go ahead!

I would love to collaborate on this.

**Comment by jywarren** [comment]
Much ❤️ to you all!!!

Shall we make a checklist of UI actions that could be tested for? 

* [ ] clicking Add Step and confirming a new box appears, and a new image appears
* [ ] Add Step for various modules
* [ ] Clicking Insert Step adds a new box, and modifies the image
* [ ] Clicking Delete Step removes the image

These could be largely independent from the UI implementation as long as the add step, delete step, insert step elements have standard classnames!

**Comment by jywarren** [comment]
Also updated location of existing UI tests! https://github.com/publiclab/image-sequencer/tree/main/test/ui/spec

**Comment by jywarren** [comment]
Here is the most likely section for the listed tests above!

https://github.com/publiclab/image-sequencer/blob/3741d679bd34812efb29d256bb4e033340d086e9/test/ui/spec/defaultHtmlSequencerUi.spec.js#L27-L41

Note that we are not yet testing click events and such. I think the tests are just really minimal stubs, confirming that the UI was set up, but not testing that it works, is that right?

Also:

* [ ] steps included via URL hash are correctly parsed and added (many variants of this, see https://github.com/publiclab/image-sequencer/blob/257113a948a2b8c2026bc07caffa9445fcde51b8/test/ui/spec/urlHash.spec.js#L1)

**Comment by Divy123** [comment]
As I discussed with Pranshu, he suggested that testing with Jest along with puppeteer is a good way to proceed here.
What do you think @jywarren , @blurry-x-face ?

**Comment by jywarren** [comment]
Hi! I'm not against a weighing of pros/cons to switching test libraries, but is there a problem with the current test setup that you're interested in addressing by switching?

**Comment by jywarren** [comment]
Gaah! I accidentally committed to `main` branch here, i'm sorry: 

https://github.com/publiclab/image-sequencer/commit/fb452f7788b7f0641fe1419f649ff5f5ba0f3be9

However, you can see a very clear UI test that is only 3 lines, for the quick selector! cc @harshithpabbati @Divy123 @rexagod @blurry-x-face

**Comment by jywarren** [comment]
I apologize for the mistake, i'll revert it as soon as it fails, but will open it in a new PR.

**Comment by jywarren** [comment]
Reverted, now working on it at: #1242 

To address #1238, which Harsh identified, it would be something like:

```js
  it('allows changing brightness value using input and Apply button', function() {
    $("[data-value='brightness']").click();
    var brightnessImage1 = $('.step:last img')[0].src;
    $('.step:last input.form-control').val('25%'); // change the value
    $('.step:last .btn-save').click(); // apply the change
    var brightnessImage2 = $('.step:last img')[0].src;
    expect(brightnessImage1).not.toEqual(brightnessImage2);
  });
```

**Comment by jywarren** [comment]
Does this makes sense to you all? cc @publiclab/is-reviewers Thanks!

**Comment by blurry-x-face** [comment]
> Hi! I'm not against a weighing of pros/cons to switching test libraries, but is there a problem with the current test setup that you're interested in addressing by switching?

Actually jest is a more maintained testing library but I will look through jasmine.

Thanks @jywarren 
cc: @Divy123

**Comment by vaibhavmatta** [comment]
@jywarren I am claiming it now. Let us work on it together.! The UI needs to be stable. Will make a PR for this super soon. 
Thanks

**Comment by jywarren** [comment]
Closing this in favor of #1369 now!
