### ISSUE TITLE
Grid Overlay error

### ISSUE THREAD

**Issue by aashna27** [publiclab/image-sequencer#1006]
### If we change the input values for GridOverlay, The grid, disappears.

![ezgif com-video-to-gif(6)](https://user-images.githubusercontent.com/26546120/55975653-12babd80-5ca8-11e9-9c01-a8b637109cf1.gif)

### Please show us where to look

https://beta.sequencer.publiclab.org

**Comment by gauravano** [comment]
Hey @aashna27, would you be solving this one? Thanks!

**Comment by aashna27** [comment]
Yeah sure. I ll give it a try.

**Comment by gauravano** [comment]
Great!
