### ISSUE TITLE
Clean up README

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#101]
Just compiling a checklist of things to clean up the README a bit here:

* [x] make a Submit a Module section (that could link to CONTRIBUTING if you think that's best)
* [x] move Module Candidates + Ideas under the Submit a Module section
* [x] `make a "nodes-and-lines" UI` issue (just to store that info from the README) marked as `enhancement`
* [x] clean out Development section and add to Issues where appropriate, or deprecate
* [x] Add an "Installation" section guiding users on setting up Image Sequencer for usage

Thanks!

**Comment by ccpandhare** [comment]
Looks great, will do!

> make a "nodes-and-lines" UI issue (just to store that info from the README) marked as enhancement

Sorry, didn't quite get this part. What is "nodes-and-lines" ?

**Comment by jywarren** [comment]
Done here too! I moved a lot of proposed modules to a new issue from which we can break things off: ](#118)
