### ISSUE TITLE
threshold throws error if used more than once consecutively

### ISSUE THREAD

**Issue by bhavayAnand9** [publiclab/image-sequencer#1010]
### 
![Screenshot 2019-04-13 at 15 24 36](https://user-images.githubusercontent.com/34943807/56078016-98518100-5e00-11e9-9c69-480fcecbbc29.png)

if we use the threshold module more than once consecutively, it throws an error.

### Please show us where to look

https://beta.sequencer.publiclab.org

### What's your PublicLab.org username?

> This can help us diagnose the issue:

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by gauravano** [comment]
Hi @bhavayAnand9, would you like to solve this one? Thanks!

**Comment by bhavayAnand9** [comment]
Yeah why not? I'll definitely look into this.

**Comment by gauravano** [comment]
Thank you!

**Comment by Divy123** [comment]
@bhavayAnand9 are you working on it?
If not, can I proceed with it?

**Comment by bhavayAnand9** [comment]
Sorry, It has been a busy week, @Divy123 please go ahead.

**Comment by Divy123** [comment]
Sure!!
