### ISSUE TITLE
Image downloading on image click is undesirable

### ISSUE THREAD

**Issue by Divy123** [publiclab/image-sequencer#1020]
### Please describe the problem (or idea)
Every time and most of the time by mistake, we click on an image it gets downloaded which is most of the time undesirable

### Solution

A download image button can be added to the panel for this purpose .

**Comment by Divy123** [comment]
CC: @jywarren @HarshKhandeparkar

**Comment by HarshKhandeparkar** [comment]
Wasn’t it added. It was discussed

**Comment by Divy123** [comment]
No its not added yet!
Can you point out towards the issue?

**Comment by HarshKhandeparkar** [comment]
It was a very old issue. It is probably closed now. I had discussed this with someone else as well but I don’t remember who. It was probaby harshith in his panel pr.

**Comment by Divy123** [comment]
Ohh so I think we can continue upon this here!!

**Comment by HarshKhandeparkar** [comment]
Yes sure. Also I would request you to have a look at https://github.com/publiclab/image-sequencer/issues/849#issuecomment-483733931

**Comment by Divy123** [comment]
@jywarren what are your views here?

**Comment by HarshKhandeparkar** [comment]
I had actually done this in the Materialize renderer. The image was materialboxed. Have you seen it?

**Comment by HarshKhandeparkar** [comment]
Link to materialbox docs https://materializecss.com/media.html. We can do something similar to the current bootstrap UI or we can add click to select pixel functionality. Either one of those. I would now actually prefer the latter. Your thought?
@jywarren

**Comment by Divy123** [comment]
@HarshKhandeparkar I think that is quite cool.
Also what do you think on adding a download button?
Sorry if I am missing something.

**Comment by VibhorCodecianGupta** [comment]
@HarshKhandeparkar is this a separate bundled library? I think we can implement the click to select pixel feature easily with the native JS canvas as well, as a separate input type, to reduce the load of an extra library

**Comment by HarshKhandeparkar** [comment]
@Divy123 img download button is ready to go :rocket:!
I was thinking of what we can do with the img when it is clicked.

@VibhorCodecianGupta Materialbox is a modified verison of lightbox. Modified in materializecss. It is used for responsize imgs. Better image preview etc. I mean that you can click on the img to enlarge, zoom into it etc. Hovering over it will add a white mask.

When I had added it to the Materialize renderer, I didn't think of the click to add pixel. I had already added a separate button tor download and the image had nothing so I "materialboxed" it.

**Comment by HarshKhandeparkar** [comment]
Wait I'll drop links to some screenshots/gifs

**Comment by HarshKhandeparkar** [comment]
* WIP draft PR: https://github.com/publiclab/image-sequencer/pull/825
* Scroll down from here to get billions of screenshots and GIFs: https://github.com/publiclab/image-sequencer/issues/708#issuecomment-457604566

**Comment by HarshKhandeparkar** [comment]
I think lighthox is a jQuery plugin but I'm not sure.

**Comment by Divy123** [comment]
@HarshKhandeparkar what's the progress in this one?

**Comment by HarshKhandeparkar** [comment]
> what's the progress in this one?

@VibhorCodecianGupta?
