### ISSUE TITLE
Webgl Distort module

### ISSUE THREAD

**Issue by tech4GT** [publiclab/image-sequencer#1021]
@jywarren I don't have a lot of experience with out gl based work, could you guide me a little here, I think I just need to pretty much model the fisheye-gl module right, but using `webgl-distort` npm module?

**Comment by VibhorCodecianGupta** [comment]
I'd really like to collaborate here, the `fisheye-gl` with puppeteer opened a lot of avenues. I think we can start with @jywarren 's webgl-distort repository

**Comment by jywarren** [comment]
Some notes here! https://github.com/publiclab/image-sequencer/issues/299

The key is:

> We'll need to refactor webgl-distort to not interact with the HTML DOM, so restructuring it to work with an Image object instead of an image element, in this line:

Thanks both!!!

**Comment by VibhorCodecianGupta** [comment]
Nice. I'll try mocking it tonight. Hopefully, I can come up with some ideas/code. Will post here ASAP

**Comment by tech4GT** [comment]
Oh, so we need to edit webgl-distort library then?

**Comment by tech4GT** [comment]
Also, Vibhor thanks a lot!! Actually we need this fairly quickly since this is a crucial part of the new exporter system, and with my end terms coming in, I really appreciate your help!! :D

**Comment by VibhorCodecianGupta** [comment]
Let's get this done by the weekend, then? Mine start in about two weeks as well. Let's make it happen @tech4GT

**Comment by tech4GT** [comment]
Okay fist thing, we need to make the library node compatible, right now requiring it in node is not doing much for me. Then using fisheye-gl as a template let's implement the example code in the readme over at `jywarren/webgl-distort`
You can open the pr, since I would be able to push code on top of that.

**Comment by tech4GT** [comment]
Hmm, @jywarren since the script is not too long do you think maybe we can copy and paste the dist file in is source files?
Or do you think we should edit the `jywarren/fisheye-gl`??

**Comment by jywarren** [comment]
I think we should edit the library separately, but you could start by doing
it locally and we can switch to requiring it later?

**Comment by Divy123** [comment]
Looks interesting!
Please count me in!!

**Comment by VibhorCodecianGupta** [comment]
@Divy123 head over to the PR for the issue if you will, I could use some ideas there. Mentioned some scopes of improvement on the issue comments there

**Comment by jywarren** [comment]
#1022 !!
