### ISSUE TITLE
Display width and height of image at each step 

### ISSUE THREAD

**Issue by Divy123** [publiclab/image-sequencer#1023]
### Please describe the problem (or idea)

What we very casually come across is getting the dimensions of the image we are processing, so I think we can provide these details somewhere in our panel. Maybe we can provide a button which can show or hide these details as per the choice of user.

**Comment by Divy123** [comment]
Cc: @jywarren @HarshKhandeparkar

**Comment by HarshKhandeparkar** [comment]
Perfect! I was thinking of opening this issue since day before yesterday. Strange...🤔

**Comment by VibhorCodecianGupta** [comment]
Let's keep an `info` glyphicon at the corner of the step UI, which is hovered/clicked upon will show the details. thoughts?

**Comment by Divy123** [comment]
@VibhorCodecianGupta can you show some example?

**Comment by jywarren** [comment]
cool idea!!!

**Comment by HarshKhandeparkar** [comment]
We don't use glyphicons so we can use the same fontawesome icon that is used for the notification API. @Divy123 @VibhorCodecianGupta?

I think a similar hover functionality is used on github somehwere but I don't remember where. Nice idea.

**Comment by VibhorCodecianGupta** [comment]
Yes, that's what I meant. I'll push some code/UI mock in a while

**Comment by HarshKhandeparkar** [comment]
Actually do we need to have the icon? Will it even be noticed?

**Comment by HarshKhandeparkar** [comment]
I think a better thing would be to just add it to the bottom of the image. Won't take a lot of space. We can also add it somewhere else in the bootstrap panel.

**Comment by HarshKhandeparkar** [comment]
What do the others think?

**Comment by Divy123** [comment]
Ok will do some work and send a PR soon!!

**Comment by blurry-x-face** [comment]
@Divy123 can I claim this issue?

**Comment by Divy123** [comment]
@blurry-x-face please go ahead!!

Thanks!!
