### ISSUE TITLE
Code consistency with ESLint and Husky

### ISSUE THREAD

**Issue by aashna27** [publiclab/image-sequencer#1039]
To ensure that our commits and code-base remains consistent which makes understanding easier for the new contributors as well as the regular ones.

**Comment by HarshKhandeparkar** [comment]
Let's add it along with babel and webpack

**Comment by HarshKhandeparkar** [comment]
#1009 #670

**Comment by aashna27** [comment]
Yeah, cool I ll add it.

**Comment by aashna27** [comment]
Also those are really cool additions.

**Comment by Divy123** [comment]
I think @aashna27 @aashna27 that we should let it remain an issue in itself. The webpack issue is a big one which may take time, so inspite of loading all of the things at one place, we should do it here itself.

In my opinion, we should break the problems into small not collect it at a place. Many issues are related in IS but that does not mean to make them one.

**Comment by HarshKhandeparkar** [comment]
I meant that we should keep track of what is happening in the other issue and work on them by syncing our work. Webpack, Babel, ESLint, all are related together, for e.g. webpack and babel are run together. So if we make progress in one of the issues, it has to be compatible with the others. I didn't mean to combine the issues but instead synchronize them if that makes sense. @Divy123

**Comment by aashna27** [comment]
Yeah yeah, there wouldn't be any combination of solutions, but refering is just to relate things. That's all.

**Comment by Divy123** [comment]
Ah ok got your point. Actually got confused with this:
> Let's add it along with babel and webpack

I think keeping them in sync is very cool!!

**Comment by Divy123** [comment]
@aashna27 can we collaborate here?

**Comment by aashna27** [comment]
@Divy this is something really new for me, so I would prefer working it all by myself, so that I learn more, but if I have any problems I would surely let you know. Thanks a lot.

**Comment by Divy123** [comment]
Sure @aashna27. Please feel free to ask in case you need any help.
