### ISSUE TITLE
Add Code Climate

### ISSUE THREAD

**Issue by Divy123** [publiclab/image-sequencer#1042]
This issue intends to add code climate.
Thoughts @jywarren ?

**Comment by Divy123** [comment]
If looks good, I would like to proceed..

**Comment by jywarren** [comment]
I think that's be great. Thanks!

**Comment by Divy123** [comment]
@jywarren I think only you can add code-climate to the repo. Please do this.
https://docs.codeclimate.com/docs/my-repository-isnt-listed-when-i-try-to-add-it-to-code-climate#section-open-source-repositories
I can contribute once you add it with handling various tasks further.
Thanks!!

**Comment by jywarren** [comment]
Oh hm, it is added here:
https://codeclimate.com/github/publiclab/image-sequencer

maybe i need to turn on the integrations... will try!

**Comment by Divy123** [comment]
@jywarren its done!!
I think we can close the issue..
