### ISSUE TITLE
Making code-base contain more comments

### ISSUE THREAD

**Issue by Divy123** [publiclab/image-sequencer#1046]
Note: **We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

We can add more and more comments to the existing code base for making it more and more new contributors friendly.

This issue requires adding more comments to various files under lib folder which are mainly related to UI.

**Comment by Divy123** [comment]
I want to do this for src folder .

**Comment by HarshKhandeparkar** [comment]
Great, we can add JSDOC comments
```js
/**
* @method methodName
* @param {Boolean} bool
* @returns [Boolean}
*/
function  returnBool(bool) {
  return bool
}
```

**Comment by HarshKhandeparkar** [comment]
See PR #1038 for examples

**Comment by Divy123** [comment]
Sure, thanks @HarshKhandeparkar !!

**Comment by Divy123** [comment]
@jywarren @tech4GT would love to listen from you upon this.

**Comment by HarshKhandeparkar** [comment]
This is a good gci-candidate. We can reformat this and with proper guidance, the students can learn a lot both about js and the library.

**Comment by Divy123** [comment]
uploaded this on gci dashboard.

**Comment by SidharthBansal** [comment]
Published on GCI dashboard!

**Comment by HarshKhandeparkar** [comment]
I have claimed this task on the GCI dashboard.

**Comment by SidharthBansal** [comment]
Awesome.

**Comment by SidharthBansal** [comment]
@HarshKhandeparkar please break it up into discrete issues of interrelated files and inter-related PRs.
Work is interrelated so each issue + pr together will be of 3 points. 
I don't want anyone will get just 3 points for so many changes in so many files.

Each PR should contain at least 15 lines. If that file contains a lesser number of lines, then we can add two files in one PR. Does this make sense?

**Comment by HarshKhandeparkar** [comment]
Ok. I'll split it up. Maybe these rules should be mentioned somewhere?

**Comment by SidharthBansal** [comment]
Which rules?

**Comment by SidharthBansal** [comment]
I have changed it into `hall of fame` task.

**Comment by SidharthBansal** [comment]
Please don't write documentation for other files, as we will not be able to give you points for them more than 15. 
So stick to 13 files which you touched ONLY
thanks
Sidharth

**Comment by HarshKhandeparkar** [comment]
Hey. I am going to open more sub-issues to this one. There are many more
files that are to be fixed. Can they be individual gci tasks?

**Comment by HarshKhandeparkar** [comment]
Oh ok. Let it be HoF. But I really think there should be issues for all the
files as the comments are actually quite inconsistent. I can't thank you
enought btw.

**Comment by SidharthBansal** [comment]
Let's first complete 13 files which you touched and all related issues of this main issue
Thanks

**Comment by SidharthBansal** [comment]
Regarding work, I have to confirm with @jywarren. May be you have to do more than 13 files documentation as it is changed to hall-of-fame

**Comment by SidharthBansal** [comment]
Atleast 15 files should be documented as per my thinking.
Rest dependends on Jeff's decision

**Comment by HarshKhandeparkar** [comment]
Oh

**Comment by SidharthBansal** [comment]
I have exam together. Complete documentation of some other tasks too in the meantime.
THanks

**Comment by HarshKhandeparkar** [comment]
Documentation of some other tasks? What do you mean? Sorry for disturbing
and all the best for your exams. Thank you!

**Comment by SidharthBansal** [comment]
You said that we need to add documentation to other tasks too. Can you please start working on those files too.

**Comment by HarshKhandeparkar** [comment]
I meant we need to fix the comments in all the other files and that I
wanted to open issues for those. I actually want others to work on those
rather than me doing everything. I have my eyes on a few other issues and I
really want to fix those(and have been wanting to do so for months). If it
is a necessity to add more files to my task, then I will do so. Please let
me know.

**Comment by SidharthBansal** [comment]
Alteast you need to do documentation for 2 more files. Can you open one
more PR.
Thanks

**Comment by HarshKhandeparkar** [comment]
I'll open one more PR tmrw.

**Comment by SidharthBansal** [comment]
Shall we close this?

**Comment by HarshKhandeparkar** [comment]
Yeah, I guess...
