### ISSUE TITLE
Remove .nojekyll

### ISSUE THREAD

**Issue by ccpandhare** [publiclab/image-sequencer#106]
Should we remove the .nojekyll ?

It will become easier for users to read the documentation.

As of now, if one wants to read the CONTRIBUTING.md he either has to voew it on GitHub as raw MarkDown or download the file. Enabling Jekyll will make it accessible on the web easily.

Not just CONTRIBUTING.md, but also the module docs in ./docs/

**Comment by jywarren** [comment]
Hmm, I wonder - can .nojekyll go in the node_modules folder? Wasn't that
what it was causing trouble with?

**Comment by ccpandhare** [comment]
As far as I know, .nojekyll has to be added to root,
Also node_modules is gitignored, so there won't be any benefits of putting
.nojekyll there.

I was proposing to remove the .nojekyll totally so MarkDown documentations
can be shown easily to users

**Comment by jywarren** [comment]
Yes, I see what you're saying, but the .nojekyll was added for a reason,
and I think it was supposed to be only on the gh-pages branch, perhaps, so
that the node_modules in there are preserved? And in the gh-pages branch,
the node_modules folder is included, I believe -- at least that's usually
how I do things.

**Comment by ccpandhare** [comment]
Yes that's right.
Sorry

Will move it to the node_modules

Thanks
