### ISSUE TITLE
Module names are incorrectly used in HTML step selector in demo

### ISSUE THREAD

**Issue by tech4GT** [publiclab/image-sequencer#1061]
The module names while adding them in the demo are wrong, they appear with spaces like "webgl-distort" appears as "webgl distort"
This is causing a critical failure  of the demo. (in the main branch -- @jywarren)

=====@HarshKhandeparkar=====
#### Update: this has been fixed by replacing the spaces with hyphens for now but a better, thorough fix would be better

Possible solution:
1. Modules have a name and an id to reference it. The id has hyphens(and only small letters) and the name has spaces and capitals. E.g.: `webgl-distort`(id), `WebGL Distort` (name)

2. We could assign hidden attributes or jQuery `$.data` properties to the module selector fields so that we can display the name but use the id for referencing the module name in the sequencer when a step is to be added.

=====@HarshKhandeparkar=====

(Update (@jywarren) this was quick-fixed in #1073 but follow-ups included at the bottom of this issue)

_Sent from my OnePlus3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_ 

_Sent from my OnePlus3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by HarshKhandeparkar** [comment]
@tech4GT I was trying to edit the issue body and remove the space. I did this from this phone app and unfortunately it adds the footer text.

**Comment by jywarren** [comment]
Hi, I wasn't able to reproduce this, I found this to work correctly:

https://sequencer.publiclab.org/examples/#steps=webgl-distort{}

Can you clarify? Thanks!

**Comment by tech4GT** [comment]
@jywarren I think we already have a pr for this. #1073

**Comment by HarshKhandeparkar** [comment]
urlHash works but the selector doesn't

**Comment by jywarren** [comment]
A gif of the issue would be great. And eventually a UI test!

**Comment by jywarren** [comment]
No, I used the selector in the page to get this url, and it worked there too.

**Comment by HarshKhandeparkar** [comment]
Uh, it didn't work for me before, and even Nirav told me that it didn't
work. Was a PR merged? Are you on the latest branch?

**Comment by jywarren** [comment]
Hi @HarshKhandeparkar i know you said you're copying in all the relevant documentation for this bug, but in the meantime I am following the exact steps laid out in the chatroom and was able to reproduce this on the main branch in the demo, running locally:

![image](https://user-images.githubusercontent.com/24359/58371705-aacfd780-7ee1-11e9-994b-ce5022ddba02.png)

**Comment by jywarren** [comment]
Exact issue for reproducing:

There is an issue with the step selection UI on the latest main branch, but not in the gh-pages demo, with modules that include spaces in their names?

To reproduce, the demo can be run locally from the latest main branch, using the "webgl-distort" module

The PR at #1073 substitutes hyphens for spaces (as a quick fix), and @HarshKhandeparkar will be copying in suggestions for a more thorough fix here in a moment.

**Comment by jywarren** [comment]
I'd also like to recommend a test for this behavior so we can be sure it doesn't happen in the future! Thanks!

**Comment by jywarren** [comment]
Also, published `v3.3.3`!

**Comment by HarshKhandeparkar** [comment]
@jywarren suggestions copied in the issue body itself.

**Comment by jywarren** [comment]
Closing, but opening a new issue for the tests!
