### ISSUE TITLE
Weekly Community Check-In #22 - "What was your Eureka moment?"

### ISSUE THREAD

**Issue by Divy123** [publiclab/image-sequencer#1065]
Hi everybody :smiley: !

We all at Public Lab :balloon: - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal :dart:. You are also welcome to share fun-fact :smile: , new ideas :bulb: , your learning goals :ballot_box_with_check: . 

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become master of tomorrow. :100: 

If you're new here, welcome, and please comment a _Hello message_ below, we would love to work with you. If you're looking for new issues, please try some of our [first-timers-only issues](https://code.publiclab.org/#r=all). 
 
We're SO EXCITED to have your help!

**Is there anything, you would like to share with us from past week's work? What is your plan for this week?** 

If you have not planned yet, just leave a Hello! so that we know that you are in sync with us :arrows_clockwise: and doing well!

The coming weeks will be absolutely full of code :computer: , tasks :spiral_notepad:, fun :tada: and excitement :smiley:!!

As always, if you're waiting for a review, or if you're stuck, please request help here OR leave a comment with @publiclab/mentors @publiclab/reviewers for some input. 🙌 

### Gitter

Gitter is an active chatroom in our community and we'll be sending weekly reminders about check-ins there. Be sure to sign up [there](https://gitter.im/publiclab/publiclab) for these updates or just to join the conversation. You can also join us through [http://publiclab.org/chat](http://publiclab.org/chat) :speech_balloon:.

## This week's theme

The theme for this week is - "What was  your Eureka moment?". Here at Public Lab, we have learnt so much that words are not enough to express. We all struggled, we enjoyed and we all gained something new. We all did and we all will. So, this is the time to share some of the most exciting Eureka moments of us while getting our Github graph greener by contributing for the good.

Personally this is very close to my heart!! I have been into JS based development since quite sometime but after I started contributing here, with each PR getting merged was a moment of spark for me!! I remember once I was adding % input functionality to crop module input here in IS and I was stuck due to some callbacks. I did not want to change the structure of PixelManipulation file and then suddenly some series of callbacks did it so easily to which I was much surprised and amused. That was the first and one of the most exciting Eureka moments for me. Would love to hear from other members as well!!!

You can find our list of previous check-ins [here](https://github.com/publiclab/plots2/issues/5627) :notebook: 

Have a great week everyone! :balloon: :heart: :tada: 

Thank you !

**Comment by gauravano** [comment]
Nice theme @Divy123 :+1: ! I have removed the list of past check-ins, as we have started maintaining the list - https://github.com/publiclab/plots2/issues/5627. Thanks!

**Comment by gauravano** [comment]
@mohitRJranjan @milaaraujo @kevinzluo @Rishabh570 @sashadev-sky @geekychaser @shubhscoder @sidntrivedi012 @SidharthBansal @cesswairimu @stefannibrasil @ViditChitkara @tech4GT @mridulnagpal @IshaGupta18 @CoderJolly @namangupta01 @sagarpreet-chadha @Souravirus @MayankKashyap @siaw23 @ryzokuken @icarito @steviepubliclab, @ebarry, @jywarren, @sagarpreet-chadha, @JonathanXu1, @uzorjchibuzor, @eli6, @rexagod, @divyabaid16, @dinaelhanan, @oorjitchowdhary, @wanzulfikri, @mohitRJranjan @publiclab/mentors @publiclab/image-sequencer-guides @publiclab/leaflet-environmental-layers-guides @Paarmita @publiclab/reviewers @Divy123 @bhavayAnand9 @Mridul97 @avsingh999 @romanrodriguez @Dhiraj240 @codeIriss @rishabhc32 @chirag-singhal @IgorWilbert @dhruvgupta167 @vrk99 @pdurbin @HarshKhandeparkar @aashna27 @Harshithpabbati @marieram @swiatek7 
@niravasher

**Comment by gauravano** [comment]
@marieram @swiatek7 @gauravano @publiclab/reviewers @publiclab/is-reviewers @publiclab/community-reps

@subhahu123 @An0u @Jaya738 @mgroovyank @shreyateeza @TANGL3SIT3S @nazeem1988 @karunagoyalk @Nirvikalpa108 @cassianoblonski @EngrEric @Anjalizi @GettyOrawo @coderbeetle @corbettbw @govindjeevan @gautamig54 @daddyjab @emestabillo @letnewKid @srujana121 @jazdao @ChinwenduSilvia @aggarwal19 @Jenniline @madelinejones @helenatxu @richa031 @fabsar @kuja24 @megha070 @Aarabhi2017 @Manvi07 @siddhishree @Julius26 @VinneyJ @sonali9696 @rarrunategu1 @coreytegeler @labseven @milomacphail @CleverFool77 @ananyaarun @ananya @divyabaid16 @publiclab-mimi @shubhi2000

**Comment by gauravano** [comment]
@Priyak5 @vaarigupta @techchic @ananya @hc-barker @edwd42 @PritiShaw @themonster2015 @supriya-kotturu @AnthoniaOkafor @jtmims @scheleon @mahmodHammad @santushk @jillpena @stoic-plus @starkblaze01 @aSquare14 @vaarigupta @alonpeer @madeofhuman @ibnjunaid @HarshKhandeparkar @aashna27 @Harshithpabbati @niravasher @mmmelissa

**Comment by gauravano** [comment]
@rarrunategu1 @daz @UNnamed66 @GauravJ3 @Greg-Tarr @Sanscripter @hodbadger

**Comment by mcawley** [comment]
Hello Public Lab community! I am a newcomer, and was very happy to hear about these check ins! Full disclosure, I recently became the Interim Executive Director for OpenStreetMap US. I am hoping to build relationships with other open communities like yours and seeking ways to improve community relations & support for new mappers in OSM. Thanks for providing a welcoming space!

**Comment by alaxalves** [comment]
Hello PublicLab team, I am from Brazil, not a newcomer but I have been contributing to PublicLab since around March, I have been selected this summer for Gsoc program to help on the Mapknitter rails upgrades. My Eureka moment was when I started workin past winter with Quasar framework having near zero experience with components architecture :smile: :smile: . But in the end I got the train rolling and delivered a very stable and very good written (btw) product. From this moment on I started liking frontend :smile: :smile: :smile: :smile:.

**Comment by Divy123** [comment]
Thanks a lot @gauravano for mentioning the contributors here!!

**Comment by sashadev-sky** [comment]
Hi! PL is where I made my first PR ever so I have definitely had so many eureka moments. A big one for me was learning about staging infrastructure and testing. Specifically, that you can test changes in a staged production environment by pushing to the `unstable` branch. This was really my first step towards understanding what goes on beyond the local environment we all set up.

7 months after my 1st PR I know I still have many more eureka moments to come for the infrastructure topic 🚀

**Comment by divyabaid16** [comment]
Hello everyone!
Nice theme @Divy123 :smile: 
My eureka moment was when I had written my first test at Public lab. Before that, I was unaware of how the unit or functional tests are written. I studied about it, asked for help and finally completed my PR. I was so happy when my PR got merged. I really learned an important aspect of development. I learned that tests can be a significant way to learn about the structure of the code base.
In fact, with new leaning, I keep on having more eureka movements.

Have a great week everyone :tada: 
Thanks!

**Comment by jywarren** [comment]
My eureka moment, maybe some of you can guess -- when I created my first `first-timers-only` issue, and... someone showed up and solved it! I was stunned! It was so fast! ❤️ 😄 💯 

I also ❤️ hearing about people learning about testing. I used to hate tests! Can you imagine!??! Now I love them! 😛

**Comment by tech4GT** [comment]
I guess mine was when I wrote up the edge detection module here. I had never formally learned Image processing before so it was basically me reading articles all over the internet. Now, 2 and half years later and having taken 2 courses on Image processing at my university, it's hands down my favourite area of work. 😄

**Comment by niravasher** [comment]
Hello everyone, I don't have any Eureka moment with me but this week I'll fix my previous work that were remaining. Few modules I dealt with before that weren't merged due to merge conflicts. Will try to resolve them.

**Comment by gauravano** [comment]
Hi everyone, my eureka moment was -- when I wrote my first test and API for plots2. Another moment was the success of https://github.com/publiclab/plots2/issues/4963 :smile: :tada:

**Comment by sashadev-sky** [comment]
@gauravano best idea 2019

**Comment by skilfullycurled** [comment]
I'm new enough to not have had a particularly interesting "eureka" moment.  This is sort of a half eureka moment because while I did discover the problem, I still don't understand why it's a problem.

In my FTO, my tests kept failing because there was white space.  I was using the "edit in browser" method and this occurred no matter how I made the change whether I was copy and pasting the code I was given, or if I typed it in myself.  

The code I was given and my own typing of it used a carriage return at the end of the line, after which Github put the next line at the appropriate depth.  After a while, I tried deleting the indentation and then using two spaces instead.  Then the test passed.  So...eureka?

To make it a full eureka, if anyone can explain why this was, I'd appreciate it.  My understanding of Ruby is that while whitespace _can_ matter in certain situations, and a carriage return can be meaningful to the termination of a line, I was under the impression that indenting did not matter in the same way that it does in Python, for example.


at the end of the line used a carriage return and it automatically moved the cursor to the right depth.

**Comment by SidharthBansal** [comment]
My eureka movement was when I wrote my first test. It was really hard initially. Now they seem to be just the flow of events.

**Comment by SidharthBansal** [comment]
Hi @publiclab/soc you all are invited to take part in these discussions. We really love to have your views folks. 
Also, in these check-in issues, all the SoC students are requested to post the following
* FTOs created last week by you
* Progress for your project
* Upcoming week Goals for you
* PR reviews last week
* What things you did collaboratively last week? This is really important we want team spirit.
With FTOs and PR reviews, we are seeking to develop a much more friendly and collaborative platform. We want you all will involve people in your project. You all will develop skills like leadership along the way. 

If you have any query then please feel free to ping me. I will try to reply to as many as I can as soon as I can.

Thanks all for reading the comment.

**Comment by gauravano** [comment]
Hey @skilfullycurled, I will consider it a eureka moment as your first PR was really great. Normally, we don't expect to see a feature implemented in FTO PR :smile:. Feel free to drop the link to the space issue you faced. 

Nice ideas @SidharthBansal :tada: :100: !

Thanks!

**Comment by skilfullycurled** [comment]
Thanks @gauravano.  I have to credit @jywarren for writing a really good FTO which allowed me to focus on those areas, and it probably helped that I was familiar with MVC.  Still, that's great feedback, you never know what's normal!

The issue I was referring to is [here](https://github.com/publiclab/plots2/pull/5459/commits/d3b03302f578e192ab065a7852b221bd2a912e13) and the version of what finally worked is here.  And the second one I was referring to above was [here](https://github.com/publiclab/plots2/pull/5459/commits/84cb96acc98d6e06ff557b5c04b2e99a613f1358).  

Additionally, I also got an error because of an [extra carriage return](https://github.com/publiclab/plots2/pull/5459/commits/fa7e8100e3643f7a291f00606e9be144ab428090) in the view.  I definitely did not expect that considering white space definitely doesn't matter in HTML (I know it's a templating language but still...).

I await further eurekament.

**Comment by gauravano** [comment]
Hey @skilfullycurled,  that was the codeclimate error. We use Travis for testing PRs. Codeclimate looks for sanitization, syntax, spacing issues, etc. Sometimes, it's really irritating and so we merge PRs(many times) without the codeclimate test pass. 

  
![Screenshot from 2019-05-18 16-12-29](https://user-images.githubusercontent.com/20878070/57968442-4912e900-7988-11e9-860e-696897a90b38.png)

Also, you can see the exact details of the test by clicking on the red cross next to the test name. It will take you to the codeclimate website and will give you suggestions for improving your code. It really helps in learning good practices :smiley:. Also, I tried to see the detailed analysis for your commit but I think, it's not available now - https://codeclimate.com/github/publiclab/plots2/pull/5459 .

Thanks!

**Comment by alaxalves** [comment]
> Hi @publiclab/soc you all are invited to take part in these discussions. We really love to have your views folks.
> Also, in these check-in issues, all the SoC students are requested to post the following each week:
> 
> * FTOs created last week by you
> * Progress for your project
> * Upcoming week Goals for you
> * PR reviews last week
> * Work completed last week.
> * What things you did collaboratively last week? This is really important we want team spirit.
>   It is like weekly scrum. Be flexible. I am giving you just a brief idea. I assume you are much more experienced than me in making good comments to explain your work in weekly checkin.
> 
> With FTOs and PR reviews, we are seeking to develop a much more friendly and collaborative platform. We want you all will involve people in your project. You all will develop skills like leadership along the way.
> 
> If you have any query then please feel free to ping me. I will try to reply to as many as I can as soon as I can.
> 
> Thanks all for reading the comment.

This week I have opened the following issues: https://github.com/publiclab/mapknitter/issues/594, https://github.com/publiclab/mapknitter/issues/598, https://github.com/publiclab/mapknitter/issues/599, https://github.com/publiclab/mapknitter/issues/600, https://github.com/publiclab/mapknitter/issues/601, https://github.com/publiclab/mapknitter/issues/602, https://github.com/publiclab/mapknitter/issues/603, https://github.com/publiclab/mapknitter/issues/604 and https://github.com/publiclab/plots2/issues/5725, I have also created milestone https://github.com/publiclab/mapknitter/milestone/8 and project https://github.com/publiclab/mapknitter/projects/2. To accomplish my GSoC I have joined forces with @cesswairimu and @kaustubh-nair to work on https://github.com/publiclab/mapknitter/issues/481 and started my work regarding https://github.com/publiclab/mapknitter/issues/598 and @icarito along with @jywarren guided me through https://github.com/publiclab/mapknitter/issues/604. I have also helped to review the following PRs: https://github.com/publiclab/mapknitter/pull/606 and https://github.com/publiclab/mapknitter/pull/586

**Comment by SidharthBansal** [comment]
Please use markdown text in the comments too so that it will look pretty good 
Like have headings, use italics, underline bold emoticons etc

**Comment by CleverFool77** [comment]
Hi This is Lekhika.
This week I've made following issues :  
**Planning Isssues**
https://github.com/publiclab/plots2/issues/5733
https://github.com/publiclab/plots2/issues/5708
https://github.com/publiclab/plots2/issues/5707

**Fto-candicate Issue**
https://github.com/publiclab/plots2/issues/5693

**Other Issue**
https://github.com/publiclab/plots2/issues/5741

I created the project for upcoming Summer of Code 2019.
https://github.com/publiclab/plots2/projects/10

I'll be working on this Project along with @gautamig54, We have been discussing regarding work and checklists. @gautamig54 made one main planning issue https://github.com/publiclab/plots2/issues/5739 to discuss all out work at one place.
We have started our work and divided the portions.

I just opened the PR https://github.com/publiclab/plots2/pull/5740 to start off my soc work for UI design.
Thanks !!

**Comment by IshaGupta18** [comment]
Hey Everyone!
Since my GSoC project is a standalone project that will be integrated later
with the main site, right now me and @namangupta01 are working on
https://github.com/publiclab/simple-data-grapher. When we ready with the
project's basic functioning, we will be integrating it with plots2!
Everyone is welcome to have a look and give their feedback on this repo!
Thanks a lot.

**Comment by gautamig54** [comment]
Hello all! I am Gautami Gupta.
I wasn't active in the last week due to certain emergencies. But now I am all good to start my SoC journey. 
I am collaborating with @CleverFool77 on UI implementation project. She has given a wonderful start to the project. We have started the planning of certain pages and ready to implement them. 
I will also be working on Notification System with @namangupta01. We have initiated the project and are on the discussion phase. 
I am looking forward to a lot of discussion and planning in the next week for the SoC. 
Hoping to have a great summer ahead.
Thanks!!

**Comment by ananyaarun** [comment]
Hi everyone !!
I am Ananya Arun an outreachy intern with public lab.
I am finally free now and ready to start my SoC journey :smiley: 
I will be working on the project Extend leaflet environmental layers.
LEL a new library, is rapidly seeing many new layers, and this project aims to add some additional structure to help make the display/management of this map data smoother.
Here is it's planning issue : https://github.com/publiclab/leaflet-environmental-layers/issues/173
The next week starting tomorrow I look forward to start working on improving the layer display of LEL and define a better structure for organization of layer displays.
Thanks have a great week everyone !!

**Comment by gauravano** [comment]
Hi @alaxalves @kaustubh-nair, great start :muscle: :tada:. 

@CleverFool77 and @gautamig54, great to see your progress and as your project will very much depend on feedback from @publiclab/community-reps so want to let you know that things might get slow sometimes over the weekend so consider having all your doubts resolved in weekdays if you like working over the weekend. 

@IshaGupta18 @namangupta01 wow, what a start, happy to see that your project is already taking the shape. Please label the issues and PRs from the start only. Also, I saw issue from a contributor so feel free to add  Code of conduct file yourself or maybe open the first FTO of the repo :)

@ananyaarun sounds great!

**Comment by gauravano** [comment]
Hi @aashna27, you showed interest in opening weekly check-in some time ago, if you're still interested, then please go ahead or let us know if you're busy.

Also, as we have started a little late on the Project update part so please open the new check-in on Tuesday evening. Thanks!

**Comment by sashadev-sky** [comment]
@SidharthBansal @gauravano I could be imagining this, but somewhere we posted a template and told GSoC students to use it as a saved reply for progress check-ins right?

**Comment by sagarpreet-chadha** [comment]
⭐️  My first eureka moment was when i was searching for open-source communities back in 2017 and founded - **PublicLab** ❣️ 

⭐️ There are tons of other eureka moments for me --- especially in LEL , LBLD projects where some issues required weeks of detective work 🔍 .

Hey @aashna27 , if interested you can open the new weekly check-in in this project : https://github.com/publiclab/leaflet-blurred-location-display . What do you think 😄 ?

Thanks !

**Comment by gauravano** [comment]
TBH @sashadev-sky I don't remember if we finalized a template for check-in progress for SoC interns. But, we can surely use it if there's any. I am still going through my mailbox and maybe find that. If you want we can open an issue and hold discussion over the message template and take @SidharthBansal's list as a start?  

Thanks!

**Comment by jywarren** [comment]
Hi, all! I just posted a draft Software Roadmap, which I'd love input on! https://publiclab.org/notes/warren/05-22-2019/draft-of-a-public-lab-software-roadmap-comments-welcome :raised_hands:

**Comment by jywarren** [comment]
@publiclab/soc @publiclab/reviewers especially!

**Comment by steviepubliclab** [comment]
Hi all!! There's a post on Public Lab I'd love to get some of your feedback and ideas on. I think a lot of your experience here in the coding community in helping to onboard newcomers, organizing information, and keep materials up to date would be really valuable in this conversation! Please share! 

https://publiclab.org/notes/stevie/05-23-2019/thinking-through-research-area-reviews

**Comment by rexagod** [comment]
Hi all! 👋

I've been a bit out-of-the-loop and lagging due to my finals recently but they are over now, so I guess with some assistance from @sashadev-sky (thank you!) I should probably be up to speed in no time.

Also, since everyone is here I'd love to pitch this new CLI tool (link below) I started working on last night that'll seamlessly integrate with `matcher.js` (my GSoC project) wherever it is in your local, and enable the user to run all different sorts of headless operations on matcher right from the CLI, i.e., a node server!! 💥 Also I've included babel, eslint (google-standards), and uglify support to maintain the code-qualify and backward compatibility w/ performance enchancements.

https://github.com/rexagod/matcher-cli

![test](https://user-images.githubusercontent.com/33557095/58371041-6ff29180-7f2b-11e9-95d4-bec028757770.gif)

PS. The final interface will be implemented in [Vorpal](http://vorpal.js.org).

Thanks!

**Comment by SidharthBansal** [comment]
Ashna please open the new check in. Just a reminder.
@publiclab/soc there are some students who haven't participated in this weekly checkin. Please tell us your progress each week. It is much better to have collaborative workplace here at PL

**Comment by SidharthBansal** [comment]
> @SidharthBansal @gauravano I could be imagining this, but somewhere we posted a template and told GSoC students to use it as a saved reply for progress check-ins right?

@sashadev-sky that would be great. Students are encouraged to use the saved replies feature.

**Comment by SidharthBansal** [comment]
I really loved your idea.
> TBH @sashadev-sky I don't remember if we finalized a template for check-in progress for SoC interns. But, we can surely use it if there's any. I am still going through my mailbox and maybe find that. If you want we can open an issue and hold discussion over the message template and take @SidharthBansal's list as a start?

@gauravano @sashadev-sky  no need to create an issue and template. We want to see the students creativity in writing posts. There is no fixed format. Students can do it as they wish to. This will help students to do introduce new things in the checkins which we will be able to learn. In case, we will give them a template then everyone will do things in same way. We want people to do things in their own way.

I hope you will agree with me. Thanks

**Comment by gauravano** [comment]
Actually, I think, @aashna27 might have missed the notification so if anybody else wants to open new check-in let us know. Thanks!

Regarding template, ok, let's not give saved reply but let's consider making a list of things we want to know every week from interns @SidharthBansal?  

> - FTOs created last week by you
> - Progress for your project
> - Upcoming week goals for you
> - PR reviews last week
> - Work completed last week.
> - What things you did collaboratively last week? This is really important we want team spirit.
> It is like weekly scrum. Be flexible. I am giving you just a brief idea. I assume you are much more experienced than me in making good comments to explain your work in weekly check-in.

- Feel free to tell us about your absence too, if you're taking a break. 
- Issue/PR you're struggling with (if any)

Thanks!

**Comment by sashadev-sky** [comment]
@gauravano @SidharthBansal ok sounds good! How about adding @gauravano bullet point list above as a check-in section to remind people what to address?

**Comment by gauravano** [comment]
Yes, let's do that. Maybe we can give heading as "Summer of Code progress
update"

**Comment by aashna27** [comment]
Hey! I am sorry I missed through the notifications, was a little busy with some system repairs but I am here now and I volunteer to open the next check-in.

**Comment by aashna27** [comment]
> Hi @aashna27, you showed interest in opening weekly check-in some time ago, if you're still interested, then please go ahead or let us know if you're busy.
> 
> Also, as we have started a little late on the Project update part so please open the new check-in on Tuesday evening. Thanks!

Hey @gauravano so I have to open the check-in on tuesday right?

**Comment by aashna27** [comment]
> star My first eureka moment was when i was searching for open-source communities back in 2017 and founded - **PublicLab** heavy_heart_exclamation
> 
> star There are tons of other eureka moments for me --- especially in LEL , LBLD projects where some issues required weeks of detective work mag .
> 
> Hey @aashna27 , if interested you can open the new weekly check-in in this project : https://github.com/publiclab/leaflet-blurred-location-display . What do you think smile ?
> 
> Thanks !

yeahh sure thanks for suggesting !! :smile:

**Comment by gauravano** [comment]
> Also, as we have started a little late on the Project update part so please open the new check-in on Tuesday evening. Thanks!

Hi @aashna27, no issues. Actually, it was for the previous Tuesday. Please open check-in by tomorrow. Thanks!

**Comment by gauravano** [comment]
Hi everyone, new check-in is open at https://github.com/publiclab/leaflet-blurred-location-display/issues/78. Thanks, @aashna27 for the great theme :smiley:.

**Comment by aashna27** [comment]
> Hi everyone, new check-in is open at [publiclab/leaflet-blurred-location-display#78](https://github.com/publiclab/leaflet-blurred-location-display/issues/78). Thanks, @aashna27 for the great theme smiley.

Yayyy!! Thanks a lot :tada:

**Comment by sashadev-sky** [comment]
@gauravano do you have the ability to edit issue descriptions in LBD? I was going to implement this but I realized I didnt.

If not, I can just do it on this issue here and mention @aashna27 to update the new check-in!

**Comment by aashna27** [comment]
Yeah please let me know the edits!

**Comment by gauravano** [comment]
Hi Sasha, I have updated the check-in body. Let me know if any further
changes are needed. Thank you!

**Comment by sashadev-sky** [comment]
@gauravano yeah its perfect! Maybe lets add it to the bottom?

**Comment by gauravano** [comment]
Done! @sashadev-sky
