### ISSUE TITLE
Add WASM acceleration to PixelManipulation code

### ISSUE THREAD

**Issue by Divy123** [publiclab/image-sequencer#1068]
### Please describe the problem (or idea)
This issue aims to convert existing pixelManipulation.js code to WASM.
> What happened just before the problem occurred? Or what problem could this idea solve?

This will lead to an increased performance.
### Please show us where to look

https://beta.sequencer.publiclab.org

### What's your PublicLab.org username?
lit2017001

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by jywarren** [comment]
Completed in #1093 ! Great work!
