### ISSUE TITLE
Adding minify-image module

### ISSUE THREAD

**Issue by Divy123** [publiclab/image-sequencer#1070]
### Please describe the problem (or idea)
This issue adds minify-image module to sequencer.

### Please show us where to look

https://beta.sequencer.publiclab.org

### What's your PublicLab.org username?
lit2017001

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by HarshKhandeparkar** [comment]
Done
