### ISSUE TITLE
Setup issue (related to npm)

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/image-sequencer#1072]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

I followed the instructions in the Readme , i initially had a higher verion of Node so , 

- i installed **n** - package manager and downloaded version  **v0.8.12** .

- Next i ran `npm run setup` and got following error : 

> What did you expect to see that you didn't?

<img width="652" alt="Screenshot 2019-05-22 at 7 47 14 PM" src="https://user-images.githubusercontent.com/14952645/58181984-6b7b6e00-7cca-11e9-94fa-44d9db26159d.png">

`npm install` also gives same error .

Any help is appreciated :)

### Thank you

cc @jywarren @Divy123 @tech4GT

**Comment by tech4GT** [comment]
Hmm, this looks like an issue with your node, since the command did not get translated to `npm i && npm i -g grunt grunt-cli && grunt build`
try using node via nvm, maybe that'll help.

**Comment by HarshKhandeparkar** [comment]
Try `npm install -g npm`. Maybe it is a version problem. Also, nodejs v6 support is dropped.

**Comment by HarshKhandeparkar** [comment]
And why is the npm version less than v1? (Pre-release)?

**Comment by HarshKhandeparkar** [comment]
Or is it a typo?

**Comment by HarshKhandeparkar** [comment]
Best way might be to update all global dependencies

**Comment by HarshKhandeparkar** [comment]
To v8 because it is a global dependency problem and not local. Another thing you can try is to delete `/usr/local/bin/lib/node_modules/` because the dependencies might be made for node v > 8 and you now have degraded the version

**Comment by Divy123** [comment]
@sagarpreet-chadha is the issue solved or is it still persisting?

**Comment by sagarpreet-chadha** [comment]
Hi all , thank you for the discussions . 
I will give it another try tomorrow and revert back here with the status . Thank you :)

**Comment by HarshKhandeparkar** [comment]
@sagarpreet-chadha I am closing this one. If you face the issue again, please feel free to reopen the issue.
