### ISSUE TITLE
Solve no-undef errors 

### ISSUE THREAD

**Issue by aashna27** [publiclab/image-sequencer#1084]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

To gain a sense of what the issue targets go to [.eslintrc.js](https://github.com/publiclab/image-sequencer/blob/main/.eslintrc.js) and comment the `no-undef': 0` rule and the go to your terminal and run below command.
```
npx eslint .
```
You will see a list of no-undef errors and by this issue we plan to reduce those errors.

- [ ] 📝 **Update** the following files 

1. [ReplaceImage.js](https://github.com/publiclab/image-sequencer/blob/main/src/ReplaceImage.js) add `const $ = window.$;` at line 4 in ReplaceImage()
2. [Ui.js](https://github.com/publiclab/image-sequencer/blob/main/src/modules/Crop/Ui.js) add `const $ = window.$;` at line 3 in CropModuleUi()
3. [Crop.js](https://github.com/publiclab/image-sequencer/blob/main/src/modules/Crop/Crop.js) and modify line 20 as 
```diff
-backgroundColor = options.backgroundColor.split(' ');
+var backgroundColor = options.backgroundColor.split(' ');
```
4. [Module.js](https://github.com/publiclab/image-sequencer/blob/main/src/modules/AddQR/Module.js) and change line 7
```diff
-  getPixels = require('get-pixels');
+ var getPixels = require('get-pixels');
```
5. [Module.js](https://github.com/publiclab/image-sequencer/blob/main/src/modules/Average/Module.js) and add as
```diff
function extraManipulation(pixels) {
+       const $ = window.$;
      var i = 0, sum = [0, 0, 0, 0];
```
6. [Module.js](https://github.com/publiclab/image-sequencer/blob/main/src/modules/ColorTemperature/Module.js) as 
```diff
-r_data = pixels.get(i, j, 0);
+var r_data = pixels.get(i, j, 0),
r_new_data = (255 / r) * r_data;
pixels.set(i, j, 0, r_new_data);

-g_data = pixels.get(i, j, 1);
+var g_data = pixels.get(i, j, 1),
g_new_data = (255 / g) * g_data;
pixels.set(i, j, 1, g_new_data);

-b_data = pixels.get(i, j, 2);
+var b_data = pixels.get(i, j, 2),
b_new_data = (255 / b) * b_data;
pixels.set(i, j, 2, b_new_data);
```
7. [Convolution.js](https://github.com/publiclab/image-sequencer/blob/main/src/modules/Convolution/Convolution.js)

```diff
-for (i = 0; i < 9; i++) {
+for(var i=0; i < 9; i++) {
    kernelValues[i] = Number(kernelValues[i]) * constantFactor;
  }
-for (y = 0; y < 3; y++) {
+for (var y = 0; y < 3; y++) {

-for (x = 0; x < 3; x++) {
+for(var x = 0; x < 3; x++) {
   
```
As explained similar changes can be made for many others files to bring down the number of errors (no-undef) for files [SetInputStep](https://github.com/publiclab/image-sequencer/blob/main/src/ui/SetInputStep.js), [Module.js](https://github.com/publiclab/image-sequencer/blob/main/src/modules/WebglDistort/Module.js), and many others. The errors can be seen in the terminal using  ``` npx eslint . ``` and similar changes can be made in files.

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by PoseidonSigmaX** [comment]
Hey! I'd like to work on this issue :)

**Comment by HarshKhandeparkar** [comment]
Go ahead!

**Comment by PoseidonSigmaX** [comment]
Hey so there are three different Ui.js files, and two of them have a cropmoduleui function. Do I eed to update both of them?

**Comment by HarshKhandeparkar** [comment]
Yes

**Comment by HarshKhandeparkar** [comment]
I guess you have to fix all the errors. You can edit any file.
Cc @aashna27

**Comment by aashna27** [comment]
@PoseidonSigmaX I have linked each file to their respective location, the links for each will take you to the required place.I hope I am making sense.

**Comment by PoseidonSigmaX** [comment]
@aashna27 In edits 6 and 7 you've placed a comma at the end of the lines to be added. I'm assuming you meant to put a semicolon there.

**Comment by aashna27** [comment]
> @aashna27 In edit 6 you've placed a comma at the end of the lines to be added. I'm assuming you meant to put a semicolon there.
> 
> Also thank you for linking the files it was really confusing before
> 
>     * The file to edit for edit 7 isn't mentioned. Could you look into that please?

Nope its a comma not a ; and yes I have now linked for 7th edit as well . Also these variable changes exist in many other files as well so it would be good if you would like to do it for other files as well.

**Comment by Starkyv** [comment]
Can I take up this issue?

**Comment by jywarren** [comment]
We'd love your help! Sorry for the slow reply!

**Comment by rahulzura** [comment]
Can I take this issue or is anyone working on it?

**Comment by HarshKhandeparkar** [comment]
You can work on it. Just make sure that no one else is working on it.

**Comment by HarshKhandeparkar** [comment]
I think this was fixed
