### ISSUE TITLE
Adding some modules from drop-down throws error

### ISSUE THREAD

**Issue by aashna27** [publiclab/image-sequencer#1094]
Adding certain modules(eg Paintbucket, overlay) from the drop-down throws error.
![Screenshot from 2019-05-31 23-01-47](https://user-images.githubusercontent.com/26546120/58723689-5f915980-83f8-11e9-993d-f84ca146d223.png)

**Comment by jywarren** [comment]
Thanks for this catch! I think we are seeing a capitalization issue - we may need to enforce lower-case in module names -- some module names are capitalized, like `Text-Overlay`, in their `info.json`:

https://github.com/publiclab/image-sequencer/blob/31bc45cb9192fda601a3f1cbe74ab0e73b395aed/src/modules/TextOverlay/info.json#L2

Could relate to https://github.com/publiclab/image-sequencer/issues/1061 maybe as well.

**Comment by jywarren** [comment]
For example, I'm trying to run:

```
sequencer.replaceImage("img","text-overlay:{text:TEXT|font:arial|color:white}")
```

But I'm getting:

```
Module text-overlay: not found.
image-sequencer.js:68743 Uncaught TypeError: Cannot read property 'description' of undefined
    at insertStep (VM1139 image-sequencer.js:68743)
```

It's on this line: 

https://github.com/publiclab/image-sequencer/blob/31bc45cb9192fda601a3f1cbe74ab0e73b395aed/src/InsertStep.js#L13-L17

It's odd because running `sequencer.addSteps('text-overlay')` in the console works fine. So does `seq.insertSteps(0,'text-overlay')`.

**Comment by jywarren** [comment]
Where is your error occurring?

**Comment by jywarren** [comment]
Ah! Ok, my issue was that instead of 

`sequencer.replaceImage("img","text-overlay:{text:TEXT|font:arial|color:white}")`

I needed:

`sequencer.replaceImage("img","text-overlay{text:TEXT|font:arial|color:white}")`

I.e. no `:` after "text-overlay"!

**Comment by aashna27** [comment]
Yeahh this issue wasn't seen in text overlay but eg in grid overlay it
existed

**Comment by aashna27** [comment]
the benchmarks shows that all modules are loading but in browser adding these modules throws error.
