### ISSUE TITLE
Some API for modules to describe their configurable options, for display in an HTML form

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#11]
Thinking how we might take a set of parameters required and provide (in the module) a description of what they should be and their defaults -- for use either by programmers, or by the HTML interface when you'd be able to configure the step as a user, using text inputs or sliders or menus. 

Thoughts on this?

**Comment by rackstar17** [comment]
@jywarren I'm interested in solving this issue, We can use a modal api for this .
As soon as the value of <select> changes we can open up a modal and based on the value of what module user chooses , we can show options in that modal ?
Just a suggestion
What do you think ?

**Comment by jywarren** [comment]
Hi, I think a modal could work, but so could a form just built into the UI
pane of each module. Maybe we should start by just trying to insert a form
with an input into a given pane using the userinterface class? If you'd
like to give that a try, I'm happy to help review and comment. Thanks!

**Comment by lvyachao** [comment]
A modal API can works (e.g. https://v4-alpha.getbootstrap.com/components/modal/) However, I can we can use Vue.js provide whole solution handling every DOM-rendering and form control events. That bring more helps. I'll cover this issue during GSOC 17.

**Comment by ccpandhare** [comment]
I think we can easily do this now :)

**Comment by ccpandhare** [comment]
This has been done in #92
