### ISSUE TITLE
Insert step funcionality is broken badly

### ISSUE THREAD

**Issue by Divy123** [publiclab/image-sequencer#1100]
Currently the insert step functionality is not at all working.

This is something urgent and should be fixed as soon as possible.

CC: @jywarren .

**Comment by Divy123** [comment]
I will be working on this as soon as I get wasm PR completed

**Comment by jywarren** [comment]
Great, thank you so much!! And let's write a test for it too!

**Comment by Divy123** [comment]
https://github.com/publiclab/image-sequencer/issues/1127

**Comment by keshav234156** [comment]
@jywarren i  think we should close this issue with #1266

**Comment by jywarren** [comment]
Ah, ok! Closing!
