### ISSUE TITLE
Uncaught TypeError: $(...).colorpicker is not a function

### ISSUE THREAD

**Issue by Divy123** [publiclab/image-sequencer#1115]
I am getting following error on my browser:

```js
Uncaught TypeError: $(...).colorpicker is not a function
```

And the load image step is not working:
![Screenshot from 2019-06-17 17-30-43](https://user-images.githubusercontent.com/31225007/59603030-f747b500-9125-11e9-9a28-0c8133dced49.png)

**Comment by Divy123** [comment]
@aashna27 any help on this?

**Comment by aashna27** [comment]
Yeah i ll see this later today evening!

**Comment by Divy123** [comment]
Thanks and can you please review https://github.com/publiclab/image-sequencer/pull/1093 ?

**Comment by aashna27** [comment]
@Divy123 I am on the latest branch but I wasn't able to reproduce this error, although would you mind verifying that bootstrap-colorpicker exists in your package.json and also that we have bootstrap-colorpicker.js and .css scripts in index.html and then npm install again and see that bootstrap-colorpicker exists in node_modules.

Attaching links for references 
https://github.com/publiclab/image-sequencer/blob/b34ec00efdd89352191fe8016c3b364f7ef64aa5/examples/index.html#L30

https://github.com/publiclab/image-sequencer/blob/b34ec00efdd89352191fe8016c3b364f7ef64aa5/examples/index.html#L45

https://github.com/publiclab/image-sequencer/blob/b34ec00efdd89352191fe8016c3b364f7ef64aa5/package.json#L35 

this error exists if its not able to find colorpicker() in short not able to find bootstrap-colorpicker!

**Comment by HarshKhandeparkar** [comment]
The new color picker is live! (https://beta.sequencer.publiclab.org)

![Screenshot from 2019-06-18 19-41-35](https://user-images.githubusercontent.com/34770591/59691769-30088c80-9201-11e9-9859-b3e9ae54d616.png)

**Comment by aashna27** [comment]
> The new color picker is live! (https://beta.sequencer.publiclab.org)
> 
> ![Screenshot from 2019-06-18 19-41-35](https://user-images.githubusercontent.com/34770591/59691769-30088c80-9201-11e9-9859-b3e9ae54d616.png)

Yayy!! This is cool..

**Comment by HarshKhandeparkar** [comment]
@aashna27 could you please re-review my $step PR? I have replied to your comments.

**Comment by aashna27** [comment]
Oh okay missed them

**Comment by aashna27** [comment]
@Divy123 if it works for you could you close this issue?
