### ISSUE TITLE
Display icon in HTML step container when a module is being wasm-accelerated? 

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#1121]
This could be neat, @Divy123 !

**Comment by Divy123** [comment]
Can you please provide a bit more information on this.

**Comment by jywarren** [comment]
Like, we could show a little lightning icon in the upper right corner of
the step card box in the HTML demo, which when you hover, shows
"accelerated with WebAssembly" in a tooltip?

**Comment by Divy123** [comment]
That's a great idea!!
Would love to work on it.

**Comment by HarshKhandeparkar** [comment]
We can reformat this for gci

**Comment by HarshKhandeparkar** [comment]
Fixed!
