### ISSUE TITLE
Add a Brightness module

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#113]
This would be great, and could be a good template for other similar modules, like contrast, saturation

* [ ] basic implementation
* [ ] UI for demo, with slider or at least numeric input (%?)
* [ ] create new issue for contrast similar to this
* [ ] create new issue for saturation similar to this

**Comment by tech4GT** [comment]
@jywarren I would love to work on this

**Comment by jywarren** [comment]
please do! Could it be implemented with the PixelManipulation sub-module?

**Comment by tech4GT** [comment]
@jywarren yes , it has been implemented with pixelManipulation submodule only in this PR
https://github.com/publiclab/image-sequencer/pull/161
