### ISSUE TITLE
unable to see new module in drop down box

### ISSUE THREAD

**Issue by MargaretAN9** [publiclab/image-sequencer#1136]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

Believe I have figured a way to load OpenCV on Image Sequencer , trying to test with @aashna27 aashnaaashna's module  but the module never displays in the dropdown box.  The program passes grunt build but I cant activate it since it isn't in the drop down list.  So, what  files need to be changed to 'see' a new module?

See  
https://github.com/publiclab/image-sequencer/pull/1120#issuecomment-505688970

> What did you expect to see that you didn't?

 I can't see the new Module 'BlobAnalysis' in the drop down box .  I think I have followed all the Module requirements (files  below) put I can get it to display.   

### Please show us where to look   The files in the Blobanalysis module are from aashnaaashna git hub site with some modifications for the loading opencv

https://github.com/MargaretAN9/Image-sequencer/tree/master/blobanalysistest

### What's your PublicLab.org username?

MaggPI

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****Windows 10 Chrome

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by MargaretAN9** [comment]
IS Files  posted at: https://github.com/MargaretAN9/ImageSequencerUpdate .   Just trying to determine why the new module doesn't show in the drop down box?  Thx 

cc @jywarren  @tech4GT @Divy123 @aashna27

**Comment by jywarren** [comment]
Hi, are you running this locally, and have you run "grunt build" to get it
working from the compiled files? I think we potentially haven't yet built
these into the compiled files in /dist/ (which is mentioned in the
CONTRIBUTING docs, but could be more clear, sorry!)

and after that I'd look to see if you are using a browser-cached version --
try opening the dev console and then right-clicking the reload button, it
should offer "Clear cache and reload" as an option. Sorry, i was offline
all weekend!

**Comment by HarshKhandeparkar** [comment]
Grunt build is run in the setup script.

**Comment by HarshKhandeparkar** [comment]
It will probably be a cache issue

**Comment by MargaretAN9** [comment]
Yes clearing the cache worked! I can now see the new module

Now working a new problem "Unable to get property '1"  of undefined or null reference 
in image-sequencer-ui.js(322,11),
