### ISSUE TITLE
Rotate module not functioning correctly

### ISSUE THREAD

**Issue by Divy123** [publiclab/image-sequencer#1137]
The rotate module implemented currently is not working correctly. I don't think this is some bug but the way it has been implemented. Right now, after rotating the image, it acquires the same dimensions as the original image due to which sometimes a rectangular image gets cropped which should not be the case.

CC: @jywarren @tech4GT @HarshKhandeparkar @aashna27

**Comment by HarshKhandeparkar** [comment]
@Divy123 what do you think should be the expected behavior? Size should remain the same and pixels should be resized or pixels same and image should become bigger?

**Comment by Divy123** [comment]
![Screenshot from 2019-06-30 16-21-49](https://user-images.githubusercontent.com/31225007/60395583-3973ec00-9b53-11e9-90f1-3341753fe2ff.png)
@HarshKhandeparkar  see this screenshot, its very clear that rotate is rotating the image but cropping at the same time. I believe the imagearea should be increased but image should not be cropped as its not the behavior of "rotate" .

**Comment by Divy123** [comment]
Any one working here?
@jywarren want to listen to  you upon this!!

**Comment by jywarren** [comment]
I guess i agree that the cropping shouldn't happen, and that it should have
the minimum height and width possible with the new rotation completed!
Thanks, all!

**Comment by Divy123** [comment]
Could you please explain a bit more on that?

**Comment by jywarren** [comment]
Just agreeing with you, re:

> I believe the imagearea should be increased but image should not be cropped as its not the behavior of "rotate" .

Thank you!

**Comment by keshav234156** [comment]
Had done changes.The problem of cropping would be solved but a stake of  liitle amount of image quality to that  of present method for rotation(that to when angle aproaches diagnol angle but best for cased like 90,180,270) 
![Screenshot from 2019-08-18 18-24-49](https://user-images.githubusercontent.com/45951376/63224701-9f8cff00-c1e5-11e9-8ad6-517be8e59ba7.png)
image at 30
![download (12)](https://user-images.githubusercontent.com/45951376/63224767-55f0e400-c1e6-11e9-9ce8-6ea656a00d88.png)
image at 90
![download (13)](https://user-images.githubusercontent.com/45951376/63224777-715bef00-c1e6-11e9-8cef-bb26fcaa7d9a.png)

have done just for angles 0 to 90 degrees.need to do some small changes for any angle. 

@jywarren @HarshKhandeparkar  do you think that it's worth implementing this method?

**Comment by HarshKhandeparkar** [comment]
Bilinear doesn't seem quite right

**Comment by HarshKhandeparkar** [comment]
You can do bicubic on a GPU

**Comment by HarshKhandeparkar** [comment]
We have that functionality in modules/_nomodule/gpuUtils.js. You can ask me for help with that. I developed it and it should be used more and more

**Comment by HarshKhandeparkar** [comment]
If you look at the 90° img, there is a weird line at the top, please try to rectify that

**Comment by HarshKhandeparkar** [comment]
Nice work @keshav234156

**Comment by keshav234156** [comment]
@HarshKhandeparkar have fixed the weird line,which was due to round() function i was using,so it was 1px line.
Can you please guide me how we can use bicubic interpolation with gpuUtils.js

**Comment by HarshKhandeparkar** [comment]
gpuUtils provides a way to use the GPU. You have to add your own code. The
file has jsdoc comments so you could understand how to use the individual
functions. For an implementation, you can have a look at the blur module.
If you have any further queries, DM me on gitter and notify me here(so that
I get the notification).

Thank you!

**Comment by keshav234156** [comment]
@HarshKhandeparkar @jywarren I think it would be better if we use bitmap.js to rotate our image.The problem with it was that it was that is cropped the image,but we can prevent crop by writing some amount of code.This were the results obtained.This would be a much simple and better solution
![Screenshot from 2019-08-20 13-21-01](https://user-images.githubusercontent.com/45951376/63328725-4a203180-c34e-11e9-80a9-690d471b9af1.png)

image at 30
![download (17)](https://user-images.githubusercontent.com/45951376/63328731-4c828b80-c34e-11e9-8d9e-7eee711d1a72.png)

image at 90
![download (18)](https://user-images.githubusercontent.com/45951376/63328775-5b693e00-c34e-11e9-914d-c2b3c43a7c45.png)

**Comment by HarshKhandeparkar** [comment]
@keshav234156 sure

_Sent from my OnePlus3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
