### ISSUE TITLE
Service worker registration failed error in console

### ISSUE THREAD

**Issue by Divy123** [publiclab/image-sequencer#1138]
```js
Service worker registration failed, error: TypeError: Cannot set property 'onstatechange' of null
    at image-sequencer-ui.js:229
```

The above error appears everytime in browser console.

**Comment by Divy123** [comment]
CC: @jywarren @tech4GT @HarshKhandeparkar @aashna27

**Comment by aashna27** [comment]
Somebody else also had opened a pr related to this, and i searched for onstatechange it exists in cache.js. Maybe some problem related to service worker installation

**Comment by vivek-30** [comment]
@HarshKhandeparkar I have fixed this problem.
if no one is working on it , then can i raise a PR for this ?

**Comment by HarshKhandeparkar** [comment]
Sure!
