### ISSUE TITLE
Minify Image module

### ISSUE THREAD

**Issue by Divy123** [publiclab/image-sequencer#1142]
@jywarren I am working on a minify-image module whose workflow is:

![min](https://user-images.githubusercontent.com/31225007/60465919-e3489b00-9c6f-11e9-959c-2ac67361eee5.png)

For this I need to convert the input datauri to a image file like a png/jpeg file (which will be deleted later). Can you help me out with how can I approach this?

**Comment by jywarren** [comment]
Actually, would you want to try implementing the "resize before preview"
step or is @aashna27 working on that? But maybe if the OpenCV work is
holding it back, you could help out with the pre-preview optimization,
which is pretty important for overall speed, and somewhat related to this?
Thank you!

**Comment by Divy123** [comment]
Sure looking into that as well!!
Thanks!!

**Comment by Divy123** [comment]
@jywarren I have successfully tested out the minify-image functionality but since this does not involve any PixelManipulation directly, I don't have to use PixelManipulation.js file. But without that I am facing a few errors. Should I open a PR where you or @IgorWilbert can probably look into?

**Comment by jywarren** [comment]
yes please, and highlight the exact errors? Thank you!!!

**Comment by Divy123** [comment]
Ok sure, thank you!!
