### ISSUE TITLE
Image overlay module

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#116]
A module that fetches a remote image via URL (or data URL) and overlays it on the canvas at a given x, y, w, h

This will be very useful!!

**Comment by ccpandhare** [comment]
That would be great!

**Comment by ccpandhare** [comment]
Maybe it could accept local images from browser based clients too

**Comment by jywarren** [comment]
Related to #233

**Comment by jywarren** [comment]
merging into #233 !
