### ISSUE TITLE
'Save' button not working?

### ISSUE THREAD

**Issue by MargaretAN9** [publiclab/image-sequencer#1161]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?
I can't save the png file on my local version of IS.   It also doesn't seem to be working on the web version.   Does anyone else notice this problem?  

Also , where does this function occur in IS?

> What did you expect to see that you didn't?
Expected a file to be downloaded.   Nothing happens. 

### Please show us where to look
Front page of IS

https://beta.sequencer.publiclab.org

### What's your PublicLab.org username?
MaggPi
> This can help us diagnose the issue:

### Browser, version, and operating system
Windows 10, chrome
> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by vaibhavmatta** [comment]
@MargaretAN9 Is it working  now? or should I work on this issue?

**Comment by vaibhavmatta** [comment]
@MargaretAN9 Save button is still not working in my chrome as well as safari browser. I am working on this issue now as I see no other working on it.

**Comment by MargaretAN9** [comment]
thx I assume tis similar to issue 1192

**Comment by vaibhavmatta** [comment]
May I start working on it? @MargaretAN9

**Comment by HarshKhandeparkar** [comment]
Fixed.
