### ISSUE TITLE
Assorted improvements to be broken into separate issues

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#118]
Please help out by [creating new issues](/publiclab/image-sequencer/issues/new) for these, and linking out to them in the comments!

## UI

* [x] spinner icons `<i class="fa fa-spinner fa-spin"></i>` in demo before steps are complete
* [x] click to expand for all images (pretty easy [on these](https://github.com/publiclab/image-sequencer/blob/master/examples/index.html#L102) [lines](https://github.com/publiclab/image-sequencer/blob/master/examples/index.html#L142))
* [ ] (bigger) "node-and-line" style UI - like a flow-based program (Quartz Composer, Pure Data, [node red](https://nodered.org/) (javascript!), etc)
    * visual nodes-and-lines UI: https://github.com/flowhub/the-graph
    * https://flowhub.github.io/the-graph/examples/demo-simple.html
* [ ] Possible web-based commandline interface: https://hyper.is/?

## Modules

Please label these as `new-feature`

* [ ] (for node-and-line style UIs) non-linear sequences with Y-splitters -- ability to split an image into two sequences! (whoa)

### Testing

* [ ] testing a module's promised functionality: each module could offer before/after images as part of their API; by running the module on the before image, you should get exactly the after image, comparing with an image diff (this is partially implemented, i think?)

**Comment by ccpandhare** [comment]
Histogram Module : #119 
Spinner Icons : #120
