### ISSUE TITLE
New preview optimization - drawing from wrong image?

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#1184]
hi @aashna27 i tried the new beta published by @HarshKhandeparkar and saw this:

![image](https://user-images.githubusercontent.com/24359/61966027-a5edd980-af9f-11e9-9ab5-181c566bdbd2.png)

It seems like maybe the previews are not drawing on the last step, but the first step? 

http://beta.sequencer.publiclab.org/examples/#steps=dither{dither:floydsteinberg}

On the other hand, I tried the non-beta main site and it just stalled 😆 so we're already doing better 😄 

![image](https://user-images.githubusercontent.com/24359/61966190-07ae4380-afa0-11e9-83ed-1ab662519c7e.png)

Aha, it finally ran. But it suffers the same issue. I think the preview system may always have been connected to the initial image, instead of the final step? not sure, but we should fix this!

![image](https://user-images.githubusercontent.com/24359/61966232-2b718980-afa0-11e9-9ad7-da9539ba3988.png)

Thanks, all!

**Comment by HarshKhandeparkar** [comment]
The site doesn't load for me
```
SyntaxError: invalid regexp group image-sequencer.js:1:9
ReferenceError: ImageSequencer is not defined
```

**Comment by HarshKhandeparkar** [comment]
was anything changed?

**Comment by keshav234156** [comment]
I am now working on this
