### ISSUE TITLE
Save Button is unresponsive

### ISSUE THREAD

**Issue by aashna27** [publiclab/image-sequencer#1192]
#### The save button for different saving options, saving sequence string download gif and save image png is unresponsive. The link does not exist rendering the functionality useless. 

![save](https://user-images.githubusercontent.com/26546120/62151805-d1b1ec00-b31e-11e9-8a4f-6cda84396257.png)

I would like to work on this but I need some connecting dots for what do the individual dropdown options do.

**Comment by jywarren** [comment]
Hi, just a quick question first, is this affecting the https://sequencer.publiclab.org demo, or just the latest main, or the beta?

Let's use the `blame` feature to track when this was edited last; i see:

https://github.com/publiclab/image-sequencer/blame/main/examples/index.html#L183

Following through previous versions, like https://github.com/publiclab/image-sequencer/blame/6339229836a42926645186d3c0dfae8fe824c2bc/examples/index.html#L174, I see #360 touched this, #942, #745. Maybe those will help!

**Comment by jywarren** [comment]
Maybe @IgorWilbert @harshithpabbati can help, as they've worked on this section of code?

**Comment by jywarren** [comment]
This is a really good one to write a UI test for, actually. And writing one now will highlight the bug (although I've confirmed it seems not to be working on the live https://sequencer.publiclab.org demo). 

Interestingly the save button seems not to be connected to any events (at least not via its id `saveButton`).

I do see references to `handleSaveSequence()` : https://github.com/publiclab/image-sequencer/search?utf8=%E2%9C%93&q=handleSaveSequence&type=

but no function definition for that... strange!

**Comment by jywarren** [comment]
Ah, it was further down in that same file. OK, it may be worth looking through the commits on these two files:

https://github.com/publiclab/image-sequencer/commits/main/examples/demo.js

https://github.com/publiclab/image-sequencer/commits/main/examples/lib/defaultHtmlSequencerUi.js

To see if any of them deleted code that would've been handling this. Thank you!!!

**Comment by aashna27** [comment]
> This is a really good one to write a UI test for, actually. And writing one now will highlight the bug (although I've confirmed it seems not to be working on the live https://sequencer.publiclab.org demo).
> 
> Interestingly the save button seems not to be connected to any events (at least not via its id `saveButton`).
> 
> I do see references to `handleSaveSequence()` : https://github.com/publiclab/image-sequencer/search?utf8=%E2%9C%93&q=handleSaveSequence&type=
> 
> but no function definition for that... strange!

Yeah this is actually the case some commit might have renamed the id and then not changed it at the function handling location because I do remember using this feature, though not exactly sure how it worked so wanted inputs on what things were done with the different options.

**Comment by aashna27** [comment]
We have download gif in 2 places 
![download-gif](https://user-images.githubusercontent.com/26546120/62415505-4ef39e80-b648-11e9-85d6-0610bf3a6072.png)
![download-modl](https://user-images.githubusercontent.com/26546120/62415506-50bd6200-b648-11e9-93e7-7370e9a24df5.png)

Do we want to keep both ?

**Comment by Michaellin250** [comment]
Can i help or no?

**Comment by aashna27** [comment]
> Can i help or no?

yeah yeah you can definitely help, actually I am trying to figure out what is the connectivity for the different dropdown options.

**Comment by vaibhavmatta** [comment]
Is anyone working on this issue. See if I can help in it. :)
