### ISSUE TITLE
Weekly community Check-In #31 - Documentation

### ISSUE THREAD

**Issue by Rishabh570** [publiclab/image-sequencer#1195]
Hi everyone :wave: !

We all at Public Lab :balloon:  - learn, grow, work, brainstorm ideas, contribute together so why not share about our _weekly goals and the awesome work_ we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal :dart: . You are also welcome to share fun-fact :smile: , new ideas :bulb: , your learning goals :ballot_box_with_check: .

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become master of tomorrow. :100:

If you're new here, welcome, and please comment a _Hello_ below, we would love to work with you. If you're looking for new issues, please try some of our [first-timers-only](https://code.publiclab.org/#r=all) issues.

We're SO EXCITED to have your help!

**Is there anything, you would like to share with us from past week's work? What is your plan for this week?**

If you have not planned yet, just leave a Hello! :wave: so that we know that you are in sync with us :arrows_clockwise: and doing well!

As always, if you're waiting for a review, or if you're stuck, please request help here OR leave a comment with @publiclab/mentors @publiclab/reviewers for some input. :raised_hands:

#### Gitter

Gitter is an active chatroom in our community and we'll be sending weekly reminders about check-ins there. Be sure to sign up [there](https://gitter.im/publiclab/publiclab) for these updates or just to join the conversation. You can also join us through http://publiclab.org/chat :speech_balloon:.

#### This Week's Theme: **Documentations for the project**

So the final evaluation process is not very far now. At this point, everybody's contributions to the projects and the community have grown quantitatively and qualitatively. Some are almost done with their projects also.

This makes the next coming weeks the best time to document what did you achieve/what is yet to be implemented along with nice code documentation to make the project easy to get started with. I think writing documentation helps you take a deeper look at the code.

What do you think? Do you already have documentations a priority in your schedule?

You can find our list of previous check-ins [here](https://github.com/publiclab/plots2/issues/5627).

## :memo:  Note to Summer of Code interns:
We request all the SoC students to read and include necessary points in their check-in comment

- Update on what you worked on last week
- Goals in the coming week
- What things you did collaboratively last week? This is really important we want team spirit.
It is like a weekly scrum. Be flexible.
- GSOC interns 2nd eval due on 26th July and please share links to blogs if available.
- Outreachy interns there is "Career opportunities" chat on  23rd July  1p.m UTC on Zulip
- Feel free to tell us about your absence too, if you're taking a break.
- Issue/PR you're struggling with (if any)

Join us for Open Code Call/ Weekly scrum on  Tuesday - http://publiclab.org/opencall 

Thanks :balloon: :tada: :rocket:

**Comment by gauravano** [comment]
@newbazz @aSquare14 @vaarigupta @alonpeer @aashna27 @harshithpabbati @jesus-montano @cryptoclidus @mohamed-elalem @konolga @gowtham5699

**Comment by gauravano** [comment]
@milaaraujo @kevinzluo @Rishabh570 @sashadev-sky @shubhscoder @sidntrivedi012 @SidharthBansal @stefannibrasil @ViditChitkara @tech4GT @mridulnagpal @IshaGupta18 @CoderJolly @namangupta01 @sagarpreet-chadha @Souravirus @MayankKashyap @siaw23 @ryzokuken @icarito @steviepubliclab, @ebarry, @jywarren, @sagarpreet-chadha, @JonathanXu1 @rexagod, @divyabaid16, @dinaelhanan, @oorjitchowdhary @publiclab/mentors @publiclab/image-sequencer-guides @publiclab/leaflet-environmental-layers-guides @Paarmita @publiclab/reviewers @Divy123 @bhavayAnand9 @Mridul97 @avsingh999 @Dhiraj240 @codeIriss @IgorWilbert @pdurbin @HarshKhandeparkar @niravasher @publiclab/reviewers @publiclab/is-reviewers @publiclab/community-reps @divyabaid16 @publiclab/community-reps @subhahu123 @govindjeevan @gautamig54 @rarrunategu1 @CleverFool77 @ananyaarun @ananya @publiclab-mimi @ananya @hc-barker @starkblaze01 @aSquare14 @vaarigupta @alonpeer @pdurbin @HarshKhandeparkar @newbazz

**Comment by alaxalves** [comment]
**Update on what you worked on last week**

- Helped @ViditChitkara finish to set up Action Cable in Rails 5.2.3
- Deprecated Sprockets in favor of Webpacker for Rails 6.0.0
- Integrated Webpacker in Rails 6.0.0
- Fixed system tests and Chrome versin in Plots2

**Goals in the coming week**

- Get Action Cable, Foreman and Puma integration fully working on Rails 5.2.3
- Get Rails 5.2.3 on main branch.
- Along with @sashadev-sky's help finish the new asset pipeline in Rails 6.0.0 with Webpacker.

**What things you did collaboratively last week?**

Me, @gauravano and @jywarren fixed the Plots2 issue regarding the system tests.

**Comment by vaibhavmatta** [comment]
Hello!
@publiclab/mentors @publiclab/reviewers @Rishabh570 @gauravano @jywarren @aashna27 
I am new to public lab but contributing in open source since a month. 

**TILL NOW:**
I've helped other contributors through comments.
Opened a new issue #1202 

**By this week:**
I am planning to find issues for which PR have not been made yet and resolving as much as possible.

I request you to please tag me if you find any such issue. It would be great help. Thanks.

**Comment by gauravano** [comment]
Hey @vaibhavmatta, welcome to Public Lab. You can start with small issues in image-sequencer or other project of your interest. 

Don't focus on solving large # of issues, focus on the quality and process. Focus on one issue and try multiple when you can manage. Code quality and process is important as it will improve your skill while contributing to Open Source.

**Comment by vaibhavmatta** [comment]
@gauravano Thanks alot. I ll make ensure that I will give maximum for the  organization and that too quality Contribution.

**Comment by namangupta01** [comment]
Hey Guys, If someone is already not opening upcoming week check-in I would like to open.

Thanks!!

**Comment by gauravano** [comment]
Sure @namangupta01!
