### ISSUE TITLE
Grid -overlay error only works for certain values and locks up

### ISSUE THREAD

**Issue by MargaretAN9** [publiclab/image-sequencer#1203]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

Grid overlay locks up  for some values ,  for input values x=100, y=100 color black, it works but for x=0, y=100 it locks up and never finishes, forcing a reload to reconnect

looks similar to issue #1006 but that was a display error , my problem is it doesn't execute

What I would like to do is vary grid spacing to match up with a microscope scale reference as shown below.  I need to control both the origin of the grid lines as well as adjust the spacing, any ideas on the best way to adjust spacing so it matches prestored input values appreciated

![image](https://user-images.githubusercontent.com/37722313/62813783-ceff8580-bada-11e9-9141-52b66b4d7aad.png)

### Please show us where to look
bliclab.org

https://beta.sequencer.pu
### What's your PublicLab.org username?
MaggPI
> This can help us diagnose the issue:

### Browser, version, and operating system
Window chrome
> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by MargaretAN9** [comment]
This works in the beta sequencer  as advertised . and it looks like #1006 was the fix?  

![image](https://user-images.githubusercontent.com/37722313/62816049-68d12d80-baef-11e9-9431-b2d5618f71d7.png)

**Comment by aashna27** [comment]
I ll make some fixes and make a pr.
