### ISSUE TITLE
Custom Resize Option in Resize Module

### ISSUE THREAD

**Issue by aashna27** [publiclab/image-sequencer#1217]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all),we've worked to make it more legible to folks who either **haven't contributed to our code-base before, or for folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before look through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Make yourself familiar with the code-base and the [resize module.](https://github.com/publiclab/image-sequencer/tree/main/src/modules/Resize)

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** 

Currently the resize module accepts a parameter to resize the image and resizes both the image height and width with that. We need to give the user and option to select which mode the user wants, "Custom Resize" or "Proportional Resize"(the current one). 

"Custom resize" would resize the image as per the width and height parameters entered.

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

 If you are not familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

### 🤔❓ Questions?

Leave a comment below!

**Comment by priyanka1204** [comment]
can i work on this issue?

**Comment by priyanka1204** [comment]
Hello @aashna27 , can i take this?

**Comment by aashna27** [comment]
Yeah yeah suree please claim it. Do assign yourself!

**Comment by BrooksPatola** [comment]
is this still open?

**Comment by HarshKhandeparkar** [comment]
I guess yes. Go ahead

**Comment by BrooksPatola** [comment]
Thanks. I'll give it ago @HarshKhandeparkar

**Comment by BrooksPatola** [comment]
@HarshKhandeparkar  If i'm understanding correctly, you wish to keep the current Proportional Resize option (125% start value) but would like to add a Custom Resize option that would take both a width and heigh percentage then apply that to the image?

**Comment by HarshKhandeparkar** [comment]
yes exactly

**Comment by BrooksPatola** [comment]
@HarshKhandeparkar  Would you have a general outline to go about doing this? Just so I am not missing any steps. If not, I will dive into it soon.

**Comment by HarshKhandeparkar** [comment]
Nope. You can start right away. I would generally start by understanding the current code and play with it and then fix the issue.

**Comment by BrooksPatola** [comment]
@HarshKhandeparkar 

I know I should include custom resize functionality in the resize module itself, but I am having difficulty finding where I should include the html tags for the module. When i run the project with 'npm start', it goes to the example page, then I can use Chrome dev tools to see the current elements, I am just unsure of the file to target to include new values. If you have any suggestions, let me know. Otherwise, I'll continue to play around more with it.

**Comment by HarshKhandeparkar** [comment]
To include new options, you have to change the info.json file inside the
module folder

**Comment by Starkyv** [comment]
Is this issue still open?

**Comment by Starkyv** [comment]
How to Claim the issue?

**Comment by Starkyv** [comment]
> @HarshKhandeparkar
> 
> I know I should include custom resize functionality in the resize module itself, but I am having difficulty finding where I should include the html tags for the module. When i run the project with 'npm start', it goes to the example page, then I can use Chrome dev tools to see the current elements, I am just unsure of the file to target to include new values. If you have any suggestions, let me know. Otherwise, I'll continue to play around more with it.

@BrooksPatola Do you need any help in solving this issue? I can help you out if so.

**Comment by HarshKhandeparkar** [comment]
If @BrooksPatola doesn't reply in a few days, I guess you can work on it if you want @Starkyv

**Comment by BrooksPatola** [comment]
@harshithpabbati  Still on it. Will update within the next week.

**Comment by Starkyv** [comment]
> @harshithpabbati Still on it. Will update within the next week.

Sure @BrooksPatola . Take your time.

**Comment by Starkyv** [comment]
> @harshithpabbati Still on it. Will update within the next week.

@BrooksPatola Can I help you with this issue? If so please enlighten me with the problem you are facing.

**Comment by HarshKhandeparkar** [comment]
If no one is working on this, let's mark this for gci

**Comment by keshav234156** [comment]
moved to #1298
