### ISSUE TITLE
Select a Module dropdown covers Add Step button in 1920 screen width

### ISSUE THREAD

**Issue by blurry-x-face** [publiclab/image-sequencer#1236]
### Select a Module dropdown covers Add Step button in 1920 * 1080 screen size.

![Screenshot from 2019-08-29 04-51-58](https://user-images.githubusercontent.com/42492389/63899534-d26f9800-ca1a-11e9-8c77-a2f2d8596c93.png)

### Browser, version, and operating system
Browser: Google Chrome 72.0.3626.81 (Official Build) (64-bit)
OS: Ubuntu 18

**Comment by blurry-x-face** [comment]
Can i work on this?

**Comment by keshav234156** [comment]
@blurry-x-face this issue has been fixed recently with #1208. So i think you can close this issue.

**Comment by keshav234156** [comment]
@jywarren what do you think about this?

**Comment by HarshKhandeparkar** [comment]
Yes sure. This was fixed. Thanks for opening this anyway @blurry-x-face. No worries, I will update the beta demo site soon.
