### ISSUE TITLE
service worker responds with cache to fetch requests everytime its available

### ISSUE THREAD

**Issue by Rishabh570** [publiclab/image-sequencer#1237]
### Please describe the problem (or idea)

> What did you expect to see that you didn't?

[This](https://github.com/publiclab/image-sequencer/blob/main/examples/sw.js#L27) line in `sw.js` is responsible for responding with cache to every fetch request whenever the cache is available. Does this mean user would be getting a cached response every time? Do we have any cache invalidation techniques to make sure cache doesn't get stale?

### Please show us where to look

https://beta.sequencer.publiclab.org

### What's your PublicLab.org username?

icode365

> This can help us diagnose the issue:

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by jywarren** [comment]
We'd prefer that the latest version is made available if it can be fetched, and that the cache remain a fallback. What should we change it to in order to achieve that? Thank you! 

cc #605 #953 #761

**Comment by Rishabh570** [comment]
Okay so for that, I guess we should be using `Network with Cache fallback Policy` then...this would ensure that response is coming from the network when it's possible, it will fall back on the app cache if needed.

Something similar is implemented [here](https://github.com/publiclab/community-toolbox/blob/main/sw.js#L25) in community toolbox, we can switch to something similar if it is not breaking anything here...?

**Comment by vivek-30** [comment]
@HarshKhandeparkar i have solved this issue can i raise a PR for this?

**Comment by HarshKhandeparkar** [comment]
Sure!

**Comment by vivek-30** [comment]
Thank you ☺️
