### ISSUE TITLE
problem with meta-modules

### ISSUE THREAD

**Issue by keshav234156** [publiclab/image-sequencer#1239]
There are many errors occuring while using meta-module(colorbar and ndvi-colormap).
Steps to reproduce
1 .chose nvdi-colormap(or colorbar)
2.then chose any other module and change the value that is not the default value
it would now change image produced by the above mentioned module as well .

![Screencastfrom29-08-19095222PMIS](https://user-images.githubusercontent.com/45951376/63961584-bae1ef00-caae-11e9-8c8a-2db9a70d2928.gif)

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by keshav234156** [comment]
@jywarren @HarshKhandeparkar please have a look

**Comment by HarshKhandeparkar** [comment]
I had a look at this already. Would like to solve this one? Do you have any idea why this is happening?

**Comment by ataata107** [comment]
@HarshKhandeparkar Is this issue still up as I would like to work on this.

**Comment by blurry-x-face** [comment]
Hi @ataata107 I'm currently working on this. But would love your inputs on this.

**Comment by ataata107** [comment]
Ok Got It.
It is the scope error. In createMetaModule,js the following line
`var internalSequencer = ImageSequencer({ inBrowser: false, ui: false });`

This line needs to go inside `function draw(input, callback) {` in createMetaModule,js

Could you help me as to know how to claim a issue as I didn't know you had already claimed this one.

**Comment by blurry-x-face** [comment]
> It is the scope error. In createMetaModule,js the following line
> `var internalSequencer = ImageSequencer({ inBrowser: false, ui: false });`
> 
> This line needs to go inside `function draw(input, callback) {` in createMetaModule,js

I did that yesterday but it didn't work, but it looks like i forgot to clear the cache, silly me :dizzy_face:

> Could you help me as to know how to claim a issue as I didn't know you had already claimed this one.

You should just comment on the issue to claim it, I did the mistake of not commeting it, sorry.

You can help on # 1211 I tried but had no luck with this. Thanks!

**Comment by blurry-x-face** [comment]
Ok so while working on #1431 I found out that this issue was not resolved and for same reason #1418 colorbar is also not working, I think I know why this might be happening I'll make a new PR for it ASAP!

**Comment by keshav234156** [comment]
@blurry-x-face This has been fixed . The main issue was that the above step was getting different but it not the case after you have made the changes in #1426

**Comment by blurry-x-face** [comment]
Ohh yes you're right this was a different issue, but the problem was same both of the variable were out of scope, So should I create a new issue for this or maybe you could just reopen this one with additional description?
