### ISSUE TITLE
PixelManipulation in many modules where unneeded?

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#1240]
It looks like the PixelManipulation functions are used in many modules which dont actually do per-pixel math. I wonder if we could optimize this!

More soon. 

cc https://github.com/publiclab/image-sequencer/issues/550

**Comment by BrooksPatola** [comment]
Would love to be part of the optimization if possible.

**Comment by jywarren** [comment]
Thank you so much! I believe unless we're actually changing per-pixel color values, it's not needed, so we can list out modules where it should be possible to remove it!

https://github.com/publiclab/image-sequencer/tree/main/src/modules/

* [ ] DecodeQr
* [ ] ImportImage
* [ ] BlobAnalysis, i think

... and then, we should look to an existing example of a module with no PixelManipulation -- or the example in the docs!

https://github.com/publiclab/image-sequencer/blob/main/CONTRIBUTING.md#contributing-modules

```js
module.exports = function ModuleName(options,UI) {

  var output;
  // Module requirements have been simplified in version 3, see https://github.com/publiclab/image-sequencer/blob/master/CONTRIBUTING.md#contributing-modules

  function draw(input,callback) {

    var output = function(input){
      /* do something with the input */
      return input;
    }

    this.output = output(input); // run the output and assign it to this.output
    callback();
  }

  return {
    options: options,
    draw: draw,
    output: output,
    UI: UI
  }
}
```

This is all that should be required!

**Comment by vaibhavmatta** [comment]
@jywarren I will go through each module and see where the pixelManipulation function is not required. Will be opening a PR for this supersoon..!

**Comment by HarshKhandeparkar** [comment]
Being fixed elsewhere.
