### ISSUE TITLE
Bugs in AddQR,Draw-rectangle,Grid-overlay after #1188

### ISSUE THREAD

**Issue by keshav234156** [publiclab/image-sequencer#1247]
- [x] AddQR is not working as expected 
![Screenshot from 2019-09-04 13-45-19](https://user-images.githubusercontent.com/45951376/64278489-7fda3280-cf6a-11e9-95a3-53335720656b.png)

- [x] Color-picker is not working in Draw-Rectangle
![Screenshot from 2019-09-04 22-44-25](https://user-images.githubusercontent.com/45951376/64278615-ccbe0900-cf6a-11e9-9f5f-39d2e20d7175.png)

- [x] Color-picker is not working in Grid-overlay
![Screenshot from 2019-09-04 22-51-22](https://user-images.githubusercontent.com/45951376/64278722-08f16980-cf6b-11e9-8b35-aa379f34222b.png)

These modules are working fine with beta version.These bugs occurred after merging PR #1188 
****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by keshav234156** [comment]
cc : @jywarren @HarshKhandeparkar

**Comment by jywarren** [comment]
Thank you for reporting!  Would you have any interest in trying to resolve
some of these? Thank you!

**Comment by keshav234156** [comment]
@jywarren currently my university exam are going on,will end on September 13.would try to fix all these issue after that.In the meantime can you please review the PR #1218
