### ISSUE TITLE
bugs in insert step functionality

### ISSUE THREAD

**Issue by keshav234156** [publiclab/image-sequencer#1261]
- [ ] insert steps add step multiple number of time and are mostly added after some random step.

- [ ] close button and radio group buttons are not working

- [ ] there are some undefined options in select module dropdown
![Sep 23, 2019 8_49 PM (2)](https://user-images.githubusercontent.com/45951376/65439019-2451e500-de44-11e9-8a00-9013fd6674ec.gif)

### Please show us where to look

https://beta.sequencer.publiclab.org

### What's your PublicLab.org username?

> This can help us diagnose the issue:

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by keshav234156** [comment]
cc : @jywarren  @HarshKhandeparkar

**Comment by jywarren** [comment]
Thank you! These are indeed serious issues. I've been stuck on developing UI tests to protect against them here: #1242 and if you are able to help resolve these we'd LOVE your help. Thank you!

**Comment by vaibhavmatta** [comment]
@jywarren May I claim this issue?

**Comment by keshav234156** [comment]
@vaibhavmatta PR #1266  which fixes this issue is already present.If you could review the PR it would be a great help!!
