### ISSUE TITLE
Save and Preview GIF buttons not working

### ISSUE THREAD

**Issue by vaibhavmatta** [publiclab/image-sequencer#1274]
### Save and Preview Buttons are not working. There comes an error in the chrome's inspect element CONSOLE whenever "Preview GIF" button is clicked.

> It may be due to unstable front-end. There can be another reason as well.

> Save button should save the processed  image to the local and Preview GIF should also work fine.

### Please show us where to look -> https://sequencer.publiclab.org

<img width="1440" alt="Screenshot 2019-10-13 at 3 52 17 AM" src="https://user-images.githubusercontent.com/50797619/66720389-8d13f800-ee19-11e9-8a4e-d10d34012786.png">

****

**Comment by vaibhavmatta** [comment]
cc: @jywarren @HarshKhandeparkar

**Comment by vaibhavmatta** [comment]
@publiclab/reviewers , @@publiclab/is-reviewers
Please add Fto label to it, Thanks : 😊

**Comment by HarshKhandeparkar** [comment]
@vaibhavmatta Please use the beta site https://beta.sequencer.publiclab.org. This issue is fixed there and it will soon be on the stable one too. Closing this one. Feel free to reopen.
