### ISSUE TITLE
Weekly community Check-In #37 - Making new FTO's and Making IS UI stable

### ISSUE THREAD

**Issue by vaibhavmatta** [publiclab/image-sequencer#1280]
Hi everyone 👋
We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become master of tomorrow. 💯

## Make UI stable :
There are many issues opened for unstable User Interface of Image Sequencer and those issues needs to be solved as soon as possible.  We would love to have help from all the contributors regarding this.  Please try and solve or make new issues which can make UI stable and better.

## Create a  first-timer-only issue :
We always have a lot of people coming in to the community. This is because of our friendly nature of welcoming new contributors 😃 This week, please take a minute and create a fto in your project of choice and match it to a person looking for an fto [here](https://github.com/publiclab/plots2/issues/6206) 

### Note to Outreachy applicants

The deadline for final applications is Nov. 5, 2019 at 4pm UTC. Applicants will not be able to create a final application after the deadline. Applicants can edit their final application until the deadline.

Applicants who submit a final application will be able to continue recording and editing their contributions to your project. They can record contributions until the intern announcement on Nov. 26, 2019 at 4pm UTC. Applicants who have not submitted a final application will not be able to record or edit their contributions.

Here at PublicLab we recommend you post your initial application on the website first [here](https://publiclab.org/notes/gauravano/03-12-2019/call-for-outreachy-2019-proposals) before posting on the Outreachy website.

### Next Check-in
If you would like to open the next Check-in please leave  a comment below expressing your interest.

Thanks 🎈 🎉 🚀

**Comment by vaibhavmatta** [comment]
@gauravano @milaaraujo @kevinzluo @Rishabh570 @sashadev-sky @shubhscoder @sidntrivedi012 @SidharthBansal @stefannibrasil @ViditChitkara @tech4GT @mridulnagpal @IshaGupta18 @CoderJolly @namangupta01 @sagarpreet-chadha @Souravirus @MayankKashyap @siaw23 @ryzokuken @icarito @steviepubliclab, @ebarry, @jywarren, @sagarpreet-chadha, @JonathanXu1 @rexagod, @divyabaid16, @dinaelhanan, @oorjitchowdhary @publiclab/mentors @publiclab/image-sequencer-guides @publiclab/leaflet-environmental-layers-guides @Paarmita @publiclab/reviewers @Divy123 @bhavayAnand9 @Mridul97 @avsingh999 @Dhiraj240 @codeIriss @IgorWilbert @pdurbin @HarshKhandeparkar @niravasher @publiclab/reviewers @publiclab/is-reviewers @publiclab/community-reps @divyabaid16 @publiclab/community-reps @subhahu123 @govindjeevan @gautamig54 @rarrunategu1 @CleverFool77
@ananyaarun @ananya @publiclab-mimi @ananya @hc-barker @starkblaze01 @asquare@pdurbin @HarshKhandeparkar@newbazz @aSquare14 @vaarigupta @alonpeer @aashna27 @harshithpabbati @jesus-montano@cryptoclidus @mohamed-elalem @konolga @gowtham5699@jywarren @ebarry @steviepubliclab @StlMaris123, @tauhir, @augustozanellato, @nstjean, @stefanosu, @alexido19, @Akashutreja, @fadib, @skai-ste, @mahimahans111, @Lisa-Caton, @pkayres, @JeffOgah, @IvetaHron, @Linda-Ikechukwu, @crisner, @vishakhanihore, @shailzaa, @saivoleti17, @chrisnorwood, @DanielKlys7, @Diegoafv, @saramace, @lojosmit, @kyebrowning, @jon-flores

**Comment by vaibhavmatta** [comment]
@ananyaarun @ananya @publiclab-mimi @ananya @hc-barker @starkblaze01 @asquare@pdurbin @HarshKhandeparkar@newbazz @aSquare14 @vaarigupta @alonpeer @aashna27 @harshithpabbati @jesus-montano@cryptoclidus @mohamed-elalem @konolga @gowtham5699@jywarren @ebarry @steviepubliclab @StlMaris123, @tauhir, @augustozanellato, @nstjean, @stefanosu, @alexido19, @Akashutreja, @fadib, @skai-ste, @mahimahans111, @Lisa-Caton, @pkayres, @JeffOgah, @IvetaHron, @Linda-Ikechukwu, @crisner, @vishakhanihore, @shailzaa, @saivoleti17, @chrisnorwood, @DanielKlys7, @Diegoafv, @saramace, @lojosmit, @kyebrowning, @jon-flores

**Comment by SidharthBansal** [comment]
Hi all!
I hope everyone enjoyed the festive season of lights Diwali. :tada: :zap: 
We have filled the initial application of GCI. Results will come tomorrow. Really excited to see the results.
All mentors are requested to fill up the mentorship forms.

I will like to do the next checkin :-)

**Comment by jywarren** [comment]
Hi, thank you @vaibhavmatta !!! Great check-in! I'm coming back online after some days of rest, and a bit behind on everything, as you can imagine 📫 

So glad to see people and the projects progressing. 🙌

**Comment by vaibhavmatta** [comment]
Pleasure @jywarren 🙂

**Comment by nstjean** [comment]
Happy Monday!
Last week I finished up my PR https://github.com/publiclab/plots2/pull/6472 and focused on creating new FTOs.
This week I will be posting my Outreachy application proposal and working on another PR https://github.com/publiclab/plots2/pull/6422 as well as opening more FTOs. I want to make a checklist of all the pages that need the function translation.

**Comment by subhahu123** [comment]
Where is GCI mentorship form @jywarren  @SidharthBansal @gauravano

**Comment by vaibhavmatta** [comment]
Hey @subhahu123 , refer to https://github.com/publiclab/plots2/issues/6238

**Comment by cesswairimu** [comment]
Hi @SidharthBansal , I believe the next check-in is yours. Thanks

**Comment by SidharthBansal** [comment]
Yeah sure!

**Comment by SidharthBansal** [comment]
Sorry for the delay. Things took a little time to finalize!

**Comment by SidharthBansal** [comment]
moved to https://github.com/publiclab/plots2/issues/6762

**Comment by cesswairimu** [comment]
Thanks @SidharthBansal
