### ISSUE TITLE
Camera should automatically close after the Image is captured once

### ISSUE THREAD

**Issue by vaibhavmatta** [publiclab/image-sequencer#1281]
#### What do we expect?
Camera should automatically close after the image is captured once.
 #### Where to see?
Look [here](https://beta.sequencer.publiclab.org/examples/#)

**Comment by HarshKhandeparkar** [comment]
Hey Vaibhav, there is a close button which works. Should we still keep this issue?

**Comment by vaibhavmatta** [comment]
@HarshKhandeparkar Yes.! Because Close button can be used if you clicked Take picture button by mistake. But Camera should automatically close after the Image is captured once. Because there is no point of keeping camera active while processing a currently captured image. Thanks

**Comment by HarshKhandeparkar** [comment]
Ok cool.

**Comment by vivek-30** [comment]
@HarshKhandeparkar i have solved this issue ,can i raise a PR for this?

**Comment by HarshKhandeparkar** [comment]
Sure

**Comment by vivek-30** [comment]
ok Thanks ☺️
