### ISSUE TITLE
Select a module button is not properly Visible in Mobile mode

### ISSUE THREAD

**Issue by vaibhavmatta** [publiclab/image-sequencer#1282]
## What do we expect?
Dimensions for *Select a module* button should be changed such that the text inside button is fully visible.

## Where to look?

![WhatsApp Image 2019-10-28 at 8 26 05 PM](https://user-images.githubusercontent.com/50797619/67689695-b4de9080-f9c1-11e9-9292-fec2107d9c18.jpeg)

**Comment by HarshKhandeparkar** [comment]
It is visible. See https://beta.sequencer.publiclab.org. In the future too, please do not refer to the main site as it is outdated though stable. Thanks!

**Comment by vaibhavmatta** [comment]
@HarshKhandeparkar I am sure that this issue is still not s=resolved on BEta as well. See I've updated the issue body above, I've marked the main site of issue in that image.

**Comment by vaibhavmatta** [comment]
@HarshKhandeparkar We both are using same device and then too 😂

**Comment by HarshKhandeparkar** [comment]
Are you using a non-conventional size device? Like an ipad or one of those
laptop cum tablet devices?

**Comment by vaibhavmatta** [comment]
Nah.! Oneplus phone

**Comment by HarshKhandeparkar** [comment]
Lol. How? Chrome browser too? What is happening to this world? Did you
clear the cache? Reload the website? Maybe restart your device(jk)

**Comment by vaibhavmatta** [comment]
haha.. Lemme try again 😂

**Comment by vaibhavmatta** [comment]
You were ryt @HarshKhandeparkar . Sorry for the trouble 😅
