### ISSUE TITLE
Add Save as PDF option to export the processed image

### ISSUE THREAD

**Issue by vaibhavmatta** [publiclab/image-sequencer#1284]
Note: **Please note we are preparing to participate in Google Code-in, and have reserved this issue for GCI participants - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

### Save as PDF
In order to save maximum printable quality of the processed image, SAVE AS PDF option should be added along with other Export options.

##### See the image below!
<img width="907" alt="Screenshot 2019-10-28 at 10 35 41 PM" src="https://user-images.githubusercontent.com/50797619/67700081-4d314100-f9d3-11e9-9c59-6765e6ea2973.png">

**Comment by debck** [comment]
@keshav234156 I think we can add this as a GCI task. What's your view on this?

**Comment by vaibhavmatta** [comment]
@debck I will be adding this by today.!

**Comment by debck** [comment]
**Uploaded to dashboard**

**Comment by SidharthBansal** [comment]
Published on GCI dashboard
