### ISSUE TITLE
Remove overlapping of button and dropdown

### ISSUE THREAD

**Issue by debck** [publiclab/image-sequencer#1287]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

The `select module` dropdown and the `Add step` button are overlapped

![123](https://user-images.githubusercontent.com/33368759/67857472-e92a8c00-fb3c-11e9-8f2e-698d47fd5551.PNG)

> What did you expect to see that you didn't?

Both the elements should have proper alignment between them.

### Please show us where to look

https://sequencer.publiclab.org/examples/#steps=

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by keshav234156** [comment]
@debck this issue has been fixed recently.please use beta version as it updated frequently.feel free to reopen the issue

**Comment by debck** [comment]
@keshav234156 got it, Thanks
