### ISSUE TITLE
Downloading image after modules contianing external links is applied

### ISSUE THREAD

**Issue by keshav234156** [publiclab/image-sequencer#1288]
Please Note:  **We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more**

Downloading modules contianing external links redirects to that link.the modules that are having external  links are ndvi,gamma-correction,edge-detect,dynamic,dither,convolution

the file where the changes are to be made is
https://github.com/publiclab/image-sequencer/blob/cff82c998f351907e724a7151670885745100066/examples/lib/defaultHtmlStepUi.js#L284-L298

![Untitled_ Oct 31, 2019 3_09 AM](https://user-images.githubusercontent.com/45951376/67901212-3f72eb80-fb8c-11e9-83f5-0406a7f5df1b.gif)

**Comment by keshav234156** [comment]
cc: @jywarren @HarshKhandeparkar

**Comment by HarshKhandeparkar** [comment]
This is a weird one. Should we make this a candidate for GCI?

**Comment by HarshKhandeparkar** [comment]
@keshav234156 @vaibhavmatta @jywarren

**Comment by keshav234156** [comment]
@SidharthBansal

**Comment by keshav234156** [comment]
**Uploaded on GCI dashboard**

**Comment by SidharthBansal** [comment]
Please hide stale comments.

**Comment by SidharthBansal** [comment]
PUBLISHED

**Comment by SidharthBansal** [comment]
Sorry I clicked on close
