### ISSUE TITLE
notify user that the CLI won't be synchronous (yet)

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#129]
It was a little confusing at first that the CLI doesn't synchronously complete. For now, let's just tell the user that it'll execute asynchronously and that you won't see the output for a moment depending on the filesize and number of steps. Then let's implement a synchronous CLI in #130!

**Comment by tech4GT** [comment]
@jywarren  I would like to work on this issue

**Comment by tech4GT** [comment]
@jywarren do we just want to prompt the user?

**Comment by jywarren** [comment]
Hi! I think we could just output a message as soon as the command is executed. That way it doesn't look like the command just ended and there was no result. We should make it clear that it may take seconds or minutes for the command to complete.

Thanks so much for your help!
