### ISSUE TITLE
Overlapping of the dragzone with the image in import image module

### ISSUE THREAD

**Issue by keshav234156** [publiclab/image-sequencer#1294]
**Please Note: We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more**
### What's the problem (or idea)
The dragzone is overlapping the image in the import module
![Screenshot from 2019-11-09 17-10-47](https://user-images.githubusercontent.com/45951376/68528056-1d0f6980-0314-11ea-816c-f7a39cbb89de.png)

### What should be done?
We can add a new class  to the following div element
https://github.com/publiclab/image-sequencer/blob/cff82c998f351907e724a7151670885745100066/src/modules/ImportImage/Ui.js#L11
and it's corresponding style in 
https://github.com/publiclab/image-sequencer/blob/cff82c998f351907e724a7151670885745100066/examples/demo.css#L62
The final result should be 
![Screenshot from 2019-11-14 00-42-49](https://user-images.githubusercontent.com/45951376/68796523-0735d780-0679-11ea-82c7-f2a67163319f.png)

### Where to look
https://beta.sequencer.publiclab.org/examples/#steps=import-image{}

**Comment by SidharthBansal** [comment]
Please explain the issue!
