### ISSUE TITLE
Selected value of the drop-down is not displayed

### ISSUE THREAD

**Issue by keshav234156** [publiclab/image-sequencer#1295]
**Please Note: We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more**

Selected value from the dropdown is not being displayed in the histogram module
![Screenshot from 2019-11-12 00-43-42](https://user-images.githubusercontent.com/45951376/68613843-a9bd5180-04e5-11ea-8bad-9d5b824d5887.png)

**Comment by keshav234156** [comment]
**UPLOADED ON GCI DASHBOARD**

**Comment by Uzay-G** [comment]
Hey @keshav234156, this works for me on mobile:

![Screenshot_2019-12-21-23-56-31](https://user-images.githubusercontent.com/52892257/71314708-b53d5a00-244d-11ea-804c-8088b3b6d4e5.png)

But on computer I can't even select a module:
![is-bug](https://user-images.githubusercontent.com/52892257/71314717-d4d48280-244d-11ea-8c33-b3cf018c4def.png)

**Comment by keshav234156** [comment]
@Uzay-G when you change the value of dropdown and then click apply button then selected value disappears.Hope it clears your doubt?
Also please claim the task related to this issue before working on it.Thanks!!!!
