### ISSUE TITLE
Make effect selection from the grid in intermediate steps working

### ISSUE THREAD

**Issue by urvashigupta7** [publiclab/image-sequencer#1299]
Dropdown works but the grid for selecting the effect  is not working when intermediate steps are added.
<img width="600" alt="C" src="https://user-images.githubusercontent.com/41363633/69049615-5176da00-0a26-11ea-8ebb-a2a8e9d93abf.PNG">

**Comment by keshav234156** [comment]
@urvashigupta7 this issue has been fixed recently.please use beta version as it is updated frequently.
