### ISSUE TITLE
Colorbar acts awry

### ISSUE THREAD

**Issue by ccpandhare** [publiclab/image-sequencer#13]
When a Colorbar module is applied, It Makes the entire page (HTML) slow. Also after adding a colorbar module, results of adding other modules is undesirable.

Should we implement a better alternative?

**Comment by jywarren** [comment]
I think we may need to think about the plotly module differently. It also
causes building to be super slow and I don't think we should need to
compile it into the library.

Maybe we should think about "terminating" modules which you can't chain
things after? Also, modules with external dependencies and how to work with
those...

**Comment by jywarren** [comment]
I think this is solved now that we no longer use the plotly library!
