### ISSUE TITLE
Insert Button In load image step

### ISSUE THREAD

**Issue by harshithpabbati** [publiclab/image-sequencer#1300]
Please Note:  **We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more**

### Problem 

We don't have an insert button in the load image step.
The insert button will be disabled until the user adds a new module after the load image.

<img width="934" alt="Screenshot 2019-11-18 at 11 04 37 PM" src="https://user-images.githubusercontent.com/43822585/69075633-ce6e7780-0a57-11ea-84c2-a64d736a8911.png">

**Comment by debck** [comment]
**Uploaded to Dashboard**

**Comment by SidharthBansal** [comment]
Published

**Comment by HarshKhandeparkar** [comment]
I have accepted this task on the dashboard.

**Comment by HarshKhandeparkar** [comment]
Hi
I noticed there are tons of bugs with the insert step functionality itself and I managed to fix it all. Should I commit it along with this PR or separately? 
NOTE: This PR does not work without the extra fixes.

**Comment by HarshKhandeparkar** [comment]
@publiclab/is-reviewers

**Comment by keshav234156** [comment]
@HarshKhandeparkar what was broken in insert step functionality we have fixed it recentely?

**Comment by HarshKhandeparkar** [comment]
I have mentioned what was broken in the PR.

**Comment by keshav234156** [comment]
coudn't get that

**Comment by HarshKhandeparkar** [comment]
Even the GIF? Look at it carefully, fullscreen. The previews disappear.

**Comment by keshav234156** [comment]
oh That was when we have preview opened at two different steps.Have you fixed that

**Comment by HarshKhandeparkar** [comment]
Yup.

**Comment by HarshKhandeparkar** [comment]
See then next GIF.

**Comment by keshav234156** [comment]
It would be better if you open a separate issue and PR that so that it would be easier to give points to you
