### ISSUE TITLE
Remove `undefined` from the processed drop-down

### ISSUE THREAD

**Issue by debck** [publiclab/image-sequencer#1303]
### Please describe the problem (or idea)

When we try to insert a step, a block appears asking us  to `Select a new module to add to your sequence.` 
This dropdown gives many `undefined` value.

![Screenshot (43)_LI](https://user-images.githubusercontent.com/33368759/69449366-c9276a80-0d80-11ea-85c8-5861253f626e.jpg)

### Please show us where to look
https://beta.sequencer.publiclab.org

****

**Comment by debck** [comment]
**Uploaded on GCI dashboard**

**Comment by keshav234156** [comment]
@debck this issue has already been fixed with the #1266 .please use beta version.if you are using beta version then try to clear offline cache to see the changes. @SidharthBansal @debck please remove the task related to this issue.

**Comment by debck** [comment]
Got it. 
@SidharthBansal Could you please delete it from the dashboard?

**Comment by SidharthBansal** [comment]
Can you please reformat it to non-gci?
Also, don't you have access to delete the tasks?

**Comment by debck** [comment]
This issue is already solved so we can close it. Also, I don't have access to delete tasks over dashboard.
