### ISSUE TITLE
Dropdown doesn't close on click

### ISSUE THREAD

**Issue by keshav234156** [publiclab/image-sequencer#1307]
**Please note we are preparing to participate in Google Code-in, and have reserved this issue for GCI participants - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

### Please describe the problem (or idea)

Currently dropdown is not closing when you click on the dropdown icon

### What did you expect to see that you didn't?
 The dropdown should close when dropdown icon is clicked

### Please show us where to look

https://beta.sequencer.publiclab.org

![Untitled_ Nov 26, 2019 7_30 PM](https://user-images.githubusercontent.com/45951376/69640420-5241e880-1084-11ea-9b50-8fd451ac9e23.gif)

**Comment by keshav234156** [comment]
**UPLOADED ON GCI DASHBOARD**

**Comment by SidharthBansal** [comment]
PUBLISHED ON GCI

**Comment by CodeSarthak** [comment]
Hi @keshav234156 @SidharthBansal can someone point me to the HTML/JS files? I am having trouble finding them.

**Comment by SidharthBansal** [comment]
@HarshKhandeparkar can you please help. I am not specialized in IS

**Comment by keshav234156** [comment]
@CodeSarthak Thanks for showing your interest in this issue.But @tsparksh has already claimed this task GCI dashboard.So can you please work on some other task

**Comment by CodeSarthak** [comment]
Sure @keshav234156 

All the best @tsparksh

**Comment by HarshKhandeparkar** [comment]
@CodeSarthak there are many other issues that may interest you. Good luck.

@tsparksh you can ask here if you face any difficulty.

**Comment by SidharthBansal** [comment]
Great coordination folks! I really appreciate the helping gesture!
