### ISSUE TITLE
Mesage notification for "Add Step"

### ISSUE THREAD

**Issue by lohitha02** [publiclab/image-sequencer#1310]
### Mesage notification for "Add Step"

Currently when we are clicking on "Add Step" option without selecting a module it simply shows nothing.

Instead when we are clicking on "Add Step" option without selecting a module it should show a message notification stating that "Please select a module first".  

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by SidharthBansal** [comment]
Please add issue description

**Comment by lohitha02** [comment]
Sure will update it.

**Comment by ataata107** [comment]
As gci is over can i work on this

**Comment by vivek-30** [comment]
@HarshKhandeparkar I have finished this one as well so can i open a PR for this 😅  .

**Comment by HarshKhandeparkar** [comment]
Launch it!

**Comment by vivek-30** [comment]
Ok @HarshKhandeparkar and thanks a lot ☺️
