### ISSUE TITLE
Multiple selection of modules from Add step is not working

### ISSUE THREAD

**Issue by lohitha02** [publiclab/image-sequencer#1313]
### Bug

On selecting a particular module and the step is loaded, we are not able to select the same module again, but it is working from the quick buttons.

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by keshav234156** [comment]
@lohitha02 can you please upload a GIF. It will help in better understanding of the issue

**Comment by HarshKhandeparkar** [comment]
What do you mean by *selecting* the same module again? Selecting from the dropdown(it is already selected)? Moreover, I was able to add the same module again.


![selectin-again](https://user-images.githubusercontent.com/34770591/69913241-6e1a0580-145b-11ea-90e7-f59688302ded.gif)

**Comment by HarshKhandeparkar** [comment]
Fixed.
