### ISSUE TITLE
Leftmost "resize quick button" not properly displayed.

### ISSUE THREAD

**Issue by Divy123** [publiclab/image-sequencer#1314]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

Currently, the first option in the quick buttons is not properly displayed.

### Please show us where to look

https://beta.sequencer.publiclab.org

### What's your PublicLab.org username? 
lit2017001

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.

**Comment by Divy123** [comment]
This may help understand better here:

<img width="508" alt="Screenshot 2019-11-30 at 2 54 40 AM" src="https://user-images.githubusercontent.com/31225007/69890839-1fb31c80-131e-11ea-8200-e53cb47f3368.png">

**Comment by Divy123** [comment]
uploaded on gci dashboard.

**Comment by Divy123** [comment]
@SidharthBansal please do publish it.

**Comment by SidharthBansal** [comment]
Please add code links

**Comment by SidharthBansal** [comment]
Also, please reformat this to FTO if it is beginner issue. We don't use easy. We use beginner label.

**Comment by SidharthBansal** [comment]
Published it on the gci dashboard
