### ISSUE TITLE
Make "clear offline cache button" blue in colour

### ISSUE THREAD

**Issue by Divy123** [publiclab/image-sequencer#1318]
**Please note we are preparing to participate in Google Code-in, and have reserved this issue for GCI participants - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open-source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

This issue requires to make "clear offline cache button" blue in color so that it looks like a button which currently it does not.

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update**

- [ ] This issue requires you to change the color of the "add step" button to blue to maintain consistency in UI. 

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming the first-timers-only issue. We're happy to keep it assigned to you as long as you need it if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by Divy123** [comment]
Uploaded on gci dashboard.

**Comment by SidharthBansal** [comment]
Published

**Comment by EC3x1903** [comment]
Hi, I would like to claim this task for GCI. It's still available, yes?

**Comment by HarshKhandeparkar** [comment]
I guess yes. If no one has claimed to have accepted the issue here, on GitHub then the issue is up for grabs.

**Comment by harshkhandeparkar** [comment]
> @publiclab/is-reviewers can I take this issue, if at all I can, since this seems to be a first timers issue?

Since you have already opened your first PR, it would be better if you leave this one for others :)

**Comment by COOL26** [comment]
Hello sir, I am Harsh Sharma from India and I am a noob programmer. I never contributed to any open-source project before. Please help me make my first ever open source commit to this project. I have a beginner-level knowledge of git and GitHub. Can you guide me on how I can solve this issue from my side?

**Comment by jywarren** [comment]
Hi @COOL26 -- sure, would you like to try editing this line? 

https://github.com/publiclab/image-sequencer/blob/4d4cca86183a3e6a0d0fb36abf287d758a7ffac8/examples/index.html#L224

You could change the class `btn-default` to `btn-primary` to get a blue color. 

I think it would also be great to move it down to this row!

https://github.com/publiclab/image-sequencer/blob/4d4cca86183a3e6a0d0fb36abf287d758a7ffac8/examples/index.html#L244

See how the button is above, and the version number is below? I'd love if the button appeared below the version number. 

<img width="1052" alt="image" src="https://user-images.githubusercontent.com/24359/213771754-f0bcd88e-897f-4b18-8805-a933771b958b.png">

You can view this running at https://sequencer.publiclab.org/

What do you think?

**Comment by COOL26** [comment]
Ok, @jywarren sir, let me try. If I face any difficulty I will contact you. As I am too new, I apologise in advance if I ask any dumb-sounding questions. :)

**Comment by COOL26** [comment]
Hello @jywarren sir, I have created a pull request, satisfying the changes as per your guidance. Please check and give your feedback.
Thank you

**Comment by jywarren** [comment]
Thank you!! Solved in https://github.com/publiclab/image-sequencer/pull/2200
