### ISSUE TITLE
fix CLI --options parameter and add example

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#132]
First a quick typo: `    -op, --opions {object}  Options for the step` "opions" should be "options" -- but also this did not seem to work for me; perhaps I'm formatting it wrong. The instructions should have a more complete example of setting options, and also how options are set for a specific step (if that's possible). 

Thanks!

**Comment by tech4GT** [comment]
@jywarren  i would like to work on this

**Comment by jywarren** [comment]
ooh, that would be great! Thanks!
