### ISSUE TITLE
Add lightening bolt icon at the top of step panel to show if the step is wasm accelerated.

### ISSUE THREAD

**Issue by Divy123** [publiclab/image-sequencer#1320]
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

Add lightening bolt icon at the top of step panel to show if the step is wasm accelerated.

### Please show us where to look

https://beta.sequencer.publiclab.org

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.

**Comment by Divy123** [comment]
Though this issue is preferred for GCI candidates, others may also give it a try.

**Comment by Divy123** [comment]
Uploaded on gci dashboard.

**Comment by SidharthBansal** [comment]
This issue is reserved for GCI only. Published on GCI website

**Comment by HarshKhandeparkar** [comment]
I just claimed this task. :smile:
