### ISSUE TITLE
Disable take a photo and choose a file button while camera is open

### ISSUE THREAD

**Issue by Divy123** [publiclab/image-sequencer#1321]
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

This issue requires disabling "take a photo button" and "choose a file" button while clicking a picture.

Thanks!!

**Comment by SidharthBansal** [comment]
Published

**Comment by lohitha02** [comment]
I think we need to disable "choose a file" button also while clicking a picture? do I need to open an issue regarding this?

**Comment by SidharthBansal** [comment]
I think you should edit this issue

**Comment by Divy123** [comment]
@SidharthBansal  edited. Please do publish it.

**Comment by SidharthBansal** [comment]
Please add code links

**Comment by Ryan10145** [comment]
I am working on this (I have claimed the respective task in the GCI dashboard).
