### ISSUE TITLE
"Rotate " module changing original dimensions of image

### ISSUE THREAD

**Issue by Divy123** [publiclab/image-sequencer#1322]
Note: **We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

The rotate module is changing the original dimensions of image, though it should only rotate the same.

### Please show us where to look

https://beta.sequencer.publiclab.org

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.

**Comment by Divy123** [comment]
Uploaded on GCI dashboard.

**Comment by keshav234156** [comment]
@Divy123 have you tried the new rotate module. Changes could be seen in beta version

**Comment by SidharthBansal** [comment]
Published on GCI dashboard

**Comment by SidharthBansal** [comment]
On request of @keshav234156 I have unpublished this task as someone else is working on this.
Thanks for informing me Keshav!

**Comment by keshav234156** [comment]
@keshav234156 it was fixed by #1218

**Comment by SidharthBansal** [comment]
Do I need to delete this task from the dashboard then?

**Comment by SidharthBansal** [comment]
@keshav234156

**Comment by SidharthBansal** [comment]
@keshav234156

**Comment by HarshKhandeparkar** [comment]
fixed.
