### ISSUE TITLE
"Resize" module not working for the given dimensions

### ISSUE THREAD

**Issue by lohitha02** [publiclab/image-sequencer#1323]
### Please describe the problem (or idea)
 The image remians unchanged irrespective of what the size is
![photo_2019-12-01_13-09-32](https://user-images.githubusercontent.com/43813629/69911120-71ea5f80-143c-11ea-945e-b61f48451e6f.jpg)

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by HarshKhandeparkar** [comment]
What is the expected output? Maybe it is the CSS that makes the image **look** smaller?

**Comment by keshav234156** [comment]
@lohitha02, once you download the image you can size of the downloaded image is changed  in comparison to the original image

**Comment by HarshKhandeparkar** [comment]
The image is changing but is scaled back by the UI. Not relevant anymore.
