### ISSUE TITLE
Install image-sequencer on local machine

### ISSUE THREAD

**Issue by keshav234156** [publiclab/image-sequencer#1324]
**Note: We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

Install and successfully setup image-sequencer on your local machine. Submit a screenshot of running on the localhost.

Share the issues you encounter along the way.
Please have a look at
https://github.com/publiclab/image-sequencer/blob/main/README.md#installation

**Comment by fluctix** [comment]
![Capture](https://user-images.githubusercontent.com/40538506/70312322-6f6f7780-1839-11ea-8ee5-c08fb7034cc7.PNG)

**Comment by keshav234156** [comment]
@fluctix can you please claim the task on GCI dashboard and upload a screenshot on GCI dashboard.
