### ISSUE TITLE
add "--simple" or "--single" mode to CLI, so you just get the final image

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#133]
This could be `--simple -s` or `--single -s` -- not sure, but we should have a commandline option that makes it work more like ImageMagick's `convert` -- abandoning for this mode the folder of sequential images and just outputting the final image. This, in concert with #130, will make it a really useful and familiar utility for those used to `convert`.

Bonus followup -- make a wrapper which emulates syntax in the style of `convert`!

**Comment by tech4GT** [comment]
I would like to work on this in concert with #130

**Comment by jywarren** [comment]
Great, thanks!!!
