### ISSUE TITLE
Allow saving onto PublicLab.org

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#1332]
PublicLab.org now allows (if you're logged in) for opening an image into the editor at https://publiclab.org/post (again, must be logged in)

The docs for this are here: https://github.com/publiclab/plots2/issues/6594#issuecomment-562389677

And I've just completed this in Infragram, here:

https://github.com/publiclab/infragram/commit/7ca92dbf9f630f6010847c26f770cbada7e5a454

So, we should add one more type to the ImageSequencer "Save" box, which is "Save to PublicLab.org" -- shown here:

![image](https://user-images.githubusercontent.com/24359/70355422-10f9c780-1840-11ea-9ac8-191095b93047.png)

Once you do this, you should see the https://PublicLab.org/post editor open, like this:

![image](https://user-images.githubusercontent.com/24359/70355495-50281880-1840-11ea-977c-687d975bfe83.png)

You can test this out by pasting the following code into the console in https://sequencer.publiclab.org --

```js
function postToPL(imgSrc) {
  var uniq = Date.now();
  $('body').append('<form method="post" id="postToPL' + uniq + '" action="https://stable.publiclab.org/post" target="postToPLWindow"><input type="hidden" name="datauri_main_image" /></form>');
  f = $('#postToPL' + uniq)[0];
  f.datauri_main_image.value = imgSrc;
  window.open('', 'postToPLWindow');
  f.submit();
}
postToPL($('img')[0].src)
```

**Comment by keshav234156** [comment]
@jywarren can I help you here?

**Comment by keshav234156** [comment]
@jywarren I just tried the console method but it says **You must be logged out to access this page** .Do you why?

**Comment by jywarren** [comment]
Ah, i think at the moment you'd done it, the latest version of PublicLab.org hadn't published yet. Can you try now?

**Comment by jywarren** [comment]
And yes, it'd be great to have help on this one! Thanks!

**Comment by keshav234156** [comment]
No can't login when i try to access https://stable.publiclab.org/post it redirects me to https://publiclab.org/home?return_to=%2Flogin  which says **you must be logged out to access this page**. Is this problem account specific?

**Comment by jywarren** [comment]
It's live on publiclab.org now so you only have to be logged in there now!
But for your earlier error you would have had to separately sign up at
stable.publiclab.org!

**Comment by keshav234156** [comment]
Oh!!got it .meanwhile i also a made a PR regarding this #1334
