### ISSUE TITLE
`sudo npm run setup` root owned files

### ISSUE THREAD

**Issue by chen-robert** [publiclab/image-sequencer#1336]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### Problem

`sudo npm run setup` as described in the README.md will create root owned files, which can break the next step of `npm start`.

![image](https://user-images.githubusercontent.com/20526314/70398233-33215000-19ce-11ea-823f-a7ff9df26b10.png)

![image](https://user-images.githubusercontent.com/20526314/70398247-47fde380-19ce-11ea-943d-ed5f838d94f7.png)

### 📋Solution

Move the `sudo` inside the `setup` script. To do this, modify https://github.com/publiclab/image-sequencer/blob/main/package.json#L10 
```
"setup": "npm i && sudo npm i -g grunt grunt-cli && grunt build",
```

You should also update the instructions in README.md, specifically the line about 
```
You can set up a local environment to test the UI with sudo npm run setup followed by npm start.
``` 
changing `sudo npm run setup` to `npm run setup`.

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update**

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

**Comment by chen-robert** [comment]
@rexagod @lohitha02 @jywarren Could this be a possible FTO? Thanks!

**Comment by jywarren** [comment]
Sure! @harshkhandeparkark what do you think?

**Comment by Marcus-auz** [comment]
If no one is working on this,i would like to work on it .

**Comment by HarshKhandeparkar** [comment]
@jywarren @chen-robert According to the npm docs, npm install should never be run using `sudo`. There are other ways of fixing the global installation error. https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

**Comment by HarshKhandeparkar** [comment]
This is an npm side and client-specific issue.
