### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by md37** [publiclab/image-sequencer#1348]
When I ran sudo npm run setup, I got that error:
Running "browserify:core" (browserify) task
>> Error: Cannot find module './utils' from '/home/md37/image-sequencer/node_modules/gpu.js/dist'
Warning: Error running grunt-browserify. Use --force to continue.

Aborted due to warnings.

npm ERR! Linux 5.0.0-37-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "setup"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! image-sequencer@3.5.1 setup: `npm i && npm i -g grunt grunt-cli && grunt build`
npm ERR! Exit status 6
npm ERR! 
npm ERR! Failed at the image-sequencer@3.5.1 setup script 'npm i && npm i -g grunt grunt-cli && grunt build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the image-sequencer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm i && npm i -g grunt grunt-cli && grunt build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs image-sequencer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls image-sequencer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/md37/image-sequencer/npm-debug.log

**Comment by HarshKhandeparkar** [comment]
hmm. @md37 can you try running `npm rebuild`? If that doesn't fix it, I will search for a solution myself. This is not an issue of IS but rather of a dependency. Sorry if you are facing trouble. 

The last thing you can try is deleting the directory and reinstalling.

**Comment by md37** [comment]
No, that doesn't fix it.

**Comment by HarshKhandeparkar** [comment]
Sorry for the inconvenience. Could you please check the package.json and tell me the version of the gpu.js used? Maybe we can degrade the version and check if the issue is resolved.

**Comment by HarshKhandeparkar** [comment]
@md37 I found the error. It is a library issue. In the meanwhile, you can run `npm install gpu.js@2.2.0`. The dev will fix it. We have to bump the version anyway. The new version fixes many things.

**Comment by robertleeplummerjr** [comment]
I believe this is the droid you are looking for: https://github.com/publiclab/image-sequencer/pull/1356
