### ISSUE TITLE
Add Commenting Guidelines to CONTRIBUTING.md

### ISSUE THREAD

**Issue by harshkhandeparkar** [publiclab/image-sequencer#1354]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open-source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### What is to be done?
We are working towards standardizing all the comments in the codebase to make the docs look professional. One of the main steps towards this would be to add some guidelines to the CONTRIBUTING.md file. Some guidelines are listed below (you can add your own too if you feel it is necessary)

1. Methods must be described using [JSDoc comments](https://devdocs.io/jsdoc/)
2. Misc code comments should be inline unless it is a long sentence.
3. No use of continuous tenses, no pronouns.
4. No redundant comments.
5. Each comment should start with an uppercase letter and end with a full stop.

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 Modify the file [CONTRIBUTING.md]

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need it if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by HarshKhandeparkar** [comment]
@SidharthBansal @publiclab/is-reviewers is this a good GCI candidate?

**Comment by HarshKhandeparkar** [comment]
Can this one be published upon approval?

**Comment by Alejandroid101** [comment]
has somebody taken this? is there a PR?

**Comment by SidharthBansal** [comment]
Yeah go for it. @HarshKhandeparkar  it will be great to divide responsibilities. You can create ftos for non gci folks. Some students can do for gci

**Comment by HarshKhandeparkar** [comment]
Ok sure. @Alejandroid101 go for it. You can ask here or the gitter channel if you are stuck at any point.

**Comment by SharmaTanish** [comment]
Hi @HarshKhandeparkar  ! I am very exited to work on this issue , if it is still open . I have learnt web development from coding ninjas and all my basic concepts are clear . I am very hardworking and have scored 94.2% in 12th . You can also go through my linkedIn profile - https://www.linkedin.com/in/tanish-a54b771b3 .
Looking forward for your reply .

**Comment by HarshKhandeparkar** [comment]
You can only do one issue labeled with `first-timers-only` because you won't be a first-timer once you do one :smile:. You can select either one of these :)

**Comment by Vedavyas11062004** [comment]
Hi @harshkhandeparkar,I want to work on this issue does any one already working on it.

**Comment by harshkhandeparkar** [comment]
> Hi @harshkhandeparkar,I want to work on this issue does any one already working on it.

Sure, go ahead!
