### ISSUE TITLE
Add comments to PR_TEMPLATE 

### ISSUE THREAD

**Issue by pythongiant** [publiclab/image-sequencer#1355]
### Please describe the problem (or idea)

The PR_TEMPLATE Currently has details that could be commented. for example 

> Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

This could be commented. [Here](https://stackoverflow.com/questions/4823468/comments-in-markdown)'s how you add comments in markdown.

**Comment by keshav234156** [comment]
@pythongiant why we need to comment this?

**Comment by HarshKhandeparkar** [comment]
So that they don't appear in the PR body. They are just instructions for the writer, not the reader.

**Comment by YogeshSharma01** [comment]
@pythongiant can I work on this?

**Comment by KarishmaVanwari** [comment]
@publiclab/is-reviewers  Can I take up this issue?

**Comment by harshkhandeparkar** [comment]
> @publiclab/is-reviewers Can I take up this issue?

Go ahead!

**Comment by KarishmaVanwari** [comment]
I've created a PR #2068 . Please do have a look @harshkhandeparkar.
