### ISSUE TITLE
Data model diagram in README

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#136]
Like this one: https://github.com/publiclab/plots2/blob/master/doc/DATA_MODEL.md

I posted a copy of that here for us to work in: https://docs.google.com/presentation/d/1HGUmthisJ_3p7lcq23_umtiLOSDoxpvb5TWoEQSvC68/edit

**Comment by jywarren** [comment]
OK, here's one we can start with -- i'm trying to show why `sequencer` doesn't just have a `sequencer.steps` property. This helps explain that:

![screenshot 2017-10-05 at 5 42 34 pm](https://user-images.githubusercontent.com/24359/31255882-db5c347a-a9f4-11e7-92dd-76cdadf9de1f.png)

**Comment by ccpandhare** [comment]
That looks really nice and certainly helps in making the user understand more of it.
Which tool did you use to make this?

**Comment by gauravano** [comment]
@jywarren idea looks great. @tech4GT you might want to look at it. Thanks!

**Comment by IgorWilbert** [comment]
Hey! I want to solve a `help-wanted` issue and this one seems to be really fun! May I take it, please?

**Comment by jywarren** [comment]
Yes please! Note that there are some diagramming templates and possibly
helpful starting points in these docs:

https://docs.google.com/presentation/d/1TCZoTfuhamRVrUak8aDgqJAwSgyhRtZg2Pgacl2_4zc/edit?usp=drivesdk

https://publiclab.org/notes/warren/01-27-2017/diagramming-knowledge-production-on-publiclab-org
