### ISSUE TITLE
Expand out offline app features for smoother cache clearing and version tracking

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#1364]
#890 #349 started making a lot of offline webapp (Progressive Web App or PWA) improvements, which is great;

#605 #761 also get at a lot of these, and the issues we'd like to improve on. 

I'd like to suggest we go through and implement each of the recommendations from this blog post, so as to make cache and version management very clear:

https://publiclab.org/notes/warren/08-19-2019/ui-principles-for-offline-apps

The key parts are:

1. displaying a version number unobtrusively at the bottom of the page (an NPM version number AND/OR a publication date, or at least a Git hash)
2. displaying a banner or a prompt to refresh the page once a new version has successfully been fetched
3. consider displaying a version number faintly in the upper right corner, or by the page title, so that screenshots of the app can capture it

Right now, we only see this, and this `v3` never changes -- so we have no idea a) if it needs clearing and b) what version we are on and c) what version is available. Let's solve this!

![image](https://user-images.githubusercontent.com/24359/70953573-c21a1200-2037-11ea-941f-bccb5a719e68.png)

**Comment by SidharthBansal** [comment]
Published

**Comment by HarshKhandeparkar** [comment]
I want to claim this task but I can't find it on the dashboard. Is it published?

**Comment by anthony-zhou** [comment]
@HarshKhandeparkar I already claimed the task and am working on it.

**Comment by HarshKhandeparkar** [comment]
No problem. No one claimed it on github so I thought it was not claimed
yet. Good luck.
