### ISSUE TITLE
Clarify and consolidate the "step" object that's passed to UI and document its API

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#137]
I've started work on this in https://github.com/publiclab/image-sequencer/pull/135/, but just trying to make the standard `info.json` from each module available in the `step` paramter passed to each UI handler. This will allow the UI access to the `description` and `url` fields in `info.json`, and generally make the assembly and composition of the `step` object more clear in code and documentation.

**Comment by jywarren** [comment]
Can we link to the exact areas of code that drive the behavior and API described here, @ccpandhare -- https://github.com/publiclab/image-sequencer#creating-a-user-interface

(when you're available, i know you're busy at the moment!)

**Comment by ccpandhare** [comment]
Sure

**Comment by ccpandhare** [comment]
Actually, I don't fully get you. What did you mean to say here, again, please?

**Comment by jywarren** [comment]
This could be reworked along the lines of #242 -- a clear API you can use when writing UIs.

**Comment by HarshKhandeparkar** [comment]
Works!
