### ISSUE TITLE
Python 2 Support

### ISSUE THREAD

**Issue by ataata107** [publiclab/image-sequencer#1370]
When i was building the project in windows I was getting this error

`print "%s.%s.%s" % sys.version_info[:3];`  Invalid Syntax

I figured out that this was due to powershell using python3 instead of 2. I changed the version to 2 and it was working.

My doubt is that is this project dependent on python2 and if yes than we could add that to the readme.md or try to shift the dependencies to python3.
Thanks...

**Comment by HarshKhandeparkar** [comment]
Do you know which dependency uses python? I don't think the main library does.

**Comment by ataata107** [comment]
node-gyp I guess is dependent on python2

**Comment by HarshKhandeparkar** [comment]
Is that a sub-dependency? If yes, which is the main one?

**Comment by HarshKhandeparkar** [comment]
We can't really fix these issues ourselves.
