### ISSUE TITLE
HTML <input> Types for Module Inputs are Incorrect

### ISSUE THREAD

**Issue by HarshKhandeparkar** [publiclab/image-sequencer#1373]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open-source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new** and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### What is to be done?
Some time back, we tried to match HTML <input> tag types(Number, Range, Text) with the standard javascript input types(integer, float, string) for modules.

But the code is a bit buggy

![Screenshot from 2019-12-19 22-56-09](https://user-images.githubusercontent.com/34770591/71194872-c30aa800-22b2-11ea-890e-47788eb4507b.png)
As can be seen from the above picture, the first contrast step uses the input type "range" whereas the second is just "text".

You will have to fix this error.

You can refer to:
1. https://github.com/publiclab/image-sequencer/blob/main/examples/lib/mapHtmltypes.js
2. https://github.com/publiclab/image-sequencer/blob/b7d5a98cdb479835e91295a14c94f405348efaad/examples/lib/defaultHtmlStepUi.js#L84 and onwards
3. https://github.com/publiclab/image-sequencer/blob/main/src/modules/Blur/info.json
4. https://github.com/publiclab/image-sequencer/blob/main/src/modules/Dither/info.json

You can also refer to other info.json files.

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 Modify the file [mapHtmlTypes.js](https://github.com/publiclab/image-sequencer/blob/main/examples/lib/mapHtmltypes.js). You can refer to other files but the final changes are to be made to this file.

:bulb:**HINT:** One of the `Object`s is directly changed, instead it needs to be cloned, changed and returned.
**NOTE**: The final change is very small but the error can be difficult to find, so don't give up. (ever!)

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need it if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by HarshKhandeparkar** [comment]
@publiclab/is-reviewers please approve.

**Comment by ataata107** [comment]
I would like to work on this will submit a PR by today

**Comment by ataata107** [comment]
#1379 fixes this issue
