### ISSUE TITLE
Fix Module Tests

### ISSUE THREAD

**Issue by HarshKhandeparkar** [publiclab/image-sequencer#1376]
### Please describe the problem (or idea)
This is a sub-issue of #1375 

Tests for the following modules fail and need to be fixed:
- [ ] Colorbar
- [ ] Draw Rectangle
- [ ] Gamma Correction
- [ ] Paint Bucket
- [ ] Replace Color
- [ ] Rotate
- [ ] Tint

These tests fail either because the modules are updated or otherwise. These need to be fixed.

### Please show us where to look

https://beta.sequencer.publiclab.org

### What's your PublicLab.org username?

> This can help us diagnose the issue:

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by keshav234156** [comment]
I am now working  on it

**Comment by HarshKhandeparkar** [comment]
I know how to fix the tests. I just haven't committed the code yet...

**Comment by keshav234156** [comment]
Can i fix now i have started to work?

**Comment by HarshKhandeparkar** [comment]
Sure. You can pull from my branch. Close this PR.

**Comment by HarshKhandeparkar** [comment]
You can DM me on gitter for help.

**Comment by jywarren** [comment]
Just noting a recent Travis log showing this:

I saw in the last run: https://travis-ci.org/publiclab/image-sequencer/jobs/631706411#L1323

```
 Failed Tests: There were 7 failures
    colorbar module works correctly
      ✖ colorbar module works correctly
    draw-rectangle module works correctly
      ✖ draw-rectangle module works correctly
    gamma-correction module works correctly
      ✖ gamma-correction module works correctly
    paint-bucket module works correctly
      ✖ paint-bucket module works correctly
    replace-color module works correctly
      ✖ replace-color module works correctly
    rotate module works correctly
      ✖ rotate module works correctly
    tint module works correctly
      ✖ tint module works correctly
```

Actually perhaps we should also be sure that these actually cause a Travis failure, since currently Travis doesn't notice that they fail for some reason?

**Comment by keshav234156** [comment]
@jywarren for that we have tape-run.tape-run is a tape test runner that runs your tests in a (headless) browser and returns 0/1 as exit code, so you can use it as your npm test script.

Should we implement it now or after we have fixed all the test errors as now it would result in travis failure because of errors.i am fixing the above module test errors but there are also some other errors that we need to fix to implement tape-run properly

**Comment by jywarren** [comment]
Yes, i think we should resolve the bugs and then enable the 0/1 exit code, thank you!!!
