### ISSUE TITLE
Add Test for Import Image Module

### ISSUE THREAD

**Issue by HarshKhandeparkar** [publiclab/image-sequencer#1377]
### Please describe the problem (or idea)
This is a sub-issue of #1375 

### Please show us where to look

https://beta.sequencer.publiclab.org

### What's your PublicLab.org username?

> This can help us diagnose the issue:

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by blurry-x-face** [comment]
Is someone working on this?

**Comment by blurry-x-face** [comment]
@keshav234156 ?
