### ISSUE TITLE
Some modules do not work in NodeJS

### ISSUE THREAD

**Issue by harshkhandeparkar** [publiclab/image-sequencer#1378]
### Please describe the problem (or idea)
This is a sub-issue of #1375 

The following modules require WebGL but do not use Puppeteer to work in node:
- [ ] Text Overlay
- [ ] Blob Analysis

### Please show us where to look

https://beta.sequencer.publiclab.org

### What's your PublicLab.org username?

> This can help us diagnose the issue:

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by blurry-x-face** [comment]
Can I claim this issue?

**Comment by HarshKhandeparkar** [comment]
Yeah sure.

**Comment by blurry-x-face** [comment]
@HarshKhandeparkar I was able to make text overlay work in node by using [canvas](https://www.npmjs.com/package/canvas), Should I try to make it work using pupeteer instead?

**Comment by HarshKhandeparkar** [comment]
No! It's awesome! Does it work with GIFs btw? (It doesn't matter if it doesn't work. We'll fix that separately)

**Comment by blurry-x-face** [comment]
![text](https://user-images.githubusercontent.com/42492389/72529106-95555680-3892-11ea-8a37-100107e31da6.gif)
I am getting this as output

**Comment by blurry-x-face** [comment]
Should I open a PR for this?

**Comment by HarshKhandeparkar** [comment]
Is it text overlay? There is an issue for GIF text overlay already.

**Comment by blurry-x-face** [comment]
> Is it text overlay? There is an issue for GIF text overlay already.

Yes its text overlay

**Comment by blurry-x-face** [comment]
> There is an issue for GIF text overlay already.

I'll look into it, Thanks!
