### ISSUE TITLE
Add a Dithering module

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#138]
I see two existing modules for this: 

https://stackoverflow.com/questions/12422407/monochrome-dithering-in-javascript-bayer-atkinson-floyd-steinberg

https://dpiccone.github.io/ditherjs/ (this uses Canvas, so is less suitable for node/browser cross-compatibility)

I think the first one has a very nice `monochrome()` function here that we could use for thresholding as well: 

https://github.com/meemoo/iframework/blob/gh-pages/src/nodes/image-monochrome-worker.js

**Comment by ccpandhare** [comment]
I think this looks great. Can this be an FTO candidate? Just realized we're short of FTO Issues!

**Comment by jywarren** [comment]
That'd be great!

**Comment by aashna27** [comment]
@jywarren this one seems an old one is it still up for claim ❓

**Comment by aashna27** [comment]
> yep but don't claim them all at once! :-P lol you're doing amazing work though!

😆 yeah sure just this one and Text overlay for now .
