### ISSUE TITLE
Make the site responsive

### ISSUE THREAD

**Issue by VladimirMikulic** [publiclab/image-sequencer#1381]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### :fire: Problem

![Screenshot_20191220_191525](https://user-images.githubusercontent.com/35997844/71281006-1f2a0680-235d-11ea-91bc-cbf9f0155eaf.png)

![Screenshot_20191220_191502](https://user-images.githubusercontent.com/35997844/71281013-25b87e00-235d-11ea-9d0b-9634dc32266e.png)

The current version of the site is not responsive. :cry: 
Your job is to make it look great on mobile devices. :iphone: 

Don't worry though, it will only take you a few simple edits. 📝

### 🚩 Goal

![Screenshot_20191220_191935](https://user-images.githubusercontent.com/35997844/71281381-053cf380-235e-11ea-9d71-407e357d48b6.png)

![Screenshot_20191220_192013](https://user-images.githubusercontent.com/35997844/71281399-0ec65b80-235e-11ea-9847-343e3271add6.png)

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Open** image-sequencer/examples/demo.css
Below `#gif` selector(line 154) add this code:

- line `47` -> remove `min-width` rule
- line `69` -> remove `min-width` rule

```css
@media(max-width: 768px) {
    #dropzone {
      margin: 0 0% 30px;
    }
}
```

**Open** image-sequencer/examples/index.html
- line `58` remove inline styles from header

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
$DIFF
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by keshav234156** [comment]
@VladimirMikulic thanks for opening up the issue.this issue was fixed.please the cache.you will then be able to see the changes.although you will still face issue of text squashing.so please change the issue accordingly.
![Screenshot_20191220-224428_Chrome](https://user-images.githubusercontent.com/45951376/71275477-7094be80-237a-11ea-830f-c9b9aea006ca.jpg)

**Comment by VladimirMikulic** [comment]
@keshav234156 I've cleared cache and yes the issue is gone(no squished text).
The only issue that I see is that page is not scaling well on mobile devices.
Elements are overflowing everywhere. 

![Screenshot_20191220_182606](https://user-images.githubusercontent.com/35997844/71277819-3c0f0b80-2356-11ea-9edd-9fa79b5b79e0.png)

**Comment by keshav234156** [comment]
@VladimirMikulic are you reffering to scrolling as overflowing.if yes, then i thinks it is needed so that think don't get squashed.is there any better way?

**Comment by VladimirMikulic** [comment]
@keshav234156 good news! I've updated the issue accordingly, it will make the website responsive and look great on mobile devices :rocket:

**Comment by AngeloSorte** [comment]
I am totally new to open source. Is this a task that when someone complete it, it is closed? Or everybody can do this as an exercise? 
Thanks and sorry again for the ignorance in the field and practise of it!☺

Angelo

**Comment by VladimirMikulic** [comment]
Hi @AngeloSorte and welcome to PublicLab :balloon: 
I am glad that you are interested in helping us with this issue.

It's all yours, go for it :rocket:

**Comment by adamg703** [comment]
I made the changes for issue #1382 and created a pull request for the changes I made.  Not sure if I did it completely right so I wouldn't mind some feedback on whether I did it correct or not.

**Comment by VladimirMikulic** [comment]
Hi @adamg703. I've left a comment on your PR :)

**Comment by KateAnn19** [comment]
Hi I’m new here :) excited to have found you guys. Is it ok to work on this still?

**Comment by VladimirMikulic** [comment]
Hi @KateAnn19, it's nice to have you here at PublicLab :rocket: 
As you can see, this issue has been taken.

You can check out other first-timers-issues :)

**Comment by 28-ys** [comment]
Hi, can i work on this ?

**Comment by VladimirMikulic** [comment]
Hi @28-ys. We already have a PR that resolves this issue. Could you please check other issues?
Thanks a lot.
