### ISSUE TITLE
Site crashes on loading large files

### ISSUE THREAD

**Issue by ataata107** [publiclab/image-sequencer#1383]
I found out that instead of uploading an image if I uploaded a gif, still it will load up that gif. If the size of gif is large and I load it and continue processing on it the site will crash.
![Screenshot from 2019-12-22 05-06-52](https://user-images.githubusercontent.com/32903329/71314993-39590700-2479-11ea-88cb-51b46fd1a465.png)

There should be some kind of prevention system that only lets the users upload an image.
P.S :- I would like to work on this update if it seems suitable by the moderators.
Thanks

**Comment by HarshKhandeparkar** [comment]
GIFs cannot be processed as of now. We will add that feature soon.

**Comment by HarshKhandeparkar** [comment]
GIFs can be processed now!

**Comment by HarshKhandeparkar** [comment]
Does this happen even with large images?

**Comment by HarshKhandeparkar** [comment]
This is not really an issue with IS itself. Large files will slow down browsers always.
