### ISSUE TITLE
Troubles starting development environment

### ISSUE THREAD

**Issue by VladimirMikulic** [publiclab/image-sequencer#1385]
When I run the `watch` task with a grunt, it successfully compiles changes but they don't affect index.html. It just keeps using the "old" JavaScript.

**Comment by HarshKhandeparkar** [comment]
You have to clear the cache to use the new index.html

**Comment by VladimirMikulic** [comment]
Oh my god. Over 1GB of cache occupied by image-sequencer. Wow.
@HarshKhandeparkar Thank you very much on this information.

In my opinion, it shouldn't use cache in development mode.
It creates a lot of confusion.

**Comment by HarshKhandeparkar** [comment]
Ik. We are working towards better caching.
