### ISSUE TITLE
Display Docs Links for Modules in the UI

### ISSUE THREAD

**Issue by HarshKhandeparkar** [publiclab/image-sequencer#1390]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open-source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new** and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### What is to be done?
Every module of IS is documented in the [docs/MODULES.md](https://github.com/publiclab/image-sequencer/blob/main/docs/MODULES.md) file and every module's info.json file contains a link to the docs page.
e.g.:
https://github.com/publiclab/image-sequencer/blob/c370a8b4ea20267462f8fa559608618ca168e457/src/modules/EdgeDetect/info.json#L36

You will have to add an HTML `<a>` link in the module UI which links to the docs, for every module. You can add the link wherever you feel it will look good.

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 Modify the file [defaultHtmlStepUi.js](https://github.com/publiclab/image-sequencer/blob/main/examples/lib/defaultHtmlStepUi.js)

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need it if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by HarshKhandeparkar** [comment]
@publiclab/is-reviewers

**Comment by robwe30** [comment]
I would like to do that, even tho i never really did something on github before.

**Comment by HarshKhandeparkar** [comment]
Absolutely! Welcome! This issue is meant to teach you GitHub. You can ask us anything. We will happily answer every question. Please do claim this issue and start work on it.

**Comment by robwe30** [comment]
> Absolutely! Welcome! This issue is meant to teach you GitHub. You can ask us anything. We will happily answer every question. Please do claim this issue and start work on it.

How do I claim?

**Comment by HarshKhandeparkar** [comment]
Just leave a comment here(So that everyone knows that you are working on the issue). We don't want multiple people working on the issue which would lead to a lot of confusion. Please go ahead.

**Comment by sanjana091001** [comment]
Hey,
Can I work on this?

**Comment by HarshKhandeparkar** [comment]
You can if @robwe30 is no longer working on it. Or if they agree to let you claim the issue.

**Comment by robwe30** [comment]
I am really sorry I don't have time atm. So please let somebody else do that. Sorry.

**Comment by harshithpabbati** [comment]
@sanjana091001 you can work on this issue. Assigning this to you
