### ISSUE TITLE
Clear Steps Button Redirects to `/`

### ISSUE THREAD

**Issue by HarshKhandeparkar** [publiclab/image-sequencer#1394]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open-source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new** and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### What is to be done?
ImageSequencer's UI has a button that clears all the steps in the current sequence and starts a new one. It just redirects to `/` which could cause issues. For example if image sequencer is opened locally using the `file://` protocol instead of `http://` then it would redirect to `/` the root of the computer's filesystem which is very dangerous.

What it should do:
1. **Clear the URLHash**: IS UI uses URL's hash `#` to load different parameters like steps. for e.g. `https://beta.sequencer.publiclab.org/examples/#steps=contrast{},saturation{}`  would open a page with contrast and saturation steps already loaded. So if the user reloads the page, the steps would still be there. You will have to first clear all the URL Hash parameters.

2. **Reload the location**: Instead of redirecting to `/`, we could just reload the current location but without the URL Hash which would load a new sequence.

Reference:
- The current code
https://github.com/publiclab/image-sequencer/blob/c370a8b4ea20267462f8fa559608618ca168e457/examples/demo.js#L85-L89
- [urlHash.js](https://github.com/publiclab/image-sequencer/blob/main/examples/lib/urlHash.js)

You can refer to any of the above files or any other files but your final changes will mostly be in the files [urlHash.js](https://github.com/publiclab/image-sequencer/blob/main/examples/lib/urlHash.js) and [demo.js](https://github.com/publiclab/image-sequencer/blob/main/examples/demo.js). You are free to make changes to other files if you feel it is necessary.

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 Modify the file [urlHash.js](https://github.com/publiclab/image-sequencer/blob/main/examples/lib/urlHash.js): Add a function which clears the URL Hash

- [ ] 📝 Modify the file [demo.js](https://github.com/publiclab/image-sequencer/blob/main/examples/demo.js): Make the changes discussed above.

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need it if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by HarshKhandeparkar** [comment]
@publiclab/is-reviewers

**Comment by root00198** [comment]
Can I work on this issue?

**Comment by zyjeng11** [comment]
@root00198  are you working on this now?

**Comment by root00198** [comment]
Yeah I already created a PR...
