### ISSUE TITLE
Standardise Util Functions Comments

### ISSUE THREAD

**Issue by HarshKhandeparkar** [publiclab/image-sequencer#1396]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open-source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### What is to be done?
We are working towards standardizing all the comments in the codebase to make the docs look professional. New developers will get benefitted if we add comments to some of the most commonly used util functions. They are listed below.
1. [pixelSetter.js](https://github.com/publiclab/image-sequencer/blob/main/src/util/pixelSetter.js)
2. [getDefaults.js](https://github.com/publiclab/image-sequencer/blob/main/src/util/getDefaults.js)

You will have to update the comments in the above files based on the guidelines mentioned below.
1. Methods must be described using [JSDoc comments](https://devdocs.io/jsdoc/)
2. Misc code comments should be inline unless it is a long sentence.
3. No use of continuous tenses, no pronouns.
4. No redundant comments.
5. Each comment should start with an uppercase letter and end with a full stop.

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 Modify the file [pixelSetter.js](https://github.com/publiclab/image-sequencer/blob/main/src/util/pixelSetter.js)

- [ ] 📝 Modify the file [getDefaults.js](https://github.com/publiclab/image-sequencer/blob/main/src/util/getDefaults.js)

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need it if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by HarshKhandeparkar** [comment]
@publiclab/is-reviewers

**Comment by iblalw17** [comment]
Can I claim

**Comment by HarshKhandeparkar** [comment]
Sure

**Comment by hedonhermdev** [comment]
Hey @iblalw17 are you working on this?

**Comment by iblalw17** [comment]
I haven’t started it, I’m new to this so don’t know what to do

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by hedonhermdev** [comment]
Ping me if you need any help, maybe I can help you out.

**Comment by iblalw17** [comment]
It isn’t let me edit the documents for some reason, I clicked edit but it’s not responding

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by hedonhermdev** [comment]
Are you using a text editor? If yes then which one? Also which documents are you trying to edit?

**Comment by HarshKhandeparkar** [comment]
I think we'll have to add cloning and committing instructions to our FTO template.

**Comment by hedonhermdev** [comment]
Yes that will be a good idea, or linking to a good introduction to Git/GitHub would be nice too, imo.

**Comment by HarshKhandeparkar** [comment]
Is there an online article that we can link to?

**Comment by hedonhermdev** [comment]
https://guides.github.com/activities/hello-world/ How about this one?

**Comment by HarshKhandeparkar** [comment]
Yeah, nice. Do you want to open a PR which makes these changes to the FTO template.

**Comment by hedonhermdev** [comment]
Sure, I’ll do that.

**Comment by udaan42** [comment]
Hello, is this issue still open? I would like to contribute if this issue is open. Thanks.

**Comment by HarshKhandeparkar** [comment]
If @iblalw17 is no longer working on this, you can start work on it.

**Comment by udaan42** [comment]
Hey @iblalw17. Could you please confirm if you are working on this ? Thanks

**Comment by iblalw17** [comment]
Feel free to work on

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by iblalw17** [comment]
I am not working on it

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by udaan42** [comment]
Thank you. I will start working on this.

**Comment by tanish14** [comment]
Is this issue still open? I would like to contribute if this issue is open. Thanks.

**Comment by HarshKhandeparkar** [comment]
The last comment was quite old, you may take it :)

**Comment by tanish14** [comment]
@HarshKhandeparkar  can you pls review the PR. Thanks :)
