### ISSUE TITLE
Make demo display corresponding commandline syntax for current sequence

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#140]
This would be great to emphasize in the demo how the same command can be run from the CLI interface.

**Comment by jywarren** [comment]
Here, so what we could do is to make a function that could try to read through all the steps and settings, and assemble a CLI string from them. The CLI syntax is here:

https://github.com/publiclab/image-sequencer#cli-usage

The CLI also can take multiple steps at once, like so:

```
    $ ./index.js -i [PATH] -s "step-name-1 step-name-2 ..."
```

But for this, double quotes must wrap the space-separated steps.

Options for the steps can be passed in one line as json in the details option like

```
$ ./index.js -i [PATH] -s "brightness" -d '{"brightness":50}'
```

But i'm not sure if it can be chained with details too -- 

@marzann -- i'm not 100% sure this is going to be easy before there is some work done to the CLI code, here:

https://github.com/publiclab/image-sequencer/blob/master/index.js

In the meantime, would you like to try something from another project in our community? Maybe this one? 

https://github.com/publiclab/plots2/issues/2493

**Comment by marzann** [comment]
@jywarren thank you, I will look over your notes on this!

**Comment by jywarren** [comment]
Hi, @marzann -- we've gone ahead and merged in the new demo code - in #214 -- a big change! Demo code is now in `/examples/lib/____.js`. Maybe one of these would be interesting to try? 

https://github.com/publiclab/image-sequencer/issues/232

Take a look!

**Comment by tech4GT** [comment]
@jywarren taking this up now!!

**Comment by jywarren** [comment]
awesome!
