### ISSUE TITLE
"Close" button doesn't close "Take a photo" box

### ISSUE THREAD

**Issue by tsparksh** [publiclab/image-sequencer#1409]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

When a camera is not connected, we can't close "Take a photo" box
![takeaphoto](https://user-images.githubusercontent.com/17945250/71659437-37951a80-2d7a-11ea-8d1d-d31aab523456.gif)

Can we fix this?

### Please show us where to look

https://beta.sequencer.publiclab.org

**Comment by ataata107** [comment]
Can I claim this?

**Comment by tsparksh** [comment]
> Can I claim this?

Sure, but it is not a GCI task

**Comment by root00198** [comment]
I was kind of already working on  it... Did mentioned because didn't felt necessary(my mistake).... The bug is resolved should I create a PR??

**Comment by ataata107** [comment]
Wow, I also happened to solve it. I don't have any problem if you create a PR but do claim it (obviously necessary) as others who claim it might have also given time to it.

**Comment by root00198** [comment]
Nah, you do it. Its yours...

**Comment by ataata107** [comment]
Ah Cool, Maybe you can work on #1411 if moderators find the issue suitable

**Comment by HarshKhandeparkar** [comment]
Related to #1412. Will get fixed upon fixing #1412.
