### ISSUE TITLE
move module tests into separate test files

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#141]
Such as /test/modules/ -- this will help encourage more module specific testing!

https://github.com/publiclab/image-sequencer/blob/master/test/image-sequencer.js

**Comment by Rishabh04-02** [comment]
@jywarren I want to do this.

**Comment by jywarren** [comment]
Wow, that would be great!!! Please do jump in here!

**Comment by Rishabh04-02** [comment]
@jywarren ``chain.js``,``image-manip.js``,``image-sequencer.js``,``replace.js`` these all will go from ``/test/`` to ``/test/modules/`` or not?
Also what about the ``images`` directory?

**Comment by jywarren** [comment]
i think `/test/modules/` is right. Images, I don't know, what do you think? Thank you!!!

**Comment by Rishabh04-02** [comment]
I think, we should leave the ``images`` at its current position and move all others to ``/test/modules/``.

**Comment by tech4GT** [comment]
@jywarren please close this issue.Thanks

**Comment by jywarren** [comment]
+1!
