### ISSUE TITLE
Processing continues even after no video feed

### ISSUE THREAD

**Issue by ataata107** [publiclab/image-sequencer#1411]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/32903329/71693823-70ada900-2dd3-11ea-8fca-c5313b720678.gif)

Clicking the take photo button even if camera is disabled continues to do processing on a white canvas.

> What did you expect to see that you didn't?

Expected the process to end because of no video stream

**Comment by vivek-30** [comment]
@ataata107  sir, is this issue still open?
if yes then i would love to work on this ☺️ .

**Comment by vivek-30** [comment]
@HarshKhandeparkar i have solved this issue but still waiting for it to be assigned what should i do?

**Comment by HarshKhandeparkar** [comment]
Go ahead!

**Comment by vivek-30** [comment]
![test](https://user-images.githubusercontent.com/75980147/105580170-c2dfb480-5db0-11eb-8449-6bcb644aa11b.gif)

this is the working gif of above problem, is this ok?

**Comment by vivek-30** [comment]
Also i have submitted a PR #1789 around 5 days ago . Could you please review it as well. I am waiting for the feedback.Also Thanks for your time :)
