### ISSUE TITLE
Image processing not correct in colorbar module

### ISSUE THREAD

**Issue by root00198** [publiclab/image-sequencer#1418]
### Please describe the problem (or idea)
When name of the colormap is changed(doesnot matter from default to greyscale or greyscale to default), it doesnot work corectly.
> What happened just before the problem occurred? Or what problem could this idea solve?
![bug](https://user-images.githubusercontent.com/31132760/71716987-928f4600-2e3c-11ea-9562-96355af8ab82.gif)

> What did you expect to see that you didn't?

The image for greyscale colobar on the top with 10px height.

### Please show us where to look

https://beta.sequencer.publiclab.org

### What's your PublicLab.org username?

> This can help us diagnose the issue:

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by root00198** [comment]
I would like to resolve it.. I think the problem is in the example, because the command line is working correctly.

**Comment by jywarren** [comment]
Great catch! We'd love your help with this!
