### ISSUE TITLE
Clicking download btn downloads multiple Files

### ISSUE THREAD

**Issue by ataata107** [publiclab/image-sequencer#1419]
### Please describe the problem (or idea)

Clicking the download button after changing the values from default of any module leads to multiple downloads. A popup appears asking for multiple downloads. If we grant the permission the results are as follows

 As Can be seen below
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/32903329/71766049-ac568900-2f21-11ea-9156-4b480b62210f.gif)

If we dont allow downloading of multiple files then we are not able to download the image after changing values.

My main concern is that shouldn't clicking download btn only trigger the listener once but in this case it triggers the listener multiple times depending on the number of time we changed the value and clicked apply button

**Comment by ataata107** [comment]
@publiclab/is-reviewers

**Comment by ataata107** [comment]
Can I claim this?

**Comment by jywarren** [comment]
Hm, good catch -- sure, we'd love help!
