### ISSUE TITLE
Add select dropdown for some module UIs in demo

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#142]
This line of code inserts an `<input>` for each module option, so that users can change that option in the demo interface:

https://github.com/publiclab/image-sequencer/blob/master/examples/demo.js#L68

Try that out here: https://publiclab.github.io/image-sequencer/examples/

Some modules have options of type `select` instead of type `integer` or `string`, like this one: https://github.com/publiclab/image-sequencer/blob/master/src/modules/SegmentedColormap/info.json#L5

Compare that to this module, which specifies an `integer`: https://github.com/publiclab/image-sequencer/blob/master/src/modules/Crop/info.json#L7

When a `select` is specified, we should insert a `<select>` element and the various options as a dropdown, rather than a text input. 

Would love help with this!

**Comment by jywarren** [comment]
It seems you've just enabled the issue triaging. I'm just scraping all issues from your repository and will give you some more information about this in a few minutes or so.

Because of the rate limit we can't scrape all information (including all comments and authors) right now - our system is already set up to scrape this in the next days over which the predictions will become more precise every day.

**Sit tight!**

**Comment by jywarren** [comment]
The contributors most likely able to help are:

@jywarren
@ccpandhare

**Comment by ccpandhare** [comment]
I shall take this up today

**Comment by jywarren** [comment]
Wow!
