### ISSUE TITLE
Minify-Image module not working

### ISSUE THREAD

**Issue by root00198** [publiclab/image-sequencer#1420]
### Please describe the problem (or idea)
Minify Image module is not showing the output image.
> What happened just before the problem occurred? Or what problem could this idea solve?
![bug](https://user-images.githubusercontent.com/31132760/71771559-0f1c4480-2f63-11ea-825a-b53c324d366f.gif)

> What did you expect to see that you didn't?
I didnt saw any output image.

### Please show us where to look

https://beta.sequencer.publiclab.org

### What's your PublicLab.org username?

> This can help us diagnose the issue:

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by blurry-x-face** [comment]
This was working fine a while back maybe #1425 caused this?
cc: @jywarren

**Comment by blurry-x-face** [comment]
![Screenshot from 2020-01-07 04-31-56](https://user-images.githubusercontent.com/42492389/71855304-aec60800-3106-11ea-89b9-f5b3747667a8.png)

Yep! As I thought culprit is most probably one of the very recent PRs as it is still working on beta site(beta was updated on 29 Dec)

**Comment by jywarren** [comment]
Ah, good catch! Once we figure this out, let's add this to our per-module
tests so that it doesn't happen again :-)

Thank you!!!!

**Comment by root00198** [comment]
I fixed the issue of image not showing.... but the image is not getting compressed, it is showing the same image...

**Comment by HarshKhandeparkar** [comment]
Try downloading the image and check its size. It is supposed to reduce the image size (like zipping or tarballing)

**Comment by root00198** [comment]
I tired tried to find difference between the two images using their's base64 format....Didn't found any.

**Comment by HarshKhandeparkar** [comment]
Maybe the image cannot be compressed? I think we should check what the npm module that is used in the minify-image module, does.
