### ISSUE TITLE
Setting up npm 0/1 exit code for the module tests

### ISSUE THREAD

**Issue by keshav234156** [publiclab/image-sequencer#1427]
Setting up npm 0/1 exit code for the modules

**Comment by keshav234156** [comment]
cc:-@jywarren

**Comment by keshav234156** [comment]
@jywarren  @HarshKhandeparkar 
https://github.com/publiclab/image-sequencer/blob/main/test/core/templates/module-test.js#L41
Why are we converting base64 to img.Why aren't we comparing base64 of both results and benchmarks?

**Comment by keshav234156** [comment]
With tape-run i am getting this error 
```
 add-qr module works correctly

    TypeError: fs.existsSync is not a function
        at getExists (http://localhost:43017/bundle.js:33320:19)
        at Object.exports.mkdirSync (http://localhost:43017/bundle.js:33390:14)
        at Object.exports.writeFileSync (http://localhost:43017/bundle.js:33433:11)
        at Object.exports.imgSync (http://localhost:43017/bundle.js:7570:6)
        at http://localhost:43017/bundle.js:144943:17
        at drawStep (http://localhost:43017/bundle.js:138015:9)
        at Object.onEachStep [as callback] (http://localhost:43017/bundle.js:138056:11)
        at exports.PNG.<anonymous> (http://localhost:43017/bundle.js:143650:41)
        at emitNone (http://localhost:43017/bundle.js:28420:13)
        at exports.PNG.emit (http://localhost:43017/bundle.js:28505:7)
        at emitNone (http://localhost:43017/bundle.js:28420:13)
        at module.exports.emit (http://localhost:43017/bundle.js:28505:7)
        at module.exports.<anonymous> (http://localhost:43017/bundle.js:117774:10)
        at emitNone (http://localhost:43017/bundle.js:28425:20)
        at Deflate.emit (http://localhost:43017/bundle.js:28505:7)
        at endReadableNT (http://localhost:43017/bundle.js:126167:12)
npm ERR! Test failed.  See above for more details.

```
@jywarren @HarshKhandeparkar Any idea why is happening?

**Comment by keshav234156** [comment]
@jywarren How about writing test in jest similar to that we have written in UI. Though that won't be in-browser(as in case of ui) so would be fast as well and also it won't require any major except some minor syntax changes in module.js and some files that are excluded from module.js(template)

**Comment by keshav234156** [comment]
@jywarren  By writting test in jest we will also be able 2 test the additional modules that we have skipped in #1330 (So that other tests are not affected).
```
 PASS  test/core/modules/webgl-distort.js
  ✓ webgl-distort module loads correctly (39ms)
  ✓ webgl-distort module loads with correct options (5ms)
  ✓ webgl-distort module works correctly (866ms)

```

```
 test/core/modules/fisheye-gl.js (7.516s)
  ✓ fisheye-gl module loads correctly (6ms)
  ✓ fisheye-gl module loads with correct options (2ms)
  ✓ fisheye-gl module works correctly (1731ms)

```

**Comment by jywarren** [comment]
Hmm, cool! Do you think this is the best immediate next step, or is refactoring in Jest more of a big-picture longer-term goal? Either is fine, just trying to follow. Thanks!

**Comment by HarshKhandeparkar** [comment]
we could use
```bash
set -e
```
in a bash environment. It would immediately exit the script with a non-zero exit code if any of the intermediate commands/scripts fail.

**Comment by keshav234156** [comment]
https://github.com/publiclab/image-sequencer/blob/main/test/core/templates/module-test.js#L38.
@jywarren do you know what's the significance of mode:test here . Currentrly i am facing problem with setting up test module works correctely part. If there is output different then the test benchmark then it gave error but test passes.That because we testing it inside sequencer.run() (don't know why we can't test properly inside sequencer.run()).So test for this always passes. the test for module load correctely with correct option works fine.

**Comment by HarshKhandeparkar** [comment]
I tried searching in the library's source code but couldn't find anything related to `mode`. What happens if that line is removed?

**Comment by jywarren** [comment]
Is testing inside `sequencer.run()` a problem because it's asynchronous? Anyways, look, i looked at the blame view to try to trace `mode`:

https://github.com/publiclab/image-sequencer/blame/main/test/core/templates/module-test.js#L38

and kept tracing back through file histories...

https://github.com/publiclab/image-sequencer/pull/748/files#diff-4f143cbfde3f260e78413a94048b1b06R29

Whew... a few more layers!

Back to this code: 

https://github.com/publiclab/image-sequencer/pull/275/files#diff-f887b503b80e10727ac6cee436178fc5R125-R133

I believe that means it is no longer necessary. We can probably open an issue to remove all instances of `mode: 'test'`?

**Comment by HarshKhandeparkar** [comment]
Ty. I'll open the issue.

**Comment by jywarren** [comment]
Hi, is this now resolved in https://github.com/publiclab/image-sequencer/pull/1550 or is this a distinct issue? Thank you!
