### ISSUE TITLE
Overlay module not working initially

### ISSUE THREAD

**Issue by blurry-x-face** [publiclab/image-sequencer#1430]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

I loaded overlay module

> What did you expect to see that you didn't?

I expected to see the output image

### Please show us where to look

![1](https://user-images.githubusercontent.com/42492389/71847002-ed04fc80-30f1-11ea-9e8c-7060b64fbece.gif)

https://beta.sequencer.publiclab.org/examples/#steps=overlay{}

### What's your PublicLab.org username?

rishabhshukla1999

> This can help us diagnose the issue:

### Browser, version, and operating system
Chrome Version 79.0.3945.79 (Official Build) (64-bit) on Ubuntu 18 LTS

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by blurry-x-face** [comment]
@jywarren Can I work on this?

**Comment by ataata107** [comment]
You need to have atleat two images for this module to work

**Comment by blurry-x-face** [comment]
Yes it should prevent this from happening, maybe show a toast notification instead of just loading?

**Comment by ataata107** [comment]
Yes that should be there

**Comment by blurry-x-face** [comment]
Right now many of the modules have this problem(ex: blend module) you can put any number in the input I was thinking maybe it should show a visible error? This was just an idea If the moderators agree I can work on it.

**Comment by root00198** [comment]
I think you should add a default image.

**Comment by HarshKhandeparkar** [comment]
I think a better way would be to change the default offset to `-1` instead of `-2`. There will always be a step before the current step. That should fix everything.

**Comment by HarshKhandeparkar** [comment]
What are your thoughts?

**Comment by root00198** [comment]
Yeah That looks like a great idea...

**Comment by jywarren** [comment]
Hm, just noting that I believe it's supposed to take image -2 and overlay it on image -1, does that make sense?

**Comment by HarshKhandeparkar** [comment]
Good point. I think it would be even better if we use `-1` as a default
only if `-2` doesn't exists. We could use an if condition here.

**Comment by blurry-x-face** [comment]
> What are your thoughts?

I was thinking of adding these inputs as ranged inputs where we could maybe display the name of the step as input, what do you think?

**Comment by HarshKhandeparkar** [comment]
https://github.com/publiclab/image-sequencer/pull/1459#pullrequestreview-341587142
