### ISSUE TITLE
Crop Module Not Producing Expected Output

### ISSUE THREAD

**Issue by blurry-x-face** [publiclab/image-sequencer#1460]
Crop Module is not working corectly and maybe it is related to #1457?

![crop](https://user-images.githubusercontent.com/42492389/72212256-9ab34980-34fe-11ea-963b-bc2decdac0e9.gif)

### Please show us where to look

https://beta.sequencer.publiclab.org

### What's your PublicLab.org username?
rishabhshukla1999

**Comment by root00198** [comment]
I would like to work on it.

**Comment by blurry-x-face** [comment]
Hi @root00198 I'm already looking into this.
 
You can help by looking for bugs that might have come because of some recent PRs, Thanks!

**Comment by ataata107** [comment]
@blurry-x-face I guess the module is working correctly only the text input field is not showing the correct value of the default which I guess needs to be changed. Currently it is showing 0 for all

**Comment by blurry-x-face** [comment]
Yes, I've found the bug and will be making a PR for it very soon!

**Comment by blurry-x-face** [comment]
Also @ataata107 , while working on this I found that color picker input was not working as expected, after clicking on it, it was just stuck there and I was unable to do anything, are you facing the same problem too? If so then I'll open a new issue for this and will be happy to work on it!
