### ISSUE TITLE
Text-Overlay Does Not Work With GIFs

### ISSUE THREAD

**Issue by ataata107** [publiclab/image-sequencer#1462]
### Please describe the problem (or idea)
In the case of the gif the text overlay is in the vertical form rather than the horizontal form and the letters are a mirror image of itself. 

> What happened just before the problem occurred? Or what problem could this idea solve?

> What did you expect to see that you didn't?

### Please show us where to look

https://beta.sequencer.publiclab.org

### What's your PublicLab.org username?

> This can help us diagnose the issue:

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by ataata107** [comment]
I would like to resolve the same
@publiclab/is-reviewers

**Comment by HarshKhandeparkar** [comment]
Go ahead. BTW, thank you for opening these issues related to GIFs.
