### ISSUE TITLE
Contrast Module should use changePixel Method

### ISSUE THREAD

**Issue by HarshKhandeparkar** [publiclab/image-sequencer#1472]
### Please describe the problem (or idea)
The Contrast module currently uses `extraManipulation` but the manipulation process is repetitive so it could use `changePixel` instead which would also WebAssembly accelerate it

Current Code:
https://github.com/publiclab/image-sequencer/blob/12c422a07b55233ae94e13fc3700da2101916c65/src/modules/Contrast/Contrast.js#L5-L25

### Please show us where to look

https://beta.sequencer.publiclab.org

### What's your PublicLab.org username?

> This can help us diagnose the issue:

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by blurry-x-face** [comment]
Can I claim this issue?
