### ISSUE TITLE
Displayed Version Number is not Visible

### ISSUE THREAD

**Issue by HarshKhandeparkar** [publiclab/image-sequencer#1473]
### Please describe the problem (or idea)
The current cache version of IS is displayed at the top right corner of the UI but is not visible.

![Screenshot from 2020-01-12 23-18-56](https://user-images.githubusercontent.com/34770591/72223173-1f9b7300-3592-11ea-8096-b8bb3ccd86c0.png)

After Highlighting:
![Screenshot from 2020-01-12 23-20-07](https://user-images.githubusercontent.com/34770591/72223177-3b9f1480-3592-11ea-8273-d809c956fe61.png)

### Please show us where to look

https://beta.sequencer.publiclab.org

### What's your PublicLab.org username?

> This can help us diagnose the issue:

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by keshav234156** [comment]
@HarshKhandeparkar can you make it a fto?

**Comment by HarshKhandeparkar** [comment]
I'll do it.

**Comment by HarshKhandeparkar** [comment]
New FTO https://github.com/publiclab/image-sequencer/issues/1475
