### ISSUE TITLE
Area selected by image-area-select.

### ISSUE THREAD

**Issue by keshav234156** [publiclab/image-sequencer#1476]
if we delete the crop step then area selected by image-area-select.in that area we are not able to click.
![Untitled_ Jan 12, 2020 11_49 PM](https://user-images.githubusercontent.com/45951376/72223653-2c6e9580-3597-11ea-8ef9-37c5abe19389.gif)

**Comment by 28-ys** [comment]
Hi, can i try this issue ?

**Comment by HarshKhandeparkar** [comment]
Sure.

**Comment by HarshKhandeparkar** [comment]
Sorry but this one already has an open PR. Please try some other issue that interests you. I am sure you will find one.

**Comment by 28-ys** [comment]
okay, Thanks
