### ISSUE TITLE
Add more GIF tests

### ISSUE THREAD

**Issue by HarshKhandeparkar** [publiclab/image-sequencer#1479]
### Please describe the problem (or idea)
GIF manipulation is in an experimental stage as of now. One of the most important steps towards making it a permanent feature would be adding more tests.

### Please show us where to look

https://beta.sequencer.publiclab.org

### What's your PublicLab.org username?

> This can help us diagnose the issue:

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by root00198** [comment]
Working on it.

**Comment by root00198** [comment]
Why are we creating a new image from base64 and then comparing the image, insted of directly comparing the base64 in result and benchmark?

https://github.com/publiclab/image-sequencer/blob/12c422a07b55233ae94e13fc3700da2101916c65/test/core/templates/module-test.js#L37-L55

like this 
`
      let result = sequencer.steps[1].output.src;
      t.equal(result == benchmark, true, '${moduleName} module works correctly');
`
