### ISSUE TITLE
Create demo bookmarklet code for inverting images on a page

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#148]
A browser bookmarklet that inverts all images on a page would be a cool demo for this lib. We could add it to the README and say "drag this link into your bookmarks bar" for example. 

(right now we need to solve #147 first, but then we could do this)

You can make a bookmarklet with a utility like: https://mrcoles.com/bookmarklet/ or just by hand; I made one that runs:

```js
var sequencer = ImageSequencer();
sequencer.replaceImage('img','invert');
```

and includes this script: https://publiclab.github.io/image-sequencer/dist/image-sequencer.js

That generated:

```js
javascript:(function()%7Bfunction%20callback()%7Bvar%20sequencer%20%3D%20ImageSequencer()%3Bsequencer.replaceImage('img'%2C'invert')%7Dvar%20s%3Ddocument.createElement(%22script%22)%3Bs.src%3D%22https%3A%2F%2Fpubliclab.github.io%2Fimage-sequencer%2Fdist%2Fimage-sequencer.js%22%3Bif(s.addEventListener)%7Bs.addEventListener(%22load%22%2Ccallback%2Cfalse)%7Delse%20if(s.readyState)%7Bs.onreadystatechange%3Dcallback%7Ddocument.body.appendChild(s)%3B%7D)()
```

**Comment by jywarren** [comment]
The contributors most likely able to help are:

@jywarren

**Comment by tech4GT** [comment]
@jywarren are we still doing this, i can even make a google chrome extension if you want?

**Comment by jywarren** [comment]
i think a bookmarklet would be a great place to start -- maybe a chrome
extension could be a follow-up issue?

**Comment by tech4GT** [comment]
@jywarren please update https://publiclab.github.io/image-sequencer/dist/image-sequencer.js file. replaceImage() is returning error

**Comment by jywarren** [comment]
Oh oops! Hmm, can you post the error as an issue? We should have a test for
that. Thanks for reporting!

On Jan 27, 2018 8:13 AM, "Varun Gupta" <notifications@github.com> wrote:

@jywarren <https://github.com/jywarren> please update
https://publiclab.github.io/image-sequencer/dist/image-sequencer.js file.
replaceImage() is returning error

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/publiclab/image-sequencer/issues/148#issuecomment-360984140>,
or mute the thread

**Comment by tech4GT** [comment]
@jywarren it runs fine with my local script so probably the file is not updated with latest commits

**Comment by tech4GT** [comment]
@jywarren please help

**Comment by tech4GT** [comment]
@jywarren looks like github has disabled embedding bookmarklets in readme https://stackoverflow.com/questions/19314567/embed-bookmarklet-in-github-readme-md

**Comment by tech4GT** [comment]
@jywarren we can add a link which opens a statically hosted page which has the actual bookmarklet since it is not allowed in github readme. What say?

**Comment by jywarren** [comment]
That sounds great! Perhaps bookmarklet.md?

**Comment by tech4GT** [comment]
Actually .md file will again not support js...i was thinking maybe hosting a page on some other service like https://www.bitballoon.com/

**Comment by jywarren** [comment]
oh, aha -- i see. well, we could host it at PublicLab.org on a wiki page, what do you think? http://publiclab.org/wiki/

**Comment by tech4GT** [comment]
@jywarren that'll be super😁

**Comment by tech4GT** [comment]
@jywarren  https://publiclab.org/wiki/imagesequencerbookmarklet

**Comment by jywarren** [comment]
Looks good! Closing in #164 -- thanks!!!
