### ISSUE TITLE
UniqueID : Random or Sequential?

### ISSUE THREAD

**Issue by ccpandhare** [publiclab/image-sequencer#15]
@jywarren I have been working on the `removeStep()`.
We need a unique ID for every step for this to be done. I am aware that we already have one. It is defined in `/src/UserInterface.js`. This is a problem. Because `/src/UserInterface.js` is imported only for browser implementations.
Hence it is a unique ID only for the Browser UI, right?

We'll need a unique ID for every step. Either now, or in the future.

For the purpose of testing my code, I have implemented a sequential Unique ID system : 0,1,2,... which is implemented in `/src/ImageSequencer.js`

My question is : should we use a sequential one, or the one which is already implemented in `/src/UserInterface.js` ?

**Comment by jywarren** [comment]
Yes, the uniqueId was only for the browser. But we could pass it as a
parameter to UserInterface if we like. Or we could just allow those modules
to be self-reliant and use two separately generated unique IDs. Open to
suggestions.

Either way I agree it's a good idea to have a unique id.

I guess I think random is good, because we might insert a module later, and
then have to re-number.

**Comment by ccpandhare** [comment]
Okay,
But we wouldn't have to re-number.
The unique ID doesn't change once defined. So even if we remove one step from the middle, the other unique IDs remain the same.

I think there's no added benefit of having two Unique ID systems, don't you think so?

**Comment by ccpandhare** [comment]
I guess some insight is already needed on this one...

**Comment by jywarren** [comment]
+1 random; git commits work that way due to non-linearity, and I think that
makes sense in case you insert a step in the middle of the stack.

**Comment by jywarren** [comment]
This and a few others can be closed now, no? Thanks!

**Comment by ccpandhare** [comment]
Yes, I think this can be closed now.
I shall add some ideas from these issues into the DEVELOPMENT.md
