### ISSUE TITLE
Using GitMate

### ISSUE THREAD

**Issue by sils** [publiclab/image-sequencer#150]
Hi there :)

I'm Lasse and this is actually not a template (yet) - I saw you've activated GitMate.io on your repository and you're using it a bit. Can you already tell how well it's working for you or if there's any bigger problems with it? We're looking to find the best area to put work in to make it more useful.

**Comment by jywarren** [comment]
The contributors most likely able to help are:

@jywarren
@ccpandhare

**Comment by jywarren** [comment]
Hi, thanks! - I guess I'm not sure if it'll start labeling our issues yet, and I'm trying it out on this repo as it's  a bit lower traffic. 

I'd like to have a bot that:

* looks at new issues and asks the author to share a link and/or screenshot if applicable
* prompts someone to add links to lines of code where changes could be made
* looks at issues marked `break-me-up` (we use this at https://github.com/publiclab/plots2) and offers suggestions on how to break up an issue into separate, self-contained pieces
* maybe looks at folks who've contributed in the past month or two but not in the past week or two, and trieds to re-engage them

Any of these helpful, or currently possible?

**Comment by sils** [comment]
Hi @jywarren , that sounds very interesting and some things are definitely doable and actually on our roadmap. CC @fneu our lead of research as well.

Wanna have a chat about it? That might be easier. If you want, you can register one at calendly.com/sils but not before monday please.

**Comment by jywarren** [comment]
Hi, I'd love to but my schedule for the next 2 weeks is pretty tight... i'm
traveling a lot. Perhaps we could sync up after the 10th of November!
Thanks a lot!

**Comment by sils** [comment]
@jywarren sure just make an appointment to https://calendly.com/sils so we don't forget :P

**Comment by sils** [comment]
ping :)

**Comment by gauravano** [comment]
@jywarren :calling:
