### ISSUE TITLE
refactoring isGIF() as a utility function

### ISSUE THREAD

**Issue by HarshKhandeparkar** [publiclab/image-sequencer#1501]
### Please describe the problem (or idea)
@jywarren's comment:
Refactoring isGIF() as a utility function so the parameters don't have to change for the function [here](https://github.com/publiclab/image-sequencer/pull/1404#discussion_r365530741)

### Please show us where to look

https://beta.sequencer.publiclab.org

### What's your PublicLab.org username?

> This can help us diagnose the issue:

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by blurry-x-face** [comment]
I'll be happy to work on it!
