### ISSUE TITLE
Add a Comment Explaining External Module Definitions

### ISSUE THREAD

**Issue by HarshKhandeparkar** [publiclab/image-sequencer#1504]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open-source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### What is to be done?
https://github.com/publiclab/image-sequencer/blob/bfff7e7b999bf256205d412a13f16e154a63beb1/src/Modules.js#L33-L34

In the above code, the commented line imports the invert module from a different repository altogether (using a `require` statement). This is a powerful feature of ImageSequencer, the modules are independent of the rest of the library's source.

The above example depicts this feature perfectly.
You have to add a comment next to the commented code, explaining the feature and the code.

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 Modify the file [Modules.js](https://github.com/publiclab/image-sequencer/blob/main/src/Modules.js)

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need it if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by chadianho** [comment]
Hi would like to claim this and contribute to it.

**Comment by chadianho** [comment]
Am I still able to contribute to the project, since the status says closed above my first comment?

**Comment by niravasher** [comment]
@chadianho the `closed` word above your first command means that the issue `external module definition using require() #1500 ` has been closed. Try to learn git and github first if you are a new comer

**Comment by hknowlton** [comment]
Hi @chadianho, welcome! Whenever you mention one issue in another, it will automatically create a comment showing that mention. The comment above yours that says "closed" is just another issue that mentions this one! You can click on it, and see that was just someone opening an issue about this, and this deciding to re-write it as a first-timer issue. This paticular issue still needs to be fixed if you want to claim it and start work. Please let me know if you have any questions or need help getting started 😄

**Comment by chadianho** [comment]
Hi @hknowlton thank you for clarifying, yes I will continue to work on this issue. Thank you.

**Comment by 28-ys** [comment]
Hi, can i work on this issue?

**Comment by hknowlton** [comment]
Hi @28-ys, this issue is being worked on by @chadianho . Feel free to browse other first time issues here - https://github.com/publiclab/image-sequencer/labels/first-timers-only

**Comment by 28-ys** [comment]
@hknowlton  okay thanks!

**Comment by chadianho** [comment]
Hi @publiclab/is-reviewers can you help me one of the tasks to complete this issue is "[ ] Insert-step functionality is working correct as expected".  What is the insert-step functionality and how do I ensure it is working correctly?

**Comment by HarshKhandeparkar** [comment]
> Hi @publiclab/is-reviewers can you help me one of the tasks to complete this issue is "[ ] Insert-step functionality is working correct as expected". What is the insert-step functionality and how do I ensure it is working correctly?

No need to worry. Just check the box. It is something related to the UI. You have not edited anything related to the UI, so just check the box.

**Comment by dipeshgund** [comment]
Hi! I would like to contribute here. Is it still available? If not, then it would be really helpful of you if you guide me to some other first-timers-only.

**Comment by HarshKhandeparkar** [comment]
It has been a while since the last PR was closed (and not merged) so sure, feel free to contribute :)

**Comment by GuptaTanisha** [comment]
@HarshKhandeparkar Can I work on this issue?

**Comment by HarshKhandeparkar** [comment]
That last comment was old, so yes! (But try to work on only one issue at a time :))
