### ISSUE TITLE
mode:'test' no longer required

### ISSUE THREAD

**Issue by HarshKhandeparkar** [publiclab/image-sequencer#1514]
### Please describe the problem (or idea)
During module tests, the option `mode: 'test'` is passed to the sequencer. This option is no longer required.
https://github.com/publiclab/image-sequencer/blob/423422a61f61f1a4fa9149b9dafee1508bbe350e/test/core/templates/module-test.js#L38

We have to find and remove all the instances of this code.

### Please show us where to look

https://beta.sequencer.publiclab.org

### What's your PublicLab.org username?

> This can help us diagnose the issue:

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by blurry-x-face** [comment]
@HarshKhandeparkar should we make this a FTO, because I don't think it might be very complicated for a first timer, what do you think?

**Comment by HarshKhandeparkar** [comment]
Yup. That is exactly what I was going to do next.

**Comment by HarshKhandeparkar** [comment]
New FTO: https://github.com/publiclab/image-sequencer/issues/1516
