### ISSUE TITLE
Remove All Instances of `mode: 'test'`

### ISSUE THREAD

**Issue by HarshKhandeparkar** [publiclab/image-sequencer#1516]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open-source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new** and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### What is to be done?
In ImageSequencer module tests, the following option is passed to the sequencer
https://github.com/publiclab/image-sequencer/blob/423422a61f61f1a4fa9149b9dafee1508bbe350e/test/core/templates/module-test.js#L38

Due to recent changes, this option is no longer required. We would want to remove any unnecessary code and keep the codebase clean and tidy.

You will have to find all the instances of `mode: 'test'` and remove the code.
There are many ways of searching lines of code in a whole project.
One of the easiest ways is to use the feature provided by most code editors. Some examples are:
1. [VSCode](https://code.visualstudio.com/docs/editor/codebasics#_search-across-files)
2. [Atom](https://flight-manual.atom.io/using-atom/sections/find-and-replace/#find-and-replace)
3. [Sublime Text](https://forum.sublimetext.com/t/how-to-find-code-text-in-all-project-files/10333)
### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 Modify all the files where this code is found.

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need it if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by Kevinand11** [comment]
I am claiming this issue. First time contributing to open source. Fingers crossed. Wish me luck

**Comment by HarshKhandeparkar** [comment]
Welcome! You can ask for any kind of help, here.

**Comment by Deogle** [comment]
If this hasn't been fixed yet, I can take it. This would be my first time contributing.

**Comment by blurry-x-face** [comment]
Yea sure, go ahead @Deogle, If you have any doubts feel free to ask them!
