### ISSUE TITLE
Error Installation problem

### ISSUE THREAD

**Issue by MrAsimZahid** [publiclab/image-sequencer#1521]
## Received this error
Aborted due to warnings.

npm ERR! Linux 5.0.0-37-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "setup"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! image-sequencer@3.5.1 setup: `npm i && npm i -g grunt grunt-cli && grunt build $$ npm rebuild --build-from-source`
npm ERR! Exit status 3
npm ERR! 
npm ERR! Failed at the image-sequencer@3.5.1 setup script 'npm i && npm i -g grunt grunt-cli && grunt build $$ npm rebuild --build-from-source'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the image-sequencer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm i && npm i -g grunt grunt-cli && grunt build $$ npm rebuild --build-from-source
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs image-sequencer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls image-sequencer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/asim/image-sequencer/npm-debug.log

> What happened just before the problem occurred? Or what problem could this idea solve?

I cloned the repository > got into the repository and
I ran this command
```
sudo npm run setup
```

> What did you expect to see that you didn't?
some setup successfully ran

### Please show us where to look
https://github.com/publiclab/image-sequencer/blob/main/README.md
https://beta.sequencer.publiclab.org

### What's your PublicLab.org username?

> This can help us diagnose the issue:

### Browser, version, and operating system

Ubuntu 18.04 LTS

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by MrAsimZahid** [comment]
![image-sequencer](https://user-images.githubusercontent.com/23510373/72629410-120b3200-3972-11ea-8936-87bf28675a90.png)

This is the screenshot of error I received.

**Comment by HarshKhandeparkar** [comment]
@MrAsimZahid thanks for opening this issue. We are sorry that you are facing this issue. We'll help you in resolving this ASAP.

**Comment by HarshKhandeparkar** [comment]
I just checked, my npm version was `v6` or something and yours is `v3`. Could you try this out with the latest version of npm?

**Comment by MrAsimZahid** [comment]
Issue Resolved using this command

sudo npm install npm@latest -g
