### ISSUE TITLE
More General Method of Displaying Docs Links

### ISSUE THREAD

**Issue by HarshKhandeparkar** [publiclab/image-sequencer#1526]
### Please describe the problem (or idea)
The following code is used to display the docs links for each module in the UI.
https://github.com/publiclab/image-sequencer/blob/d1b9b8beccdbe5ba98cf4e352af103b4913a5fe6/examples/lib/defaultHtmlStepUi.js#L48-L50

The code just links to a general link that may not work for every module. Instead, the link should be imported from every module's `info.json` file instead.
https://github.com/publiclab/image-sequencer/blob/d1b9b8beccdbe5ba98cf4e352af103b4913a5fe6/src/modules/BlobAnalysis/info.json#L6

### Please show us where to look

https://beta.sequencer.publiclab.org

### What's your PublicLab.org username?

> This can help us diagnose the issue:

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by hedonhermdev** [comment]
Can I work on this?

**Comment by HarshKhandeparkar** [comment]
Go ahead.

**Comment by Jigyasa-Kumari** [comment]
Hi, I am Jigyasa, and I am an Outreachy 2020 applicant. Is this issue still open, and can I work on this?

**Comment by HarshKhandeparkar** [comment]
Yeah sure. Go ahead.

**Comment by vivek-30** [comment]
sir is this issue still open, if yes i would love to work on it.

**Comment by HarshKhandeparkar** [comment]
Considering that the last comment was made almost a year ago, yes, it is open! Go ahead! Ty.

**Comment by vivek-30** [comment]
ok thanks sir

**Comment by vivek-30** [comment]
Sir i had understood entire problem and worked on it. Then i found the most appropriate way to handle this issue but when i 
try to commit the changes, then an error occur , then i searched for that error but nothing worked so can you help me out to resolve this error.

#### The error is something like :

![Screenshot 2021-01-14 at 4 58 35 PM](https://user-images.githubusercontent.com/75980147/104585899-bb226080-568a-11eb-9725-9bc6bc9faf4f.jpg)

**Comment by HarshKhandeparkar** [comment]
Can you show the code?

**Comment by vivek-30** [comment]
sure sir,
This is code which i have changed-
 
![Screenshot 2021-01-14 at 8 36 32 PM](https://user-images.githubusercontent.com/75980147/104608890-7279a000-56a8-11eb-94c3-270ec6ce9e2b.jpg)

### Inside examples/lib/defaultHtmlStepUi.js

**Comment by HarshKhandeparkar** [comment]
So the error isn't related to your changes?

**Comment by vivek-30** [comment]
I thinks so ,bcoz sir recently i have made one more commit which did not gave any error but i am not getting why this creepy error is arriving this time ,whenever i try to commit it.

**Comment by HarshKhandeparkar** [comment]
If it is not related to your code, you can just use `--no-verify` and open a PR. We'll see if there is any error :)

Also, please don't call me sir :joy:

**Comment by vivek-30** [comment]
ok sir 😅  ,but the happy part is i resolved this error and also thanks for your kind help ♥️.
i went through this [page](https://github.com/typicode/husky/issues/716) and found real cause of this error.
lastly thank u so much @HarshKhandeparkar .

**Comment by HarshKhandeparkar** [comment]
Nice! Np! Waiting for your PR :wink:

**Comment by HarshKhandeparkar** [comment]
Also, please don't call me sir :rofl:

**Comment by vivek-30** [comment]
Now as per your guidance i have made these changes.
plz have a look -
![Screenshot 2021-01-15 at 2 12 44 PM](https://user-images.githubusercontent.com/75980147/104705823-64775e00-5740-11eb-8ed1-36fd21725596.jpg)
Is it ok now
