### ISSUE TITLE
UI Chatroom Link Should Link to the Gitter Channel

### ISSUE THREAD

**Issue by HarshKhandeparkar** [publiclab/image-sequencer#1527]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open-source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new** and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### What is to be done?
The UI of ImageSequencer has a link in the footer that leads to one of the general chatrooms on publiclab.org. However, ImageSequencer has its own gitter chatroom now -> https://gitter.im/publiclab/image-sequencer.

You will have to update this link

Files to refer to:
1. https://github.com/publiclab/image-sequencer/blob/d1b9b8beccdbe5ba98cf4e352af103b4913a5fe6/examples/index.html#L221

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 Modify all the files where this code is found.

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need it if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by pcube99** [comment]
I want to claim this issue.

**Comment by HarshKhandeparkar** [comment]
You can't claim more than one FTO.

**Comment by BrooksPatola** [comment]
I can do this...

**Comment by HarshKhandeparkar** [comment]
Go ahead!

**Comment by BrooksPatola** [comment]
I have made PR Update url in footer to ImageSequencer gitter chatroom #19.

Although I may have done this PR wrong, as many commits were displayed.

Let me know how to proceed...

**Comment by blurry-x-face** [comment]
@BrooksPatola could you give the correct link to your PR

**Comment by 28-ys** [comment]
Hi there,
@blurry-x-face  basically we need to add a link in footer to gitter chatroom right?

**Comment by 28-ys** [comment]
I guess this link is already there below Need Help.
[ Ask In our chat room ]button.

**Comment by blurry-x-face** [comment]
No, the link should be https://gitter.im/publiclab/image-sequencer

**Comment by 28-ys** [comment]
Hi there,
@blurry-x-face  I have make changes but nothing is update on browser even after killing server and run again its kind of weird actually it loads the external Index.js file first then it loads the index.js file which is in the examples some js function make changes when it loads as refresh it on browser with command+shift+R (by this it remove the cache) then it update the changes accordingly.

**Comment by blurry-x-face** [comment]
Did you cleared the cache?

**Comment by 28-ys** [comment]
Hi there,
@blurry-x-face I have make changes but nothing is updated on browser even after killing the server and run it again its kind of weird actually it loads the external Index.js file first then it loads the index.js file which is in the examples some js function make changes on index.js when it load on browser . as i refresh it on browser with command+shift+R (by this it remove the cache) then it update the changes accordingly.

**Comment by 28-ys** [comment]
@blurry-x-face  yes i clear the cache then only it changes the update on browser.

**Comment by 28-ys** [comment]
@blurry-x-face  yeah only after refresh it by pressing (command+shift+R) it loads the changes i make.

**Comment by 28-ys** [comment]
@blurry-x-face  one more thing as i reload it by removing cache it didn't load the external index.js file it directly loads the index.js file which is in examples and show changes i make accordingly.

**Comment by 28-ys** [comment]
Hi @blurry-x-face  just check out the link now.

**Comment by 28-ys** [comment]
Hi there,
 @blurry-x-face  please guide me further finding good issues i want contribute.

**Comment by 28-ys** [comment]
Hi guys 
@HarshKhandeparkar @harshithpabbati  @blurry-x-face  please help in finding issues mostly all the issues are taken i want contribute and i wanted to do GSOC this year .

**Comment by blurry-x-face** [comment]
Try solving issues with label `bug`

**Comment by HarshKhandeparkar** [comment]
@28-ys are you interested in contributing to #1624. This will make you comfortable with the codebase and will perhaps give you ideas for SoC.

**Comment by 28-ys** [comment]
@blurry-x-face  @HarshKhandeparkar  Thanks!
