### ISSUE TITLE
UI Learn More Link Should Lead to the README

### ISSUE THREAD

**Issue by HarshKhandeparkar** [publiclab/image-sequencer#1528]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open-source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new** and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### What is to be done?
The UI of ImageSequencer has a link with the text `Learn More` in the header that leads to the wiki page of ImageSequencer on publiclab.org. This link is just a mini README.
You have to change this link to the full README of ImageSequencer.
![Screenshot from 2020-01-18 00-14-07](https://user-images.githubusercontent.com/34770591/72637512-813f5100-3987-11ea-9c60-8cf319c61598.png)

Files to refer to:
1. https://github.com/publiclab/image-sequencer/blob/d1b9b8beccdbe5ba98cf4e352af103b4913a5fe6/examples/index.html#L69

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 Modify the file [index.html](https://github.com/publiclab/image-sequencer/blob/main/examples/index.html)

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need it if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by pcube99** [comment]
I want to claim this issue.

**Comment by HarshKhandeparkar** [comment]
Sorry but you cannot claim more than a single first-timers only issue.

**Comment by arghac14** [comment]
@HarshKhandeparkar can I work on this?

**Comment by HarshKhandeparkar** [comment]
Sure. Go ahead. You can ask for any kind of help, here.

**Comment by arghac14** [comment]
@HarshKhandeparkar  I have fixed the issue, please review the PR #1539
