### ISSUE TITLE
Module Selector dropdown showing error in console

### ISSUE THREAD

**Issue by blurry-x-face** [publiclab/image-sequencer#1531]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/image-sequencer/labels/help-wanted) issues. Thanks!

### What is to be done?
After searching module name in module search input if we clear the input field a error is shown in console, try to remove that error. Refer to below GIF for more info!

![err](https://user-images.githubusercontent.com/42492389/72648050-059dce00-39a0-11ea-9b67-5a7b10be00f5.gif)

Files to refer to:
https://github.com/publiclab/image-sequencer/blob/c22c6c70d098715d610c72afe83ef8f6b3d9d57a/examples/lib/defaultHtmlSequencerUi.js#L27

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?
Leave a comment below!

**Comment by arghac14** [comment]
@blurry-x-face can I take this one?

**Comment by blurry-x-face** [comment]
Yes, ho ahead!

**Comment by ss62171** [comment]
I would like to work on this issue.

**Comment by HarshKhandeparkar** [comment]
Sure

**Comment by bajajvinamr** [comment]
I would like to work on this issue.

**Comment by GuptaTanisha** [comment]
@blurry-x-face Is this issue open?

**Comment by SharmaTanish** [comment]
Hi @blurry-x-face  ! I am very exited to work on this issue , if it is still open . I have learnt web development from coding ninjas and all my basic concepts are clear . I am very hardworking and have scored 94.2% in 12th . You can also go through my linkedIn profile - https://www.linkedin.com/in/tanish-a54b771b3 .
Looking forward for your reply .

**Comment by jywarren** [comment]
Hi all, can we try to confirm if this is still happening by running https://sequencer.publiclab.org with the JS console open? Then we can see if we need to close it. 

Thanks everyone for being helpful! And, welcome!
