### ISSUE TITLE
Weekly community Check-In #45 - "The First Step"

### ISSUE THREAD

**Issue by daemon1024** [publiclab/image-sequencer#1540]
Hi everybody! 
 
We all at Public Lab  - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal  . You are also welcome to share fun-fact  , new ideas :bulb: , your learning goals .
 
We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become master of tomorrow. 
 
New contributors, please comment down below and introduce yourself! We welcome you all to Publiclab and are here to help if you encounter any issues! 
 
# The First Step :footprints: 
This week tell us about how did you take your first step towards contributing to Public Lab. The first step could be a interaction with another member, could be an issue you faced while using some project of PublicLabs , could be just your first step towards open source itself. 

## Note to GCI students 
We are really grateful for all the amazing work you are doing :heart: . As we are approaching the end of the the program please make sure you fill in your grade sheets as well as rate the mentors 

- [Student Gradesheet](https://docs.google.com/forms/d/1e60ybBZNaJ_Aai_pJHIzFL4gxMVsVngZBUYw3gK_1dE/viewform?ts=5df7b8f8&edit_requested=true)
- [Mentor gradesheet](https://docs.google.com/forms/d/1DO5U3APs6nyOorHWIvz5jwFz_Nvw4xhjGredIwprQCg/viewform?edit_requested=true)

# Next check-in
If you'd like to open the next check-in, please comment down below ! We'd love to help you 

**Thanks to all of you for making Publiclab amazing!!**

**Comment by cesswairimu** [comment]
@sssash18, @Tlazypanda, @Uzay-G, @VladimirMikulic, @pcube99, @nstjean, @imajit, @nicoleiocana, @simonastefan, @dependabot-preview[bot], @giovannyg, @jywarren, @NitinBhasneria, @seabl, @priyanka-choubey, @anthony-zhou, @hknowlton, @Bhanu-mbvg, @pythongiant, @EmirVatric, @KateAnn19, @daemon1024, @abdiclear, @Electrickal, @crisner, @shipcy, @sunguru98, @keshavsethi, @gxite

**Comment by cesswairimu** [comment]
@Rishabh570 @sashadev-sky @IshaGupta18 @SidharthBansal @vaibhavmatta @shubhscoder @aSquare14 @sidntrivedi012 @stefannibrasil @ViditChitkara @tech4GT @mridulnagpal @CoderJolly @namangupta01 @sagarpreet-chadha @Souravirus @MayankKashyap @siaw23 @ryzokuken @icarito @steviepubliclab, @ebarry, @jywarren, @sagarpreet-chadha, @JonathanXu1 @rexagod, @divyabaid16, @dinaelhanan, @oorjitchowdhary @publiclab/mentors @publiclab/image-sequencer-guides @publiclab/leaflet-environmental-layers-guides @Paarmita @publiclab/reviewers @Divy123 @bhavayAnand9 @Mridul97 @avsingh999 @Dhiraj240 @codeIriss @IgorWilbert @pdurbin @HarshKhandeparkar @niravasher @publiclab/reviewers @publiclab/is-reviewers @publiclab/community-reps @divyabaid16 @publiclab/community-reps @subhahu123 @govindjeevan @gautamig54 @rarrunategu1 @CleverFool77 @milaaraujo @kevinzluo @shipcy @developer22-university @keshavsethi @emilyashley @smarty1palak @daemon1024

**Comment by cesswairimu** [comment]
Great thanks @daemon1024

**Comment by jywarren** [comment]
Hello, and thank you!!!!

**Comment by nstjean** [comment]
Hi all! Public Lab has been my first contribution to Open Source, it always seemed rather daunting to contribute to a big project somewhere. I came from Outreachy, wanting to apply as an Intern. Unfortunately my first step was very frustrating! :laughing: I could not get Rails to install and run on my windows machine. I ended up having to dual-boot, but that didn't go smoothly either. Once I got it all set up and plots2 running it's been good! :+1:

**Comment by giovannyg** [comment]
Hello and thanks for give newcomers the opportunirty to contribute to open source and help us in the process.

**Comment by crisner** [comment]
Hello! 👋 My first step towards contributing to Public Lab was through Outreachy. I have made small contributions to other open-source projects before mainly through Hacktoberfest but I've felt that my contributions to Public Lab have been the most meaningful. ❤️

**Comment by SidharthBansal** [comment]
Mentors are requested to fill the form
https://docs.google.com/forms/d/1UcmXtNEVjZW6fozpW_9gWduRpnfVNG816JTswx85_VA/edit asap
DEADLINE 27 January 18 IST
Thanks all

**Comment by cesswairimu** [comment]
Hey all :wave:, my first step to actively contribute to PublicLab was through Rails Girls Summer of Code. I didn't get the internship but I found a great community :heart:

**Comment by SidharthBansal** [comment]
My first step was fixing a regex. I spent two months fixing that one character error at PL. I learned a lot about git and regex(more than required). I started solving regex problems on HackerEarth. That was funny. I was on wrong track to solve that problem. Then @jywarren guided me. @jywarren is really helpful. I remember that first PR. 🚀 
Lesson learned: Don't hesitate to ask. Mentors are there to show you the right track 🎉 
If they are helpful then you are lucky 💯

**Comment by katungi** [comment]
Hey people, I just joined. @cesswairimu  introduced me to the project and i am very excited to work with you all. I am new to open source but i hope this will be the perfect introduction.

**Comment by niravasher** [comment]
Hi! My fitst contribution to PL was making changes to the PL.Editor

**Comment by cesswairimu** [comment]
Hi all, anyone interested in opening next week's check-in? :eyes:

**Comment by NitinBhasneria** [comment]
Hello everyone, My first task was rhe first-timer issue due to which I gained confidence and then I started in other UI issue. As I tried contributinf in other organisations too I found peoples in public lab are more active and responsive also thank u for helping me @SidharthBansal @jywarren @nstjean .🤗

**Comment by cesswairimu** [comment]
Moved to https://github.com/publiclab/plots2/issues/7364 .Thanks all
