### ISSUE TITLE
IS not working on safari

### ISSUE THREAD

**Issue by hedonhermdev** [publiclab/image-sequencer#1541]
### Please describe the problem (or idea)
The icons for the modules are not visible as they are the same colour as the background colour.

### Please show us where to look
https://beta.sequencer.publiclab.org/

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by hedonhermdev** [comment]
![Screenshot 2020-01-19 at 11 08 03 PM](https://user-images.githubusercontent.com/23262887/72685541-3ea98000-3b11-11ea-89ed-d8df325d3e51.png)
![Screenshot 2020-01-19 at 11 08 34 PM](https://user-images.githubusercontent.com/23262887/72685549-4ec15f80-3b11-11ea-8fa9-ffc1afeecd43.png)

**Comment by saurabhkanswal** [comment]
what browser you are using?
Maybe image is not loaded successfully behind the icons. @hedonhermdev can you please reload the page again because it working fine for me.

**Comment by saurabhkanswal** [comment]
@hedonhermdev are you running locally? what commands are you using?
 because i am not getting this issue and it's working fine for me.
![pubbb](https://user-images.githubusercontent.com/26677033/72733102-2f800c00-3bbd-11ea-91a5-6957111b6556.PNG)

**Comment by HarshKhandeparkar** [comment]
If you are running this locally, then there is a chance that you haven't installed the node modules properly. Try running `npm run setup`.

**Comment by blurry-x-face** [comment]
@hedonhermdev are you still stuck with this?

**Comment by hedonhermdev** [comment]
So this happens only when I open the page in safari and not on Google Chrome. Maybe browser compatibility issues?

**Comment by blurry-x-face** [comment]
This also doesn't work on firefox #1211

**Comment by hedonhermdev** [comment]
Oh, when I load it looks similar to that in the screenshots in #1211

**Comment by HarshKhandeparkar** [comment]
Firefox has fixed their issue. If the issue still persists in Safari, please ask for support there.
