### ISSUE TITLE
Problem in extraManipulation

### ISSUE THREAD

**Issue by blurry-x-face** [publiclab/image-sequencer#1547]
After #1533 some modules are facing problem because of 
https://github.com/publiclab/image-sequencer/blob/2b3e5a2915262acb41cd6a9e39ab4b20807a5eb1/src/modules/_nomodule/PixelManipulation.js#L317
My #1546 was working fine before addition of this code but after its addition it has broken for some reason.
Also many of the tests were also failing [ref](https://github.com/publiclab/image-sequencer/pull/1542#issuecomment-576289735)

We need to fix this soon!

**Comment by blurry-x-face** [comment]
CC: @HarshKhandeparkar @root00198

**Comment by blurry-x-face** [comment]
For starters we can do [this](https://github.com/publiclab/image-sequencer/pull/1533#issuecomment-576291663), it will fix the immediate problem!

**Comment by root00198** [comment]
I think the issue is that the  getDataUri in this line https://github.com/publiclab/image-sequencer/blob/2b3e5a2915262acb41cd6a9e39ab4b20807a5eb1/src/modules/_nomodule/PixelManipulation.js#L317
is an asynchronous call, and the generateOutput is called even before the frame could be set.

**Comment by blurry-x-face** [comment]
Yes, this seems to be the problem, but I don't think we need to use getDataUri this way, it can be used in some other way, calculating it here when most of the modules don't even require it, this seems useless to me.

**Comment by blurry-x-face** [comment]
So, Colorbar module is also not working after this!

**Comment by blurry-x-face** [comment]
And also Resize module.

**Comment by blurry-x-face** [comment]
Why did the tests pass even though they were not working?

**Comment by root00198** [comment]
The test didn't passed, I think...

**Comment by blurry-x-face** [comment]
Yea you're right, tests didn't pass https://travis-ci.org/publiclab/image-sequencer/jobs/638695414#L1970
If that was the case then why was there green tick on travis?

![Screenshot from 2020-01-21 20-08-52](https://user-images.githubusercontent.com/42492389/72813733-e21da080-3c89-11ea-8735-3207316c6237.png)

**Comment by blurry-x-face** [comment]
@jywarren @HarshKhandeparkar

**Comment by jywarren** [comment]
Oof, thank you, and can we get some reviews on #1551? Looking now, thanks for the discuss and fix!

Also noting https://github.com/publiclab/image-sequencer/pull/1550 and #1427 regarding the Travis green checkmark issues... great catch.
