### ISSUE TITLE
Intermittent test failure in Travis

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#1554]
After #1550 maybe? I saw this issue:

> Uh oh, it looks like with the various test changes we now have a test failure on the main branch. https://travis-ci.org/publiclab/image-sequencer/builds/640158326

> is anyone able to take a look at this? i'm working on another priority issue at the moment.
it failed in Node 10 but not 8. i'm retriggering it to see if it's intermittent!

(...)

> Seems it was intermittent... it passed this time! But that is a bit disconcerting. I'm going to document in an issue, but less urgent than it had been... thanks!

**Comment by root00198** [comment]
Okay, so I think the issue why a particular test is failing is because of look-same module, which we are using to compare two images, in test suite... Look-same is not reliable refer issue #1536

**Comment by jywarren** [comment]
Taking this off because we now use GitHub Actions!
