### ISSUE TITLE
Crop module UI

### ISSUE THREAD

**Issue by ataata107** [publiclab/image-sequencer#1558]
### Please describe the problem (or idea)
There is UI on top left corner when we select crop module. Some PR might have caused that

![Screenshot from 2020-01-22 13-08-55](https://user-images.githubusercontent.com/32903329/72874604-6b7bb400-3d18-11ea-9d0d-f201a81a2529.png)

> What happened just before the problem occurred? Or what problem could this idea solve?

> What did you expect to see that you didn't?

### Please show us where to look

https://beta.sequencer.publiclab.org

### What's your PublicLab.org username?

> This can help us diagnose the issue:

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by ss62171** [comment]
I would like to work on this.

**Comment by blurry-x-face** [comment]
Hi @ss62171, this already has a pr!

**Comment by ss62171** [comment]
@blurry-x-face didn't see that.
