### ISSUE TITLE
Add a Contrast module

### ISSUE THREAD

**Issue by tech4GT** [publiclab/image-sequencer#157]

**Comment by jywarren** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @jywarren.

**Comment by Mridul97** [comment]
Hi, I was trying to create this module. The module will accept values between -100 and 100, but we turn these into a double between the values of 0 and 4. 

This is the output for contrast value of 50. Please have a look!

![ss_11](https://user-images.githubusercontent.com/21158457/46327913-d421b780-c621-11e8-800d-7c45903b2c4d.jpg)

**Comment by jywarren** [comment]
Oh wow this looks great. Do you have a PR for it? I'd love to accept this! Thank you!

**Comment by Mridul97** [comment]
I have created a PR #463 Please have a look!
