### ISSUE TITLE
Edge detect is not working correctly

### ISSUE THREAD

**Issue by blurry-x-face** [publiclab/image-sequencer#1576]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

I tried running edge detect in browser and it gave following output (default values)

![Screenshot from 2020-01-26 07-35-06](https://user-images.githubusercontent.com/42492389/73129625-6d8e8d00-400e-11ea-9747-5c632371942d.png)

I tried running edge detect in node and it gave following output (default values)

![image_1](https://user-images.githubusercontent.com/42492389/73129618-4041df00-400e-11ea-9eb6-813d8fe2bd74.png)

> What did you expect to see that you didn't?

### Please show us where to look

https://beta.sequencer.publiclab.org

### What's your PublicLab.org username?

> This can help us diagnose the issue:

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by blurry-x-face** [comment]
@HarshKhandeparkar could you look into this!

**Comment by blurry-x-face** [comment]
@publiclab/is-reviewers can anyone please look into this!

**Comment by HarshKhandeparkar** [comment]
Looking :mag:

**Comment by HarshKhandeparkar** [comment]
Got a fix! That was very fast.

**Comment by HarshKhandeparkar** [comment]
Can't make out whether it is working or not. `sequencer.publiclab.org` was working just fine some time back but now even that is not producing the expected output.

**Comment by HarshKhandeparkar** [comment]
Okay, I don't know what to do now. This could even be a browser problem. Now I cannot test it on another browser because FF doesn't work :crying_cat_face:

**Comment by blurry-x-face** [comment]
Try to repeat following steps:

1. Open beta site
2. Load edge detect module
3. Change the image to [this](https://github.com/publiclab/image-sequencer/blob/main/examples/images/IS-QR.png)

Save the generated output and then remove the edge-detect step and clear the cache, now follow the following steps:

1. Open beta site.
2. Load [this](https://github.com/publiclab/image-sequencer/blob/main/examples/images/IS-QR.png) image.
3. Add edge-detect step

Now compare the two outputs.
My results:

Output 1:

![download (7)](https://user-images.githubusercontent.com/42492389/73472233-b77dc700-43b0-11ea-8290-0e3fe924d874.png)

Output 2:

![download (8)](https://user-images.githubusercontent.com/42492389/73472258-c1072f00-43b0-11ea-909d-c7b190fcc68a.png)

@HarshKhandeparkar could you confirm this.

**Comment by blurry-x-face** [comment]
> Okay, I don't know what to do now. This could even be a browser problem. Now I cannot test it on another browser because FF doesn't work

IS also doesn't work on safari :(

**Comment by HarshKhandeparkar** [comment]
OMG! The outputs ARE different! What???

**Comment by blurry-x-face** [comment]
> OMG! The outputs ARE different! What???

:rofl: my reaction exactly

**Comment by blurry-x-face** [comment]
@HarshKhandeparkar  Could you make it work without using gpu.js and confirm if the problem still persists

**Comment by blurry-x-face** [comment]
@jywarren could you please look into this!

**Comment by HarshKhandeparkar** [comment]
GPU.js is actually only used for blur. If that is working then I don't think it's a GPUjs problem.

**Comment by blurry-x-face** [comment]
Yea you're right, I just checked.
What do you think the problem could exactly be?

**Comment by HarshKhandeparkar** [comment]
I think I'll work on this for Bug Stomp February.

**Comment by HarshKhandeparkar** [comment]
Hey guys! I think I found out the issue!
![Screenshot from 2020-02-15 19-46-50](https://user-images.githubusercontent.com/34770591/74589538-19cefc80-502c-11ea-9728-2e79d5e2f889.png)

It is mixing up images somehow.

**Comment by HarshKhandeparkar** [comment]
The QR image was loaded before loading the flowers.

**Comment by HarshKhandeparkar** [comment]
@publiclab/is-reviewers

**Comment by HarshKhandeparkar** [comment]
FIXED! Opening a PR soon!
@publiclab/is-reviewers
