### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by niravasher** [publiclab/image-sequencer#1577]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

Tests for modules like add-qr, blur, convolution, edge-detect, fisheye-gl, webgl-distort are failing.

### Please show us where to look

https://beta.sequencer.publiclab.org

### What's your PublicLab.org username?
niravasher
> This can help us diagnose the issue:

### Browser, version, and operating system
ubuntu 19.04
> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by blurry-x-face** [comment]
Can you share the link to the travis build where tests were failing?

**Comment by niravasher** [comment]
I get failed tests on my terminal but on travis CI they have passed.
![Screenshot from 2020-01-26 14-48-19](https://user-images.githubusercontent.com/32176296/73133164-03e0a400-404b-11ea-8012-d2c85cbfc732.png)

**Comment by blurry-x-face** [comment]
Could you try rebasing?
