### ISSUE TITLE
Amount of tint not working

### ISSUE THREAD

**Issue by govindgoel** [publiclab/image-sequencer#1578]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?
In the tint option we can specify the amount of tint but when we change the color after that you cannot change the value of amount of tint.

> What did you expect to see that you didn't?
The value of amount of tint can be changed after that

### Please show us where to look

https://beta.sequencer.publiclab.org/examples/#steps=tint{}

### What's your PublicLab.org username?

> This can help us diagnose the issue:

![ ](https://media.giphy.com/media/ZccMSEVRnszP5JjNny/giphy.gif)

### Browser, version, and operating system
Brave Browser Version 1.1.21 Chromium: 79.0.3945.79 (Official Build) (64-bit)
Firefox Version 71.0 (64-bit)

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by ataata107** [comment]
Sorry wasn't able to catch this error seems to be working fine for me can you reconfirm.

**Comment by govindgoel** [comment]
@ataata107  Checked again but not working I will try to work on this.

**Comment by niravasher** [comment]
Even I am getting the same problem. Before changing color I can change the amount of tint but after changing color, I can't @ataata107

**Comment by niravasher** [comment]
This is not just for tint, but any module in which color has to be chosen has this bug @govindgoel @ataata107

**Comment by blurry-x-face** [comment]
I fixed this bug in #1465 and it is working fine, try rebasing

**Comment by blurry-x-face** [comment]
@govindgoel could you confirm that it worked after rebasing or not?

**Comment by blurry-x-face** [comment]
This issue has been resolved in #1465
