### ISSUE TITLE
Add a Saturation Module

### ISSUE THREAD

**Issue by tech4GT** [publiclab/image-sequencer#158]

**Comment by jywarren** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @jywarren.

**Comment by jywarren** [comment]
Maybe using this library -- convert to HSV color model, increase saturation, then convert back? 

https://www.npmjs.com/package/colorsys

**Comment by jywarren** [comment]
@danielleshwed how about this one? It should be possible by running each pixel through the `pixelManipulation` function then using `colorsys` as above to change that pixel. Not super efficient, but it should work! Does that make sense? So it'd be kind of like the Green Channel module, structurally.

**Comment by danielleshwed** [comment]
@jywarren great! i will give it a go 👍

**Comment by jywarren** [comment]
awesome!!!
