### ISSUE TITLE
Grid display

### ISSUE THREAD

**Issue by niravasher** [publiclab/image-sequencer#1586]
### Please describe the problem (or idea)

> What did you expect to see that you didn't?

We can have a button which toggles display of 3 X 3 grid
![Screenshot from 2020-01-28 16-36-13](https://user-images.githubusercontent.com/32176296/73258886-a421fe80-41ec-11ea-92fb-fe2a4ba19e1c.png)

### Please show us where to look

https://beta.sequencer.publiclab.org

### What's your PublicLab.org username?
niravasher

### Browser, version, and operating system
19.04

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by blurry-x-face** [comment]
Don't we already have a module for this?

**Comment by niravasher** [comment]
Ok, did not see that.
