### ISSUE TITLE
enable processing on alternate thread using greenlet (workerize)

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#159]
https://github.com/developit/greenlet

This would be a cool option esp for browser use!

**Comment by tech4GT** [comment]
@jywarren  I would like to take up this issue😁

**Comment by tech4GT** [comment]
@jywarren can i start working on this?😅

**Comment by jywarren** [comment]
Sure! We're almost done with edge detection. Do you think this is a tough one?

**Comment by tech4GT** [comment]
I have been researching a little and yeah this is a little tough but nothing we can't handle😁
Cheers

**Comment by tech4GT** [comment]
@jywarren this is included in my summer proposal with an additional host of features like offline use and push notifications so putting this on hold for now, I hope that's fine?

**Comment by jywarren** [comment]
Sure, that sounds great!

**Comment by tech4GT** [comment]
@jywarren we just got Native support for worker threads in node.js!!🎉

**Comment by tech4GT** [comment]
We can now implement this natively!!!

**Comment by tech4GT** [comment]
@ryzokuken Am I right? We are looking to run the image processing calculations on a different thread in both browser and node, so we can now just implement it in node and will browserify handle it for the browser?

**Comment by jywarren** [comment]
Whoa.... link? Cool!

**Comment by tech4GT** [comment]
https://github.com/nodejs/node/pull/20876#issue-189524671

**Comment by tech4GT** [comment]
@ryzokuken can you please guide me a little here
Thanks

**Comment by Mridul97** [comment]
Yes, I would love to give this a try! Thanks! @jywarren

**Comment by Mridul97** [comment]
@jywarren @tech4GT Could you please tell which all image processing calculations we want to run on a different thread?

**Comment by tech4GT** [comment]
@Mridul97 So thing with this one is that this makes more sense for the browser since it becomes unresponsive while waiting for complex steps like edge-detect to run, what we want is a system where `sequencer.run()` is called on a different thread.

**Comment by tech4GT** [comment]
So you need to figure how to pass all the image data from one thread to another and then back without introducing any significant delay, I tried this using the web worker API but it copies the data you are trying to pass in the new thread, making it slower for large amounts of data like images.

**Comment by tech4GT** [comment]
I also found this page a while back https://keithwhor.github.io/multithread.js/ 
It also uses the web worker api but this is easier to use.

**Comment by Mridul97** [comment]
Ah okay, I will try to find a way to pass data from one thread to other faster. Thanks!

**Comment by Mridul97** [comment]
@jywarren @tech4GT We want to run this function inside a different thread right?

https://github.com/publiclab/image-sequencer/blob/09669fe858fb738d6311c52f3306793b621c7358/examples/lib/defaultHtmlSequencerUi.js#L56

So we cannot use any npm? because browserify is not used on this file. I am sorry if I am not making sense:sweat_smile:

**Comment by Mridul97** [comment]
So we don't have to use greenlet?

**Comment by tech4GT** [comment]
Greenlet is also based on worker api only, I'll suggest try browserifying it and then using it!

**Comment by Mridul97** [comment]
Oh okay, Thanks!

**Comment by Mridul97** [comment]
I was installing webworker-threads npm but I got the following error. Could you please help me with this. @tech4GT 

![ss_21](https://user-images.githubusercontent.com/21158457/46578336-4972fb00-ca1b-11e8-8e48-c45522ee9e87.jpg)

![ss_22](https://user-images.githubusercontent.com/21158457/46578338-51329f80-ca1b-11e8-84ab-4a6a917aba84.jpg)

**Comment by tech4GT** [comment]
Hmm, it seems this only works on mac, look it says requires os darwin.

**Comment by Mridul97** [comment]
Oh I see it requires os darwin. Thanks!

**Comment by tech4GT** [comment]
I would suggest pass the sequencer object to a worker thread through the web worker api and then try to optimise the amount of data that is being passed. For instance we don’t need all the step outputs since we can process them, stuff like this.

**Comment by Mridul97** [comment]
Oh okay, I will try doing that. Thanks!

**Comment by Mridul97** [comment]
@tech4GT I tried to pass sequencer object to the worker thread from the main thread but I got the error 'could not be cloned'. I also tried to pass sequencer.run but I got the same error. Could you please help me with this.

**Comment by tech4GT** [comment]
Yes mridul, this is difficult part, I think cloning custom objects has to follow certain rules, you would have to google that, so you would have to format the sequencer object accordingly before passing trying to pass it.

**Comment by Mridul97** [comment]
@tech4GT I read that we cannot pass methods to the worker thread so I defined the run function in task.js and passed the images object and sequenceLength. I am actually stuck, there is no error showing but I am not getting the desired output. Will you please have a look once. Should I open a PR so that you can look at the code?

**Comment by Mridul97** [comment]
I have created a PR #398. Please have a look!

**Comment by tech4GT** [comment]
Hmm mridul don't we have access to `new ImageSequencer()`  in the worker thread, Can't we pass the sequence and the image and then process them in a new sequencer object?

**Comment by tech4GT** [comment]
Okay mridul I'll look into this in detail tom, gtg right now. Thanks for all the hard work on this one and don't worry we'll figure something out!

**Comment by Mridul97** [comment]
I tried creating a new ImageSequencer(), it didn't work. I think we don't have access to new ImageSequencer () in the worker thread. Please help!

**Comment by tech4GT** [comment]
Hmm, Mridul actually I am not working this week, let's look at this next week, maybe I'll think of something until then. Thanks!

**Comment by Mridul97** [comment]
Okay!

**Comment by HarshKhandeparkar** [comment]
Lets revive this.
