### ISSUE TITLE
Module for sharpening images

### ISSUE THREAD

**Issue by blurry-x-face** [publiclab/image-sequencer#1612]
### Please describe the problem (or idea)

We currently do not have any module for sharpening a image, I was looking for a good way to make the image to look more sharp and I came across this: [ref](https://en.wikipedia.org/wiki/Unsharp_masking)

What does everyone else think of this?

**Comment by blurry-x-face** [comment]
@publiclab/is-reviewers should I go ahead with this?

**Comment by ataata107** [comment]
Yes this would be really good

**Comment by jywarren** [comment]
Solved by @waridrox! Thank you!!!
