### ISSUE TITLE
Offset the back to top button to right

### ISSUE THREAD

**Issue by govindgoel** [publiclab/image-sequencer#1628]
### Please describe the problem (or idea)
> What did you expect to see that you didn't?
The back to top buton covers the save the image box so it can be shifted to right so that it looks fine

### Please show us where to look

https://beta.sequencer.publiclab.org

![ ](https://media.giphy.com/media/h597u61tu4iCbHBqxP/giphy.gif)

### What's your PublicLab.org username?

> This can help us diagnose the issue:

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by alti21** [comment]
Hi can I work on this?

**Comment by govindgoel** [comment]
This is fixed
