### ISSUE TITLE
Edge Detect Possibly Glitching on Horizontal Edges

### ISSUE THREAD

**Issue by HarshKhandeparkar** [publiclab/image-sequencer#1632]
### Please describe the problem (or idea)
![](https://user-images.githubusercontent.com/42492389/73129618-4041df00-400e-11ea-9eb6-813d8fe2bd74.png)

The image above is an example output of our edge detect module. It is supposed to generate finest possible edges in the non maximum suppression step itself.
But there are many thick horizontal edges (in the square at the corner for example)

### Please show us where to look

https://beta.sequencer.publiclab.org

### What's your PublicLab.org username?

> This can help us diagnose the issue:

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by ataata107** [comment]
Can you share the original image on which edge detection was applied? Thanks

**Comment by HarshKhandeparkar** [comment]
The image is on our repo `/examples/images/IS-QR.png`t

**Comment by ataata107** [comment]
![edge-detect](https://user-images.githubusercontent.com/32903329/74829035-29a15600-5336-11ea-91e7-e532f7e173b7.png)
This is the output without the blur applied. I guess blurring is causing the thick edges

**Comment by HarshKhandeparkar** [comment]
The vertical edges aren't as thick as before but they are still weird.
