### ISSUE TITLE
Edge detection module

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#166]
Let's make a module that detects object edges, kind of like in this note: https://publiclab.org/notes/amirberAgain/01-12-2018/python-and-opencv-to-analyze-microscope-slide-images-of-airborne-particles

Some leads:

* [ ] https://github.com/yuta1984/CannyJS - edge detection
* [ ] http://codepen.io/taylorcoffelt/pen/EsCcr - more edge detection

The module could actually output a JSON description of the edges, maybe? Like how the QR code module outputs the value of the QR code it decodes? That's here:

https://github.com/publiclab/image-sequencer/blob/c5dee8aef330d1bb4c88f88ea7471d4982c1859f/src/modules/DecodeQr/Module.js#L40

**Comment by jywarren** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @ccpandhare.

**Comment by tech4GT** [comment]
@jywarren i would like to work on this issue

**Comment by jywarren** [comment]
ooh, awesome! Please do, thank you!

**Comment by ccpandhare** [comment]
#168 Does get into this, but we probably need to modify that from a greyscale output to actual edges.

**Comment by tech4GT** [comment]
@ccpandhare i am working on that, right now it is just a sobel filter will be adding a lot of stuff to it😁
