### ISSUE TITLE
Auto-generate testable demos from all pull requests with GitPod.io

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#1665]
To make testing out new PRs faster and easier, we could integrate with GitPod.io, which auto-builds and hosts a browser-based version. I think, though i'm not sure, that we could do this with IS: 

https://www.gitpod.io/

**Comment by blurry-x-face** [comment]
I believe this would be amazing integration and would help in better review of the PRs

**Comment by nisarhassan12** [comment]
I volunteer to make a Pr for this.
