### ISSUE TITLE
Output not generated if contents of output folder are deleted

### ISSUE THREAD

**Issue by tech4GT** [publiclab/image-sequencer#170]
Hi, this is a first-timers-only issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!😁

The problem

If the output folder is an empty directory (if you delete the contents of the ouput folder) the sequencer output will not get exported since callback is not called in that case
This line should be fixed

https://github.com/publiclab/image-sequencer/blob/32c5a29906e35c2741262f467e3fb73fff31d546/src/ExportBin.js#L5

Solution
Add a check which enables the callback being called in the case the length of the files array is 0

Steps to fix
- [x] claim this issue with a comment
- [x]     set up a repository locally and make sure that all tests pass
- [x]     start a pull request (see contributing to Public Lab software) but mark it as "in progress"
- [x]     fix the issue following the steps above
- [x]     make sure all tests pass
- [x]     alert someone via either the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org/developers) if you have questions!

**Comment by jywarren** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @jywarren.

**Comment by tech4GT** [comment]
@jywarren this will make a good first timer issue please add the label😁

**Comment by jywarren** [comment]
This does look like a good first-timers issue! Before we label it as such, would you mind reformatting it following some of these suggestions? 

https://publiclab.org/n/13667

Thank you! It'll be exciting to see more people join in :-) 👍

**Comment by tech4GT** [comment]
@jywarren how does this look?

**Comment by jywarren** [comment]
It looks good, but it's really worth the extra effort to copy in the welcoming text too! People just feel great about it when you're extra welcoming and use some emoji :-) 👍

**Comment by tech4GT** [comment]
@jywarren done, please have a look😁

**Comment by jywarren** [comment]
Great we can clean up some comments if you want too

**Comment by mayank1010** [comment]
i will give it a go

**Comment by tech4GT** [comment]
Sure mayank go ahead😁

**Comment by danielleshwed** [comment]
i am interested in working on this if it is available

**Comment by jywarren** [comment]
@danielleshwed we'd love to have your help, @tech4GT maybe we could make another first timers issue since @mayank1010 is already working on this one? 

Thanks!

**Comment by tech4GT** [comment]
@jywarren sure I'll do that right away
@danielleshwed welcome to the community 😁

**Comment by tech4GT** [comment]
@danielleshwed Jeff is busy right now, start with [#177](https://github.com/publiclab/image-sequencer/issues/177), just go through the contributing.md file to make a basic module and add the line referenced in the issue for the blur module, don't worry about the labels it's a relatively simple issue😁

**Comment by tech4GT** [comment]
@jywarren this issue can be closed now, thanks
