### ISSUE TITLE
Add "Loading version number" instead of "unable" message in UI

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#1724]
The message shown while loading the version number could use a tweak.

![Screen Shot 2020-07-10 at 3 00 15 PM](https://user-images.githubusercontent.com/24359/87189123-17608e00-c2be-11ea-8a25-165baf1221cf.png)

It says "unable to load version number" until the page is finished loading. Maybe it should say:

`Loading version number` until it's loaded, but if it fails we rescue and try changing to `Unable to load version number`?

What do you think?

_Originally posted by @jywarren in https://github.com/publiclab/image-sequencer/pull/1567#issuecomment-656835348_

**Comment by frappelatte28** [comment]
Hey! @jywarren Can I work on this issue?

**Comment by jywarren** [comment]
That would be great! Would you like some help finding the area of code for this? I'd start by searching the codebase for ""unable to load version number" -- thanks!!

**Comment by vivek-30** [comment]
hi @frappelatte28 mam are you still solving this issue if not then i have made a decent progress regarding the same  and want a feedback for that so is it ok if i will raise a PR for this issue

**Comment by frappelatte28** [comment]
Go ahead @vivek-30 I am busy with my semester exams, I will find some issues as soon as this semester thing ends.

**Comment by vivek-30** [comment]
**Thank you**  mam ☺️

**Comment by vivek-30** [comment]
Hlo @jywarren sir, looking up the above issue i found something related which when modified gives desired output( but partially ) 
here what i have found in examples/index.html

![Screenshot 2021-01-15 at 3 29 52 PM](https://user-images.githubusercontent.com/75980147/104711483-6f81bc80-5747-11eb-89a5-7c5ffcf64a0c.jpg)

One Thing which is a bit confusing is that when i test the project on port other than `3000` ( say- `4000` ) then it gives output as required but not on `3000` could you plz help me.

**Comment by vivek-30** [comment]
Actually ,sir its my bad 😅 ,It was just the offline cache that the browser was using that time .
But now it is working as expected
