### ISSUE TITLE
Better method of parsing %ages

### ISSUE THREAD

**Issue by HarshKhandeparkar** [publiclab/image-sequencer#1725]
### Please describe the problem (or idea)
https://github.com/publiclab/image-sequencer/blob/d33afe09da371c8aa69a3e84027b030f47b476bf/src/modules/Resize/Resize.js#L5

The resize module parses %ages eg `50%` by just removing the last character `50% -> 50` but this is an issue since one can type `50% ` with space or just `50`. We need to find a better way to parse percentages in all modules.

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by adzo261** [comment]
Hi, can I do this?

**Comment by HarshKhandeparkar** [comment]
Sure @adzo261

**Comment by adzo261** [comment]
Can `options.resize` be a floating-point percentage value like `70.65%` ? . Since we are parsing it as int, I am assuming integral percentages. Correct me if I am wrong.

**Comment by HarshKhandeparkar** [comment]
I think it can be a floating point but I don't think that will make a big difference... Let there be support for it though because one can type `90.0`. What do you think?

**Comment by adzo261** [comment]
I agree. We should cover floating-point also.
