### ISSUE TITLE
CRITICAL: Dynamic module uses eval

### ISSUE THREAD

**Issue by HarshKhandeparkar** [publiclab/image-sequencer#1728]
### Please describe the problem (or idea)
The `dynamic` module uses the javascript `eval` function to evaluate expressions. But the exec method should not be used **at any cost** because it will **execute any js code that is entered in the textbox**.

![image](https://user-images.githubusercontent.com/34770591/96298324-e48e0a80-100f-11eb-8b59-52e5bf1ea90c.png)

This is a major security threat to the IS demo and any other projects that use IS.
### Please show us where to look

https://beta.sequencer.publiclab.org

### What's your PublicLab.org username?

> This can help us diagnose the issue:

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by jywarren** [comment]
Hi, do you have any ideas for other ways to accomplish this functionality? Thanks!

Could we swap for https://github.com/silentmatt/expr-eval ?

**Comment by jywarren** [comment]
https://github.com/publiclab/image-sequencer/blob/8c461bbeeebd5c79676185ecf209f1d9181ad1f2/src/modules/Dynamic/Module.js#L17-L22

could we swapped for:

```js

```

Also, i think you maybe meant `eval` and not `exec`? Thanks Harsh!

**Comment by HarshKhandeparkar** [comment]
Oh yeah sorry, I meant eval.

**Comment by HarshKhandeparkar** [comment]
> Hi, do you have any ideas for other ways to accomplish this functionality? Thanks!
> 
> Could we swap for https://github.com/silentmatt/expr-eval ?

I guess there are packages like the one you found. We can switch if it doesn't break anything... What kind of expressions need to be supported though? :thinking:

**Comment by jywarren** [comment]
It's designed just for simple mathematic expressions to do color channel compositing - so this should be fine!

**Comment by jywarren** [comment]
Check out #1729!
