### ISSUE TITLE
Building out a contributor community for Image Sequencer

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#173]
Hi, all -- @publiclab/reviewers too -- i'm interested in how we might get a group of JavaScript/Node folks to also review projects like this one. I know we have some in the group, but is it annoying to ask for reviews across projects if not everybody does lots of JavaScript, or do you think it's OK to be pinging reviewers for any PR? 

@ccpandhare @tech4GT i'm interested in hearing from you as well! Are either of you in the reviewers group or want to be? 

https://publiclab.org/wiki/developers#Reviewers

**Comment by tech4GT** [comment]
@jywarren i am currently not a reviewer but i would love to be😁

**Comment by jywarren** [comment]
Added you! More resources here: https://publiclab.org/software-outreach

**Comment by tech4GT** [comment]
@jywarren thanks a lot😁

**Comment by tech4GT** [comment]
@jywarren I can see how busy you are and I wanted to help, so I was thinking that maybe what we can do is that I can review and help people especially first timers to build their pull requests for image-sequencer and once the pr is just right i will ask for a closing review from you, that will reduce your workload at least for this project, what say?

**Comment by jywarren** [comment]
:-) thank you! that would be fantastic. I really appreciate it -- you're
doing great work on this project :-)

**Comment by jywarren** [comment]
Moving to a new issue here: https://github.com/publiclab/image-sequencer/issues/656
