### ISSUE TITLE
Not working in Safari

### ISSUE THREAD

**Issue by jlev** [publiclab/image-sequencer#1738]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

Load page, can't take or upload photos.
Console error "Invalid regular expression: invalid group specifier name"

Quick google search indicates that error message may be due to using look-behinds in regular expressions.
https://stackoverflow.com/questions/51568821/works-in-chrome-but-breaks-in-safari-invalid-regular-expression-invalid-group

### Please show us where to look

https://beta.sequencer.publiclab.org

### What's your PublicLab.org username?

> This can help us diagnose the issue:

jlev

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

Mac OS 10.15.7
Safari 14.0

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by HarshKhandeparkar** [comment]
Umm, does it work on other browsers? If yes, then it might be a safari regex implementation issue...

**Comment by HarshKhandeparkar** [comment]
Can you tell which line of code is throwing the error?

**Comment by jlev** [comment]
Not in production, because there aren't source code maps published.

Running locally, the error I get is
```
[Error] SyntaxError: Invalid regular expression: invalid group specifier name
	(anonymous function) (image-sequencer.js:107485)
```

Looks like it was fixed in https://github.com/micromatch/picomatch/issues/15
