### ISSUE TITLE
More Issue Templates

### ISSUE THREAD

**Issue by harshkhandeparkar** [publiclab/image-sequencer#1757]
![image](https://user-images.githubusercontent.com/34770591/97834257-66af4c00-1cfd-11eb-9c88-41ba433adbb9.png)

We have the above issue templates as of now. Adding the following issue templates might be helpful:
- Feature Request
- FTO
- A default template instead of a blank one.
Any suggestions? Please :point_down: :upside_down_face: 

References:
- [Github templates docs](https://docs.github.com/en/enterprise/2.16/user/github/building-a-strong-community/about-issue-and-pull-request-templates)
- [Templates in this project](https://github.com/publiclab/image-sequencer/tree/main/.github/ISSUE_TEMPLATE)

**NOTE**: The FTO template is [here](https://github.com/publiclab/image-sequencer/blob/main/.github/fto-template.md), it just needs to be moved. (And any changes if required)

**Comment by unnati914** [comment]
I want to work on this issue

**Comment by harshkhandeparkar** [comment]
Sure! Which templates do you plan on adding?

**Comment by unnati914** [comment]
We can have a seperate template for enhancements, any design issue we contribute to.. any proposal we have for the project etc.

**Comment by unnati914** [comment]
any feature additions too :D

**Comment by harshkhandeparkar** [comment]
:rocket: :+1:
