### ISSUE TITLE
Add option to export edge-detected image with black background

### ISSUE THREAD

**Issue by tech4GT** [publiclab/image-sequencer#176]
Desired output
![](https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/%C3%84%C3%A4retuvastuse_n%C3%A4ide.png/1000px-%C3%84%C3%A4retuvastuse_n%C3%A4ide.png)

- [ ] Export image with black background
- [ ] Add support for jpeg images

**Comment by jywarren** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @jywarren.

**Comment by jywarren** [comment]
This is a follow-up to https://github.com/publiclab/image-sequencer/pull/168 !! Thanks!

**Comment by Ankit-Singla** [comment]
Is this issue open?
If so, I would like to work on this one if it's okay?

**Comment by tech4GT** [comment]
@Ankit-Singla this is a relatively difficult issue, we would love your help here though!! Don't hesitate to ask if you get stuck! Thanks!!

**Comment by Ankit-Singla** [comment]
I was thinking to present it as an input to the user, whether he/she wants the background to be white or black in the existing 'Detect Edges' module. Does this seem fine, or should I integrate this alternatively. @tech4GT 
Thanks

**Comment by HarshKhandeparkar** [comment]
@tech4GT @jywarren I am working on this (almost done). I'm actually going to complete the module with hysterisis. I think I have found out a pretty good way of doing that. The black background is working. Just a few more lines of code needed to complete hysterisis. Will open a pr soon 😊
