### ISSUE TITLE
Make text alignment easier with a few more buttons

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#1767]
> https://sequencer.publiclab.org/examples/#steps=text-overlay{text:You%20grilled%20raptors%3F|x:150|y:280|font:arial|color:rgba(241%2C235%2C30%2C1)|size:20}

I made a meme and realized the text overlay tools are pretty rough... I kind of wish for a bit more ability to align center, vertical align, some other simple tools like that. I wonder how much work that would be?

![Screenshot_20201116-080907](https://user-images.githubusercontent.com/24359/99256459-70e44680-27e3-11eb-9b80-4f8296325599.png)

**Comment by YogeshSharma01** [comment]
@jywarren I get your points can i work on this.

**Comment by HarshKhandeparkar** [comment]
Go ahead @YogeshSharma01

**Comment by YogeshSharma01** [comment]
Hi, @HarshKhandeparkar we can add options for text to set itself on the left side of the image and at the right side of the image or in the center of the image.

**Comment by HarshKhandeparkar** [comment]
Sounds good! Go ahead!

**Comment by YogeshSharma01** [comment]
Thanks, @HarshKhandeparkar, I actually working on the Community toolbox just right after finish my work from there I'll start work on this.

**Comment by vivek-30** [comment]
@HarshKhandeparkar  can i work on this?

**Comment by YogeshSharma01** [comment]
Vivek actually I'm working on it and asap I'll give a PR actually I'm busy
in my exams and working on community toolbox as well.
Warm Regards,
Yogesh Sharma

**Comment by vivek-30** [comment]
ok @YogeshSharma01  take your time, no hurry and if you need any kind of help plz let me know i will be happy to help you ☺️

**Comment by YogeshSharma01** [comment]
@vivek-30 thanks

**Comment by vivek-30** [comment]
@HarshKhandeparkar may be @YogeshSharma01  is very busy and i have finished this issue so if you allow i can submit a PR so that this issue is no longer open?

**Comment by vivek-30** [comment]
what will you say?, i think he is also working with some different issue he can finish it meanwhile

**Comment by HarshKhandeparkar** [comment]
If Yogesh agrees, you can open a PR :)

**Comment by vivek-30** [comment]
@YogeshSharma01 if you are working on community toolbox then i can fix this issue on your behalf. Also i have already resolved this just need to push it .

**Comment by YogeshSharma01** [comment]
Hi, Vivek 
Yeah sure go-ahead.
Warm Regards,
Yogesh Sharma

**Comment by vivek-30** [comment]
Thanks a lot @YogeshSharma01 😊
