### ISSUE TITLE
Weekly Community check-in #83  - Check-in with us

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/image-sequencer#1768]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become a leader of tomorrow. 💯

## How are you doing?- Check-in with us 

The second wave of the virus is currently hitting most of the nations... lets do another check in on how we are doing overall and how things are going in your country. Also feel free to share new things you have picked up or some activities you are doing to keep sane :heart: 

## Next Check-in
If you would like to open the next check-in..Leave a comment below. We are happy to help if its your first time

**Thanks everyone for making Public Lab awesome** :heart:  
Have a great week ahead all :balloon:

**Comment by tawahpeggy** [comment]
Thanks for checking in @cess. The virus has really left the whole world speechless and has affected all of us in one way or the other.
I will love to do the next check-in

**Comment by tawahpeggy** [comment]
Last week was especially difficult for me as i wasnt feeling too well. thank God I feel a whole lot stronger now and hope this week turns out much more better and fruitful.
A great and fruitful week to you all too.

**Comment by Tlazypanda** [comment]
Hey everyone :wave: How are you all doing? :sweat_smile:  

I am sorry to hear this @tawahpeggy Hope you are feeling better! I was also having covid symptoms for a couple of weeks and had self isolated but am feeling better now :tada:  

Some great work here by all the Outreachy folks :tada:  :heart: 
Also noticed that the site has slowed down as flagged by skylight and also on gitter chat @icarito @jywarren  should we have an issue for the specific routes with the biggest slowdowns and possibly understand the reasons behind it? :thinking:

**Comment by tawahpeggy** [comment]
> Hey everyone  How are you all doing? 
> 
> I am sorry to hear this @tawahpeggy Hope you are feeling better! I was also having covid symptoms for a couple of weeks and had self isolated but am feeling better now 
> 
> Some great work here by all the Outreachy folks  
> Also noticed that the site has slowed down as flagged by skylight and also on gitter chat @icarito @jywarren @cesswairimu should we have an issue for the specific routes with the biggest slowdowns and possibly understand the reasons behind it?

yes i am @Tlazypanda , thanks for the concern.its good to know you are okay too.

**Comment by jywarren** [comment]
I'm glad to hear both of you are feeling stronger/better now. It's getting even scarier out there; we'll probably lock down again soon (should probably already). Please be as safe as you can. 

I'm trying not to get stressed about all the things I had hoped to do this year and which have to be delayed. There are much more serious things in the world but sometimes it can feel like one's own plans and projects are being put off over and over and we're powerless to do anything! So, trying to treat this time as it is - time which i'm grateful to have to be safe and to focus on what we can do here and now. 

I also saw the slowdowns via @icarito and think some are managed... perhaps there are some optimizations we could try to pick back up again -- https://github.com/publiclab/plots2/issues/8242, or anything from https://github.com/publiclab/plots2/search?q=optimize&type=issues

Please be well, all! I appreciate you!!!!!!

**Comment by jywarren** [comment]
And, congrats to @RuthNjeri for this really big PR getting finished! https://github.com/publiclab/plots2/pull/8620 with thanks to @sagarpreet for the assistance.

**Comment by RuthNjeri** [comment]
Hi everyone!

Yes, the pandemic has really made me scared as well, anytime I feel a scratch in my throat I quickly drink a concoction of ginger, turmeric, lemon, and garlic that my mother usually has on standby. I never leave the house without a sanitizer and a mask...seems like we are all trying to survive until a treatment or vaccine is accessible...

Happy to hear you are all okay now @Tlazypanda and @tawahpeggy!

Thanks, @jywarren! A huge thank you to @sagarpreet-chadha who always provided timely feedback and was very helpful in unblocking me when I got stuck!

I want to see if I can write up some new issues and also look at the issues linked here to help out some more. 

Have an awesome week everyone! Stay safe.

**Comment by cesswairimu** [comment]
Glad to hear everyone is doing fine.
I am stay indoors..only leaving for supplies but the introvert in me is thriving so no complains :smile: 
Fantastic job @RuthNjeri and @sagarpreet-chadha  on the notes preview feature :tada: :tada:

**Comment by tawahpeggy** [comment]
> Glad to hear everyone is doing fine.
> I am stay indoors..only leaving for supplies but the introvert in me is thriving so no complains 
> Fantastic job @RuthNjeri and @sagarpreet-chadha on the notes preview feature  
> 
> @tawahpeggy ping me if you need help on next week's check-in. Thanks

sure thing @cesswairimu  congrates @RuthNjeri am so proud of you.thanks alot for this massive work. keep up

**Comment by cesswairimu** [comment]
Moved to https://github.com/publiclab/plots2/issues/8760 . Thanks everyone :heart:
