### ISSUE TITLE
Add a Gaussian Blur module

### ISSUE THREAD

**Issue by tech4GT** [publiclab/image-sequencer#177]
Hi, this is a first-timers-only issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!

The problem
Implementing a Gaussian blur module using https://www.npmjs.com/package/ndarray-gaussian-filter
We have already used this module in the edge detection module in this line  https://github.com/publiclab/image-sequencer/blob/5922b0de581f6ad3626c4f22713caeca870c336c/src/modules/EdgeDetect/Module.js#L28

Also have a look at this pr to submit a perfect module https://github.com/publiclab/image-sequencer/pull/161/files

Solution
Follow the patter of other modules and write a blur module see [contributing.md](https://github.com/publiclab/image-sequencer/blob/master/CONTRIBUTING.md) and do the actual image manipulation like in the above line

Steps to fix

 claim this issue with a comment
 set up a repository locally and make sure that all tests pass
 start a pull request (see contributing to Public Lab software) but mark it as "in progress"
 fix the issue following the steps above
 make sure all tests pass
 alert someone via either the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!
Please email the developers list (see https://publiclab.org/developers) if you have questions!

**Comment by jywarren** [comment]
[GitMate.io](https://gitmate.io) thinks the contributors most likely able to help are @ccpandhare, and @jywarren.

**Comment by tech4GT** [comment]
@jywarren will this be a good first timer issue?

**Comment by tech4GT** [comment]
@jywarren please add the first timers label, also i will detect and create some more fto issues as soon as possible

**Comment by jywarren** [comment]
Hi, I think this is a great `help-wanted` issue and will label accordingly. But I think it may be a bit much for a very first contribution -- often, fto issues lay out exactly what lines of code must change, so as to help first-timers go through the process and get to know the workflow and tools, before asking them to solve a problem. Make sense? But this is great and many folks should be able to solve this too!

**Comment by jywarren** [comment]
Perhaps you want to link to the good example module here: https://github.com/publiclab/image-sequencer/pull/161 too!

**Comment by tech4GT** [comment]
@jywarren sure it's just that this will be adding one line to the example module and that line was already used in edge detection so i thought it could be a fto issue, but no prob I'll link the pr😁

**Comment by tech4GT** [comment]
@jywarren also I'll detect and put up some fto issues as soon as possible 😁

**Comment by jywarren** [comment]
awesome. thanks!

**Comment by danielleshwed** [comment]
Hi, I've attempted this issue and submitted a pull request :) Please let me know if there are any issues..

**Comment by tech4GT** [comment]
@jywarren this issue can be closed now solved in #186
