### ISSUE TITLE
Removing scroll-to-top on mobile devices

### ISSUE THREAD

**Issue by waridrox** [publiclab/image-sequencer#1851]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 Currently the scroll-to-top button on the image-sequencer shows up in mobile-view whose functionality is to bring the user to top of the webpage.
On mobile devices, the scroll-to-top button gets in the way while interacting with the webpage thereby leading to bad user-experience.
We want this feature to be removed from the mobile-view as the mobile screens have limited screen area to begin with and nowadays swipe gesture can take care of that efficiently.

<img width="176" alt="Screenshot 2021-03-16 at 9 50 50 PM" src="https://user-images.githubusercontent.com/58583793/111343836-d2d58f80-86a1-11eb-9c65-97c73b47f06a.png">

.**Update** the file [demo.css](https://github.com/publiclab/image-sequencer/blob/main/examples/demo.css) in the `publiclab/image-sequencer/blob/main/examples/demo.css` repository (press the little pen Icon) and edit the line as shown below. 

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:
https://github.com/publiclab/image-sequencer/blob/417c1b18261a87acb93ff0d455687e846947add0/examples/demo.css#L173-L187

 ```diff
 #move-up { 
   position: fixed; 
- bottom: 50px; 
+ bottom: 30px;
- right: 40px; 
+ right: 20px;
   z-index: 550; 
   display: none; 
   background:transparent; 
   border:none; 
 } 
  
 #move-up i { 
- font-size:60px; 
+ font-size:50px;
   opacity:0.7; 
   color:#BABABA; 
 } 

+ @media (max-width: 768px), (max-height 700px) {
+ #move-up {
+           display: none !important; /* !important is used to override the jQuery style */
+ }
+}
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:
1. If you are not familiar with GitHub or the pull request model, [here is a guide you can follow](https://guides.github.com/activities/hello-world/) on how GitHub works.
2. If you are familiar with the terminal or would like to learn to use it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

3. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by waridrox** [comment]
@jywarren @cesswairimu Kindly add the `fto` label :)

**Comment by HarshKhandeparkar** [comment]
If another reviewer/maintainer approves this, they can add the first-timers-only label :)

**Comment by jcads** [comment]
Can I work on this one?

**Comment by HarshKhandeparkar** [comment]
Go ahead! :rocket:

**Comment by jywarren** [comment]
Thank you @waridrox for creating this and @jcads for taking it up!!! And @HarshKhandeparkar for supporting!!! 🎉
