### ISSUE TITLE
Add documentation about the debug script

### ISSUE THREAD

**Issue by tech4GT** [publiclab/image-sequencer#187]
Hi, this is a first-timers-only issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!😁

The problem

We need to add documentation for how to run the debug script 

image-sequencer/src/ExportBin.js

https://github.com/publiclab/image-sequencer/blob/9d3e511bca74d44fffeb75e3cd2154cb6c9aa935/package.json#L7

Solution
Add a few lines of description and an example about how to use the debug script to the README.md. It should look something like this

```
npm run debug invert
```

Steps to fix

 

- [x] claim
- [x]  this issue with a comment
- [x]  set up a repository locally and make sure that all tests pass
- [x]  start a pull request (see contributing to Public Lab software) but mark it as "in progress"
- [x]  fix the issue following the steps above
- [x]  make sure all tests pass
- [x]  alert someone via either the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!
- [x] Please email the developers list (see https://publiclab.org/developers) if you have questions!

**Comment by jywarren** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @jywarren.

A possibly related issue is #170: Output not generated if contents of output folder are deleted.

**Comment by Gayathrir1666** [comment]
I will take up this issue and solve it.This is the first time I am contributing here!

**Comment by tech4GT** [comment]
Sure go ahead, thanks for your help looking forward to your pr😁👍

**Comment by tech4GT** [comment]
closed via #192
