### ISSUE TITLE
Add a list of working modules and their parameters in the documentation

### ISSUE THREAD

**Issue by tech4GT** [publiclab/image-sequencer#188]
If someone wishes to browse our modules one would have to go through the info.json file of every module. We can simplify this by having a list of modules and the their info in the README itself.
@jywarren what say?

**Comment by jywarren** [comment]
[GitMate.io](https://gitmate.io) thinks the contributors most likely able to help are @jywarren, and @ccpandhare.

**Comment by jywarren** [comment]
can we reduce redundancy at all? What if we have a list in README of
modules, each of which links to their respective info.json files for more?

good thinking!

**Comment by tech4GT** [comment]
@jywarren sure, that can be done😁

**Comment by ccpandhare** [comment]
Yes, having all that into the readme wouldn't be a good idea, I feel. 
The readme needs a bit reworking itself, I do feel at times that it's pretty long!

**Comment by tech4GT** [comment]
@ccpandhare yes i share the view so what i was thinking was maybe we can make a note on publiclab.org and link it here for someone who wishes to browse through all the modules kind of like we handle the bookmarklet...what say?

**Comment by ccpandhare** [comment]
I'm not sure how that'll work out...
@jywarren isn't it?

**Comment by tech4GT** [comment]
@ccpandhare what if we shorten the readme and leave it bare bones and create a comprehensive documentation separately like many packages with large documentation do...will that be better?
We can have something like `read full reference` link in readme

**Comment by jywarren** [comment]
We can link into additional Markdown files in a /docs/ folder... what do
you think? Like on plots2!

**Comment by ccpandhare** [comment]
I do agree with Varun on this..!

**Comment by tech4GT** [comment]
@jywarren totally we can do that👍

**Comment by HarshKhandeparkar** [comment]
Docs were updated through https://github.com/publiclab/image-sequencer/issues/506. Closing this
