### ISSUE TITLE
Add a loading spinner fallback for modules for which progress cannot be calculated

### ISSUE THREAD

**Issue by tech4GT** [publiclab/image-sequencer#189]
The modules which do not use pixelManipulation currently have no loading bar and since we use external modules to implement them we cannot measure progress and make a progress bar for them hence we should add a spinner (https://www.npmjs.com/package/cli-spinner) to inform the user that the image is being processed

**Comment by tech4GT** [comment]
@jywarren would this be the right way to go?

**Comment by jywarren** [comment]
[GitMate.io](https://gitmate.io) thinks the contributors most likely able to help are @jywarren, and @ccpandhare.

**Comment by ccpandhare** [comment]
This looks good! Do you think you could reformat this into an FTO?

**Comment by tech4GT** [comment]
@ccpandhare maybe this would not be a very good fto issue since i was planning something for this
I was thinking we can pass progress object to the module where the module writer can override it with a progress bar if he/she likes, that way it'll be very generic...what do you think?

**Comment by ccpandhare** [comment]
That makes sense to me!
