### ISSUE TITLE
Change the warning log

### ISSUE THREAD

**Issue by tech4GT** [publiclab/image-sequencer#194]
Hi, this is a first-timers-only issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!

The problem

We need to fix the following log

https://github.com/publiclab/image-sequencer/blob/973ec6d6e47fff49381e7c4b32c9b87f3947862c/index.js#L60

Solution
Change the log to say "Please wait \n output directory generated will be empty until the execution is complete"

Steps to fix

 Claim
- [ ] this
- [ ] issue with a comment
- [ ] set up a repository locally and make sure that all tests pass
- [ ] start a pull request (see contributing to Public Lab software) but mark it as "in progress"
- [ ] fix the issue following the steps above
- [ ] make sure all tests pass
- [ ] alert someone via either the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!
- [ ] Please email the developers list (see https://publiclab.org/developers) if you have questions!

**Comment by jywarren** [comment]
[GitMate.io](https://gitmate.io) thinks the contributors most likely able to help are @jywarren, and @danielleshwed.

Possibly related issues are #187 (Add documentation about the debug script), and #170 (Output not generated if contents of output folder are deleted).

**Comment by tech4GT** [comment]
@jywarren since our execution is not exactly async, maybe this will be a more suitable log😁

**Comment by jywarren** [comment]
Yes!!!!

**Comment by Ronaq13** [comment]
I want to work on this.

**Comment by tech4GT** [comment]
@Ronaq13 hello there, welcome to the community😁
I'll assign the issue to you now
Thanks👍

**Comment by ccpandhare** [comment]
That'll be great @Ronaq13!

**Comment by tspakes** [comment]
Hello. I am new to the open-source community and Public Lab. It seems that this issue is still open despite a previous user expressing desire to work on this. Could I please be assigned this issue to help me get started?

**Comment by tspakes** [comment]
Looking at index.js, I see that this has already been completed. It would probably be a good idea to close this issue so that others don't attempt to complete it.

**Comment by tech4GT** [comment]
@tspakes sorry for the inconvenience. Welcome to publiclab community try a first timers issue to get started😁
