### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by kindanduseful** [publiclab/image-sequencer#196]
Hey, Public Lab community! Great-looking project (love the typefaces)!

How about:
1. ability to save the sequence in some shareable format (eg. url link)
2. ability to insert steps into an already built sequence 

Rock on!

**Comment by tech4GT** [comment]
@kindanduseful thanks a lot for the input, the sharing idea we will be working on this summer and i really like the adding a step to already built sequence, can you please open a separate issue for that I would start working on it as soon as possible.
What do you say @jywarren ?

**Comment by ccpandhare** [comment]
Actually... I think we have something like this in place...

**Comment by tech4GT** [comment]
separate issues for the improvements have been opened, closing this now

**Comment by jywarren** [comment]
Also linking this to https://github.com/publiclab/image-sequencer/issues/127 for the ability to share not only a sequence of steps, but the settings for each step, which is sometimes critical in reproducing a sequence!
