### ISSUE TITLE
Can add units to the dimension of the image

### ISSUE THREAD

**Issue by shreyshreyansh** [publiclab/image-sequencer#1969]
![Screenshot 2021-10-06 101106](https://user-images.githubusercontent.com/53744971/136141782-1b2afcfa-159d-44bc-ad0f-30ce56d1d9d3.jpg)

*image width: 611px* 
*image height: 429px*

**Comment by anantraghuvanshi** [comment]
Hey @shreyshreyansh, may I take up this issue?

**Comment by KarishmaVanwari** [comment]
Hey @shreyshreyansh can I take up this issue?

**Comment by shreyshreyansh** [comment]
Actually I don’t own this repo

**Comment by KarishmaVanwari** [comment]
Okay, then whom can I ask to get this issue assigned? @shreyshreyansh

**Comment by shreyshreyansh** [comment]
Tag @jywarren

**Comment by KarishmaVanwari** [comment]
Okay, thanks @shreyshreyansh 
Hey @jywarren , can I take up this issue?

**Comment by harshkhandeparkar** [comment]
> Okay, thanks @shreyshreyansh Hey @jywarren , can I take up this issue?

Sure! Also you may tag `publiclab/is-reviewers` from next time \:)

**Comment by KarishmaVanwari** [comment]
> > Okay, thanks @shreyshreyansh Hey @jywarren , can I take up this issue?
> 
> Sure! Also you may tag `publiclab/is-reviewers` from next time :)

Okay, thanks!

**Comment by KarishmaVanwari** [comment]
Hey @harshkhandeparkar, I have created a PR #2066 . Please have a look!
