### ISSUE TITLE
Errors on /index.html, /examples/ndvi/index.html

### ISSUE THREAD

**Issue by ccpandhare** [publiclab/image-sequencer#2]
**/index.html and /examples/ndvi/index.html give out errors on running (Safari, Chrome, Firefox on Mac)**

#### The following pops up every time a module is called
[Error] IndexSizeError (DOM Exception 1): The index is not in the allowed range.
	getImageData (image-sequencer.js:184439)
	draw (image-sequencer.js:184439)
	output (image-sequencer.js:184203)
	(anonymous function) (image-sequencer.js:184551)
	emit (image-sequencer.js:26578)
	(anonymous function) (image-sequencer.js:12768)
	run (image-sequencer.js:163900)
	drainQueue (image-sequencer.js:163870)
#### The following error comes up only when "Add Step is clicked"
[Error] TypeError: undefined is not an object (evaluating 'options.el.html')
	draw (image-sequencer.js:184409)
	run (image-sequencer.js:184221)
	(anonymous function) (index.html:78)
	dispatch (image-sequencer.js:60435)
	handle (image-sequencer.js:60247)

#### The following pops up every time "Add step is clicked"
[Error] TypeError: undefined is not an object (evaluating 'options.el.html')
	draw (image-sequencer.js:184409)
	run (image-sequencer.js:184221)
	(anonymous function) (index.html:76)
	dispatch (image-sequencer.js:60435)
	handle (image-sequencer.js:60247)

#### On clicking "Add Step"
Uncaught TypeError: Cannot read property 'html' of undefined
    at Object.draw (image-sequencer.js:184409)
    at Object.run (image-sequencer.js:184221)
    at HTMLButtonElement.<anonymous> (index.html:76)
    at HTMLButtonElement.dispatch (image-sequencer.js:60435)
    at HTMLButtonElement.elemData.handle (image-sequencer.js:60247)

#### On clicking "Add Step"
ReferenceError: event is not defined image-sequencer.js:184383:11
	onImage/reader.onload /dist/image-sequencer.js:184383:11

**Comment by ccpandhare** [comment]
The same errors also come on the github-hosted demos.

**Comment by jywarren** [comment]
Hi, can you try again in an incognito window to be sure you don't have older cached .js files loading? 

I just tested this out on MS Edge on a Windows machine. 

@nadya - Hi! would you mind trying the demos out on your Mac? 

1. https://jywarren.github.io/image-sequencer/
2. https://jywarren.github.io/image-sequencer/examples/ndvi/

@ccpandhare these are what you're trying, right?

**Comment by ccpandhare** [comment]
Yes this is what I've been trying..

**Comment by jywarren** [comment]
Ah! I had not updated the example code buttons -- so the core library is working, but the buttons are not. Yes, this needs to be fixed -- I can take a look at it soon, but I think the issue is that `sequencer.run()` is being run on the initial `image-select` module, which is not finding its element, since it makes a custom UI. This API is very new, so i'm open to ideas on how to solve this.

**Comment by ccpandhare** [comment]
Issues Fixed!
PR #6
