### ISSUE TITLE
add "drag to crop" UI feature to Crop module

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#205]
I was thinking that the ability to drag a region to be cropped using the Crop tool would be great, when using the default HTML UI. It might take a couple hundred lines of code, however, and I'm not sure we'd want that in the core library. Is this an example of something we should develop as a separate module entirely?

**Comment by jywarren** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @ccpandhare.

Possibly related issues are https://github.com/publiclab/image-sequencer/issues/5 (image cropping module), https://github.com/publiclab/image-sequencer/issues/158 (Add a Saturation Module), https://github.com/publiclab/image-sequencer/issues/157 (Add a Contrast module), https://github.com/publiclab/image-sequencer/issues/27 (add fisheyegl module), and https://github.com/publiclab/image-sequencer/issues/113 (Add a Brightness module).

**Comment by tech4GT** [comment]
@jywarren we can use a jQuery plugin for that, that would keep it separated from our core code
please have a look at this http://odyniec.net/projects/imgareaselect/

**Comment by jywarren** [comment]
This is fantastic. Excellent find!!!!!!

**Comment by tech4GT** [comment]
@jywarren this one is almost done, will be submitting pr by tomorrow 
Thanks😁

**Comment by jywarren** [comment]
Oh awesome.

**Comment by jywarren** [comment]
Complete in #245!!!
