### ISSUE TITLE
Module info in demo should source from info.json

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#209]
Several modules have `info.json` descriptions but these aren't being shown in the demo, at https://publiclab.github.io/image-sequencer/examples/#steps=ndvi-red,segmented-colormap (for example). 

See:

https://github.com/publiclab/image-sequencer/blob/d887f5eb61096d5b05f9caf6ca47149b4cd8fd0a/src/modules/NdviRed/info.json#L3

But when it's set in `options.description` it does work:

https://github.com/publiclab/image-sequencer/blob/d887f5eb61096d5b05f9caf6ca47149b4cd8fd0a/src/modules/Invert/Module.js#L8

We should do this automatically, rather than having to add this line in the module itself. 

Would that go into InsertStep?

https://github.com/publiclab/image-sequencer/blob/master/src/InsertStep.js

@ccpandhare @tech4GT 

This will help with module simplification in #122 -- we could also automate the `title` field!

**Comment by jywarren** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @ccpandhare.

Possibly related issues are https://github.com/publiclab/image-sequencer/issues/126 (Move configuration options in demo from "add step" to each step's info area), https://github.com/publiclab/image-sequencer/issues/142 (Add select dropdown for some module UIs in demo), https://github.com/publiclab/image-sequencer/issues/108 (Math Module), https://github.com/publiclab/image-sequencer/issues/112 (Scale module), and https://github.com/publiclab/image-sequencer/issues/82 (Demos rework + starter module rethink).

**Comment by jywarren** [comment]
Or should this go on these lines, in the demo?

https://github.com/publiclab/image-sequencer/blob/d887f5eb61096d5b05f9caf6ca47149b4cd8fd0a/examples/demo.js#L38-L39

**Comment by tech4GT** [comment]
@jywarren nice catch, I am a little busy right now but I'll get this sorted ASAP
Thanks😁

**Comment by tech4GT** [comment]
@jywarren got the problem!!!

**Comment by tech4GT** [comment]
@jywarren actually the thing is we export the module itself and it's info separately like 2 elements in an array hence we won't get the original description defined in info.json on the step object but we would get it on the modulesInfo["Module name"] object

**Comment by jywarren** [comment]
This now works!! https://github.com/publiclab/image-sequencer/pull/221
