### ISSUE TITLE
Make demo images click-to-download

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#210]
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://publiclab.github.io/community-toolbox/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

Images on the demo should be downloadable by clicking on them: 

https://publiclab.github.io/image-sequencer/examples/#steps=ndvi-red,segmented-colormap

That means wrapping this line in an, an `<a>`  with `target="_blank"` so they open in a new window.

https://github.com/publiclab/image-sequencer/blob/d887f5eb61096d5b05f9caf6ca47149b4cd8fd0a/examples/demo.js#L43

and then adding below this line to update the `href` of the `<a>` element: 

https://github.com/publiclab/image-sequencer/blob/d887f5eb61096d5b05f9caf6ca47149b4cd8fd0a/examples/demo.js#L118

**Comment by jywarren** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/publiclab/image-sequencer/issues/3 (CORS Image error on GitHub hosted demos), https://github.com/publiclab/image-sequencer/issues/4 (demo of image processing using leaflet map tiles), https://github.com/publiclab/image-sequencer/issues/148 (Create demo bookmarklet code for inverting images on a page), https://github.com/publiclab/image-sequencer/issues/5 (image cropping module), and https://github.com/publiclab/image-sequencer/issues/140 (Make demo display corresponding commandline syntax for current sequence).

**Comment by marzann** [comment]
Could I work on this, or it is first-timers-only? I had one small previous contribution.

**Comment by tech4GT** [comment]
@marzann welcome to the community😊
It's preferred that first timers solve this issue but you take it up if you want it'll help you get familiar with the project

**Comment by marzann** [comment]
@tech4GT: Sorry about the delay, I have been busy. Thank you so much for the welcome. I like the project, and would like to go ahead with issue #210. I have never contributed to the publiclab repos. Quick question, for testing, should I use grunt localhost, rather that npm?

**Comment by tech4GT** [comment]
Yeah that would be better😁✌️

**Comment by marzann** [comment]
Tysm. I am having trouble showing website on localhost via npm or grunt. What is the preferred way of doing that?

**Comment by tech4GT** [comment]
@marzan  actually we do not host the website on a server in grunt(nice pointing It out, I'll open an issue for this) so for now you should start a simple http-server in the project folder
For that you can use https://www.npmjs.com/package/http-server

**Comment by marzann** [comment]
@tech4GT, thank you! This worked like a charm, so now I can work on the issue, and test it.

**Comment by jywarren** [comment]
Solved, thank you @marzann !!!

If you're interested in tackling another one, we'd be happy to help you find something interesting!!

**Comment by marzann** [comment]
@jywarren, thank you. :) I will look over the open issues. Also, if you could recommend a new contributor issue, that would be great.

**Comment by tech4GT** [comment]
@marzann have a look at #140 , it's again an issue related to the demo so you should feel comfortable with it. Best of luck👍

**Comment by tech4GT** [comment]
You can see the cli syntax in the documentation,😄

**Comment by tech4GT** [comment]
You know what would be cool, a button that says view cli command and it alerts the user with the syntax when pressed. Excited!!

**Comment by marzann** [comment]
I will look this over, thank you for the suggestion. :)

**Comment by marzann** [comment]
@tech4GT, could you give me more details for #140? 
Would the button be for https://publiclab.github.io/image-sequencer/examples/#steps=ndvi-red,segmented-colormap? 
Would the button go next to Choose file, and next to Add Step?

**Comment by tech4GT** [comment]
Actually I was thinking maybe we can incrementally build this after each step and keep on adding into it

**Comment by tech4GT** [comment]
For example if I apply invert then I'll get the button next to inverted image and then I apply green channel so next to final image I'll get the button which gives the syntax for the whole sequence before it which is ivert then green channel

**Comment by tech4GT** [comment]
@marzann does that make sense?

**Comment by marzann** [comment]
@tech4GT, yes it does make sense. 
Could you give me more details on the implementation?

**Comment by tech4GT** [comment]
Yeah, I think we can modify the html that gets generated by sequencer and add the button there and then use js to set its js to alert the cli syntax on getting clicked, how does that sound?

**Comment by tech4GT** [comment]
@marzann sorry for this but jeff is actually refactoring the code in demo.js so I think we should get back to this once that’s done so that we don’t break anything in the process. I apologise if you had already started working on this!!

**Comment by marzann** [comment]
Thank you for the heads up. If after the refactoring this issue is still open, let pick it up from here.

**Comment by marzann** [comment]
That sounds good. Thank you both!
