### ISSUE TITLE
Make an icon for the project

### ISSUE THREAD

**Issue by tech4GT** [publiclab/image-sequencer#211]
@jywarren I was thinking maybe we can design an icon for image-sequencer which can appear in the title of the demo as well. What say?
PS I got the idea from the meetup we organized, maybe in the future we can put image-sequencer logo on the posters

**Comment by jywarren** [comment]
[GitMate.io](https://gitmate.io) thinks the contributors most likely able to help are @jywarren, and @ccpandhare.

Possibly related issues are https://github.com/publiclab/image-sequencer/issues/23 (Planning Issue for the Image Sequencer GSoC Project), https://github.com/publiclab/image-sequencer/issues/210 (Make demo images click-to-download), and https://github.com/publiclab/image-sequencer/issues/200 ("Meta" modules -- modules made of other sequences of modules).

**Comment by jywarren** [comment]
I like this idea! I'll try to come up with some ideas... ✏️ 📄

**Comment by jywarren** [comment]
What about something like this? 

![image](https://user-images.githubusercontent.com/24359/38834247-dd6dc60a-4195-11e8-816f-ccd4e2f02797.png)

[full-res file](https://user-images.githubusercontent.com/24359/38834272-f633068c-4195-11e8-85f8-8022f10b32f0.jpg)

**Comment by tech4GT** [comment]
This looks cool🎉

**Comment by tech4GT** [comment]
@jywarren since we will be adding offline support in the summer we should have a material icon as well, how's this one
![ic_launcher](https://user-images.githubusercontent.com/25617855/38838610-915de3e4-41f4-11e8-9d63-0e50a28813bd.png)

**Comment by jywarren** [comment]
ooh, very modern! sketching here:
https://docs.google.com/presentation/d/1TCZoTfuhamRVrUak8aDgqJAwSgyhRtZg2Pgacl2_4zc/edit#slide=id.g1a6154e201_0_153

that also has a nice mockup of an early UI that might be interesting to
you.

OH i love this new one! Can we make it pink though? Or purple? Such
friendlier colors :-)

**Comment by tech4GT** [comment]
![ic_launcher](https://user-images.githubusercontent.com/25617855/38838785-7994b8f4-41f5-11e8-968d-b3ab0c2abba9.png)
How's this?

**Comment by tech4GT** [comment]
That is very nice ui, I love it!!!

**Comment by tech4GT** [comment]
@jywarren I know the perfect ui framework for this
have a look at https://semantic-ui.com/
This is a very mordern css framework which will fall totally in line with the modern style ui we want to go for

**Comment by jywarren** [comment]
This purple icon is amazing. Let's add it to the repo!

**Comment by tech4GT** [comment]
@jywarren I should add it as the icon for the demo right?

**Comment by jywarren** [comment]
sure! I believe we may also be able to add them for use as "home icons"?
but i'm not sure if this is up to date:
https://designmodo.com/create-icons-ios-android/

**Comment by tech4GT** [comment]
@jywarren actually i was thinking as we move towards the pwa in the summer we can use it there, Since pwa icons get added on home screens of android phones..
for now i will make it the demo icon..
as for ios since this is a material design icon we would have to design another one for ios.

**Comment by jywarren** [comment]
Awesome. Thanks, Varun!!

**Comment by tech4GT** [comment]
closing in favor of #217
