### ISSUE TITLE
Crop Module not working correctly

### ISSUE THREAD

**Issue by tech4GT** [publiclab/image-sequencer#213]
<img width="1233" alt="screen shot 2018-04-18 at 6 02 48 pm" src="https://user-images.githubusercontent.com/25617855/38932104-df373590-4332-11e8-97da-de59dc17ce9e.png">

**Comment by jywarren** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @jywarren.

Possibly related issues are https://github.com/publiclab/image-sequencer/issues/5 (image cropping module), https://github.com/publiclab/image-sequencer/issues/205 (add "drag to crop" UI feature to Crop module), https://github.com/publiclab/image-sequencer/issues/146 (Monochrome "fallback" on Dynamic module not working), https://github.com/publiclab/image-sequencer/issues/108 (Math Module), and https://github.com/publiclab/image-sequencer/issues/112 (Scale module).

**Comment by tech4GT** [comment]
@ccpandhare It would be great if you can help, Thanks

**Comment by HarshKhandeparkar** [comment]
Crop module works fine now I think. Can this be closed? @jywarren @gauravano

**Comment by jywarren** [comment]
Reopening as I've reproduced it here! https://sequencer.publiclab.org/examples/#steps=crop{x:127|y:127|w:266|h:266}

![image](https://user-images.githubusercontent.com/24359/52751777-a3ce2a80-2fbe-11e9-9c01-60803c1d557f.png)

**Comment by HarshKhandeparkar** [comment]
I've noticed that this only happens when x and y values are provided

**Comment by jywarren** [comment]
I wonder if we should simply rewrite the crop module as it seems a relatively simple module. Could we use the canvas resize module?

**Comment by jywarren** [comment]
Related to these lines?

https://github.com/publiclab/image-sequencer/blob/6fa8b1b8808d202355f51f9e3471d2f0423d3288/src/modules/Crop/Crop.js#L17-L52

**Comment by jywarren** [comment]
We can write a test around these parameters which fail... https://sequencer.publiclab.org/examples/#steps=crop%7Bx:127%7Cy:127%7Cw:266%7Ch:266%7D

**Comment by jywarren** [comment]
It also looks to me like we're missing a channel in each, either no blue or no red.

**Comment by VibhorCodecianGupta** [comment]
Looking into this and other relevant crop module issues.

**Comment by VibhorCodecianGupta** [comment]
Reproduced it again, @Divy123 cc @jywarren 

here: 
![Screen Shot 2019-04-19 at 3 15 07 PM](https://user-images.githubusercontent.com/29275810/56418923-240e5600-62b6-11e9-8499-9440184d62f4.png)

**Comment by VibhorCodecianGupta** [comment]
fixed in #1019
