### ISSUE TITLE
Refine/simplify "add module" interface in demo

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#215]
I think it'd be better for UI consistency to have the "configure step" interface always show in the same place, so not at the moment of adding a new module, but only after you've added it. You can always delete the module if you want a different one!

This would simplify the UI a bit, like this:

![screenshot 2018-04-19 at 2 12 36 pm](https://user-images.githubusercontent.com/24359/39010588-14a89750-43dd-11e8-8bc7-bea2b4453751.png)

What do you think, @tech4GT ? Related to https://github.com/publiclab/image-sequencer/issues/197

**Comment by tech4GT** [comment]
@jywarren that sound good to me, infact I have been thinking about this as well so that ui remains consistent and user can scroll down as more steps are added

**Comment by tech4GT** [comment]
@jywarren also I was thinking we can have a preview button, pressing which a modal appears which contains just the images through all the steps like a timeline, what say?

**Comment by jywarren** [comment]
I like the "timeline view" idea -- cool!

**Comment by jywarren** [comment]
Hmm, interesting -- looking ahead, does this simplification involve "simply" (lol) removing these lines of code?

https://github.com/publiclab/image-sequencer/blob/4d75fb9640f9f5ddf9e05ad451a2672a2bd85cb5/examples/demo.js#L171-L200

**Comment by tech4GT** [comment]
@jywarren I and mayank have decided to plan for the summer tomorrow, it would be great if you can join us. We can discuss all the major points..

**Comment by jywarren** [comment]
Oh, tomorrow may be difficult -- what time? I'm usually more free during the week. But I can try! 

Can you use  http://www.inyourowntime.info/ ?

**Comment by tech4GT** [comment]
@jywarren what will be the best suited time for you, I can adjust since it's my holiday?

**Comment by tech4GT** [comment]
@jywarren that is totally doable😃👍

**Comment by jywarren** [comment]
Awesome will u be meeting in chatroom?

**Comment by tech4GT** [comment]
@jywarren what do you suggest? I was thinking hangouts?

**Comment by tech4GT** [comment]
@jywarren mayank and I are ready, whenever you say😄

**Comment by jywarren** [comment]
I'm in a noisy place actually, I'm sorry - maybe I can join for a bit on
chat and you all can continue in video...

**Comment by tech4GT** [comment]
@jywarren actually mayank also cannot video call today so we all are on chat

**Comment by tech4GT** [comment]
@jywarren what is your hangouts email??
