### ISSUE TITLE
(upcoming) Add "post to PublicLab.org" button to embeddable demo

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#223]
We should embed Image Sequencer's browser version on PublicLab.org, and have a `Save` button that lets people post their image as a note. Example code to test this out would be:

```
$('body').append('<form action="https://publiclab.org/post?legacy=true" method="post"><input type="text" name= "i" value="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAQABADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAf/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/8QAFQEBAQAAAAAAAAAAAAAAAAAABgj/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwCdABykX//Z" /><input type="submit" /></form>')
```

Then press the "submit" button -- although we'd do this in JavaScript instead of course. 

It might also be tested out using a small image:

https://publiclab.org/post?legacy=true&i=data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAQABADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAf/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/8QAFQEBAQAAAAAAAAAAAAAAAAAABgj/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwCdABykX//Z`

This may or may not work pending publiclab/plots2#2675

**Comment by jywarren** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/publiclab/image-sequencer/issues/142 (Add select dropdown for some module UIs in demo), and https://github.com/publiclab/image-sequencer/issues/215 (Refine/simplify "add module" interface in demo).

**Comment by tech4GT** [comment]
@jywarren this sound awesome 👍👍

**Comment by jywarren** [comment]
This should now work because https://github.com/publiclab/plots2/pull/2675/ was resolved!

**Comment by jywarren** [comment]
Finally solved this, moving to: https://github.com/publiclab/image-sequencer/issues/1332
