### ISSUE TITLE
Color separation module

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#225]
This could probably be a meta-module or a dynamic module -- the ability to "extract" just one color from an image, to be able to do things like this eventually:

https://www.instagram.com/p/Bhcuh8QntX5/

**Comment by Divy123** [comment]
@HarshKhandeparkar can I work on this?

**Comment by HarshKhandeparkar** [comment]
I guess this is done? @jywarren?

**Comment by jywarren** [comment]
Yes, i think so? https://github.com/publiclab/image-sequencer/blob/055b17c75f79f21aee81490c6a7175df34c8647a/src/modules/ReplaceColor/ReplaceColor.js

Thanks!!!
