### ISSUE TITLE
(multiple) Optimize code based on CodeClimate recommendations

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#228]
CodeClimate shows a lot of possible improvements that could be made to this codebase. We don't have extremely high test coverage, but we can tackle these optimizations one by one, and many are suitable for [first-time contributors](https://publiclab.github.io/community-toolbox/#r=all)!

[CodeClimate issues](https://codeclimate.com/github/publiclab/image-sequencer/issues?category=complexity&engine_name%5B%5D=structure&engine_name%5B%5D=duplication)

If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is your first time, try to solve one of these yourself! Please ask for help by posting a comment below.

Each issue CodeClimate points out is listed below. Some may be able to "convert" these to issues with the button shown. Otherwise just note which you'd like to address in the comments:

![image](https://user-images.githubusercontent.com/24359/39411172-cd748346-4bd2-11e8-8204-9b6ef8516324.png)

Once you've chosen one, try opening a pull request with your improvements and we'll help you take the next step!

**Comment by jywarren** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @tech4GT.

**Comment by AmanGarg97** [comment]
Hi , Is this issue still open and can I start working on this? @jywarren

**Comment by jywarren** [comment]
oh, that would be really great! Thank you!

**Comment by Rishabh570** [comment]
@jywarren I guess this should get closed now...?

**Comment by jywarren** [comment]
Ah, actually this could be done more -- if you click on this link you can see a lot of suggestions!

https://codeclimate.com/github/publiclab/image-sequencer/issues?category=complexity&engine_name%5B%5D=structure&engine_name%5B%5D=duplication

**Comment by Sand038** [comment]
Can I start working on https://codeclimate.com/github/publiclab/image-sequencer/src/Run.js/source#issue-558e648db4003071ea478cd2af6b7799?

**Comment by HarshKhandeparkar** [comment]
@sand038 welcome! I think touching the run.js file directly may not be good. Even I have never touched it before. Are you familiar with the codebase? If not then can you try refactoring something else like a module? That will give you a good idea of how everything works. If you have started work already then its ok. Go ahead. If you haven't still then you can try something else or if you are ok with it then you can try refactoring. Please ask if you need any help. We will be ready to answer any questions. Good luck! Thanks!
