### ISSUE TITLE
Begin building the default UI in core or in image-sequencer-ui package

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#246]
Take a look at https://github.com/publiclab/image-sequencer/pull/245 to see the new organization of the default HTML ui -- 

We should consider spinning that out into part of ImageSequencer core, or a new NPM package called `image-sequencer-ui`!

Connected to https://github.com/publiclab/image-sequencer/issues/232 (ui fixes) and #197

**Comment by jywarren** [comment]
started with generic image selector in https://github.com/publiclab/image-sequencer/pull/253

**Comment by jywarren** [comment]
I think we are good here, although we should open a new issue to move all UI files to /src/ui or /ui/src -- @publiclab/is-reviewers what do you think?

**Comment by HarshKhandeparkar** [comment]
Hi! I'm working on separating ui files in #825

**Comment by HarshKhandeparkar** [comment]
Will be addressed in a separate issue.

**Comment by HarshKhandeparkar** [comment]
https://github.com/publiclab/image-sequencer/issues/1238
