### ISSUE TITLE
Add step.toString() and sequencer.toString() methods

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#250]
Breaking this out of https://github.com/publiclab/image-sequencer/issues/200 --

Based loosely on: 

https://github.com/publiclab/image-sequencer/blob/cbbfbff4bc14f494c423867cc4572b001c5c3c4d/examples/lib/defaultHtmlSequencerUi.js#L30-L37

and discussion from https://github.com/publiclab/image-sequencer/issues/200

Much discussion of how to implement per-step options in https://github.com/publiclab/image-sequencer/issues/127 

however this can start with just a standardized way to get a list of all current steps in a string, so:

`sequencer.toString()`

Right now, each image in the sequencer has its own steps, but are these all identical? I feel they ought to be -- according to our model, it should be a consistent sequence that you then pass images through, not a collection of images which you assign steps to. 

So really we may need to rework this to be `sequencer.steps` rather than `sequencer._image_name_.steps` before we can continue this project. 

But once this is done, we can do a follow-up where each step can return its settings, like for example: `sequencer.step[0].toString() => "blur[amount:40]"` or similar

**Comment by jywarren** [comment]
Here's where we're adding new steps to the URL hash string, which is similar although this code is not that flexible. With the new `sequencer.toString()` we could just replace the URL hash with the complete string the sequencer produces:

https://github.com/publiclab/image-sequencer/blob/1de72d7325cfa8ea1ab38ba8f5f5b1c75e31195f/examples/lib/defaultHtmlSequencerUi.js#L42-L45

**Comment by tech4GT** [comment]
@jywarren I completely get this!! Awesome!!

**Comment by tech4GT** [comment]
@jywarren should I move onto this or complete all the functions of #242 ??

**Comment by jywarren** [comment]
Yes, let's shift to this for the time being. Thanks! Thisll let us do the
string configuration in the URL and such. Very useful!
