### ISSUE TITLE
Suppress progress bars in tests

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#254]
This may be a dual issue - i see a lot of piling up of progress bars when running `npm test` -- but not sure if this is because multiple bars are running at once in tests, or what. But in general i think we should suppress progress bars in tests, does this make sense?

![image](https://user-images.githubusercontent.com/24359/39825269-669c30c4-537f-11e8-877b-3fa4b59fcd40.png)

**Comment by tech4GT** [comment]
@jywarren oh I see yeah, I'll have the progress bars suppress on running tests. This makes complete sense!!

**Comment by tech4GT** [comment]
@jywarren infact we can disable progress bars in Dev environment and have them show up only in production
