### ISSUE TITLE
Break out longer functions into sub source files and require in

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#26]
If it's possible, can you check if you can break out any of your longer functions into sub files? If you need shared scope, maybe you'll have to pass them in via the function parameters, so they'll be less inter-referential. 

But this will make your code into smaller, more independent and easier (one thing per function) parts. So I think it's worth it in some cases!

**Comment by ccpandhare** [comment]
Yes, I do agree with this. I will see to it.

**Comment by ccpandhare** [comment]
Although #28 does not do exactly this, I believe it addresses the issue partially... What do you think @jywarren ?

**Comment by ccpandhare** [comment]
Now #28 Addresses this issue wholly. Is this okay?

**Comment by jywarren** [comment]
yep, looks great!

**Comment by ccpandhare** [comment]
Closing this issue then
