### ISSUE TITLE
Blur module producing a black 'border' at the top and bottom

### ISSUE THREAD

**Issue by ccpandhare** [publiclab/image-sequencer#260]
## Example Image
![Example Image](https://user-images.githubusercontent.com/20787612/40291921-aa173118-5ce5-11e8-811a-1eae9485c681.png)
## Example Image Blurred
![Example Image Blurred](https://user-images.githubusercontent.com/20787612/40291929-b792debe-5ce5-11e8-8e34-093bacbd0546.png)

Is this the intended behaviour of the algorithm or is this a bug?

**Comment by jywarren** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @jywarren.

Possibly related issues are https://github.com/publiclab/image-sequencer/issues/177 (Add a Gaussian Blur module), https://github.com/publiclab/image-sequencer/issues/108 (Math Module), https://github.com/publiclab/image-sequencer/issues/112 (Scale module), https://github.com/publiclab/image-sequencer/issues/5 (image cropping module), and https://github.com/publiclab/image-sequencer/issues/69 (Create Histogram Module).

**Comment by HarshKhandeparkar** [comment]
This actually uses another module ndarray-gaussian-blur in this. This is not an original module. This is probably a problem with that npm package. Maybe a version bump will fix this?

**Comment by jywarren** [comment]
It's worth a try!

**Comment by HarshKhandeparkar** [comment]
I'll handle this in gpu.js PR.
