### ISSUE TITLE
Add Tests for getStep function

### ISSUE THREAD

**Issue by tech4GT** [publiclab/image-sequencer#262]
Add the following tests for the API function getStep which gets the previous steps

- [x] Test for the the blend module

- [x] once we have meta modules, we could pass in a module which has a callback build into its draw method, and confirm that the callback gets called with a correct value for some `getStep()` output.
- [x] Remove these lines https://github.com/publiclab/image-sequencer/blob/09c4f250a28a41531c71e0678145cbd7d60d5562/src/modules/Invert/Module.js#L15-L17

**Comment by jywarren** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @jywarren.

Possibly related issues are https://github.com/publiclab/image-sequencer/issues/51 (More Testing), https://github.com/publiclab/image-sequencer/issues/230 (Add test coverage monitoring via CodeClimate), https://github.com/publiclab/image-sequencer/issues/27 (add fisheyegl module), https://github.com/publiclab/image-sequencer/issues/157 (Add a Contrast module), and https://github.com/publiclab/image-sequencer/issues/113 (Add a Brightness module).
