### ISSUE TITLE
getStep may return wrong step when used in the non-final step?

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#266]
I'm using images from here: https://publiclab.org/notes/warren/12-24-2010/ndvi-test-lima-peru

I started here: https://publiclab.github.io/image-sequencer/examples/

Then added: `importImage`, `blend`, and `ndvi` -- i left default settings for all three.

What i see is that once I add `ndvi` the `blend` step seems to only fetch the previous step, not the original image. See this gif:

![ndvi](https://user-images.githubusercontent.com/24359/40515069-62e161a6-5f79-11e8-80ff-121cf4a8f970.gif)

We should be able to catch this with better testing, but perhaps it's something we can untangle ourselves first?

**Comment by jywarren** [comment]
[GitMate.io](https://gitmate.io) thinks a possibly related issue is https://github.com/publiclab/image-sequencer/issues/150 (Using GitMate).

**Comment by tech4GT** [comment]
@jywarren looking into this now!!

**Comment by jywarren** [comment]
Awesome! The test images i linked to are really helpful. We are looking to get the black and white version as output!

**Comment by tech4GT** [comment]
@jywarren After some research here are the results
We are calling the module from within the addStep function and there is a variable(function) getStep defined  in the addStep scope which we wish to pass on to the module.
There are 3 ways we can do this
- Input parameter: pass as a parameter, we do not want to do this
- this: Using `this` of the function scope we can bind getStep and the data it operates on to the `this` of module, here we would have to use this.getStep(), hence not desirable
- global variable: this is kind of what we were doing with the this binding but with unnecessary complexity, so we make the getStep global then we can call it directly but the data also becomes shared among all steps and hence the relative `offset` won't do

My solution: I have passed the input given to the module's draw as a parameter to the getStep(global function) through which we can determine the relative offset in the steps array
