### ISSUE TITLE
Prior steps need not re-run when a new module is added or deleted

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#269]
In the demo, I see the entire sequence being re-triggered when a module is added or deleted. 

We should only have to run the final new step, if a new one is added, and if one is deleted, only the steps after it. Let's look at the logic and if we need to make `run()` accept a parameter like `sequencer.run(startIndex)` we can do that.

**Comment by jywarren** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/publiclab/image-sequencer/issues/27 (add fisheyegl module), https://github.com/publiclab/image-sequencer/issues/138 (Add a Dithering module), https://github.com/publiclab/image-sequencer/issues/157 (Add a Contrast module), https://github.com/publiclab/image-sequencer/issues/158 (Add a Saturation Module), and https://github.com/publiclab/image-sequencer/issues/113 (Add a Brightness module).

**Comment by tech4GT** [comment]
@jywarren Actually I also noticed this while working on the getStepApi, but this would call for some major changes in demo architecture or even in the architecture of the sequencer itself, I would suggest we keep this long term, what say?
