### ISSUE TITLE
Module not found error in demo

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#278]
https://publiclab.github.io/image-sequencer/examples/#steps=import-image,blend,ndvi,colormap is returning `Module  not found.` -- not sure why. Looking...

**Comment by jywarren** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @tech4GT.

Possibly related issues are https://github.com/publiclab/image-sequencer/issues/145 ("reader is not defined" error on demo), https://github.com/publiclab/image-sequencer/issues/3 (CORS Image error on GitHub hosted demos), https://github.com/publiclab/image-sequencer/issues/142 (Add select dropdown for some module UIs in demo), https://github.com/publiclab/image-sequencer/issues/209 (Module info in demo should source from info.json), and https://github.com/publiclab/image-sequencer/issues/215 (Refine/simplify "add module" interface in demo).

**Comment by tech4GT** [comment]
@jywarren the url is not correct, The current format is channel(channel:green),invert() like this

**Comment by jywarren** [comment]
So then https://publiclab.github.io/image-sequencer/examples/#steps=import-image(url:0),blend(blend:function(r1%2C%20g1%2C%20b1%2C%20a1%2C%20r2%2C%20g2%2C%20b2%2C%20a2)%20%7B%20return%20%5B%20r1%2C%20g2%2C%20b2%2C%20a2%20%5D%20%7D),ndvi(filter:red),colormap(colormap:fastie)

OK - so because we're splitting on both comma and `(`, that's broken previous saved sequences, that's not good. I think we have to come up with a solution here...

**Comment by tech4GT** [comment]
@jywarren Oh I got it!! Fixing this now!! Sorry my bad!!

**Comment by jywarren** [comment]
Since we're now URL-encoding the functions, we can go back to splitting on `,` alone, and then:

* if there are no configurations specified OR
* the config is the default

then we can leave out the configs?

**Comment by jywarren** [comment]
No problem! I guess we should've added more thorough tests... when we write the `importStepsFromString()` method we can more fully test that and catch things like this 😄

**Comment by jywarren** [comment]
The quickest fix right now should just be to switch to `,` separation, i think? We can do the other default-sensitive stuff as a follow-up.

**Comment by jywarren** [comment]
To preserve this usage: https://publiclab.org/notes/warren/05-30-2018/use-image-sequencer-for-ndvi-plant-analysis-with-2-images

**Comment by tech4GT** [comment]
@jywarren I am getting an error loading the monarch image but this is working fine!!

**Comment by jywarren** [comment]
really? did you not see the error I saw?

**Comment by jywarren** [comment]
I think we need to change this line:

https://github.com/publiclab/image-sequencer/blob/871453b857b80a89e51819b0cb68324ef18a403e/src/ImageSequencer.js#L226

**Comment by jywarren** [comment]
I can do it if it's too late at night?

**Comment by tech4GT** [comment]
<img width="408" alt="screen shot 2018-06-03 at 11 33 24 pm" src="https://user-images.githubusercontent.com/25617855/40889581-ac5202f4-6786-11e8-95fe-a3b2155c412f.png">
@jywarren I think this is working fine but the image is not being loaded

**Comment by jywarren** [comment]
Are you sure you're in the right branch? On the link that I shared at top, it doesn't even load the steps.

**Comment by tech4GT** [comment]
@jywarren got the problem!!

**Comment by tech4GT** [comment]
https://publiclab.github.io/image-sequencer/examples/#steps=import-image(url:https%3A%2F%2Fpubliclab.github.io%2Fimage-sequencer%2Fexamples%2Fimages%2Fmonarch.png),blend(blend:function(r1%2C%20g1%2C%20b1%2C%20a1%2C%20r2%2C%20g2%2C%20b2%2C%20a2)%20%7B%20return%20%5B%20r1%2C%20g2%2C%20b2%2C%20a2%20%5D%20%7D),ndvi(filter:red),colormap(colormap:fastie)

Hit this url and for now please enter the path https://publiclab.github.io/image-sequencer/examples/images/monarch.png in import image

**Comment by jywarren** [comment]
I wrote a test for this -- see https://github.com/publiclab/image-sequencer/pull/279

**Comment by tech4GT** [comment]
and click save, it should work

**Comment by jywarren** [comment]
I don't believe the monarch.png issue is blocking, although we should separately solve it -- it doesn't stop https://publiclab.github.io/image-sequencer/examples/#steps=import-image,blend,ndvi,colormap from running though!

**Comment by tech4GT** [comment]
@jywarren the `()` are essential!!

**Comment by tech4GT** [comment]
please use them after every step they are essential!!

**Comment by jywarren** [comment]
Fixed in #279 ! Thanks Varun!

**Comment by jywarren** [comment]
Part of the solution was to substitute `|` pipe characters for the commas when inside of the step settings, so:

`#steps=invert,crop(x:1|y:0|h:10|w:10)`
