### ISSUE TITLE
Skip writing defaults into toString

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#281]
So if the step settings match the defaults, let's not write them into the `toString` output. That way we can keep it pretty short. 

For example in https://publiclab.github.io/image-sequencer/examples/#steps=import-image,blend,ndvi,colormap

Now we have #278 fixed, when you click that, it correctly loads all the steps, BUT the URL quickly gets really long due to the defaults getting saved into it. It's great that the URL writing is working, but we can skip any settings which are already the defaults, and then the URL can stay a bit shorter. 

This isn't the most important thing but it's really helpful and convenient!

**Comment by jywarren** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @tech4GT.

Possibly related issues are https://github.com/publiclab/image-sequencer/issues/169 (ability to write metadata into exif tags), and https://github.com/publiclab/image-sequencer/issues/250 (Add step.toString() and sequencer.toString() methods).

**Comment by Mridul97** [comment]
Hey, I have opened a PR #334  to fix this issue. Please take a look. @jywarren
