### ISSUE TITLE
Colorbar generation module

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#285]
That generates a color bar to overlay on an image (useful in showing scales with the `colormap` module) -- this could start by mapping pixel `x` values to a gradient from 0 to 100% brightness, then run the `colormap` module on it, then overlay this image at some location on another image. 

This might take a few more new modules -- or something like the `blend` module but that overlays an image at a `x, y, w, h`?

The gradient could be done with the dynamic module, which does have an `x` and `y` pixel location to work with, although we'd need to be sure it had access to the image width?

To save time, the color bar could be generated at only 1 pixel tall.

**Comment by jywarren** [comment]
Hi, @tech4GT -- this is one module I guess i'd like to see if you'd be able to implement... it's really important for knowing the actual value by examining an image. What do you think, after your big changes?

**Comment by jywarren** [comment]
For example think about knowing the NDVI value of one spot on this image: https://publiclab.org/notes/Claytonb/08-13-2016/plant-health-ndvi-white-balance

**Comment by tech4GT** [comment]
@jywarren Sure!! Once we are done with meta modules I'll start this!!

**Comment by jywarren** [comment]
fantastic!!!

**Comment by tech4GT** [comment]
@jywarren So I was looking into this, can you please explain the gradient part a little more, or maybe you can give me some more links where i can read more about this...
Right now What I gather is that this can be a meta-module like "dynamic(gradient) colormap overlay"
So I'll start by working on an overlay module first then we can discuss what will be the input to the dynamic module and that should be enough right?

**Comment by jywarren** [comment]
+1 meta module - this really seems like an ideal thing for it!

I think we could basically 

1. make a new image that's a gradient, 
2. then make a new module that can insert that gradient into another image, 
3. then maybe we need to display UI that says `color bar maps from 0-100` or whatever the scale is?
4. would we ideally want a text module to insert text? That's harder now without canvas, but...see text overlay at https://github.com/publiclab/image-sequencer/issues/165

**Comment by tech4GT** [comment]
@jywarren Thanks for the info but I still don't get the gradient part, can you please elaborate on that. Also we can have a different module for the mapping so that we can ask for that input at run time, what say?

**Comment by jywarren** [comment]
so the first step could be do just make a full-image gradient from black to white. Then we can run that through a colorize filter. 

A gradient could be like (very rough pseudocode):

```js
PixelManipulation(function(x, y) {
  return (x / image.width) * 255; // map the x dimension to a 0-255 value
}
```

**Comment by tech4GT** [comment]
@jywarren do we do this on both the dimensions and take average?

**Comment by tech4GT** [comment]
Or we do that for every row of pixels individually?

**Comment by jywarren** [comment]
We could do it for every line, but we could also just make an image that is
1 pixel tall. I think if we want a horizontal gradient, we'd only want to
do this on the x-axis. But maybe people want gradients for other reasons,
so we could allow setting which direction the gradient should run as an
option? But it doesn't have to be implemented to accomplish this task... it
could be marked for later expansion.

**Comment by tech4GT** [comment]
@jywarren Now researching this!! I think I have a pretty good idea of how this could work. One concern though should we make it only one pixel tall? Would it be visible?

**Comment by tech4GT** [comment]
@jywarren I think I have figured this out! Once meta modules are merged in I can get this done!!

**Comment by jywarren** [comment]
if we make an image one pixel tall, we can display it at any height, and
maybe in the UI for this module we set a height minimum?

**Comment by tech4GT** [comment]
@jywarren I'll take the height as an input then, what say?

**Comment by jywarren** [comment]
sure!

**Comment by tech4GT** [comment]
Perfect!!
