### ISSUE TITLE
get settings updates in demo to only run() from current index

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#286]
Using the new version of Run!

**Comment by jywarren** [comment]
Actually I realized the new Run is a major version update because we've broken the previous version of Run. Can you also bump a major version?

**Comment by tech4GT** [comment]
@jywarren I think I did this in it too!! I did update the demo to run from current index on save and addstep, run from 0 when page is visited!!

**Comment by tech4GT** [comment]
bumping major version though!!

**Comment by tech4GT** [comment]
@jywarren Also can we putout a tweet about the sequencer 2.0 this is so exciting!!!!!

**Comment by jywarren** [comment]
:-)))

**Comment by tech4GT** [comment]
Awesome!! Closing this via #287

**Comment by tech4GT** [comment]
@jywarren what issues are you facing specifically??

**Comment by jywarren** [comment]
I added a set of 3 invert operations, and when i delete the middle one, the
last one doesn't re-run. I think we should be able to write a test for this
sort of thing... but for now, manually testing it showed some
inconsistencies like this.

**Comment by tech4GT** [comment]
@jywarren hmm this wierd, I just tried it and It worked

**Comment by tech4GT** [comment]
@jywarren are we serving the right files??

**Comment by jywarren** [comment]
Try opening this locally and then deleting the `invert` step:
http://localhost:8000/examples/#steps=import-image(url:%2Fexamples%2Fimages%2Fmonarch.png),saturation(saturation:0.5),channel(channel:green),invert()

**Comment by jywarren** [comment]
ER wait! Deleting the "channel" step i mean! The Invert step is then
unaffected for me?

**Comment by tech4GT** [comment]
@jywarren looking into this now!!

**Comment by tech4GT** [comment]
Ah small error!! found it!!

**Comment by tech4GT** [comment]
@jywarren should we now publish to npm??

**Comment by jywarren** [comment]
I already did!!!
