### ISSUE TITLE
Incorporate test images into tests

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#29]
Closed #1 as it is a bit out of date now, but I still would like tests which incorporate a "before" and "after" image, as attempted in this code:

https://github.com/jywarren/image-sequencer/blob/3d43eceff9a51ed2f85c3ce42277017c7890e435/test/image-sequencer.js#L31-L59

At simplest, we could perform an operation, then reverse it -- like, for example, inverting and inverting again -- and then confirm that the image is the same after the test, perhaps using:

* https://www.npmjs.com/package/blink-diff
* smaller and faster: https://www.npmjs.com/package/@schornio/pixelmatch

Or even as an initial step, do an operation on an image and `expect()` that it's not the same -- just confirm that /something/ happened. Then move on to more complex tests of actual test images. 

If this is in another PR, please link it here, thanks!

**Comment by ccpandhare** [comment]
I was onto it. Got stuck at the PixelManipulation thing yet again.

**Comment by ccpandhare** [comment]
Now that we're done with that, I think this can be worked upon!
