### ISSUE TITLE
drag/drop error on 1st step of demo

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#290]
I tried uploading an image to the demo in gh-pages and got an error... a no module error, in https://publiclab.github.io/image-sequencer/examples/#steps=import-image,blend,ndvi,colormap

Can you check on this Varun? Thanks!!!

**Comment by tech4GT** [comment]
Working on this now!!

**Comment by tech4GT** [comment]
@jywarren go it!! Small bug in demo.js
