### ISSUE TITLE
Ability to distort an image with 4 corner points (perspective distortion)

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#299]
https://github.com/publiclab/Leaflet.DistortableImage allows distortion of images using 4 points, in the browser.

(https://github.com/jywarren/webgl-distort produces a distorted image and could be integrated as a webgl-only module -- see https://github.com/publiclab/image-sequencer/issues/64)

We could implement this kind of "drag four corners" interface as an HTML UI, backed with a distortion library. 

This issue would have 3 parts: 

1. implement a module with 8 parameters -- relative pixel location change as `x, y` for each corner
2. an HTML UI to accomplish this, similar to Leaflet.DistortableImage, shown below
3. a module building on the above which allows distorting one image over another to "align" them -- so just using another image as a background (passed in similar to the `blend` module)

![screen shot 2018-06-27 at 4 15 19 pm](https://user-images.githubusercontent.com/24359/41997278-8614aa86-7a25-11e8-8636-f53cd0633197.png)

See this demo: https://publiclab.github.io/Leaflet.DistortableImage/examples/select

This would be helpful in getting 2 images which aren't an exact overlay match to line up, so that they can be used to generate NDVI: https://publiclab.org/notes/warren/12-24-2010/ndvi-test-lima-peru

**Update**

This probably should use this module: 

https://github.com/jywarren/webgl-distort

Or some variant of it. And to work in node, it'll depend on https://github.com/publiclab/image-sequencer/issues/216, webgl for node. 

The UI could start with just a set of pixel coordinate parameters. We could later try to refactor in a more complete HTML UI as in Leaflet.DistortableImage as a follow-up!

**Comment by pahenry** [comment]
It would be helpful for alignment purposes if the opacity of the top layer could be reduced while adjusting the alignment.

**Comment by jywarren** [comment]
For sure! Leaflet DistortableImage has that menu option, and we can try to
preserve it in this adaptation.

**Comment by Divy123** [comment]
Can I please work on this issue?

**Comment by jywarren** [comment]
That'd be great!

**Comment by Divy123** [comment]
@jywarren can you please provide some more details into it .
I went through [https://github.com/publiclab/Leaflet.DistortableImage ](url) and was not able to judge the working .
Can you please provide some insights?

**Comment by jywarren** [comment]
Added some insights in an update above; this'll depend on #216 -- I think we should try to make a minimal module first based on webgl-distort, which wouldn't need to try to integrate the whole Leaflet codebase. Make sense?

**Comment by jywarren** [comment]
We'll need to refactor webgl-distort to not interact with the HTML DOM, so restructuring it to work with an Image object instead of an image element, in this line:

https://github.com/jywarren/webgl-distort/blob/3e0f5a2c0bf5a7f7d00dec6b8e1f960f40cf4e06/dist/webgl-distort.js#L41

We should be able to support the original usage too, but make a new core module that can be used within image-sequencer. What do you think?

**Comment by aashna27** [comment]
@jywarren Can you provide use case or any more information , as I was thinking of doing this. Any information about your expectations

**Comment by jywarren** [comment]
Ah, this will be the interface for
https://github.com/publiclab/image-sequencer/issues/64 ! Does that help?

**Comment by aashna27** [comment]
Yeah it helps, I was thinking of adding this to my proposal but for now I had left it as I didn't have information, so if you could please go through my proposal and let me know your review it would be really great,
https://publiclab.org/notes/aashnaaashna/04-03-2019/soc-proposal-image-sequencer?_=1554388031

**Comment by jywarren** [comment]
I'm going to close this now, as it's working, including in Node! https://github.com/publiclab/image-sequencer/issues/216 #1021
