### ISSUE TITLE
CORS Image error on GitHub hosted demos

### ISSUE THREAD

**Issue by ccpandhare** [publiclab/image-sequencer#3]
## There are Cross Origin Resource Sharing Canvas errors on Safari, IE, Opera, Mobile based-browsers.
This is because they not implemented CORS enabled images yet. [MDN Source](https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image)
The entire code of Image Sequencer depends on CORS Enabled images.

CORS enabled images are supported **only** on Desktop based Chrome and Firefox
Other desktop based browsers and support by **any** mobile-based browser is questionable as of now.

### Can we do something about this? Because not doing so would render "Image Sequencer" useless for a huge chunk of Desktop users and all Moblie users?

**Comment by ccpandhare** [comment]
For example, we could render the image stages on a canvas instead of the native HTML img element. CORS images are allowed in canvases.

But there is a problem with this. This would render the canvas sort of though to handle with as then we can't export the canvas, as the mentioned MDN article says.

Anything we could do about this?

**Comment by jywarren** [comment]
Hi, @ccpandhare - although there are significant use cases that do rely on CORS, an image dragged into the interface by a user shouldn't need CORS, since it's not making a cross-origin request. Can you describe exactly the steps that you did to get this error?

**Comment by jywarren** [comment]
Looks like you figured it out? Cors restrictions only apply to cross domain
image requests, not to images directly uploaded or hosted on the same
domain. This does create some usage limitations it nothing too bad - and if
a server side app uses image-sequencer and wants to use images from another
service, it can proxy remote images to circumvent, OR it can disallow image
export (not ideal but this is a pretty obscure case).
