### ISSUE TITLE
Disable/dim the Save button until step inputs have been changed

### ISSUE THREAD

**Issue by tech4GT** [publiclab/image-sequencer#302]
Hi, this is a first-timers-only issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!

The Issue:
We need to disable the Save button which is used to save changes to a step until changes have been made to the step
Here's where the Save button is made: 

https://github.com/publiclab/image-sequencer/blob/630eb773de712873d6323eb86275fadb2b802fc1/examples/lib/defaultHtmlStepUi.js#L94-L96

We can use the same kinds of selectors to modify it, add more text, change the styling -- using Bootstrap styles: 

https://getbootstrap.com/docs/3.3/css/

**Comment by ebinxavier** [comment]
I would like to contribute something to this project. I am a first-timer, I have cloned the project locally and I need to modify this file "image-sequencer/examples/lib/defaultHtmlStepUi.js" right? Please help me I am new to github and open source.

**Comment by tech4GT** [comment]
Hello there!! Welcome to the community!!😁

**Comment by ebinxavier** [comment]
okay, I have forked and cloned the source. Let me familiarize the project. I will try to do my best. :)

**Comment by ronmaple** [comment]
Hello,

This is my first time trying to contribute. So far I'm just trying to understand the issue. I've installed and run locally, and tried it out on the 'brightness' field as my first attempt.

So basically, the displayed button on the screen shot is one of the buttons we're trying to disable when the field is empty?

What I did was I just selected the form with jquery (var trythis), and evaluated for an empty field that executes a disable attribute on the selected button.

So essentially this is the idea, but either create a series of code to manually select and change each one, or a more dynamic 'one function changes all' type of thing?

<img width="993" alt="screen shot 2018-08-02 at 10 25 00 am" src="https://user-images.githubusercontent.com/31875601/43600135-a855af20-963e-11e8-9228-c621e36f2094.png">

**Comment by tech4GT** [comment]
Hello @ronmaple Welcome to the community first of all!!😁
What we want here is that the `Save` button for each step shall remain disabled until the value of the field is changed. Right now as the user starts typing into the field of selects a new option from the dropdown the `Save` button should become enabled. Down the line we will add some form of verification for the inputs that are typed in the fields as well.

**Comment by tech4GT** [comment]
I think you should write a function with the following signature and set it on the `change()` of every field.
```js
function toggleSave(field){
// Find the associated save with this field and enable or disable it based on the value
}
```

**Comment by ronmaple** [comment]
Looking into using `paramName` to select for the fields... and have a `switch` statement on a `change` event listener for `inputDesc.type`

**Comment by Mridul97** [comment]
Hello I am new to github and would like to contribute something to this project, I have forked this project and cloned my own fork. Can I work on this issue ? I am a first timer, so I may require some help.

**Comment by tech4GT** [comment]
Hi @Mridul97 welcome to publiclab 😄
You can go ahead for sure!

**Comment by Mridul97** [comment]
I tried to start a local environment to test the UI. I did these steps : 
1. Made a package.json file using npm init.
2. Installed image-sequencer using npm install image-sequencer --save
3. Tried to run a local environment using npm start
But I could not run a local environment, I got errors. Please help me how to run a local environment to test UI. This is my first time working on an open source project.

**Comment by Mridul97** [comment]
I also tried to do the following steps :- 

1. Go to the project folder.
2. Installed all the dependencies in package.json using npm install
3. Tried to run a local environment using npm start

But it failed again, I got many errors. Please help me how to run a local environment to test UI. I have tried all the steps given in the README.md but not able to run the local environment.
Please Help!!

**Comment by tech4GT** [comment]
Hey there! Sorry for the trouble. So you need to 
- fork and clone the project
- run npm I
- run npm start

**Comment by Mridul97** [comment]
Hey I tried those steps but I am getting errors. Please have a look.
![untitled](https://user-images.githubusercontent.com/21158457/44308472-3ad17580-a3d4-11e8-986f-49838fc8795f.jpg)

**Comment by tech4GT** [comment]
Oh actually you don't have grunt installed!!
Try this `npm install -g grunt grunt-cli`

**Comment by Mridul97** [comment]
Hey, I made a change to disable/enable 'save' button. Please take a look. Pull request #322.

**Comment by jywarren** [comment]
Solved! Thanks!
