### ISSUE TITLE
Design Overhaul(More modern UI)

### ISSUE THREAD

**Issue by tech4GT** [publiclab/image-sequencer#304]
We are planning a design overhaul according to this mockup 
<img width="552" alt="screen shot 2018-07-17 at 5 04 15 pm" src="https://user-images.githubusercontent.com/25617855/42815025-a9976ac0-89e3-11e8-8300-2f8b69b540cc.png">

**Comment by tech4GT** [comment]
@jywarren I am facing trouble making this design since bootstrap does not have quite the same ring as this, Should I include some elements from semantic-ui?
https://semantic-ui.com/

**Comment by tech4GT** [comment]
@jywarren semantic-ui is another css framework like bootstrap, the thing is that bootstrap has kind of cartoonish and rounded elements, whereas we are looking for a more modern design

**Comment by jywarren** [comment]
I guess I'm thinking that for the time being, many other PL projects are in
Bootstrap, so we may want to stick with that for the time being. It's also
a very comprehensive library with many many UI features, so it's flexible.
But if we find that it's not suitable for a very specific reason in the
future, we can discuss!

**Comment by tech4GT** [comment]
@jywarren what if we do both? I mean we can include some elements from semantic UI as well in the current page

**Comment by jywarren** [comment]
I guess i just think that for the basic UI we should keep things as simple
as possible. I'm sorry Varun it sounds like you really like semantic-ui --
I just want to be making decisions that keep this easy to use and very
standard parts, you know? Is semantic-ui very well maintained like
Bootstrap?

Do you think it'd be a lot of work to maintain two different UI systems? It
would help keep us from making decisions that are for only one UI.

**Comment by tech4GT** [comment]
@jywarren Yeah that makes sense!! Actually semantic-ui is much more elaborate than bootstrap as well so you may be right, we should stick with bootstrap. Ok I'll start trying this out!! Thanks

**Comment by Mridul97** [comment]
I would like to work on this issue. Can I work on this issue?

**Comment by jywarren** [comment]
As one possible way forward, I think we could explore Blockly -- https://developers.google.com/blockly/

This is a bit different but pretty interesting too!

**Comment by Mridul97** [comment]
Cool! I will definitely explore Blockly. Thanks!

**Comment by HarshKhandeparkar** [comment]
@Mridul97 @jywarren @tech4GT materialize is a good option here I guess. Its modern and is even based on material design and simple too. Very similar to bootstrap.

**Comment by HarshKhandeparkar** [comment]
This is an example website created using materialize

https://pixinvent.com/materialize-material-design-admin-template/html/fixed-menu/

**Comment by jywarren** [comment]
Moving to #78 & #673!
