### ISSUE TITLE
default string format doesn't work in Markdown

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#306]
unfortunately, it reads the `()` as part of the URL syntax, it seems!

https://publiclab.github.io/image-sequencer/examples/#steps=ndvi(filter:blue),colormap(colormap:fastie)

See https://publiclab.org/notes/MaggPi/07-18-2018/ndvi-micrsocopy#c20160

Maybe we should switch for `{}`?

**Comment by tech4GT** [comment]
@jywarren can you please elaborate on this? I'm sorry I did not quite get you.

**Comment by jywarren** [comment]
ah - i tried pasting a URL with the parentheses in it into a PL wiki page,
but it didn't save properly as a full link because Markdown thinks it
should try to parse the ()... you know?

**Comment by jywarren** [comment]
sure!!!

**Comment by jywarren** [comment]
could we make square brackets the standard, but allow it to still accept
parenthesis for backwards-compatibility?

**Comment by tech4GT** [comment]
@jywarren yes we can but I'm afraid then it won't be reasonable as an fto. I'll do it myself then😄

**Comment by jywarren** [comment]
ok! Thanks!

**Comment by jywarren** [comment]
Solved in #313 !
