### ISSUE TITLE
Issue with non-JPEG images also affecting alpha channel

### ISSUE THREAD

**Issue by ccpandhare** [publiclab/image-sequencer#31]
## The Issue
Now `PixelManipulation` works perfectly fine for JPEG images. Issues come up when we use PNG/GIF images. I am currently using a petty fix so that this works for all images. This is what I do in `PixelManipulation.js` :
```
options.format = "jpeg";
```
I am hardcoding the format to "jpeg" whenever a module using `PixelManipulation` is used.
So this is working for all images. But as a result, we can't work with images having an alpha channel.

This is what is happening: (Have spent about 2 days on this)
* `savePixels()` generates a readable stream -- `r`
* `base64-stream` generates a writable stream -- `w`
* `r.pipe(w)` pipes `r` to `w`
* the event listener 'finished' is attached to the `pipe` which is responsible for converting the image data to a DataURI.

In JPEG images this process works perfectly fine. But for PNG/GIF, the 'finished' event never gets triggered (I've tested this.)

Surprisingly, the same code worked for a 16x16 pixel PNG image.

## Possible Explanation(s)
I am aware that `save-pixels` uses different parsers for PNG, JPEG, GIF. This may be causing some issue. But also, The code works fine when the writable stream is as follows
```
var w = require('fs').createWriteStream('output.png')
```
instead of:
```
var w = base64.encode();
```

So this may be an issue with the `base64-stream`.

## Overview
* Works fine for JPEG
* Issue saving PNG or GIF images
* Temporary fix applied : convert all images to JPEG
* Implication : We can't work with alpha channel images

## Another Fix (not a good idea, didn't do this)
Create a temporary binary PNG/GIF file using `fs`, convert it into a DataURI using `urify` and then destroy the temporary binary. Didn't do this because this won't work for Browsers.

**Comment by jywarren** [comment]
Let's post a bounty for this one and move forward without alpha for now.
Thanks!

**Comment by ccpandhare** [comment]
Okay I will do that!

**Comment by ccpandhare** [comment]
I have posted a bounty on [BountySource](https://www.bountysource.com/issues/46732565-issue-with-non-jpeg-images-also-affecting-alpha-channel) over here. Focussing on other stuff now and will get back to this soon.
