### ISSUE TITLE
Non-expanding, fully opaque meta modules

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#315]
The new meta modules is very powerful! You can select one like `NDVI-Colormap`, and it expands to:

https://publiclab.github.io/image-sequencer/examples/#steps=ndvi(filter:red),colormap(colormap:default)

But, right now, if you want to use a meta module like `NDVI-Colormap`, you can't just use it in a string like:

https://publiclab.github.io/image-sequencer/examples/#steps=ndvi-colormap

`Module NDVI-Colormap not found.`

A modification of meta-modules would be great, where:

1. they are, to all external appearances, just normal modules that don't expand
2. they contain other modules, but 'secretly' -- i.e. they run a mini-sequencer inside themselves, so they simply accept an incoming image, and produce an output image, and act in every way like a normal module
3. they would remain shown as a single step, permanently

Then you could modify the internals of a meta module -- say, to optimize it -- and nobody would ever know!

@tech4GT this may be too much to accomplish before the end of SoC, but I'm interested to hear your thoughts!

**Comment by tech4GT** [comment]
@jywarren this is a very interesting idea and yes I don't think we can do this before the end of soc but I will surely work on this afterwards.
One good thing is that our architecture is perfect and all we need to do in order to achieve this is change the expand steps function.

**Comment by tech4GT** [comment]
This will be very interesting to implement

**Comment by jywarren** [comment]
agreed, very interesting! And that's great to hear. Think of all the
excellent architectural choices we made earlier in the year that will allow
us to do this! 👏👏👏

**Comment by Mridul97** [comment]
I would like to give this issue a try. Can I work on this issue?

**Comment by jywarren** [comment]
this one is a deep one! But @tech4gt has said he thinks it will be possible
with relatively minimal changes. Perhaps he can guide a bit! But YES this
would be amazing!

**Comment by Mridul97** [comment]
No not at all!!

**Comment by tech4GT** [comment]
Thanks!

**Comment by jywarren** [comment]
Hi @tech4GT would you mind sharing any work you've done so far in a PR, or maybe outlining a couple steps towards this goal? I'd love to see progress made on it and if we could do it in parts, even better!

**Comment by jywarren** [comment]
For example, would you consider simply building a module which starts a unique separate instance of ImageSequencer inside itself, passes in a string, and then replies with the output?

**Comment by tech4GT** [comment]
@jywarren Sure, I'll open a PR today!

**Comment by jywarren** [comment]
To make creating these new meta-modules easier, we may be able to create a generator for these, which is to say, a way to automate the creation of opaque meta modules given:

1. a JSON object or string of steps
2. a function which maps the outer module options to the options objects of the internal steps (or falling back to the defaults if mapping is not provided)
3. a set of overriding defaults for internal steps (which could be done via the mapping function too)

This could take the form:

```js
module.exports = require('generateMetaModule')(function mapOptions(options) {

  var defaults = require('./../../util/getDefaults.js')(require('./info.json')); // standard defaults fetch

  options.x = options.x || defaults.x;
  options.y = options.y || defaults.y;
  options.colormap = options.colormap || defaults.colormap;
  options.h = options.h || defaults.h;

  // map above defaults into internal steps options:
  return [
    { 'name': 'gradient', 'options': {} },
    { 'name': 'colormap', 'options': { colormap: options.colormap } },
    { 'name': 'crop', 'options': { 'y': 0, 'h': options.h } },
    { 'name': 'overlay', 'options': { 'x': options.x, 'y': options.y, 'offset': -4 } }
  ];
});
```

**Comment by tech4GT** [comment]
@jywarren Let us first finalize the structure of the meta module itself, after that I'll integrate it into createMetaModule function! We can use a flag like options.opaque.
This way we can use all the earlier meta-module work we did, since all that will be changing is the internal structure of the meta-module but the api layer can stay as it is!! This will need minimal code change!! Super exciting!! :tada:

**Comment by tech4GT** [comment]
So I was able to figure out 2 ways in which circular dependencies can occur
1. Dynamically loading a module, we can check for it while loading it
2. From the source code, this though rare can occur due to a programming error so let's make a test for this.

I will add to this list if I am able to think of more. Thought?
cc @publiclab/is-reviewers
