### ISSUE TITLE
Delete buttons and indices slightly off in demo

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#318]
I noticed after adding the new colorbar module, the delete buttons delete the wrong module, it deletes the `n+1` module instead of `n` -- probably to do with the extra "parent" meta module? 

Another smaller thing is that once the metamodule is expanded, the meta-module's UI controls don't seem to work any more, is that right? Maybe we should hide the meta module UI until we have fully internalized meta modules as in #315?

@tech4GT your thoughts?

**Comment by tech4GT** [comment]
@jywarren hmm I see!! Let me see what can be done

**Comment by jywarren** [comment]
Very nice though!

![overlay](https://user-images.githubusercontent.com/24359/43729870-9cacc730-9977-11e8-89f9-471fd4cb11cf.png)

**Comment by tech4GT** [comment]
This issue has been already solved, now closing this up.
