### ISSUE TITLE
create a replaceImage() method that uses all the current steps to process and replace an image in the DOM

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#32]
This will be a good way to integrate this project's abilities into other sites. Like, replace an image on a webpage.

**Comment by ccpandhare** [comment]
I already have this in the functionality.
If draw(image) method is run on on the first step (loadImages) then the
image is replaced with the input. I just have to make this more user
friendly. :)

**Comment by jywarren** [comment]
Yes, I know you already have the functionality... I guess I'm thinking of a
single line command that also accepts an element selector from the page, so
Yu can use it just like jQuerys element.hide().

And a simple example! Great.

**Comment by ccpandhare** [comment]
This was solved in #35

**Comment by ccpandhare** [comment]
Recently Completed this Issue and pushed changes to #35 
I have even added a small working browser demo :-)
