### ISSUE TITLE
Small fixes to NDVI

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#320]
Note to self - we should show NDVI value from -1 to 1, rather than 0-255 ... very easy fix!

**Comment by Mridul97** [comment]
I would like to work on this issue. Can I work on this issue?

**Comment by Mridul97** [comment]
Hey, could you please tell me that changes has to be made in this changePixel function ?
![ss](https://user-images.githubusercontent.com/21158457/45227908-4501d800-b2df-11e8-9583-9c306e3c8215.jpg)

**Comment by Mridul97** [comment]
Do we have to do something like this ? I mean this will change the value of ndvi from 0-255 to -1 to 1 but this doesn't make any change in the working of the project ?
![ss_1](https://user-images.githubusercontent.com/21158457/45247611-62a66000-b326-11e8-816e-04eb1b83fe80.jpg)

**Comment by jywarren** [comment]
Try using it in a browser and screenshotting how the value is displayed!

**Comment by Mridul97** [comment]
Where exactly is the value displayed? I used NDVI on a image but I did not see any value displayed in the interface?

**Comment by jywarren** [comment]
ah, when you hover over the image, i believe it should be shown in the web
interface to the left. Is it not?

**Comment by Mridul97** [comment]
I have created a PR #333. Please take a look.

**Comment by jywarren** [comment]
Solved!!!
