### ISSUE TITLE
detect edges stalling or broken? 

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#323]
https://publiclab.github.io/image-sequencer/examples/#steps=edge-detect{blur:2|highThresholdRatio:0.2|lowThresholdRatio:0.15}

Even on a reasonably powerful machine this seems to hang with the example image. @tech4GT any ideas? It shouldn't be this power-hungry, right?

**Comment by tech4GT** [comment]
My laptop broke down, currently trying to setup my dev-environment on an old windows laptop while my mac is repaired, hopefully will be able to look into this today.

**Comment by tech4GT** [comment]
Hmm @jywarren i think I have found the problem, there is a little issue with the hysteresis step, so I am going to fix that, plus I think should we move this into a metamodule, the workflow will look like this "grayscale,blur,sobel,double-threshold,connected-component-labelling,hysteresis" or should we keep this as one module only?

**Comment by tech4GT** [comment]
I think that would depend on if we want to use this in other meta-modules, since the current implementation does not support meta-module inside of a meta-module.

**Comment by jywarren** [comment]
aha, well, interesting. Will the truly isolated meta modules support nested
meta modules? Then if so maybe we refactor this as a meta module AFTER that
work?

**Comment by tech4GT** [comment]
Yeah totally! We can keep this as a long term issue. I'll make the issue right now.

**Comment by jywarren** [comment]
super!
