### ISSUE TITLE
Add a footer to the main page

### ISSUE THREAD

**Issue by tech4GT** [publiclab/image-sequencer#335]
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

Hi, this is a first-timers-only issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!

## The Problem:
We need to add a footer to the demo and provide some generic information in it, exact content of the footer is yet to be decided.

## How to Solve?
We need to add a footer to the main index.html file at the following location
https://github.com/publiclab/image-sequencer/blob/88364decf6a6111a0be31fd98010576d5c6f918e/examples/index.html#L88
It should look something like this
```js
<footer class="page-footer font-small">
 </footer>
```
Instance Count 1

**Comment by mkiara** [comment]
Hi. May I try?

**Comment by tech4GT** [comment]
Hi @mkiara while we would love your help, this issue has been reserved for Google Code-in. It would be awesome if you can pick an issue which is not labelled`gci`
Thanks!!

**Comment by mkiara** [comment]
Alright. Thank you sir.

**Comment by SidharthBansal** [comment]
This task is published on GCI dashboard. Thanks all.

**Comment by SidharthBansal** [comment]
Go ahead

**Comment by generationXcode** [comment]
Thanks

**Comment by generationXcode** [comment]
what can I write in the footer?

**Comment by generationXcode** [comment]
![the_work_i_did](https://user-images.githubusercontent.com/43435971/47430747-d659da80-d7b7-11e8-8483-14b5510d3dd5.png)

**Comment by oorjitchowdhary** [comment]
@publiclab/image-sequencer-guides Is this already solved?

**Comment by jywarren** [comment]
I think we could make some more footer additions, yes! What about two sections below like this:

![image](https://user-images.githubusercontent.com/24359/52802236-8a27f400-304d-11e9-8e1c-c7f8d83cf369.png)


The Questions could link to https://publiclab.org/image-sequencer. Want to try implementing this? Thanks!!!

**Comment by Harshithpabbati** [comment]
ok fine i will do this.

**Comment by jywarren** [comment]
thank you!!!

**Comment by Harshithpabbati** [comment]
should i just add the need help and improve this as you show the image??

**Comment by HarshKhandeparkar** [comment]
@Harshithpabbati you can use your imagination. Add whatever you want. That image was just an example.

**Comment by Harshithpabbati** [comment]
thank you @HarshKhandeparkar
