### ISSUE TITLE
Add a list of available modules to the documentation

### ISSUE THREAD

**Issue by tech4GT** [publiclab/image-sequencer#337]
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

Hi, this is a first-timers-only issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!

## The Problem:
We need to list all the Image processing modules available in sequencer in the readme file.

## How to Solve?
You can find the list of modules here 
https://github.com/publiclab/image-sequencer/blob/master/src/Modules.js

These modules with their short descriptions need to be included under a modules section in the readme file.

Instance Count 1

**Comment by SidharthBansal** [comment]
This task is published on GCI dashboard. Thanks all.

**Comment by JonathanXu1** [comment]
Hey there, is anyone working on this?

**Comment by HarshKhandeparkar** [comment]
Seems like this is a duplicate and has been fixed.
