### ISSUE TITLE
Difference in Infragram & ImageSequencer ndvi-red results

### ISSUE THREAD

**Issue by ccpandhare** [publiclab/image-sequencer#34]
## Original

![original](https://user-images.githubusercontent.com/24359/27974077-565d176e-632a-11e7-8e02-52465bc43d50.jpg)

#### Full Image
![Image Sequencer](https://preview.ibb.co/b25c3Q/Image_Sequencer.jpg)

#### Full Image
![Infragram](https://preview.ibb.co/euEn3Q/Infragram.jpg)

Is the algorithm we are using for `ndvi-red` correct?
```
    function changePixel(r, g, b, a) {
      var ndvi = 255 * (b - r) / (1.00 * b + r);
      return [ndvi, ndvi, ndvi, a];
    }
```

**Comment by jywarren** [comment]
Looks like negative values are getting output as positive in
ImageSequencer, perhaps? See the black tree trunks? 🌲

Those are zero or negative values. Maybe negative values aren't getting
zeroed out?

**Comment by ccpandhare** [comment]
Changed the code to this:
```
    function changePixel(r, g, b, a) {
      var ndvi = 255 * (b - r) / (1.00 * b + r);
      ndvi = (ndvi>0)?ndvi:0;
      return [ndvi, ndvi, ndvi, a];
    }
```

Output:
![Output](https://preview.ibb.co/hEoQq5/Image_Sequencer2.jpg)

I will check the `infragram-js` repository for details.

**Comment by ccpandhare** [comment]
I think Infragram uses the same algorithm.
```
ndvi = (nir, vis) ->
        n = nir.width * nir.height;
        d = new Float64Array(n);
        for i in [0...n]
                d[i] = (nir.data[i] - vis.data[i]) / (nir.data[i] + vis.data[i]);
return new JsImage(d, nir.width, nir.height, 1);
```
```
if mode == "ndvi"
       [r,g,b] = get_channels(img)
       ndvi_img = ndvi(r,b)
       # this isn't correct for NDVI; we want values from -1 to 1:
       # [[min],[max]] = ndvi_img.extrema()
       min = -1
       max = 1
       normalize = (x) -> (x - min) / (max - min)
       result = jsColorify(ndvi_img, (x) -> colormap(normalize(x)))
       update_colorbar(min, max)
```

Isn't it?

**Comment by jywarren** [comment]
Ah, i wonder -- do you need to be doing: 

```js
var ndvi = (255 / 2) * (1 + b - r) / (1.00 * b + r);
```

So that values from -1 to 1 are mapped from 0-255?

**Comment by ccpandhare** [comment]
I think NDVI should just be
```js
var ndvi = (b - r) / (b + r)
```
[Wikipedia](https://en.wikipedia.org/wiki/Normalized_Difference_Vegetation_Index#Rationale)

**Comment by jywarren** [comment]
The issue is that there's a difference between what the NDVI value /is/ and what we can display in an image. Infragram.org decides that since there are negative values in NDVI, we should map actual NDVI values of -1 to 1, which are:

```js
var ndvi = (b - r) / (b + r)
```

to the full range we can show in an image, which is 0 to 255, so, broken into two steps:

```js
var ndvi = (b - r) / (b + r)
var pixel_value = 255 * (ndvi + 1) / 2;
```

**Comment by ccpandhare** [comment]
I am afraid that doesn't do the task either... Will look into this.
This is the output when I used the above code:
![Image](https://preview.ibb.co/iJkOHv/Unknown.jpg)

**Comment by ccpandhare** [comment]
Somehow, We aren't reaching the extremes. I mean, The parts which are darker in the Infragram version are lighter here and the lighter ones are darker here.

**Comment by jywarren** [comment]
That's odd -- I ran this a few times manually with NDVI outputs:

```js
ndvi = 1
1
255 * (ndvi + 1) / 2
255
ndvi = -1
-1
255 * (ndvi + 1) / 2
0
ndvi = 0.33
0.33
255 * (ndvi + 1) / 2
169.57500000000002
ndvi = -0.33
-0.33
255 * (ndvi + 1) / 2
85.425
```

This seems about right, no? Can you try outputting some of the pixel color values to be sure the NDVI is falling between -1 and 1? I don't really see how it could do otherwise.

**Comment by ccpandhare** [comment]
Yes, the `ndvi` value is between -1 and 1.
Here's a [PasteBin Link](https://pastebin.com/dS2WqJLP) to the ndvi of each of the pixels of this image, for reference.

But interestingly, most ndvi values are close to zero.

**Comment by jywarren** [comment]
Can you output the R and B values? I wonder if they're not quite right... wrong scale or something? Maybe they're 0-100 for some reason?

**Comment by ccpandhare** [comment]
Sure,
This [PasteBin Link](https://pastebin.com/bZ02d21W) has r, b and ndvi values.

**Comment by jywarren** [comment]
Hmm, now that I think about it, isn't the last image you posted correct? That is, for areas of 0 NDVI, it should appear 50% grey. Infragram is rendering those black, which would be -1. 

Do you want to post a question to the site on the topic and ask Chris Fastie and Ned Horning to confirm this?

https://publiclab.org/tag/ndvi has a lot of good info on this, and maybe test images others have used. 

You could also ask a question there!

**Comment by ccpandhare** [comment]
Sure will do that!
Thanks for the link!

**Comment by ccpandhare** [comment]
[This](https://publiclab.org/questions/ccpandhare/07-08-2017/how-to-verify-if-my-programmatically-generated-ndvi-version-of-an-image-is-correct) is the link to the question I have asked on the website.

**Comment by ccpandhare** [comment]
I have some good news on this front, finally!
### A Relief, Finally!
Chris Fastie suggested I try an image he gave. I think I got the right output from ImageSeqeucer.
It even matched that of Infragram!
But I do have Some interesting news here.

### Original
![Original](http://preview.ibb.co/fT1Xea/vegetation_01.jpg)

### Infragram Output
![Infragram](http://preview.ibb.co/cVsikF/infragram.png)

### Image Sequencer Old Algorithm Output
This is the output of the algorithm you wrote earlier:
```js
      var ndvi = 255 * (b - r) / (1.00 * b + r);
      return [ndvi, ndvi, ndvi, a];
```
![Old ImageSequencer](https://preview.ibb.co/dLEw5F/vegetation_01_ndvired.jpg)

### Image Sequencer New Algorithm Output

This is the output using the newer algorithm:
```js
      var ndvi = (b - r) / (b + r);
      var x = 255 * (ndvi+1) / 2;
      return [x, x, x, a];
```
![New ImageSequencer](http://preview.ibb.co/eFnfza/vegetation_01_ndvired_new.jpg)


What is surprising is that the older algorithm performed better. Whereas we had established that the newer algorithm maps all values. Moreover, Chris said that the new algorithm is correct, too!

So why didn't the older algorithm work for the previous image, is also another question.

**Comment by jywarren** [comment]
I think the older algorithm is flooring anything below zero! But you should post these results to Chris and ask him too:

https://publiclab.org/questions/ccpandhare/07-08-2017/how-to-verify-if-my-programmatically-generated-ndvi-version-of-an-image-is-correct

**Comment by ccpandhare** [comment]
Okay, Done that!

**Comment by ccpandhare** [comment]
Chris suggested another image. I tried that out. The same issue was there:
* Old algorithm : broken at negative values
* New Algorithm : faint.

So I created another algorithm "Improved Algorithm":
```
var ndvi = 255 * (b - r) / (b + r);
ndvi = (ndvi > 0) ? ndvi : 0;
return [ndvi,ndvi,ndvi,a];
```
This is basically the old algorithm, with the difference that I map negative values of ndvi to 0.
This algorithm produced the exact same result as Infragram! I am not sure if this algorithm is correct!

### Original Image
![Original](http://preview.ibb.co/c7kx0F/vegatation_02.jpg)

### Infragram Output
![Infragram](http://preview.ibb.co/msDjfF/infragram.png)

### Improved Algorithm
![Improved Algorithm](http://preview.ibb.co/h4p1Sv/improved.jpg)

### Old Algorithm
![Old Algorithm](http://preview.ibb.co/nDEqLF/old.jpg)

### New Algorithm
![New Algorithm](http://preview.ibb.co/fQ36ua/new.jpg)

**Comment by jywarren** [comment]
Ok, this is good to know. I think this may show how infragram.org is
destroying some information when in non colorized mode. To do better we
should preserve sub zero values and pass the whole thing to the colorized
for easier viewing.

I think we're good here then!

**Comment by ccpandhare** [comment]
This is definitely not the right method.
It worked for this:
![Original](http://preview.ibb.co/fT1Xea/vegetation_01.jpg)

But not for this:
![Original](https://user-images.githubusercontent.com/24359/27974077-565d176e-632a-11e7-8e02-52465bc43d50.jpg)

Interestingly, mapping all negatives to 0 and all positives to 255 worked for the second one.

So are we missing something in the algorithm?

Maybe our mapping isn't correct.
Maybe we shouldn't have a linear map at all.
Maybe we should have a linear map for a certain range of ndvi values and them map values exceeding them to 0 or 255. Something like:

```
-1 to -x : 0
-x to 0 : linear function
0 to x : linear function
x to 1 : 255
```
What do you think about this? This will solve all test cases. But I am afraid this isn't right.

On the other hand: I totally agree with this:
>  I think this may show how infragram.org is destroying some information when in non colorized mode. 

This is certainly the correct explanation.

**Comment by ccpandhare** [comment]
I think there is data rounding off in Infragram as you pointed out.

**Comment by jywarren** [comment]
Yes. I think the lower contrast image is actually the correct one. To make
it more readable we should colormap it.

**Comment by Fastie** [comment]
Jeff might be right that the lower contrast version ("new algorithm") is correct. The NDVI values for that photo are mostly between -0.2 and +0.3, so there should be very little black or white in the grayscale image, assuming that -1 is black and +1 is white. Here is the histogram of NDVI values computed by Fiji:
![w25floathist](https://user-images.githubusercontent.com/1805899/28171468-82a3968c-67b6-11e7-8eac-9df84e1abd33.PNG)

However, Ned's Photo Monitoring plugin produces an image with high contrast just like the "Infragram" or "Improved Algorithm" versions above. So Infragram and the Photo Monitoring plugin might be computing NDVI correctly but mapping the grayscales strangely. Ned could help with the mapping done by the plugin.

Below is the histogram of NDVI values for Clayton's Chicka Boom row crop photo with all NDVI values > 0.

![claytonndvihist](https://user-images.githubusercontent.com/1805899/28171870-d37ff586-67b7-11e7-8654-fb08a66de40d.PNG)

**Comment by jywarren** [comment]
very helpful. i think we're on the right track then, and part of the NDVI
module may need to be a config option to set the output range (defaulting
to -1=>1 mapping to 0-255).

Also, i think we should make a histogram module! Kinda weird, but it could
output a histogram graph given an image input! but let's think about that
later (it could use plotly, though inefficiently, and would probably break
some module rules)

**Comment by ccpandhare** [comment]
I will open up an issue for the histogram module.
Also, What colormap should we use then? Or should we use one at all?

**Comment by jywarren** [comment]
I'm not sure -- isn't a basic histogram just a graph, not colorized? Maybe stick with the simplest version for now?

**Comment by ccpandhare** [comment]
Yes, true.
I was actually referring to the colormap we were going to apply to ndvi-red in order to get better contrast for the viewers...

**Comment by jywarren** [comment]
Oh haha ok yeah. So last I remembered we broke colormap into its own
module. Are we talking about what the default is or what we should show in
the example demonstrating ndvi? Again, apologies if I'm slow at the moment.

**Comment by ccpandhare** [comment]
No no, I totally understand that you have a lot to look after!

Actually we were getting different outputs for `ndvi-red` than what Infragram gives.
After a lot of tests, we concluded that Image Sequencer gave the right results, and that Infragram uses some "colormap" to enhance the image for better viewing.

The histogram thing was completely different, Sorry. That must have confused you - I shouldn't have said everything in one comment.

**Comment by jywarren** [comment]
But didn't I see a separate colormap module you wrote? I think we can just
consider ndvi separately from color mapping; after all, Infragram does them
as two separate steps. Does that answer your question?

**Comment by ccpandhare** [comment]
Yes there is a separate colormap module. Yes, this does solve my question. I was under the impression that we should have a colormap too.
Okay then, I think this can be closed now and `ndvi-red` is good to go!

**Comment by jywarren** [comment]
Wait, do we need an NDVI module which accepts an option for which channels
to use, default to red/blue? Rather than this? Or maybe ndvi-red is just a
wrapper if ndvi which defaults to red? Or am I overthinking this.

**Comment by ccpandhare** [comment]
It could be renamed to `ndvi` and default to R and B channels.
As of now it doesn't accept any such parameters.
