### ISSUE TITLE
'Save' button for an action is automatically disabled in UI

### ISSUE THREAD

**Issue by Ankit-Singla** [publiclab/image-sequencer#340]
The 'Save' button is automatically disabled whenever a new action/process is applied on any image, or after some parameters are changed and the 'Save' button is clicked. It requires being clicked _two times_ on changing values of parameters, as it does not get autofocus when the values are changed.
@tech4GT @jywarren

**Comment by tech4GT** [comment]
hmm, yes this appears to be a problem, I think we should enable the save button on "focus" based event. Thanks for pointing out @Ankit-Singla 
Would you like to work on this issue?

**Comment by Ankit-Singla** [comment]
Yes, I would love to give it a try.

**Comment by jywarren** [comment]
Merging with #377!

**Comment by tech4GT** [comment]
Okay, this is still not fixed reopening this!

**Comment by HarshKhandeparkar** [comment]
The buttons works but only when the input field is updated `.on('change')`

**Comment by tech4GT** [comment]
Hmm, harsh I was expecting behavior where we don't have to shift focus after changing the field to enable the button.

**Comment by tech4GT** [comment]
Yeah that's what we would like fixed :)

**Comment by HarshKhandeparkar** [comment]
Of we add a `.on('focus')` event listener then the button gets focused even when the input has not changed.

**Comment by tech4GT** [comment]
Hmm, I don't think that's going to cut it since we want to enable it only when the value is changed. Maybe this needs some research work!

**Comment by HarshKhandeparkar** [comment]
I think a onKeyUp or similar event listener would work but change in values should be taken into account

**Comment by tech4GT** [comment]
Harsh I think we would need to make a custom function for this, this kind of functionality usually exists in frameworks like vue and react so we can take some inspiration from there I guess.

**Comment by HarshKhandeparkar** [comment]
Or we can get the initial valie when the field is focused and compare it onkeyup or onchange.

**Comment by HarshKhandeparkar** [comment]
```

inputfield.on('focus', function() {
    var initValue = inputfield.value;
    inputfield.on('change/keyup', function() {
         focusButton(initValue);
    };
};

function focusButton(initValue) {
    if (inputfield.value != initValue) {
         inputfield.focus();
    };
};

```

**Comment by HarshKhandeparkar** [comment]
I'm trying to fix this. I'll open a PR and we will discuss this there.
