### ISSUE TITLE
Add a success prompt for module installation from npm

### ISSUE THREAD

**Issue by tech4GT** [publiclab/image-sequencer#343]
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

Hi, this is a first-timers-only issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!

## The Problem:
We want to show a success message to the user if the module was successfully installed from npm

## How to Solve?
You can print the message to the user's screen like this
```js
console.log("Your module was installed successfully!!");
```

This line can be added below this one.
https://github.com/publiclab/image-sequencer/blob/88364decf6a6111a0be31fd98010576d5c6f918e/index.js#L35

Bonus: It would be really nice if the prompt is colored green. You can take hint from the following line
https://github.com/publiclab/image-sequencer/blob/88364decf6a6111a0be31fd98010576d5c6f918e/index.js#L70

Also you can find the codes for all colors here https://stackoverflow.com/questions/9781218/how-to-change-node-jss-console-font-color

Instance Count 1

**Comment by SidharthBansal** [comment]
This task is published on GCI dashboard. Thanks all.
