### ISSUE TITLE
Add a function to create a gif from the outputs of all steps

### ISSUE THREAD

**Issue by tech4GT** [publiclab/image-sequencer#344]
@jywarren We can add an option which enables sequencer to export the whole sequence as a gif, I think this makes sense since right now we do not have any way of exporting the complete sequence as a single file. What do you think, would this be useful?

**Comment by jywarren** [comment]
👍🏽🎉

**Comment by tech4GT** [comment]
@rockstar777 While it is always better to do things natively if possible, I think using a library here should be fine. Just make sure the library does not slow down the page. Thanks!

**Comment by tech4GT** [comment]
Ok so gifshot looks really promising!! GO ahead!👍

**Comment by rockstar777** [comment]
@tech4GT can you help me in finding src link of images at each step?
thanks

**Comment by rockstar777** [comment]
@tech4GT Please review PR

**Comment by rockstar777** [comment]
![gif_step](https://user-images.githubusercontent.com/26599651/46262688-43b07d80-c522-11e8-8e64-4de97261011e.gif)
