### ISSUE TITLE
Display a flash message on removal of a step

### ISSUE THREAD

**Issue by Mridul97** [publiclab/image-sequencer#345]
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

# First Timers Only
Hi, this is a first-timers-only issue. This means this has been worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!

# The Problem
We want to display a flash message like 'Step Removed' whenever user removes a step.

![ss_8](https://user-images.githubusercontent.com/21158457/46210038-38f0bf80-c34d-11e8-8cd5-32b54acdb5eb.jpg)

# The Solution
Ideally we would like that the message should fade in whenever a step gets removed and fade out after a short time like 1 second. So that it makes the website more interactive and also doesn't disturb the flow of the website. 

A function to display the message can be triggered on click of remove button.

Remove button is made here:

https://github.com/publiclab/image-sequencer/blob/88364decf6a6111a0be31fd98010576d5c6f918e/examples/lib/defaultHtmlStepUi.js#L38-L43

The function should fade in the display message and fade it out after 1 second.

**Comment by tech4GT** [comment]
Good one, @Mridul97 Let's make this one a medium gci issue, Thanks!

**Comment by jywarren** [comment]
Hi, great! Is there a simple "flash notification" library you'd recommend for someone, or example code of what a notification could look like? Bootstrap has an "alert" component you could use; you could try linking to that -- https://getbootstrap.com/docs/3.3/

**Comment by rockstar777** [comment]
please review

**Comment by SidharthBansal** [comment]
This task is published on GCI dashboard. Thanks all.
