### ISSUE TITLE
Include a back-to-top Button on scrolling down

### ISSUE THREAD

**Issue by rbhatia46** [publiclab/image-sequencer#346]
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

## First Timers Only
Hi, this is a first-timers-only issue. This means this has been worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!

## The Problem
We want to include a button at the bottom-right corner of the screen in the main UI when we scroll the page to make it easy to go back to top with a smooth scrolling effect, which is currently missing and can be implemented as shown below.

![scrolleffect](https://user-images.githubusercontent.com/20289101/46234729-40d45200-c395-11e8-849b-ca839f9d462d.gif)

## The Solution
We want to layout the button using an <a> tag in HTML, along with [font-awesome](https://github.com/FortAwesome/Font-Awesome), then style it using CSS and finally write a few lines of jQuery to make the scrolling part work.

A seperate JavaScript file can be made for this functionality under [examples/lib/scrollToTop.js](https://github.com/publiclab/image-sequencer/tree/main/examples/lib), containing the necessary JavaScript code.

The HTML can be included in the [examples/index.html](https://github.com/publiclab/image-sequencer/blob/main/examples/index.html) and the CSS in [examples/demo.css](https://github.com/publiclab/image-sequencer/blob/main/examples/demo.css).

Make sure to include the JavaScript file in the `<script>` tag before the body ends and the button in the HTML markup above that. 

**Instance Count = 1**

**Comment by jywarren** [comment]
Love this! Great!

**Comment by tech4GT** [comment]
Very nice idea indeed!!

**Comment by SidharthBansal** [comment]
Published on GCI dashboard

**Comment by Alfen16** [comment]
How do I claim this issue??? or open it with Desktop Github?

**Comment by SidharthBansal** [comment]
For claiming the task just write a comment asking to claim it

For reproducing the task you need to install the software first
