### ISSUE TITLE
Adjust/Correct the position of Buttons in Mobile View

### ISSUE THREAD

**Issue by rbhatia46** [publiclab/image-sequencer#355]
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

## First Timers Only
Hi, this is a first-timers-only issue. This means this has been worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!

## The Problem
The 'Add Step' and 'Download' button is placed too close to the 'Channel' select list as shown below in the mobile view. It can be given a bit of margin from the top to make it look nice.

![screenshot_20180929-175700](https://user-images.githubusercontent.com/20289101/46245990-d5ca6000-c414-11e8-87c4-167b73985140.png)

## The Solution
We can write very simple Media Query for this and define the style rules for both the buttons by giving some `margin-top` to make it look nicer. The changes can be made in [example/demo.css](https://github.com/publiclab/image-sequencer/blob/main/examples/demo.css).

**Instance Count = 1**

**Comment by vikul1234** [comment]
@rbhatia46  can I work on this issue?

**Comment by jywarren** [comment]
This was solved! Thanks!!!
