### ISSUE TITLE
'No file chosen' wrongly placed in Import Image module

### ISSUE THREAD

**Issue by Paarmita** [publiclab/image-sequencer#356]
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

## First Timers Only
Hi, this is a first-timers-only issue. This means this has been worked to make it more legible to folks who either haven't contributed to our codebase before or even folks who haven't contributed to open source before.

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!

## The Problem
'No file chosen' option in import image module is misplaced, ie. out of the box
 
![screenshot from 2018-09-29 22-14-47](https://user-images.githubusercontent.com/26546816/46248308-5ef18f00-c435-11e8-9fab-2db0722440ed.png)

## The Solution
We need to modify css such that it comes inside border or under Choose file button.
The line which needs to be mdified is:

https://github.com/publiclab/image-sequencer/blob/88364decf6a6111a0be31fd98010576d5c6f918e/src/modules/ImportImage/Ui.js#L16

https://github.com/publiclab/image-sequencer/blob/88364decf6a6111a0be31fd98010576d5c6f918e/src/modules/ImportImage/Ui.js#L11

You need to add class to it and add the new css for the specific class. 

**Instance Count = 1**

**Comment by vikul1234** [comment]
@Paarmita  can I work on this issue

**Comment by vikul1234** [comment]
@Paarmita  It's work properly look this, can  you post another screenshot
![ss](https://user-images.githubusercontent.com/22452641/46253591-e6261d80-c49c-11e8-8872-b950a9b6a3b8.PNG)

**Comment by Paarmita** [comment]
@vikul1234 Plz add an import image module, then you will be able to reproduce this.

**Comment by Yugandhartripathi** [comment]
I would like to work on this.

**Comment by RishabhBhaai** [comment]
Can I work on this issue?
I want to contribute for the first time.

**Comment by tech4GT** [comment]
This issue has been reserved for GCI @vikul1234 
We would really appreciate your help on another one which is not labelled `gci`. Thanks!!

**Comment by jywarren** [comment]
This is a great issue - @Paarmita thanks! Maybe one addition is that you can link to a page including the import-image module using a permalink:

http://sequencer.publiclab.org/examples/#steps=import-image

**Comment by Paarmita** [comment]
@jywarren Yup! we can do that as well.

**Comment by SidharthBansal** [comment]
This task is published on GCI dashboard. Thanks all.

**Comment by makoteq** [comment]
what we have to give in response on GCI?

**Comment by JonathanXu1** [comment]
@makoteq  I believe this task has either not appeared on GCI, someone already claimed it, or it was completed but not closed.

**Comment by oorjitchowdhary** [comment]
@Paarmita @jywarren @SidharthBansal Has this issue been already solved? I can't find any PRs related to this

**Comment by jywarren** [comment]
If there hasn't been a PR, i think it is still open. Do you see the
described design in the demo? Thanks!

**Comment by adiwahyudi02** [comment]
Can I take this issue? @jywarren @Paarmita

**Comment by HarshKhandeparkar** [comment]
Seems like this is redundant and has been fixed elsewhere and is outdated. Can this be closed? @jywarren @gauravano

**Comment by Paarmita** [comment]
@HarshKhandeparkar Thanks for the review.

**Comment by gauravano** [comment]
This issue is not required as there is a change in page design. Thanks @HarshKhandeparkar @Paarmita !

**Comment by HarshKhandeparkar** [comment]
Maybe we can open a new `fto` though as it is not working for smaller screens

Import-image:


![screenshot_20190121_003315_com android chrome](https://user-images.githubusercontent.com/34770591/51443792-4ffc5880-1d14-11e9-8ecb-7cd27b2f5178.jpg)


Load-image first step:


![screenshot_20190121_003318_com android chrome](https://user-images.githubusercontent.com/34770591/51443793-5b4f8400-1d14-11e9-9ac8-1748fd59d015.jpg)

**Comment by gauravano** [comment]
Sure! Go ahead!

**Comment by HarshKhandeparkar** [comment]
Ok. Will do that sometime.
