### ISSUE TITLE
What Should Module Logs Include?

### ISSUE THREAD

**Issue by ccpandhare** [publiclab/image-sequencer#36]
We decided to have logging. SO, what data should be logged? Where does the logged data go?
Does it remain accessible only for that session or should it get stored in a LOG file (for Node.js)?

I think the following should be logged:
* Module Name & Options
* Image details (dimensions,format)
* Success/Failure in generating image

Please let me know what all I am missing.
Thanks :-)

**Comment by jywarren** [comment]
we should have a standard but human-readable JSON log format, maybe one
which could be used to re-run the sequence with the same options?

Would we also log when module options are changed, say, in the web UI?

**Comment by ccpandhare** [comment]
Oh. You meant it this way? I thought it was more of a success/error log. Somewhat like syslog.
I get what you are saying.

>Would we also log when module options are changed, say, in the web UI?

That is a great question. Haven't thought of it but yes, I think we should.

So the Log could actually be a set of jsons which represent the user input. Basically everything what the user runs via `sequencer.SOMETHING` along with options and the output as well.

Also what do you think of this:
>Where does the logged data go? Does it remain accessible only for that session or should it get stored in a LOG file (for Node.js)?

?

**Comment by jywarren** [comment]
Let's treat sequencer.log as an array and as the canonical place for this
to be stored. All other means can be built off this.

I think we could also log errors, but anytime we change the sequencer or
the settings, we might as well keep a snapshot of the current state in the
log in a runnable way, I figured!

**Comment by ccpandhare** [comment]
So something like this, right?

```js
log = [
    {method: "addSteps", json_q: { (data goes here) }},
    {method: "run", json_q: { (data goes here) }},
    ...
];
```

**Comment by ccpandhare** [comment]
I have pushed a basic draft of this to ccpandhare:development

**Comment by jywarren** [comment]
Sure. Do you want to store the total state (list of steps and
configurations per step) on each log entry or do you think that's too much?

On Jul 4, 2017 12:10 PM, "Chinmay Pandhare" <notifications@github.com>
wrote:

I have pushed a basic draft of this to ccpandhare:development

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/publiclab/image-sequencer/issues/36#issuecomment-312912623>,
or mute the thread

**Comment by ccpandhare** [comment]
Well I do think that it's a bit too much... We can store it in a different object, maybe `sequencer.state` ?

**Comment by jywarren** [comment]
Cool!
