### ISSUE TITLE
unreachable code error

### ISSUE THREAD

**Issue by rockstar777** [publiclab/image-sequencer#361]
![error](https://user-images.githubusercontent.com/26599651/46262695-60e54c00-c522-11e8-995e-c1e74923117d.png)

**Comment by SidharthBansal** [comment]
Hi, thanks for creating an issue.
Can you please explain the issue?
In the gitter chat, you told me to mark it as ``first timer only `` issue. There are a few guidelines for creating a first timer issues
1. It  should explain the issue well in simple english statements. As it is for the person who starts OSS
2. We need to provide the potential solution to the problem
3. We need to provide the code links
4. We need to use similar template to generate issues for first timers as on https://github.com/publiclab/plots2/issues/3462
5. You need to assist an individual to make pr at Public labs
Also, if you are creating an issue for gci you need to write the following statement in the issue body
```We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.```

It is much more difficult to create first timer than to solve help wanted issues. But don't worry we all are here to help you guys.
Best of luck!

**Comment by SidharthBansal** [comment]
Thanks for catching a bug

**Comment by rockstar777** [comment]
sorry for inconvenience

**Comment by SidharthBansal** [comment]
No need to worry.
We are here to help

**Comment by tech4GT** [comment]
Okay I looked through this and this seems to be a browser specific, since the issue does not happen on my machine. Please try clearing your browser cache and reopen this if the problem persists. Thanks!
