### ISSUE TITLE
add placeholder when brightness step applied

### ISSUE THREAD

**Issue by rockstar777** [publiclab/image-sequencer#363]
## First Timers Only

Hi, this is a first-timers-only issue. This means this has been worked to make it more legible to folks who either haven't contributed to our codebase before or even folks who haven't contributed to open source before.

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!

## The Problem

Add placeholder like percentage that is applied when brightness step is applied.
![bright](https://user-images.githubusercontent.com/26599651/46283182-4d24fe80-c591-11e8-8f5a-1cbdc6160f40.png)

## The Solution

![screenshot 26](https://user-images.githubusercontent.com/26599651/46301889-31d3e680-c5c5-11e8-8cf2-4e281aa74436.png)

The above code can be found in https://github.com/publiclab/image-sequencer/blob/main/examples/lib/defaultHtmlStepUi.js
try to put placeholder in input element with its corresponding value.
value can be found in step.options

best of luck for the first PR :tada: :tada:

**Comment by kostadriano** [comment]
Hi, Can I claim this issue?

**Comment by kostadriano** [comment]
for me to be sure, what you need is a placeholder with an example like this?
![image](https://user-images.githubusercontent.com/15300776/46322213-08fc2300-c5be-11e8-9e17-a0cbd81e172e.png)

**Comment by rockstar777** [comment]
Yes, It should display when we apply step UI, so that user could get data used when adding a step

**Comment by kostadriano** [comment]
https://github.com/publiclab/image-sequencer/pull/370

**Comment by wptechprodigy** [comment]
Is this still up for grabs?

I want to work on it right away.

**Comment by wptechprodigy** [comment]
defaultHTMLStepUi.js seem to be empty after I had forked, cloned and view it with vim on my Termux CLI

**Comment by wptechprodigy** [comment]
What could be the cause?

**Comment by rockstar777** [comment]
I think it is merged, try to find another issue.
It should not be empty but may due some cloning error.
Try to open it in different text editor, may be it works.
Thanks for your interest.
keep contributing
