### ISSUE TITLE
Restrict upload of files other than images(jpeg,png etc)

### ISSUE THREAD

**Issue by vsk4** [publiclab/image-sequencer#364]
In [image-sequencer](https://publiclab.github.io/image-sequencer/examples/#steps=) only image type  files types must be uploaded,all other file types like pdf, JS, .md files must be ignored/rejected.
while uploading a gif  the uploaded gif is broken. please refer to the screenshots/gif attached.

![screen shot 2018-10-01 at 7 46 32 pm](https://user-images.githubusercontent.com/23310407/46294155-c254fb80-c5b2-11e8-8801-f3ed4859f825.png)
![20181001-074034](https://user-images.githubusercontent.com/23310407/46294033-89b52200-c5b2-11e8-942a-47076ecc61ea.gif)
![screen shot 2018-10-01 at 7 44 56 pm](https://user-images.githubusercontent.com/23310407/46294038-8d48a900-c5b2-11e8-98a0-7ff0779b7cbf.png)

**What to be done : -** 
while uploading restrict all the files other than image format files.This is the best fix for this issue.

**Comment by avsingh999** [comment]
@vsk4  great catch

**Comment by vsk4** [comment]
Hello, I want to work on this issue .

**Comment by aashna27** [comment]
@avsingh999 please review.

**Comment by AmanGarg97** [comment]
Hey  @jywarren  can I start working on this if this issue is not resolved?

**Comment by jywarren** [comment]
I think it's complete, @aashna27 can you confirm? Thanks!!!

**Comment by aashna27** [comment]
Yes it is, the pr might not have referenced this issue. But it has been done. Sorry for the confusion.
