### ISSUE TITLE
Arrange the modules in alphabetical order

### ISSUE THREAD

**Issue by Mridul97** [publiclab/image-sequencer#375]
We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.

# First Timers Only
Hi, this is a first-timers-only issue. This means this has been worked to make it more legible to folks who either haven't contributed to our codebase before or even folks who haven't contributed to open source before.

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!

# The Problem
Arrange the modules in alphabetical order, the modules right now are not in alphabetical order.

![ss_20](https://user-images.githubusercontent.com/21158457/46489476-1a923480-c823-11e8-9e01-1363cdfe6523.jpg)

# The Solution
We need to modify the src/Modules.js file. We need to arrange the modules in the src/Modules.js file in alphabetical order.

https://github.com/publiclab/image-sequencer/blob/70654a5aace44893e9940ea6b902b875d7e4cddc/src/Modules.js#L4-L26

<strong>Instance Count = 1</strong>

**Comment by LeeWarnock** [comment]
claiming 😀

**Comment by Mridul97** [comment]
Hi @LeeWarnock, we have reserved this issue for gci. Please look for any other issue which is not labeled as gci-candidate.

**Comment by LeeWarnock** [comment]
of course! 😄 Thanks!

**Comment by SidharthBansal** [comment]
This task is published on GCI dashboard. Thanks all.
