### ISSUE TITLE
Extra information on new convolution module

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#376]
Hi! The new module is AMAZING. Just a couple follow up requests, @Mridul97 --

![image](https://user-images.githubusercontent.com/24359/46490106-163f2a80-c7d5-11e8-98c9-9464d56bb57c.png)

First, I'd like to have a link to what convolution is and what it's good for, just a wikipedia link as for matrix math i guess... anything that'd help people craft their own inputs.

Second, I'd like to show the current default matrix in the UI input so people know what's being run. 

Would you be able to make these changes? Let's also open a new issue to offer a few "sample" inputs that do different things! Ooh, here's a great page: https://en.wikipedia.org/wiki/Kernel_(image_processing)

Thanks!

**Comment by Mridul97** [comment]
Great! Yes, I will make these changes. This will make the website more informative!

**Comment by jywarren** [comment]
Awesome :-)

**Comment by tech4GT** [comment]
@jywarren Awesome!! We have a very clever fix for the default thing in #384 
Closing this one now!!
