### ISSUE TITLE
Module save button is sometimes greyed out when needed

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#377]
I'm seeing this on the Convolution module but it may affect all modules. 

![image](https://user-images.githubusercontent.com/24359/46490443-05db7f80-c7d6-11e8-9698-e8509abc18b7.png)

We could start by finding the line of code which drives this in the UI code!

Thanks!

**Comment by Mridul97** [comment]
@jywarren I think this is happening because in the code below it is querySelector where as it should be querySelectorAll!

https://github.com/publiclab/image-sequencer/blob/70654a5aace44893e9940ea6b902b875d7e4cddc/examples/lib/defaultHtmlStepUi.js#L101

**Comment by jywarren** [comment]
oh awesome, good catch!

This could be a first-timers-only issue, then. :-)

**Comment by tech4GT** [comment]
@jywarren There is more to this issue as pointed out by @Ankit-singla on #340 
Both of these can be fixed together I think then.
cc @Ankit-singla

**Comment by jywarren** [comment]
Hmm, #340 is now live, but I still see this happening. Maybe there is another sneaky bug in there somewhere? 

https://publiclab.github.io/image-sequencer/examples/#steps=convolution{constantFactor:0.1111111111111111|kernelValues:1%201%201%201%201%201%201%201%201}

**Comment by jywarren** [comment]
yes please! thank you!

**Comment by jywarren** [comment]
I think this has maybe been figured out? I haven't seen it happen recently.

**Comment by aashna27** [comment]
Is anybody working on it ?

**Comment by jywarren** [comment]
It may be worth testing out the latest code, as I think there have been
some various submitted fixes!

**Comment by HarshKhandeparkar** [comment]
I am working on this.

**Comment by HarshKhandeparkar** [comment]
@jywarren please close this one.
