### ISSUE TITLE
add a website icon to the website link

### ISSUE THREAD

**Issue by rohan2599** [publiclab/image-sequencer#378]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [$FILENAME]($BRANCH_URL) in the `$REPO` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://publiclab.github.io/community-toolbox/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
$DIFF
solution :
go to : https://github.com/publiclab/image-sequencer/blob/main/examples/index.html
codelink:
-https://github.com/publiclab/image-sequencer/blob/70654a5aace44893e9940ea6b902b875d7e4cddc/examples/index.html#L52
-https://github.com/publiclab/image-sequencer/blob/70654a5aace44893e9940ea6b902b875d7e4cddc/examples/index.html#L53
+</a>
+by <a href= "https://publiclab.org" title = "Publiclab Website"><i class = "fa fa-globe"></i> Publiclab</a>
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

**Comment by DakshGondaliya** [comment]
I want to work on this issue.

**Comment by rohan2599** [comment]
@DakshGondaliya  goahead

**Comment by tech4GT** [comment]
@rohan2599 Please do take a review from @publiclab/mentors on the issues you raise before assigning them to contributors(especially first timers), we want to make sure that no effort goes to waste, and it's always nice to have another opinion, isn't it. Thanks!

**Comment by rohan2599** [comment]
I forgot to do that ! Sorry @tech4GT  . and  @publiclab/mentors please review the issue

**Comment by tech4GT** [comment]
@jywarren In my view the link seems to be fine, What do you think?

**Comment by jywarren** [comment]
Hmm, here it is:

https://github.com/publiclab/image-sequencer/blob/70654a5aace44893e9940ea6b902b875d7e4cddc/examples/index.html#L53

I'm OK with adding the globe icon but perhaps keeping all other text the same?

Thanks! @tech4GT is right, it's best to get a quick review. But your help is much appreciated!!! 👍

**Comment by Apoorva-13** [comment]
Hi can i take up this issue?

**Comment by tech4GT** [comment]
@Apoorva-13 I think this one has already been taken, we would really like you try another one! Thanks!!😄

**Comment by Apoorva-13** [comment]
ok thanks:)
