### ISSUE TITLE
Browser Based Tests Using tape-run

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#38]
And confirm that the library runs the same in both nodejs and phantomjs -- this will be cool! You could do it in a separate file called browserSpec or something.

**Comment by ccpandhare** [comment]
Hey, I actually couldn't understand this part. Tried to think about it the whole day but to no relief:
> You could do it in a separate file called browserSpec or something.
Could you clarify this please?

Also, Can PhantomJS be used for unit testing? like can we run it in "npm test" ?
Doesn't PhantomJS require the opening of a browser? Am I missing something?

**Comment by jywarren** [comment]
PhantomJS is a browser compiled to run headlessly on the commandline --
it's pretty neat. JavaScript libraries that run in a browser environment
can do automated testing using PhantomJS even on the commandline. So, for
example, there is a DOM.

So this is the idea of actually making automated tests for both Node and
browser environments, but that all actually can be run headlessly on the
commandline. :-) kind of a funny idea but it could help us ensure the core
library's functions are always tested as working OK in both environments.

**Comment by ccpandhare** [comment]
PhantomJS uses the `tape-run` module to headlessly test browser code.
We can also directly use the `tape-run` module. Should we do this?

**Comment by jywarren** [comment]
huh, interesting... wait, what do you mean?
https://www.npmjs.com/package/tape-run -- yes, that looks good!
