### ISSUE TITLE
Provide a function signature for blend step

### ISSUE THREAD

**Issue by Ankit-Singla** [publiclab/image-sequencer#382]
I have noticed that some actions, like blend require a function as input. I think it would be great to provide a function signature for the same, to make it more descriptive.
![fnsignature](https://user-images.githubusercontent.com/22820781/46517418-c6bc3580-c88c-11e8-87e5-bc6b6b319a26.png)

**Comment by varun560** [comment]
@Ankit-Singla i want to work on this.Can you explain in a little more detail?

**Comment by Ankit-Singla** [comment]
Sorry @varun560 , I don't have the authority to assign the issue to you. Actually this issue has not been confirmed yet. Let's just wait for the mentors to review this.

**Comment by tech4GT** [comment]
@Ankit-Singla Nice suggestion!! I think this is a great idea!!(I feel silly we didn't think of this haha)!
I think we can user the default value defined in info.json here! In fact this will be nice if use it for all modules! You can go ahead and work on this!
@varun560 I think @Ankit-Singla would be working on this issue, we can really use your help on other issues, Thanks to both of you!!

**Comment by Ankit-Singla** [comment]
Thank you @tech4GT . I'll give it a try.
