### ISSUE TITLE
Input/Output mismatch on applying edge-detect

### ISSUE THREAD

**Issue by Ankit-Singla** [publiclab/image-sequencer#383]
In some cases, 'Detect Edges' is giving output not corresponding to the input image, but some other image loaded after that, and whose processing steps had later been removed.

This is the sequence of steps I followed :
1. Loaded initial image (default)
![screenshot 2018-10-05 at 11 07 27 am](https://user-images.githubusercontent.com/22820781/46518097-3ed82a80-c890-11e8-9056-5a86a2827817.png)

2. Applied 'Import Image' to load another image
![screenshot 2018-10-05 at 11 08 08 am](https://user-images.githubusercontent.com/22820781/46518108-4d264680-c890-11e8-9815-e5ccb7d74d2a.png)

3. Applied 'Edge Detect'
![screenshot 2018-10-05 at 11 13 14 am](https://user-images.githubusercontent.com/22820781/46518575-82339880-c892-11e8-884e-fa2f320dd197.png)

4. Removed/Deleted Step 2. 'Import Image', but the 'Detect Edge' module gives result for Step 2. image, instead of the Step 1. input even on applying 'Detect Edges' again, resulting in input/output mismatch.
![screenshot 2018-10-05 at 11 13 45 am](https://user-images.githubusercontent.com/22820781/46518603-b1e2a080-c892-11e8-9ead-d0f516b47549.png)

@tech4GT

**Comment by tech4GT** [comment]
Thanks for pointing this out @Ankit-Singla 
I'll look into this one!!
