### ISSUE TITLE
Link in the description does not work as required

### ISSUE THREAD

**Issue by Mridul97** [publiclab/image-sequencer#386]
Read more link in the description at the left side of the image downloads the image rather than opening the information webpage. The link should open a information webpage.

**Comment by Mridul97** [comment]
@jywarren @tech4GT can I work on this issue?

**Comment by Mridul97** [comment]
Oh, I meant when we click on the 'Read more' link it downloads the image where as It should open a webpage that contains more information about that module!

![link](https://user-images.githubusercontent.com/21158457/46566954-20cd0180-c946-11e8-8081-603248e2bd34.gif)

**Comment by tech4GT** [comment]
Ah I see! Nice catch!! @Ankit-Singla would you like to work on this one?

**Comment by Ankit-Singla** [comment]
Yes, I would love to give it a try.

**Comment by aashna27** [comment]
@Ankit-Singla are you still working on this one ??

**Comment by gauravano** [comment]
Hi @tech4GT @aashna27 how about opening a FTO from this one? Thanks!

**Comment by gauravano** [comment]
Just checked @tech4GT. It's fixed. Thanks!
