### ISSUE TITLE
Creating a new issue template

### ISSUE THREAD

**Issue by vanguard07** [publiclab/image-sequencer#388]
We could implement something like done here [ISSUE_TEMPLATE.md](https://github.com/publiclab/plots2/blob/master/.github/ISSUE_TEMPLATE.md) @jywarren

**Comment by vanguard07** [comment]
@publiclab/reviewers Please review

**Comment by tech4GT** [comment]
Okay I tried the link but it does not seem to lead anywhere, please check the link. Also if we have an issue template on plots do you think we need to add it here as well?

**Comment by vanguard07** [comment]
@tech4GT I have updated the link.
My suggestion is that having all the templates (Issue template, PR template, fto template) will help us understand the issues and pull requests more clearly. 😅

**Comment by tech4GT** [comment]
Hmm, I suppose this can make sense for someone not all familiar with the plots project. Maybe let's wait to hear what jeff thinks of this. Thanks for pointing this out though! 😄 
cc @jywarren

**Comment by Divy123** [comment]
@jywarren @tech4GT can I work on this please?

**Comment by lohitha02** [comment]
Is this issue still open? If yes then I would like to work on it.

**Comment by gauravano** [comment]
Hey @lohitha02, this issue is solved by @sashadev-sky in https://github.com/publiclab/image-sequencer/pull/420 so closing this now. Sorry for the inconvenience. And, we would love your help with other issues. Thanks!
