### ISSUE TITLE
Tweaks to getImages & docs

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#39]
Just reading through this again and trying to think as a newcomer --

Should we add `loadImage()` as well as `loadImages()`? I guess I feel the initial default assumption should be that the library works on a single image, and multiple images is a additional mode. That's sort of conceptually simpler too, as a starting point. The README could then say `use loadImage(...)` then have a section called `For multiple images, use loadImages()`. I feel this could be clearer, what do you think?

**Comment by ccpandhare** [comment]
Yes I agree with this. There's another change I was wanting to make to the
Readme. The TravisCI status being shown is of jywarren:master. It should be
corrected to publiclab:master

**Comment by jywarren** [comment]
ah, definitely! good catch!

**Comment by ccpandhare** [comment]
Well this does add semantic meaning to the syntax, to be honest.

**Comment by ccpandhare** [comment]
Fixed in #44 : Improved Docs, Chainable Methods
