### ISSUE TITLE
Add download button to download image from a specific module

### ISSUE THREAD

**Issue by Paarmita** [publiclab/image-sequencer#391]
In order to download the image, we need to click on it to do this. But if a button can be made to this, which is a good pattern to follow. 

UI for download button can be 

![screenshot from 2018-10-06 02-32-26](https://user-images.githubusercontent.com/26546816/46560161-53f49e00-c910-11e8-80ec-4f2042c15c1e.png)

Files need to be changed in order to add the button 
https://github.com/publiclab/image-sequencer/blob/2e7e042baab7e0bf43b821ea9e197cacf6efeac2/examples/lib/defaultHtmlStepUi.js#L40

**Comment by tech4GT** [comment]
@Paarmita I think we already have a lot of ways to download stuff, adding one more seems redundant, what do you think?

**Comment by Paarmita** [comment]
@tech4GT But it would be a great way to do so and removing other like clicking on the image. The button near Add step only downloads the last module image and not other.
And what does save sequence do as it didn't worked in my case?

**Comment by tech4GT** [comment]
@Paarmita I see, let's keep this one long term then since right now apart from click to download and the download buttons, we are adding a save as gif button and too many buttons sort of give a bad UX. Let's keep this on hold until we figure out exactly how we want to handle the downloads part, I think @Mridul97 is working on some major design changes as well so maybe we can look into this post that.
As for the `Save Sequence` feature, it encodes the complete sequence and stores it in the browser's localstorage(in a json file in cli), this will then pop up in the dropdown menu of modules, do you get it?

**Comment by Harshithpabbati** [comment]
Is this closed??
Can I work on this??

**Comment by HarshKhandeparkar** [comment]
@Harshithpabbati do you think this button will be helpful? Currently clicking the image downloads it so adding a new button will be kind of redundant.

Another way would be to remove the image click to download functionality

What would you like to do? Do you have any other ideas?

**Comment by Harshithpabbati** [comment]
@HarshKhandeparkar It's better to have a download button because everyone don't know that they can download it by clicking on the image..What would you say??

**Comment by HarshKhandeparkar** [comment]
Go ahead.

**Comment by Harshithpabbati** [comment]
Where do I add the download button??

**Comment by Harshithpabbati** [comment]
![adddownload](https://user-images.githubusercontent.com/43822585/52911140-d2e9e200-32c5-11e9-8c27-2a1c027d53e6.png)
Is this ok if I add it here

**Comment by HarshKhandeparkar** [comment]
@Harshithpabbati you have to add the button for each step. In the examples/lib/defaultHtmltStepUi.js file linked above in the issue body.

**Comment by Harshithpabbati** [comment]
Even now it changes for each step. It gets the image with most recent change

**Comment by HarshKhandeparkar** [comment]
That's already available in the download as PNG box. This button should be added next to the remove step and add buttons

**Comment by Harshithpabbati** [comment]
oh ok sure i will make the change.

**Comment by Harshithpabbati** [comment]
![download](https://user-images.githubusercontent.com/43822585/52911514-da5fba00-32ca-11e9-971e-e9b0ad3abd26.png)
Is this the thing which you want??

**Comment by HarshKhandeparkar** [comment]
Yes. Looks cool! Please open a PR. We can do the further discussion there

**Comment by Harshithpabbati** [comment]
i didn't made the function.I jst placed it there

**Comment by Harshithpabbati** [comment]
I mean the download button will not work..

**Comment by HarshKhandeparkar** [comment]
Np open a PR.

**Comment by Divy123** [comment]
> @Paarmita I see, let's keep this one long term then since right now apart from click to download and the download buttons, we are adding a save as gif button and too many buttons sort of give a bad UX. Let's keep this on hold until we figure out exactly how we want to handle the downloads part, I think @Mridul97 is working on some major design changes as well so maybe we can look into this post that.
As for the `Save Sequence` feature, it encodes the complete sequence and stores it in the browser's localstorage(in a json file in cli), this will then pop up in the dropdown menu of modules, do you get it?

This discussion has already taken place and I think @Harshithpabbati should wait for the response of @tech4GT  to proceed further.
We don't want any of your work to get wasted so I request you to please wait until Varun gives a green flag as this might not be a need here.

**Comment by HarshKhandeparkar** [comment]
@Divy123 that discussion is very old. Many changes have taken place since that. The four save buttons have been merged into one. Instead of clicking the image, clicking a button can be better as ot is more obvious. Also the image click can be used for a different thing like getting a larger preview. What do you think?

**Comment by Divy123** [comment]
@HarshKhandeparkar your suggestions are good enough, but following with the discussion and I think we should wait for Varun's opinion here.

**Comment by HarshKhandeparkar** [comment]
Ok then. As you say 😊

**Comment by HarshKhandeparkar** [comment]
@jywarren @tech4GT we would like to hear your opinion here.

**Comment by meet2410shah** [comment]
I also want to solve the issue.

**Comment by Harshithpabbati** [comment]
There's a open pr here.So kindly you can search for other one 
Thanks:)

**Comment by HarshKhandeparkar** [comment]
Done
