### ISSUE TITLE
Fix alignment of message in Add step box

### ISSUE THREAD

**Issue by vanguard07** [publiclab/image-sequencer#392]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.
### Problem 
Fixing the alignment of message "Select a new module to add to your sequence." in the Add step box on home page. 

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [index.html](https://github.com/publiclab/image-sequencer/blob/main/examples/index.html) and [demo.css](https://github.com/publiclab/image-sequencer/blob/main/examples/demo.css) in the `image-sequencer` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://publiclab.github.io/community-toolbox/#r=all) for some help in taking your first steps!

Below are the steps as to how to approach the solution:

1. Go to https://github.com/publiclab/image-sequencer/blob/2e7e042baab7e0bf43b821ea9e197cacf6efeac2/examples/index.html#L81 and change it to - `<p class="info">Select a new module to add to your sequence.</p>`

2. Go to [demo.css](https://github.com/publiclab/image-sequencer/blob/main/examples/demo.css) and add the following lines in the end of the stylesheet:
```
.info {
padding: 8px;
text-align: center;
}
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

**Comment by dlarner3194** [comment]
I can take this one

**Comment by vanguard07** [comment]
@publiclab/mentors Please review.

**Comment by dlarner3194** [comment]
I submitted a PR for this issue [here](https://github.com/publiclab/image-sequencer/pull/393)

**Comment by vanguard07** [comment]
@dlarner3194 I made a mistake while writing the solution. Apologies for that. Could you update you PR accordingly. (Just replace the '#' with '.' in demo.css)

**Comment by tech4GT** [comment]
Hi @vanguard07 @dlarner3194 Can you please elaborate on this issue with a screenshot?

**Comment by vanguard07** [comment]
@tech4GT 
Before:
![screenshot 88](https://user-images.githubusercontent.com/23207859/46574119-5e6c7180-c9bc-11e8-84a4-a04f00338ca9.png)
After:
![screenshot 89](https://user-images.githubusercontent.com/23207859/46574122-717f4180-c9bc-11e8-8656-3bb92d149465.png)

**Comment by tech4GT** [comment]
hmm, I guess we can go ahead with this, my one concern is how it will react to smaller and larger screen sizes, did you try that?

**Comment by vanguard07** [comment]
@tech4GT Yes I tried that. It looks good to me.
Before:
![screenshot 90](https://user-images.githubusercontent.com/23207859/46574175-46e1b880-c9bd-11e8-98b6-621c3c7daa8f.png)
After:
![screenshot 91](https://user-images.githubusercontent.com/23207859/46574179-4e08c680-c9bd-11e8-9726-8c3d7d2b10ea.png)

**Comment by tech4GT** [comment]
Awesome!! You can go ahead and work on this one then, this looks good to me. Thanks!

**Comment by karthikhegde05** [comment]
Hello sir, My name is Karthik Hegde. I wanted  to ask if I could claim this issue and send a pull request. This would be my first contribution to opensource community.

**Comment by dlarner3194** [comment]
> @dlarner3194 I made a mistake while writing the solution. Apologies for that. Could you update you PR accordingly? (Just replace the '#' with '.' in demo.css)

Updated

**Comment by jywarren** [comment]
@karthikhedge05 - we'd love a contribution from you. This task is taken already but there are more at https://code.publiclab.org#r=all - please check it out! We can also help you find one if there's not one available. Thank you and welcome!

**Comment by HarshKhandeparkar** [comment]
This has been fixed.
