### ISSUE TITLE
Disable the Save Sequence button until one step is added

### ISSUE THREAD

**Issue by tech4GT** [publiclab/image-sequencer#395]
# First Timers Only
Hi, this is a first-timers-only issue. This means this has been worked to make it more legible to folks who either haven't contributed to our codebase before or even folks who haven't contributed to open source before.

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!

# The Issue
The `save-sequence` button in the UI should be disabled until some step is added in the sequence.

Here's where the `save-sequence` button is made:

https://github.com/publiclab/image-sequencer/blob/9168c15cf9ece28521e92c5fb1d5dd453518c937/examples/index.html#L99

We can make the button disable at the start and then enable it on first click of Add step button. We have to also disable the button if all the steps are removed.

**Comment by tech4GT** [comment]
@Mridul97 Could you format this into a first timers issue, much thanks!!

**Comment by Mridul97** [comment]
Done! Should we make it a gci-candidate issue?

**Comment by maciejmyslinski** [comment]
I'm on it.

**Comment by Divy123** [comment]
Is this issue still open?

**Comment by tech4GT** [comment]
@maciejmyslinski Are you still pursuing this one? If not @Divy123 can proceed with this. Thanks!

**Comment by Divy123** [comment]
@tech4GT I have taken up this issue as of now and started with the code base.
https://github.com/publiclab/image-sequencer/blob/b30b539dab5c329d874a1c5f235fa2518605da10/src/InsertStep.js#L39-L41
Is this the array (stepsArray) the one with number of steps?

**Comment by tech4GT** [comment]
@Divy123 No you are looking in the wrong place, you need to look at the UI in examples folder and not the src.

**Comment by HarshKhandeparkar** [comment]
This already works. Closing this one. 😊
