### ISSUE TITLE
demo of image processing using leaflet map tiles

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#4]
This would have to use a CORS enabled tile source so as to allow canvas manipulation of images from another domain. But it'd be cool -- on the fly image processing on a web map.

**Comment by jywarren** [comment]
This could be done by setting up a basic Leaflet map in an example, and using this listener to find when tileLayers are loaded: https://stackoverflow.com/questions/27378572/leaflet-fire-event-when-tile-layer-loading-begins-and-ends#27379032

```js
layerInstance.on('load', function (event) {
    // fetch all the tile URLs, so in jQuery:
    $('img.leaflet-tile');
});
```

Then use the new `replaceImage()` method on them!

**Comment by ccpandhare** [comment]
Sorry, I am still unable to make out...
What are we trying to accomplish with leaflet.js?

**Comment by jywarren** [comment]
So one use case of replaceImage could be to replace all images that are
tiles in a web map like leaflet. But we would have to continue triggering
replaceImage as new map tiles are loaded, so we need to listen for the
event Leaflet emits when new tiles have been loaded, and run replaceImage
on all the new tiles.

I realised also that means we may want to append a class like
"image-sequenced" (maybe?) to images that have been replaced already, so we
can just grab all the images inside the leaflet map element and not replace
tiles twice.

Make sense?

On Jul 13, 2017 9:19 AM, "Chinmay Pandhare" <notifications@github.com>
wrote:

Sorry, I am still unable to make out...
What are we trying to accomplish with leaflet.js?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/publiclab/image-sequencer/issues/4#issuecomment-315075331>,
or mute the thread

**Comment by jywarren** [comment]
Just a followup fleshing this out a bit more; the demo could be later built out into a plugin named `Leaflet.TileFilter: A Leaflet plugin that accepts a pixel compositing function and runs it on every pixel of incoming tiles, on the fly`

```js
function filter(pixel) { // [r, g, b, a]
  var ndvi = (r + b) / (r - b);
  return [ndvi, ndvi, ndvi, 1]
}

var src = "http://tilesource.com/..."

var tileFilter = new Leaflet.TileFilter(filter, src);

// tileFilter acts like a tile layer

tileFilter.update(filter);
```

**Comment by ccpandhare** [comment]
This looks nice!

**Comment by jywarren** [comment]
Yay this is now possible!

Go here and drag the NDVI bookmarklet into your bookmarks bar: https://publiclab.org/wiki/imagesequencerbookmarklet#NDVI

Then go here: https://publiclab.github.io/Leaflet.DistortableImage/examples/

and click the bookmarklet!

**Comment by gauravano** [comment]
@jywarren you want to open a new issue using this one? Thanks!

**Comment by jywarren** [comment]
Which part do you think? Breaking it out as a plugin? Thanks, Gaurav?

**Comment by jywarren** [comment]
I've spun this into it's own Leaflet plugin here: https://github.com/publiclab/leaflet-multispectral and submitted it to the [Leaflet Plugins listing](https://github.com/Leaflet/Leaflet/blob/master/docs/plugins.md#tileimage-display) here: https://github.com/Leaflet/Leaflet/pull/6499
