### ISSUE TITLE
Typo in CONTRIBUTING.MD

### ISSUE THREAD

**Issue by PrzemyslawPolrolniczak** [publiclab/image-sequencer#401]
Hi,

I just noticed that link to "Ideas" in section 'Jump To' is dead.

**Comment by jywarren** [comment]
Ah, thanks for the catch! Would you be interested in submitting a fix?

**Comment by Mridul97** [comment]
Hi, Is this issue resolved? Can I work on this on?

**Comment by gauravano** [comment]
Hi @Mridul97 you can check and if the issue still persists, go ahead. Thanks!

**Comment by Mridul97** [comment]
@gauravano It seems already fixed. Thanks!
