### ISSUE TITLE
Remove Redundant text and Capitalize first word

### ISSUE THREAD

**Issue by aashna27** [publiclab/image-sequencer#407]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file as explained.
[See this page](https://publiclab.github.io/community-toolbox/#r=all) for some help in taking your first steps!

Navigate to the path   "src\modules\Blur\info" and make changes to the info.json file 

1. Go to line  3 and line 7:
```diff
"description": "Gaussian blur an image by a given value, typically 0-5",

 "desc": "amount of gaussian blur(Less blur gives more detail, typically 0-5)",
```
2. Then modify them as follows: 
```diff
 "description": "Gaussian blur an image by a given value", 


 "desc": "Amount of gaussian blur(Less blur gives more detail, typically 0-5)",

```

Before: 
![image](https://user-images.githubusercontent.com/26546120/46913856-f36dfc80-cfb2-11e8-8a66-1f58b95561d7.png)

After:
![image](https://user-images.githubusercontent.com/26546120/46913975-9ecb8100-cfb4-11e8-9ffc-4a0fd71a0bdb.png)

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

**Comment by sashadev-sky** [comment]
I would like to work on this issue.

**Comment by sk9331657** [comment]
Go ahead .

**Comment by sashadev-sky** [comment]
thank you, this is done.

**Comment by sk9331657** [comment]
> thank you, can I please have a review?

Sure.

**Comment by albanmahmut** [comment]
Can I contribute this one?

**Comment by tech4GT** [comment]
@albanmahmut I think this was already fixed by @sashadev-sky but we can really use your help on another one. Thanks! 😄

**Comment by albanmahmut** [comment]
> @albanmahmut I think this was already fixed by @sashadev-sky but we can really use your help on another one. Thanks!

Ah, I see. Yes, I would appreciate it. :) @tech4GT
