### ISSUE TITLE
Fix installation setup by improving package.json.

### ISSUE THREAD

**Issue by aashna27** [publiclab/image-sequencer#409]
The scripts in the package.json file are segregated incorrectly and this leads to unresolved warnings while trying to run the project locally. 

![image](https://user-images.githubusercontent.com/26546120/46916542-a8b3ab00-cfd9-11e8-98b7-d24a568dc278.png)

The unnecassary warnings prevent the project, from running locally. An updation of the Readme.md and package.json is required.

Note:I am working on this.

**Comment by tech4GT** [comment]
Hmm, this seems to be a windows specific issue. I’ll take a look. Thanks for pointing this out.

**Comment by aashna27** [comment]
Yeah .. but i would like to work on this.

**Comment by tech4GT** [comment]
Oh sure, go ahead! We would love your help😄
PS please make sure you don't break the script for Unix environments

**Comment by aashna27** [comment]
yeaahh suree !!! :)

**Comment by tech4GT** [comment]
Also try clearing your npm cache and then running the script again.(hope you're running it as administrator).

**Comment by aashna27** [comment]
Yeah , thanks. I did try all these but the problem persisted
