### ISSUE TITLE
Add anchor for read more

### ISSUE THREAD

**Issue by aashna27** [publiclab/image-sequencer#416]
I believe the description should have an anchor to the url provided, rather than the link being specified as plain text.  
![image](https://user-images.githubusercontent.com/26546120/47045473-84f68d80-d1b0-11e8-9102-b644704e8763.png)

Note: I want to work on it.

**Comment by jywarren** [comment]
Agreed! How would you like to solve it? Thanks!

**Comment by aashna27** [comment]
The Read more would link to the url provided.
