### ISSUE TITLE
expose direct commandline interface via commander

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#42]
This would be really great to show in the README, too -- to demonstrate that it's possible to use this in an everyday commandline setting:

https://www.npmjs.com/package/commander

I think it'd have to accept some kind of command string, maybe JSON like:

```
imagesequencer --help
imagesequencer -s "crop:cropOptions,..." image.png
```

This may need more thought but it'd be a cool idea to have a section in the docs that's like `From the commandline`

**Comment by ccpandhare** [comment]
Wow! It's really a coincidence that I was thinking of developing a Binary
for ImageSequencer, too! I'd love to do that!

**Comment by jywarren** [comment]
Complete!!

**Comment by jywarren** [comment]
Shall we make a new NPM release?

**Comment by jywarren** [comment]
That should be a new major version # in semver, no?

**Comment by ccpandhare** [comment]
Yes, That Would be a new version! Thanks!
