### ISSUE TITLE
configurable parameters for blend module image number

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#421]
I believe the blend image module, which combines two previous step's outputs, has a fixed or static choice of which two images to use. We should make the default be what it currently is, but allow a settable option parameter for which earlier step to blend in, as an integer index. So two steps back would be -2, three would be -3. 

This shouldn't be too hard to make into a first-timers-only issue!

**Comment by vagita24** [comment]
Can i take this  issue?

**Comment by tech4GT** [comment]
Sure @vagita24!! Go ahead!

**Comment by KusioDev** [comment]
I didn't see the vagita24 comment, and I've made my solution for this issue.

**Comment by tech4GT** [comment]
Oh! Hmm, @kusioDev please do claim the issue before working on it. It saves a lot of effort. Anyway since you have already opened a project, @vagita24 we can really use your help on another one. Thanks!😄

**Comment by KusioDev** [comment]
Sorry, I'm new to this, and I'm still learning. Next time I'll claim the issue so others won't waste their time 😁

**Comment by tech4GT** [comment]
Thanks a lot @KusioDev It's okay, don't stress on it. Thanks for your contribution 😄

**Comment by gauravano** [comment]
Yes, it's solved in #424. Closing now. Thanks!
