### ISSUE TITLE
add slider UI to some modules HTML UI: brightness, blur

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#423]
I believe there's a few simple slider libraries available! jQuery slider, and you can probably search https://npmjs.com for more options. 

Let's start with the brightness module and make adjusting brightness easier for people!

**Comment by aashna27** [comment]
I would like to work on this.

**Comment by tech4GT** [comment]
Sure!! Go ahead! Thanks! :Smile:
