### ISSUE TITLE
Allow upload of only image file types in import-image module

### ISSUE THREAD

**Issue by aashna27** [publiclab/image-sequencer#429]
### We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI !

Hi, this is a first-timers-only issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!

# Task:

The "import-image" makes user to upload a file.
Currently, while uploading "All files" types are allowed. 
###### The module
![image](https://user-images.githubusercontent.com/26546120/47272472-d1bcd880-d5a3-11e8-9d7f-8be4cf27a773.png)

###### Upload File 
![image](https://user-images.githubusercontent.com/26546120/47272475-e305e500-d5a3-11e8-98e8-b7cdd1ed2d7b.png)

###### File Types 
![image](https://user-images.githubusercontent.com/26546120/47272492-36783300-d5a4-11e8-917b-602f778015e4.png)

**Comment by SidharthBansal** [comment]
@tech4GT can you please tell whether this is needed?

**Comment by jywarren** [comment]
I think this one is OK to do!

**Comment by tech4GT** [comment]
This one has been fixed.
