### ISSUE TITLE
Text overlay module

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#431]
It'd be great to have a module which accepts a `string`, `font_size` (default 10pt?), `x`, `y`, `width`, and `height`, and `color`, and draws the text onto the image at the specified dimensions. 

The default text would probably be Lorem ipsum, or maybe `Hello world.`.

Since we don't use `canvas` utilities, we would need to manually render the fonts. However, this library seems to be able to generate bitmaps from font file glyphs:

https://github.com/mattdesl/fontpath

This is a bit of a complex module, but interested to see someone give it a try! Ideally `fontpath` can be set up to output a bitmap which we can insert. 

Other ideas:

https://github.com/mattdesl/fontpath-simple-renderer

**Comment by Mridul97** [comment]
I would love to work on this issue. Can I work on this?

**Comment by Mridul97** [comment]
I would love to work on this issue. Can I give this issue a try?

**Comment by Mridul97** [comment]
I would love to work on this issue. Can I give it a try?

**Comment by Mridul97** [comment]
I would love to work on this issue. Can I give it a try?

**Comment by ho-dor** [comment]
is this issue solved @Mridul97 ? can I help @jywarren ?

**Comment by Mridul97** [comment]
@ho-dor No, this issue is not solved. Actually I was busy with college last week. Yes we can work on it together if you want:smile:

**Comment by aashna27** [comment]
@Mridul97 are you workig on this ??
If not can I take this up ?

**Comment by Mridul97** [comment]
@aashna27 You can take it! Thanks!

**Comment by aashna27** [comment]
> @aashna27 You can take it! Thanks!

Thanks 😄

**Comment by jywarren** [comment]
How are things going on this? I know it's a tough one, how are you thinking of approaching it?

**Comment by aashna27** [comment]
I went through the links you had provided and couldn't really figure it out without using canvas. As it requires adding fonts and rendering it on the image. Then I moved on to new issues, my mistake.. I ll search more on this.

**Comment by jywarren** [comment]
no problem! did fontpath + adding fonts seem plausible? I know this is a pretty tough issue. We don't have to solve it perfectly all at once; a basic implementation would be OK. 

Another option is a pure-JS implementation of Canvas, maybe...

**Comment by HarshKhandeparkar** [comment]
@jywarren is there any lib which converts fonts to bitmaps or something?? @publiclab/is-reviewers

**Comment by jywarren** [comment]
Check out the demo section of fontpath!

**Comment by HarshKhandeparkar** [comment]
@jywarren @publiclab/is-reviewers https://www.npmjs.com/package/canvas

**Comment by aashna27** [comment]
Great, this one adds text to image. Cool, i ll go ahead with this one, or maybe try with just canvas.

**Comment by aashna27** [comment]
Thanks @HarshKhandeparkar ☺️

**Comment by VibhorCodecianGupta** [comment]
@aashna27 I found a pretty cool implementation of text overlay of gimp and I was working on, I might be able to convert it. Can you give me a day or two? If I'm able to, I'll need some help with it as well. Otherwise you can go ahead with the canvas approach, and expect all the help from me :)

**Comment by aashna27** [comment]
Yeahh suree ☺️

**Comment by HarshKhandeparkar** [comment]
@VibhorCodecianGupta what lang is GIMP written in? Also can you please provide a link to the code?
