### ISSUE TITLE
display add step menu with common modules as "quick" buttons

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#432]
When selecting a new step to add at the demo, https://sequencer.publiclab.org, we should have a way to quickly add the most common types of 

Sort of like the Instagram menu shown in this screenshot!

This can be a design issue first - needing mockups, sketched ideas, discussion. We'd love some help!

![screenshot_20181021-231523](https://user-images.githubusercontent.com/24359/47276756-7f6dbe80-d587-11e8-96ce-bdf0f1492426.png)

We can use Fontawesome icons: https://fontawesome.com/v4.7.0/

Please help out by identifying good icons (pasting in a URL to FontAwesome's icon page, and a screenshot of the icon itself) for:

* brightness
* contrast
* saturation
* rotate
* crop

If you have ideas for the design, please upload an image of your mockup or sketch!

**Comment by jywarren** [comment]
![screenshot_20181021-231523](https://user-images.githubusercontent.com/24359/47276756-7f6dbe80-d587-11e8-96ce-bdf0f1492426.png)

**Comment by jywarren** [comment]
We can probably use fontawesome for the icons!

**Comment by jywarren** [comment]
The "adjust" icon is generic but good, maybe for brightness? https://fontawesome.com/v4.7.0/icon/adjust

![image](https://user-images.githubusercontent.com/24359/48316606-f0ffc200-e5b3-11e8-91c3-e23b7102c2ec.png)

**Comment by jywarren** [comment]
Refresh is good! https://fontawesome.com/v4.7.0/icon/refresh

![image](https://user-images.githubusercontent.com/24359/48316612-0543bf00-e5b4-11e8-9dbd-f852d5e3083f.png)

**Comment by JonathanXu1** [comment]
Hi, I'd like to work on this task. Before I get on making a prototype, I would like to confirm the icon set with you guys.

How are these icons:
brightness: https://fontawesome.com/icons/sun?style=regular
![image](https://user-images.githubusercontent.com/22998430/48519299-7399b300-e83a-11e8-90f5-0184d18c0baf.png)

contrast:  https://fontawesome.com/icons/adjust?style=solid
![image](https://user-images.githubusercontent.com/22998430/48519203-1aca1a80-e83a-11e8-8adc-4e1d2b87a26d.png)

saturation: https://fontawesome.com/icons/tint?style=solid
![image](https://user-images.githubusercontent.com/22998430/48519458-fae72680-e83a-11e8-98f4-2e3217e7a1e7.png)

rotate: https://fontawesome.com/icons/redo?style=solid
![image](https://user-images.githubusercontent.com/22998430/48519417-d5f2b380-e83a-11e8-9a99-7a658480e3c7.png)

crop: https://fontawesome.com/icons/crop-alt?style=solid
![image](https://user-images.githubusercontent.com/22998430/48519498-1f430300-e83b-11e8-88ea-f41146bac60c.png)

**Comment by jywarren** [comment]
this is great! Good finds! Yes, and one GCI task was just finding the
icons, so that's a great start. We'd love your help with this!

**Comment by jywarren** [comment]
this looks good, but perhaps it could be displayed below the step,
similarly to how the Add Step box is shown, but wider. And then perhaps Add
Step with the dropdown could be below these quick button options, since we
won't have a button for everything. What do you think?

Hmm, i can't seem to find that task... perhaps it got changed or deleted.
Sorry!

**Comment by JonathanXu1** [comment]
So something like this?

![prototype2](https://user-images.githubusercontent.com/22998430/48522777-fd03b200-e847-11e8-9a91-489772ab76ea.png)

**Comment by jywarren** [comment]
I think that looks great. Maybe you can move "Select a new module..." up
above it, and have the existing Add Step in the same box but below your
icons. It could say "More modules" above the Add Step area. How about that?

**Comment by JonathanXu1** [comment]
How's this?
![prototype2](https://user-images.githubusercontent.com/22998430/48524681-528f8d00-e84f-11e8-831d-b6e344ee1547.png)

**Comment by jywarren** [comment]
This is awesome. Just be sure that clicking Add Step while "More modules"
is selected doesn't do anything! I think there may be a way to disable the
initial option in a select... worth looking up!

This is so exciting :-)

**Comment by JonathanXu1** [comment]
Great, I'll start coding this now. By the way, do you have auto-reload capabilities with grunt serve on localhost?

Also, I'm having some trouble loading specific icons:
![image](https://user-images.githubusercontent.com/22998430/48531350-f423d800-e869-11e8-89ea-5a349565ac11.png)
As you can see in the code, the number within the tags is just to see where the icons ought to be.
![image](https://user-images.githubusercontent.com/22998430/48531335-eb330680-e869-11e8-96c6-678f70fd126e.png)

There are no errors in the console. I suspect this is because we're using Font Awesome v 4.5 instead of the latest version. I haven't upgraded the node module because I don't think v 5.5 is backwards compatible. Should I use PNGs instead, or do you know if there's another reason?

**Comment by jywarren** [comment]
Hi, hmm, you should be able to auto-detect and build with just the command `grunt`!

Ah ok, so your icons now work? Could you open a pull request for this, it's tremendous! Thank you!

**Comment by jywarren** [comment]
Could you put each icon in a circle, to make it seem more "clickable"? You can set the `border-radius:40px;` in CSS or there may be a Bootstrap style for round things... Awesome!!!

**Comment by JonathanXu1** [comment]
Yeah sure I'll work on it right now!

**Comment by JonathanXu1** [comment]
I've finished the bulk of your requests, but am having some issues. I've opened a pull request so you can see the details: https://github.com/publiclab/image-sequencer/pull/479

**Comment by gauravano** [comment]
@jywarren could you please update the issue as per work done by Jonathan, so that we would be able to figure out the remaining work. thanks!

**Comment by tech4GT** [comment]
@gauravano I think we can close this one, this is pretty much done! :tada:

**Comment by gauravano** [comment]
Thanks @tech4GT for update :smile: !
