### ISSUE TITLE
Rotate module

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#434]
We should have a rotate module that accepts an angle. I'm sure there's a library we can use to make this easy. Maybe:

https://www.npmjs.com/package/imagejs

We'd love help with this one!

**Comment by jywarren** [comment]
Wow that would be super!!!

**Comment by Divy123** [comment]
Can I work on this issue @jywarren ?

**Comment by aashna27** [comment]
@Divy123 I am really sorry I could give time to it but i would like to pursue this. I would let you know if I need some help 😄

**Comment by Divy123** [comment]
Sure @aashna27 .
