### ISSUE TITLE
Resize/scale module

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#435]
We should have a resize/scale module that accepts a percent parameter. I'm sure there's a library we can use to make this easy. Maybe:

https://www.npmjs.com/package/imagejs

We'd love help with this one!

**Comment by KusioDev** [comment]
Can I take this one 😃?

**Comment by jywarren** [comment]
That would be awesome, thank you!

**Comment by aashna27** [comment]
@KusioDev would love to help you, if you need . 😄

**Comment by KusioDev** [comment]
@aashna27 Sure, I'm still new to this, and I would appreciate some help 😄 
If you have discord you can add me Kusioo#4401 😎

**Comment by Paarmita** [comment]
Closing this one, As PR has been merged. Thanks @KusioDev :)
