### ISSUE TITLE
Enhance gif view

### ISSUE THREAD

**Issue by rockstar777** [publiclab/image-sequencer#436]
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

## The Problem
Enhance gif view, Gif should show in popup view instead of it showing in same page.
some thing like this.
 https://www.w3schools.com/bootstrap/bootstrap_modal.asp

## The Solution
check this link
https://getbootstrap.com/docs/4.0/components/modal/
write html code here
https://github.com/publiclab/image-sequencer/blob/main/examples/index.html#L90
 js if reqiured here
https://github.com/publiclab/image-sequencer/blob/965399a2b4a3322354f371a1dbc674059f42d436/examples/index.html#L100
and css if required here
https://github.com/publiclab/image-sequencer/blob/965399a2b4a3322354f371a1dbc674059f42d436/examples/demo.css#L134

Thanks
**Instance Count = 1**

**Comment by SidharthBansal** [comment]
Can you please tell code links in the repository?
So that I can publish this onto GCI main website.
We need to have code links in the issues before posting them onto GCI dashboard.
Thanks

**Comment by rockstar777** [comment]
yeah sure in a moment
thanks

**Comment by rockstar777** [comment]
@SidharthBansal I think this can be pushable on gci dashboard
Thanks
