### ISSUE TITLE
Break out string parsing functions into a separate file called Strings.js

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#458]
This is some great code! Let's break it out so it's more readable. We might even make a folder called `strings` and break it out more thoroughly. 

https://github.com/publiclab/image-sequencer/blob/2243a4b8f7dae9741873b721c9a6d41582fa3c98/src/ImageSequencer.js#L234-L344

Keep an eye on the tests here, which will tell us if we've properly moved the code:

https://github.com/publiclab/image-sequencer/blob/main/test/modules/import-export.js

**Comment by jywarren** [comment]
@Mridul97 would you be at all interested in this one? Just curious!

**Comment by ho-dor** [comment]
Can I claim this @jywarren, please?

**Comment by jywarren** [comment]
Yes please, that'd be great!!!

**Comment by VibhorCodecianGupta** [comment]
@jywarren this has been inactive for a while, shall I take this up?

**Comment by jywarren** [comment]
sure, is anyone currently working on it?

**Comment by VibhorCodecianGupta** [comment]
Doesn't look like it

**Comment by jywarren** [comment]
Sure, then, go ahead! Thank you!

**Comment by Mridul97** [comment]
@VibhorCodecianGupta I am working on this one. Could you please take up any other issue. Thanks!

**Comment by jywarren** [comment]
Sorry Mridul, i keep replying in my email inbox, and not seeing prior
comments. Apologies!

**Comment by Mridul97** [comment]
No problem at all! @jywarren

**Comment by VibhorCodecianGupta** [comment]
@Mridul97 yup, no issues!
