### ISSUE TITLE
Close-parentheses in Dynamic module input get lost when sourced from URL

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#459]
The new ability to use a `map()` function in the Dynamic module (#457) works, but the URL gets messed up;

http://localhost:8000/examples/#steps=dynamic{red:map(r%2C0%2C255%2C0%2C128)|green:g|blue:b|monochrome%20(fallback):r%20%2B%20g%20%2B%20b}

This loses the closing ) from the map(...) function when you open it... not sure why!

https://github.com/publiclab/image-sequencer/blob/2243a4b8f7dae9741873b721c9a6d41582fa3c98/src/ImageSequencer.js#L286-L323

**Comment by VibhorCodecianGupta** [comment]
@jywarren Is this issue up for grabs?

**Comment by jywarren** [comment]
yes please!

**Comment by Divy123** [comment]
Is this issue still open? I would love to work on this.

**Comment by VibhorCodecianGupta** [comment]
@Divy123 this is almost done! could you find another issue? :D

**Comment by Divy123** [comment]
yeah sure @VibhorCodecianGupta :smile:

**Comment by Mridul97** [comment]
Hi, @VibhorCodecianGupta are you working on this issue? Can I work on this issue?

**Comment by VibhorCodecianGupta** [comment]
@jywarren done #580
