### ISSUE TITLE
Overlay module offset parameter doesn't work

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#465]
The Overlay module has a parameter called "offset" which lets you set which step is overlaid onto. But it doesn't seem to work:

See it malfunctioning here in the final step:

http://sequencer.publiclab.org/examples/#steps=crop{x:0|y:0|w:611|h:479},gradient{},colormap{colormap:stretched},crop{x:0|y:0|w:611|h:60},resize{resize:25%25},overlay{x:5|y:5|offset:-5}

Compare to:

http://sequencer.publiclab.org/examples/#steps=crop{x:0|y:0|w:611|h:479},gradient{},colormap{colormap:stretched},crop{x:0|y:0|w:611|h:60},resize{resize:25%25},overlay{x:5|y:5|offset:-3}

It always seems to source the same image!

The code for the Overlay module is here: https://github.com/publiclab/image-sequencer/tree/master/src/modules/Overlay

**Comment by jywarren** [comment]
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://code.publiclab.org/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

**Comment by keshav234156** [comment]
@jywaren made some cahnges.
![Screenshot from 2019-08-28 22-20-37](https://user-images.githubusercontent.com/45951376/63875940-29a54680-c9e2-11e9-826f-54d61774004d.png)
![Screenshot from 2019-08-28 22-20-53](https://user-images.githubusercontent.com/45951376/63875952-2d38cd80-c9e2-11e9-9fe2-2a72d7095f6d.png)
![Screenshot from 2019-08-28 22-21-00](https://user-images.githubusercontent.com/45951376/63875960-2f9b2780-c9e2-11e9-9919-b465cff28fe7.png)
![Screenshot from 2019-08-28 22-21-05](https://user-images.githubusercontent.com/45951376/63875969-32961800-c9e2-11e9-9abb-a7f009c5cb1a.png)
 
Is this the expexted behaviour?

**Comment by jywarren** [comment]
Yes! It is! Wow, great work! Do you have a PR open for this? Thank you!

**Comment by keshav234156** [comment]
@jywarren it's also working fine with the beta version.I think that this issue has been fixed with #1082 .
So we could now this this issue

**Comment by keshav234156** [comment]
@jywarren @HarshKhandeparkar can you please close this issue as it's already fixed in #1082 and is working as expected in beta version .
