### ISSUE TITLE
Add an "insert step" button on each step UI

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#466]
This code shows the excellent "insert step" method in use:

https://github.com/publiclab/image-sequencer/blob/5f57123503993e889fbd3869cdcbc356c7d0bf6b/test/modules/image-sequencer.js#L139-L144

We should add a new button (next to the trash button) which lets you insert a new module:

![sketch-1541958834514 png](https://user-images.githubusercontent.com/24359/48316374-ea238000-e5b0-11e8-95e4-d187bea90d74.jpeg)

See this for how the add step UI works, that could be adapted here:

The available modules are added to the select here:

https://github.com/publiclab/image-sequencer/blob/4d996b9968f95fd7f6158bde3034d9f5c43f6737/examples/demo.js#L11-L16

Here is how the "add step" button is triggered:

https://github.com/publiclab/image-sequencer/blob/a17d1a6ccd78e91043d823b134722c80a61ea491/examples/demo.js#L34

Here is the function that's run when the button is pressed; this could be adapted to accept a 'step' parameter too, so the insertion could happen at a different place in the sequence:

https://github.com/publiclab/image-sequencer/blob/88364decf6a6111a0be31fd98010576d5c6f918e/examples/lib/defaultHtmlSequencerUi.js#L38-L60

@holykol perhaps you'd be interested in this one? Or someone else? We'd love some help!

**Comment by Divy123** [comment]
@jywarren can I work on this?
Looks interesting to me.

**Comment by jywarren** [comment]
oh that would be great, thank you!

**Comment by JonathanXu1** [comment]
Hey I'm interested in this task! Is anyone working on it? Just to clarify, will the add-step button display a drop-down and do the same thing as the "add-step" button on the bottom of the page?
![image](https://user-images.githubusercontent.com/22998430/49046749-2ce57a80-f1a3-11e8-9b4e-a3433066db2f.png)

**Comment by jywarren** [comment]
I think the insert-step button might actually insert the entire box as
shown above, but between two steps. This might mean we have to have a
method which "constructs" the html for the interface, and be able to call
it to be inserted in a given HTML element, and specify an index at which to
add the new step, you know?

**Comment by JonathanXu1** [comment]
Oh cool, thanks for clarifying. And I presume it hides itself after a new step is created? I'd love to work on this task but I'm not sure if someone else is working on it...

**Comment by jywarren** [comment]
yes, that's right. I don't think someone is at the moment?

**Comment by Divy123** [comment]
I am working on it actually.
Sorry for being late.I am having my semester exams right now.
So will continue after 30th Nov. @jywarren  @JonathanXu1

**Comment by jywarren** [comment]
Oh I'm sorry, no prob! Good luck with your exams!!!

**Comment by JonathanXu1** [comment]
Ah no worries, good luck on your exams!

**Comment by Divy123** [comment]
@jywarren  I am working on the issue right now.
There is a problem that none of the changes that I am making are being visible on my localhost.
Can you please help me with this?

**Comment by Divy123** [comment]
Thanks @jywarren .One more thing while the majority of the work is done, that please look into the screenshot below:
![screenshot from 2018-12-14 21-03-21](https://user-images.githubusercontent.com/31225007/50012184-fb164580-ffe3-11e8-8c2b-06e2b6aacee5.png).
Getting a basic understanding I have added appropriate index in the run function but still the step is being added at the last. Can you please guide me on this?

**Comment by tech4GT** [comment]
@Divy123 I think the problem here is not with run but with addSteps method, I think we need to use the insertSteps method to put the steps in the right order.

**Comment by Divy123** [comment]
@tech4GT  please see this. I have changed it like this but still not working.
![screenshot from 2018-12-14 22-29-57](https://user-images.githubusercontent.com/31225007/50016693-e9d33600-ffef-11e8-948c-7b68d542a7cf.png)

**Comment by tech4GT** [comment]
I think the function needs the image too, do check out given by @jywarren above and try it in that format, if that doesn't work I'll be more than happy to look at your code.
PS It's kind of late here so I may get to it tom. :smile:

**Comment by Divy123** [comment]
@tech4GT I tried passing ( _sequencer.images,id+1,stepName) as arguments to insertStep but then I am getting errors.
Probably the errors are due to me passing wrong arguments. Can you please help me understand the role of image in the set of parameters?
Attached is the error I am getting:
![screenshot from 2018-12-14 23-59-56](https://user-images.githubusercontent.com/31225007/50020763-fc07a100-fffc-11e8-82fa-2bef71594789.png)
`_sequencer
    .insertSteps(_sequencer.images,id+1,newStepName)
    .run( {index: _sequencer.images.image1.steps.length - sequenceLength-1 } );`is my code for insertStep.

**Comment by Divy123** [comment]
This particular issue is resolved!

**Comment by Divy123** [comment]
@tech4GT  I have almost don the work. Just one thing is there I am not able to figure out.
The inserted step is added at the correct position in steps array, the url is getting updated correctly but in the UI the inserted step is always being added at the last.Though on  a page refresh all the steps including the newly inserted one comes at its correct position. Can you please help me with that?

**Comment by tech4GT** [comment]
oh, try looking into the run function, I think the steps are not being re-run properly.

**Comment by tech4GT** [comment]
Try running it from 0, if that works then you can figure out the right index. Glad to hear you are making progress on this :blush:
