### ISSUE TITLE
Ability to set background color when "over cropping" to enlarge canvas

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#467]
When the crop module is given dimensions larger than the original image, it adds blank (transparent) pixels to the image edges; see this example:

http://sequencer.publiclab.org/examples/#steps=crop{x:0|y:0|w:611|h:479}

![image](https://user-images.githubusercontent.com/24359/48326907-cf312a00-e609-11e8-9840-59be62388551.png)

It would be excellent to offer as a parameter the color that can be filled instead of left blank. Here is the section of code where it's performed; perhaps we could tell if a pixel is outsider the original bounds and fill it with the given color?

https://github.com/publiclab/image-sequencer/blob/4d996b9968f95fd7f6158bde3034d9f5c43f6737/src/modules/Crop/Crop.js#L12-L21

**Comment by KusioDev** [comment]
It looks interesting! But how would we set the color? RGB, HEX, or color input?

Anyway, I'd like to work on that one 😅

**Comment by jywarren** [comment]
Cool, great! Yes, let's set the color for now via a hex value... could that
work? Or shall we say an array like [r, g, b, a] to make an easier first
step?

Later, we might want to include some color conversion tools so you could
use various methods of indicating a color.

**Comment by Mridul97** [comment]
@jywarren I would love to work on this!

**Comment by jywarren** [comment]
That'd be awesome!!!
