### ISSUE TITLE
UI Improvements 

### ISSUE THREAD

**Issue by Divy123** [publiclab/image-sequencer#470]
The UI for browser can be improved in these ways:
1.`choose file` option should be made to centre.
2.Project description can be made to look better.
3.`open source by public lab` line can be made to appear at the bottom of the page
4.The step description can be made to appear at  right and the resultant image at the left.
5.`Add Step` and `Download PNG` view boxes can be aligned vertically for a better view.
6.Buttons can be made to look better.

###The files to be looked in are 
[https://github.com/publiclab/image-sequencer/blob/main/examples/demo.css](url)

**Comment by Rishabh570** [comment]
@Divy123 I would like to work on this

**Comment by Divy123** [comment]
@Rishabh570 I am currently working on it.
Please look into some other issue.Thanks for your help.

**Comment by Rishabh570** [comment]
@Divy123 No worries, I'll be available for help though :)

**Comment by HarshKhandeparkar** [comment]
Some of these improvements are in their own issue in the issues tab and are currently being worked on.
