### ISSUE TITLE
Change Gif to GIF in 'View Gif' button.

### ISSUE THREAD

**Issue by Divy123** [publiclab/image-sequencer#471]
File that can be looked in:
[https://github.com/publiclab/image-sequencer/blob/main/examples/index.html](url)

**Comment by Rishabh570** [comment]
@Divy123 I would like to work on this

**Comment by Rishabh570** [comment]
Hi @Divy123, please close this issue :)

**Comment by jywarren** [comment]
Hi, do you want to try #477? We'd love your help!
