### ISSUE TITLE
A Semantic Issue

### ISSUE THREAD

**Issue by ccpandhare** [publiclab/image-sequencer#48]
How addSteps, removeSteps, etc. work currently :
If no image is specified in the addSteps or removeSteps arguments, then the operation is performed on all images.

Recently we allowed chaining of methods which enables us to do this:
```js
    sequencer.loadImage('image.jpg').addSteps('ndvi-red').run()
```
As you can see, no image is specified with `addSteps`. This means that `ndvi-red` will be added to ALL images present in the sequencer.

What should be done:

* If chained, apply the steps only to the image which is being chained by storing which steps are being chained and the image associated in the object returned by these methods?

or

* Force the user to specify the image.

**Comment by jywarren** [comment]
I guess I think a diagram would be useful here, showing images, their
movement through the steps, etc.

I was tempted to say we should just create a separate instance of sequencer
for each image... but that doesn't make a lot of sense.

Not only is it useful to be able to "cache" any image that's passed
through, so we can efficiently rerun things, but if we want to load a new
image in, it makes some sense that it wouldn't "flush out" preciously run
images.

But then, as we load in images, will memory use go up enormously? What if
we try to run this on 1000 images as a batch process?

What if we don't cache by default, and we don't store per step image state
unless specifically set in an options flag like cache: true?

I'm not sure yet, but these are the use cases to consider. What do you
think?

J

**Comment by ccpandhare** [comment]
I think you are right. We should cache the state only if it is required.

Also I have created a pull request which solves the issue I have mentioned above #53
