### ISSUE TITLE
Bug in example/lib/defaultHtmlStepUi.js

### ISSUE THREAD

**Issue by HarshKhandeparkar** [publiclab/image-sequencer#480]
### Flash Message During Step Removal Typo Bug

![gci-bug](https://user-images.githubusercontent.com/34770591/48676821-ef289680-eb91-11e8-911d-b1c949c2b461.gif)

https://github.com/publiclab/image-sequencer/blob/bf13d5807ab34b04517a3c9d3b4c318342432a48/examples/lib/defaultHtmlStepUi.js#L19

> DOMNotification is not defined and is a typo

**Comment by gauravano** [comment]
hey @HarshKhandeparkar, could you please give your Email ID?

**Comment by HarshKhandeparkar** [comment]
Why do you need by Email ID?

**Comment by gauravano** [comment]
Actually, we can talk here only:

@HarshKhandeparkar thanks so much for your enthusiasm in the weekly check-in! Sorry we made some last minute changes, but we thought it over a bit and felt that a) we worried that some memes might end up making people feel bad, even by accident, and b) we have a strong need for reviewers anyways. I hope this makes sense why we deleted your comment from weekly check-in and didn't want this to be discouraging - we are super grateful for your help in collaboratively hosting the community. Thanks so much for your time and keep up the great work!

**Comment by HarshKhandeparkar** [comment]
Oh Np. Even I thought I would delete my comment but you had already done that. I was hesitant to comment at first but I saw your comment and I thought it won't be much of an awkward thing. But anyways, thank you, Np, welcome etc. 😊

**Comment by gauravano** [comment]
Great!
