### ISSUE TITLE
List of UI tasks to be broken out into issues

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#487]
Looking for help with these! They could also make good GCI issues @publiclab/mentors !

* [x] change "Save" module button to "Apply"
* [x] change description text above quick-add buttons so it stays as "apply a new step" instead of getting replaced by the last applied module's description (needs gif to demonstrate issue)
* [x] make Image Sequencer header reload the page with no steps
* [x] add a "start a new sequence" button somewhere in header
* [x] add "take a photo" as alternative to "Choose file" in initial load image step
* [x] move "Download PNG" box down onto same line as "Save Sequence" leaving Add Step box full-width
* [x] show spinner icon while gif is generating
* [x] Fix alignment of Add Step button and dropdown next to it
* [x] add toggle-able "collapse" button next to step name (like "load-image") to hide image, description (leaving just the line and the title)
* [x] add Resize module to list of quick buttons, as in [this image](https://user-images.githubusercontent.com/24359/48908983-f5d93700-ee39-11e8-88b3-58ea81efe467.png)

### Sliders

* [x] make sliders (for range inputs) touch-draggable (using a library) - like brightness
* [x] set brightness default to not be totally white
* [ ] set contrast default to something useful
* [x] set contrast to range slider UI

### Save sequence

* [x] have "save sequence" also show a message showing where to find the saved sequence
* [ ] have "save sequence" link to docs showing how to turn a sequence into a meta module
* [x] have "save sequence" link clarify that it will only be available in this browser

**Comment by Rishabh570** [comment]
@jywarren Opened [this](https://github.com/publiclab/image-sequencer/issues/489) issue for changing "save" to "apply" in add step UI...

**Comment by jywarren** [comment]
Awesome!

**Comment by jywarren** [comment]
Actually we could make a gci task to break out this list into separate
issues, too! Just an idea :-)

**Comment by Rishabh570** [comment]
@jywarren and they'll be getting credits/points for that?

**Comment by jywarren** [comment]
I think so, if they're well formatted! We could ask them to post a
screenshot and describe the feature a bit more. Not everyone will be able
to but some are pretty simple.

**Comment by aashna27** [comment]
added #491 for "set brightness default to not be totally white"

**Comment by aashna27** [comment]
should I continue with breaking up or leave it for gci task ?

**Comment by Rishabh570** [comment]
> I think so, if they're well formatted! We could ask them to post a
screenshot and describe the feature a bit more. Not everyone will be able
to but some are pretty simple.

That would be great :+1:

**Comment by oorjitchowdhary** [comment]
@jywarren @Rishabh570 @aashna27 So is this a GCi task? I may be able to make these into well-formatted issues... We can also use the plots2 repo issue template

**Comment by Rishabh570** [comment]
Pinging @jywarren for that, you can make these into well formatted into issues...you can get credits/points for it :)

**Comment by oorjitchowdhary** [comment]
So I can start working right?

**Comment by Rishabh570** [comment]
Yep, that would be great :+1:

**Comment by oorjitchowdhary** [comment]
Added these till now... Pls take a look at them...
1. add "take a photo" as alternative to "Choose file" in initial load image step
2. move "Download PNG" box down onto same line as "Save Sequence" leaving Add Step box full-width
3. add Resize module to list of quick buttons, as in this image

**Comment by oorjitchowdhary** [comment]
Add some more #495 and #496

**Comment by oorjitchowdhary** [comment]
Pls take a look and make a task on the gci dash so that i can claim it...
Also, I have to make issues for whole of the list right?

**Comment by Rishabh570** [comment]
You can create issues out of whole list but it's totally up to you...if you
want to do it or not :)

**Comment by oorjitchowdhary** [comment]
Ok so I'll be getting credits on the GCI platform right?

**Comment by oorjitchowdhary** [comment]
Which is the task which is to be claimed here

**Comment by oorjitchowdhary** [comment]
@jywarren @rishabh570

**Comment by Rishabh570** [comment]
@oorjitchowdhary You can just create separate issues based on ideas suggested in the issue description and mention this issue if eligible you'll get credits for that...

**Comment by jywarren** [comment]
Hi, creating a task now! https://codein.withgoogle.com/dashboard/tasks/5897760814399488/

**Comment by JonathanXu1** [comment]
Hey, I just claimed this task. Would you like me to make a separate issue for each bullet point?

**Comment by jywarren** [comment]
Sure, if you're able to add something significant to help guide people in
each issue. See, it wouldn't be much better than a list if it were just the
same item. Thanks!!!!

**Comment by JonathanXu1** [comment]
Here's an example: https://github.com/publiclab/image-sequencer/issues/498

Would you like it like this?

**Comment by JonathanXu1** [comment]
Another issue: https://github.com/publiclab/image-sequencer/issues/499
For this GCI task to be completed, do I need to make issues for each of the bullet points?

**Comment by jywarren** [comment]
nope, just one or two is enough! Thank you!

**Comment by JonathanXu1** [comment]
Alright, three's the charm :)
Submitted the task!

**Comment by jywarren** [comment]
amazing! very well done.

**Comment by gauravano** [comment]
Hi @oorjitchowdhary, all issues looks good, please append the issue number in the checklist so that no-one else opens the same issue. Thanks!

**Comment by oorjitchowdhary** [comment]
I have mentioned this issue in all of them..

**Comment by oorjitchowdhary** [comment]
#492 #493 #494 #495 #496 all are opened up by me..

**Comment by gauravano** [comment]
![screenshot from 2018-11-27 18-34-10](https://user-images.githubusercontent.com/20878070/49083591-127ad200-f273-11e8-9244-652a78a3716b.png)

Mention after the above tasks in issue body.

**Comment by oorjitchowdhary** [comment]
> Looking for help with these! They could also make good GCI issues @publiclab/mentors !
> 
> * [x]  change "Save" module button to "Apply"
> * [ ]  change description text above quick-add buttons so it stays as "apply a new step" instead of getting replaced by the last applied module's description (needs gif to demonstrate issue)
> * [ ]  make Image Sequencer header reload the page with no steps
> * [ ]  add a "start a new sequence" button somewhere in header
> * [ ]  add "take a photo" as alternative to "Choose file" in initial load image step
> * [ ]  move "Download PNG" box down onto same line as "Save Sequence" leaving Add Step box full-width
> * [ ]  show spinner icon while gif is generating
> * [ ]  Fix alignment of Add Step button and dropdown next to it
> * [ ]  add toggle-able "collapse" button next to step name (like "load-image") to hide image, description (leaving just the line and the title)
> * [ ]  add Resize module to list of quick buttons, as in [this image](https://user-images.githubusercontent.com/24359/48908983-f5d93700-ee39-11e8-88b3-58ea81efe467.png)
> 
> ### Sliders
> * [ ]  make sliders (for range inputs) touch-draggable (using a library) - like brightness
> * [ ]  set brightness default to not be totally white
> * [ ]  set contrast default to something useful
> * [ ]  set contrast to range slider UI
> 
> ### Save sequence
> * [ ]  have "save sequence" also show a message showing where to find the saved sequence
> * [ ]  have "save sequence" link to docs showing how to turn a sequence into a meta module
> * [ ]  have "save sequence" link clarify that it will only be available in this browser

You mean to checklist here.. I'm actually unable to edit that

**Comment by oorjitchowdhary** [comment]
Hi @codesarthak.. I understand you are trying to complete this gci task.. But I've already opened some issues which you opened up too..

**Comment by oorjitchowdhary** [comment]
#512 is the same as #496 opened by me

**Comment by oorjitchowdhary** [comment]
#512 is the same as #494 opened by me
#513 is the same as #496 
Pls open up different issues as duplication of issues leads to a lot of confusion... 
Thanks 😃

**Comment by CodeSarthak** [comment]
Oh @oorjitchowdhary , really very sorry. Actually, I got confused because they were not checked in the checklist. Will pick up some others.  : )

**Comment by jywarren** [comment]
Wow I think these are all done!!! Amazing work, folks!
