### ISSUE TITLE
White balance module

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#488]
I think this could be done with the OpenCV.js module which is under development in #237 -- but for what it's worth, it'd be great to have a white balance module:

https://stackoverflow.com/questions/51372779/color-balance-formula-adding-too-much-white

could help!

We'd love help with this one!

**Comment by Divy123** [comment]
This issue seems interesting to me. I would like to work on it.

**Comment by Divy123** [comment]
I am already working on this issue. Please look into some other issue.

**Comment by VibhorCodecianGupta** [comment]
@Divy123 Apologies, Since there was no progress or updates here, I assumed it unclaimed. Will take care from now on. Let's leave it to the reviewer's discretion 😅

**Comment by Divy123** [comment]
No problem @VibhorCodecianGupta :smile: .

**Comment by jywarren** [comment]
Ah, no problem - perhaps you could collaborate? One thing I'm interested in
is if we could have a "click on a grey area" type interface to choose what
is the white point from a given image by clicking on the image. What do you
think?

**Comment by VibhorCodecianGupta** [comment]
@jywarren Didn't really get the deliverable. Do you mean something like clicking on any point in the given picture, and that returns the nearest white pixel? I'm sure I'm getting this wrong. Is there any example of what you desire?

**Comment by jywarren** [comment]
Ah, no, i just mean that a common way to determine a white balance is to
click on the image on a pixel which you visually deem to be "neutral"
colored, and to use that pixel to calculate a white balance correction.
Does that make sense?

**Comment by Divy123** [comment]
Sure @jywarren . @VibhorCodecianGupta can we collaborate on this?

**Comment by VibhorCodecianGupta** [comment]
@jywarren right, I get you. So what the PR #585 does, is taking input in the form of picture temperature, and accordingly, transform the picture. White balance/colour balance as it is called is applied on the basis of that temperature.
So the addition that you made can be made by accessing the pixel value clicked, and then find the correction based on that. I will have to search for a good algorithm for this purpose, will get on with it. Also, there is an internet issue at my location, I'll post the references I used in making my PR too.

**Comment by jywarren** [comment]
That sounds great. If you think #585 is ready to go we can merge that and
continue work on the follow-up, or we could merge both together?

**Comment by VibhorCodecianGupta** [comment]
@jywarren it's on your discretion. However, I'd say merging #585 would be a good idea, Pushing too many changes at once is always less preferred, I could work on the pixel-based white balance as a follow-up task. Thoughts?

**Comment by VibhorCodecianGupta** [comment]
@jywarren that's your discretion, but I'd suggest breaking it into subproblems. Since #585 is in itself complete, it could be merged, and the above-suggested idea can be implemented as a follow-up. Looking for algorithms now. Cheers!

**Comment by Harshithpabbati** [comment]
Was anyone is working in making the actual white balance or can i give it a shot??

**Comment by HarshKhandeparkar** [comment]
Go ahead!

**Comment by VibhorCodecianGupta** [comment]
@Harshithpabbati I'm working on this 😅 give me some time, I think I can come up with the module

**Comment by Harshithpabbati** [comment]
Sure carry on with it.

**Comment by jywarren** [comment]
I just pinged Nirav on this but this will also be really helpful to this
module -- ability to click to select a point (to choose the "neutral" point
for white balance): https://github.com/publiclab/image-sequencer/issues/796

Thanks all!
