### ISSUE TITLE
Change "Save" to "Apply" on save button in add step UI

### ISSUE THREAD

**Issue by Rishabh570** [publiclab/image-sequencer#489]
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

## First Timers Only
Hi, this is a first-timers-only issue. This means this has been worked to make it more legible to folks who either haven't contributed to our codebase before or even folks who haven't contributed to open source before.

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!

## The Problem

**Save** button on a new step should have text on it saying: **Apply** instead of **Save**

Currently, it looks like,

![screenshot from 2018-11-22 20-59-40](https://user-images.githubusercontent.com/25483260/48912398-8300a800-ee9b-11e8-84e0-8f86f07ca9b3.png)

## The Solution

[This](https://github.com/publiclab/image-sequencer/blob/main/examples/lib/defaultHtmlStepUi.js#L133) line in `examples/lib/defaultHtmlStepUi.js` would be updated in order to do the required changes.

``` DIFF
- "<p><button class='btn btn-default btn-save' disabled = 'true' >Save</button><span> Press save to see changes</span></p>"
+ "<p><button class='btn btn-default btn-save' disabled = 'true' >Apply</button><span> Press save to see changes</span></p>"
```
It would look like this,

![screenshot from 2018-11-22 21-05-26](https://user-images.githubusercontent.com/25483260/48912216-0f5e9b00-ee9b-11e8-9d55-ba6777e44812.png)

**Instance Count = 1**

**Comment by rajcrk** [comment]
I would like to work on this issue.
Getting on it right now.

**Comment by HarshKhandeparkar** [comment]
I feel like the text besides it should also change to "press apply to see changes" or simply "press to see changes"

**Comment by jywarren** [comment]
Agreed!

**Comment by Rishabh570** [comment]
@HarshKhandeparkar Yess...

**Comment by oorjitchowdhary** [comment]
Is anyone working on this... I'd like to work on this issue

**Comment by Paarmita** [comment]
@oorjitchowdhary I guess @rajcrk is working on this. You can see other first time issues.

**Comment by oorjitchowdhary** [comment]
@rajcrk are you still working on this? if not, @publiclab/mentors can I take this up?

**Comment by aashna27** [comment]
Since this is a first timer issue I would suggest you to move on with some other as you have already helped solve many other issues and let it be for someone new. :-)
@oorjitchowdhary

**Comment by oorjitchowdhary** [comment]
@aashna27 Okay sure.. 😃

**Comment by tech4GT** [comment]
I think this was solved, closing this now! Thanks everyone! :smile:
