### ISSUE TITLE
image degredation over repeated steps (invert)

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#49]
Aha, very interesting! If you repeat clicking too long, the image degrades; we can address this in a follow-up issue but it's really cool to see, actually! Must be decimal/integer issues. 

![index 2](https://user-images.githubusercontent.com/24359/27985934-d757b8c6-63c3-11e7-816b-ed3c748dc9ca.jpg)

Kind of fascinating actually I wonder if it's conversing values from decimal to integer and back over and over. We could actually test for this, to be honest, by running the invert 20 times. 

As to a solution, I think there are non drifting decimal math implementations we could use from other libraries.

**Comment by ccpandhare** [comment]
Jeff, I can assure you that's not the issue.
But what you said will definitely be beneficial sometime in the future! Thanks!

I just tried this:
```js
var r = savePixels(pixels, options.format, {quality: 100});
...
```
That is, explicitly asking save-pixels to save in high quality.
After that, there was no deterioration as we can see above at all.

But that created a new problem. The build failed.
One unit test failed.
![Screenshot of failed test](https://preview.ibb.co/n9hSvF/Screen_Shot_at.jpg)

As you can see in the screenshot, the two values which tape says are "not equal" are actually equal.

I even tried equating them in JS. Still unequal. I assure you, they are equal. Because of this, I had to remove the `{quality: 100}` parameter. And hence we are facing that issue.

**Comment by ccpandhare** [comment]
Why do you think the reason could be?
For two strings to be unequal but seem equal when printed?
Different encoding?
Or What could it possibly be? I am just out of thoughts :/

**Comment by jywarren** [comment]
Whoa. Can you paste in the two strings here? What if you convert both to
string with parseString, just in case?

**Comment by ccpandhare** [comment]
Sorry, this somehow skipped me. Thanks for your suggestion about the `String()` but that didnt work. Based on StackOverflow answers, I have tried `string.trim()`, that didn't work either.

Also, this works:
`string1.substring(0,string1.length-25) == string2.substring(0,string2.length-25) //true`

If 25 is replaced with any number less than 25, the above returns false.

These are the two strings:
(When I compare them on http://www.textdiff.com/ It says that there's nothing common in the two strings! It also shows similar results -- the '25' thing)

data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAf/AABEIABAAEAMBEQACEQEDEQH/xAGiAAABBQEBAQEBAQAAAAAAAAAAAQIDBAUGBwgJCgsQAAIBAwMCBAMFBQQEAAABfQECAwAEEQUSITFBBhNRYQcicRQygZGhCCNCscEVUtHwJDNicoIJChYXGBkaJSYnKCkqNDU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6g4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2drh4uPk5ebn6Onq8fLz9PX29/j5+gEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoLEQACAQIEBAMEBwUEBAABAncAAQIDEQQFITEGEkFRB2FxEyIygQgUQpGhscEJIzNS8BVictEKFiQ04SXxFxgZGiYnKCkqNTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqCg4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2dri4+Tl5ufo6ery8/T19vf4+fr/2gAMAwEAAhEDEQA/APxnr/Kc/wC/gKACgAoA/wD/2Q==


data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAf/AABEIABAAEAMBEQACEQEDEQH/xAGiAAABBQEBAQEBAQAAAAAAAAAAAQIDBAUGBwgJCgsQAAIBAwMCBAMFBQQEAAABfQECAwAEEQUSITFBBhNRYQcicRQygZGhCCNCscEVUtHwJDNicoIJChYXGBkaJSYnKCkqNDU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6g4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2drh4uPk5ebn6Onq8fLz9PX29/j5+gEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoLEQACAQIEBAMEBwUEBAABAncAAQIDEQQFITEGEkFRB2FxEyIygQgUQpGhscEJIzNS8BVictEKFiQ04SXxFxgZGiYnKCkqNTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqCg4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2dri4+Tl5ufo6ery8/T19vf4+fr/2gAMAwEAAhEDEQA/APxfr/Kc/wC/gKACgAoA/wD/2Q==

**Comment by jywarren** [comment]
Aha! I looked really carefully -- the first string ends with:

`APxfr/Kc/wC/gKACgAoA/wD/2Q==`

The second ends with:

`APxnr/Kc/wC/gKACgAoA/wD/2Q==`

Notice: `APxfr` vs. `APxnr` -- !!

just one character off.

**Comment by jywarren** [comment]
If you re-encode again, does it stay `APxfr`?

**Comment by ccpandhare** [comment]
Wow those are exceptionally great observation skills there, I must say!

**Comment by ccpandhare** [comment]
No, re-encoding doesn't change anything, I tried.
I think the method I am using for testing this isn't ideal.
I doubly-invert a DataURL and equate two DataURL strings.

I should probably use a different sort of comparison. Like one with a threshold.
I don't know why doubly inverting a DataURL would give a slightly different result when generated in High Quality. Do you know any articles which would help me identify which part of a DataURL/Image Binary contain what information

**Comment by jywarren** [comment]
I agree we should try a different way of diffing. Look at the resources in
the README, I found some that work on images and return a percentage
difference.

**Comment by ccpandhare** [comment]
Thanks for the update! I will do that.

**Comment by ccpandhare** [comment]
The issue that we are facing, of the unequal DataURLs, could it be the result of the lossy JPEG compression?

**Comment by ccpandhare** [comment]
Turns out I am right! I converted that image to PNG and now it works! What should be done now? I still think that comparing with a threshold should should be implemented.

**Comment by jywarren** [comment]
Sure, open up a new issue for image diff based testing. Great!

**Comment by ccpandhare** [comment]
The module you mentioned `npm:image-diff` is pretty heavy. I am not sure we should use it.
Maybe I can write a lightweight library for that myself.

**Comment by jywarren** [comment]
There were a few others, no? And we don't need to include it in the library itself; it could just be included in the test suite and under `devDependencies`. 

https://github.com/publiclab/image-sequencer/blob/master/CONTRIBUTING.md#module-candidates -- had several diff modules. I'd like to open this issue and take slow steps in this direction; not urgent!

**Comment by jywarren** [comment]
oops, ok -- #83!
