### ISSUE TITLE
Correct default view for brightness module

### ISSUE THREAD

**Issue by aashna27** [publiclab/image-sequencer#491]
### Problem

The brightness module when selected displays a white screen in the image area instead of the image from the previous step or the selected image.
![image](https://user-images.githubusercontent.com/26546120/48921209-24035900-eec4-11e8-8a27-871782e228ac.png)

However the default view should be something like this

![image](https://user-images.githubusercontent.com/26546120/48976349-e3663400-f0ab-11e8-885e-19fe7ab52050.png)

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by oorjitchowdhary** [comment]
I'd like to work on this.. Can I please get help regarding the code links for the main image sequencer page and the brightness module .. Thanks

**Comment by oorjitchowdhary** [comment]
Our task here is to show the image in the brightness box right?

**Comment by aashna27** [comment]
http://sequencer.publiclab.org/examples/#steps= 

http://sequencer.publiclab.org/examples/#steps=brightness{brightness:100} 
Go ahead!!

**Comment by aashna27** [comment]
yes basically the image coming from the previous step should be visible when brightness module is added.

**Comment by oorjitchowdhary** [comment]
> yes basically the image coming from the previous step should be visible when brightness module is added.

Ok

**Comment by oorjitchowdhary** [comment]
> http://sequencer.publiclab.org/examples/#steps=
> 
> [http://sequencer.publiclab.org/examples/#steps=brightness{brightness:100}](http://sequencer.publiclab.org/examples/#steps=brightness%7Bbrightness:100%7D)
> Go ahead!!

Sorry if I wasn't clear.. I meant to ask for the code files which would be required here... I'm not so familiar with this repo...

**Comment by aashna27** [comment]
> > http://sequencer.publiclab.org/examples/#steps=
> > [http://sequencer.publiclab.org/examples/#steps=brightness{brightness:100}](http://sequencer.publiclab.org/examples/#steps=brightness%7Bbrightness:100%7D)
> > Go ahead!!
> 
> Sorry if I wasn't clear.. I meant to ask for the code files which would be required here... I'm not so familiar with this repo...

https://github.com/publiclab/image-sequencer/tree/main/src/modules/Brightness 
I hope this works for you. This is basically the folder of this module.

**Comment by oorjitchowdhary** [comment]
@aashna27 Yes, Thanks

**Comment by CodeSarthak** [comment]
Yes, @oorjitchowdhary , there are two instances of this on GCI. Should be removed asap to avoid confusion.

**Comment by JonathanXu1** [comment]
Yep there are still the two tasks available on the dashboard. @oorjitchowdhary are you still working on it?

**Comment by oorjitchowdhary** [comment]
@jonathanxu1 yes I'm working on it

**Comment by JonathanXu1** [comment]
@oorjitchowdhary you also seem to be working on issue #487 . Keep in mind that according to GCI, you can only work on one issue at a time

**Comment by oorjitchowdhary** [comment]
@JonathanXu1 Yeah I know.. my #487 got approved so I'll do this now...

**Comment by oorjitchowdhary** [comment]
![oorjitrunningoraclevmvir](https://user-images.githubusercontent.com/39333058/49096601-deaea500-f290-11e8-8bad-62a7b94f0a83.gif)
@aashna27 I'm stuck here.. Through my changes in the code, it takes the `load-image` as the image in brightness but somehow doesn't show the file uphead... It is only visible after a change in the `brightness` .. Check out the gif which explains this..

**Comment by aashna27** [comment]
> ![oorjitrunningoraclevmvir](https://user-images.githubusercontent.com/39333058/49096601-deaea500-f290-11e8-8bad-62a7b94f0a83.gif)
> @aashna27 I'm stuck here.. Through my changes in the code, it takes the `load-image` as the image in brightness but somehow doesn't show the file uphead... It is only visible after a change in the `brightness` .. Check out the gif which explains this..

I am busy with a submission today so if anyone from @publiclab/mentors could have a look till then.

**Comment by oorjitchowdhary** [comment]
Yeah sure


On Nov 27, 2018, at 10:31 PM, aashna27 <notifications@github.com<mailto:notifications@github.com>> wrote:


[oorjitrunningoraclevmvir]<https://user-images.githubusercontent.com/39333058/49096601-deaea500-f290-11e8-8bad-62a7b94f0a83.gif>
@aashna27<https://github.com/aashna27> I'm stuck here.. Through my changes in the code, it takes the load-image as the image in brightness but somehow doesn't show the file uphead... It is only visible after a change in the brightness .. Check out the gif which explains this..

I am busy with a submission today so if anyone from @publiclab/mentors<https://github.com/orgs/publiclab/teams/mentors> could have a look till then.

**Comment by oorjitchowdhary** [comment]
Okay sure

**Comment by oorjitchowdhary** [comment]
@aashna27 Could you help me..

**Comment by aashna27** [comment]
> @aashna27 Could you help me..

Yeah sure. I ll look for the bug.

**Comment by oorjitchowdhary** [comment]
`https://github.com/publiclab/image-sequencer/blob/main/src/modules/Convolution/Module.js`
`https://github.com/publiclab/image-sequencer/blob/main/src/modules/Brightness/Module.js`
There is no difference between the modules of `brightness` and `convolution` apart from the different functions.. But still we can see the picture by using `convolution` whereas it doesn't show up in `brightness`

**Comment by oorjitchowdhary** [comment]
I'm unable to understand this..

**Comment by oorjitchowdhary** [comment]
@aashna27 @Paarmita

**Comment by oorjitchowdhary** [comment]
Anyone pls help.. I have my deadline today

**Comment by oorjitchowdhary** [comment]
@tech4GT with no changes in the respective code modules.. The brightness module doesn't show the picture whereas the contrast, convolution.. All show the picture from the previous step...

**Comment by tech4GT** [comment]
I guess that’s because the default value is set to 0 no?

**Comment by oorjitchowdhary** [comment]
@tech4GT I'm unable to change it through the brightness module

**Comment by oorjitchowdhary** [comment]
The default .. where do I change it?

**Comment by jywarren** [comment]
It should be in the info.json file inside /src/modules/Brightness/, I
believe!

**Comment by oorjitchowdhary** [comment]
> It should be in the info.json file inside /src/modules/Brightness/, I believe!


If I edit it there, nothing happens.. It still shows brightness=100 in the default

**Comment by jywarren** [comment]
Did you run `grunt build` after making the change? That will compile
everything in /src/ into the final /dist/ directory.

**Comment by oorjitchowdhary** [comment]
Oh.. lemme check that out

**Comment by oorjitchowdhary** [comment]
![screenshot 39](https://user-images.githubusercontent.com/39333058/49237825-164e5600-f425-11e8-9fd4-e9cc7c47ffc9.png)
Pls help me with this...

**Comment by jywarren** [comment]
ah, have you installed all modules with `npm install`? It looks like it's
missing a dependency. Great work sticking with this, you'll get it soon,
i'm sure!

**Comment by tech4GT** [comment]
You’ll have to change it in Module.js file of the brightness module

**Comment by tech4GT** [comment]
https://github.com/publiclab/image-sequencer/blob/ddf4bd0dae5bb40e8144b2a10979e59dc12752ed/src/modules/Channel/Module.js#L6
This is how you can add that default value.
Something like
```
Options.brightness = options.brightness || 0
```

**Comment by oorjitchowdhary** [comment]
> This is how you can add that default value.
> Something like
> ```
> Options.brightness = options.brightness || 0
> ```

Yes I figured that out.. That doesn't work out too..

**Comment by oorjitchowdhary** [comment]
![oorjitrunningoraclevmvir 1](https://user-images.githubusercontent.com/39333058/49267426-77574780-f480-11e8-8bf1-90c115b93e96.gif)
Brightness module takes input as blank white screen on default...

**Comment by oorjitchowdhary** [comment]
![oorjitrunningoraclevmvir](https://user-images.githubusercontent.com/39333058/49267445-948c1600-f480-11e8-9da7-9d8b1cf9f349.gif)
The output of previous step is only taken as `input` when you change the brightness through the bar..

**Comment by oorjitchowdhary** [comment]
> ![oorjitrunningoraclevmvir](https://user-images.githubusercontent.com/39333058/49267445-948c1600-f480-11e8-9da7-9d8b1cf9f349.gif)
> The output of previous step is only taken as `input` when you change the brightness through the bar..

So when you download this one, it downloads the edited picture

**Comment by tech4GT** [comment]
Hmm I would have too look through this in code then, I’ll see this as soon as I get some time. 🙂

**Comment by oorjitchowdhary** [comment]
So what should I do for my gci task. I have 12 hrs left..

**Comment by tech4GT** [comment]
Oh, sorry I did not know that, I’ll look through this in an hour or two then. Don’t worry we’ll get this done. :)

**Comment by oorjitchowdhary** [comment]
Okay

**Comment by tech4GT** [comment]
@oorjitchowdhary This looks like a browser issue to me, this works fine in my browser!
<img width="375" alt="screen shot 2018-11-21 at 10 50 19 am" src="https://user-images.githubusercontent.com/25617855/49271989-dc696800-f495-11e8-8d8d-d19206359393.png">

**Comment by oorjitchowdhary** [comment]
@tech4GT so the issue is solved in your browser? That is umm.. Surprising 🤔

**Comment by bhavayAnand9** [comment]
Confirmed this issue with chrome, safari.

**Comment by oorjitchowdhary** [comment]
@tech4GT @jywarren @aashna27 If it is a browser issue, then the code is working fine and any changes to it aren't required... Right?
So, I believe, I should submit my task for review 🤔

**Comment by tech4GT** [comment]
I wonder why it works on my computer though?

**Comment by bhavayAnand9** [comment]
If you do a fresh build & run and then add the first step as brightness then only this issue will occur.

**Comment by oorjitchowdhary** [comment]
@bhavayAnand9 So i have to the `rgb values` to 1.5? and add that `console.log`?

**Comment by bhavayAnand9** [comment]
@oorjitchowdhary No, not rgb values but `val` variable which is declared in line 23 in module.js. and this isn't a fix instead just a way to help you figure out what is going wrong and where.

**Comment by oorjitchowdhary** [comment]
Uhh

**Comment by oorjitchowdhary** [comment]
So i remove `(options.brightness)/100.0` and put it as 1.5

**Comment by oorjitchowdhary** [comment]
> So i remove `(options.brightness)/100.0` and put it as 1.5

Not working

**Comment by bhavayAnand9** [comment]
Oh, This is so simple fix.

Explanation: 
`val` value is dependent on `option.brightness` which is a  parameter to `Brightness` function. If you console log `options.brightness` you'll find it undefined, which I don't know why that is.

so adding this line `options.brightness = options.brightness || 100;` will set the `option.brightness ` value to 100 only if it's undefined.

@oorjitchowdhary Here's what you need  to do. Just add these two lines of code in starting of 'changePixel' function.

`            //If options.brightness is undefined, set it to 100 by default`
`            options.brightness = options.brightness || 100;`

hope this helps!

**Comment by oorjitchowdhary** [comment]
> > This is how you can add that default value.
> > Something like
> > ```
> > Options.brightness = options.brightness || 0
> > ```
> 
> Yes I figured that out.. That doesn't work out too..

Wow.. I had tried that long ago.. but placed it in above the `function changePixels`

**Comment by jywarren** [comment]
oh wow, so were you all able to figure this out? That's awesome!

**Comment by oorjitchowdhary** [comment]
@jywarren yes.. TEAMWORK = OPEN SOURCE = 💯🔥

**Comment by oorjitchowdhary** [comment]
https://codein.withgoogle.com/tasks/6322686255955968/?sp-organization=6519545549291520&sp-is_beginner=False

Another thing.. There is duplicate of this same task.. It should be removed asap

**Comment by jywarren** [comment]
Great! did this. 🙌 👍 💯
