### ISSUE TITLE
Move 'Download PNG' box on the same line as 'Save Sequence'

### ISSUE THREAD

**Issue by oorjitchowdhary** [publiclab/image-sequencer#493]
### Please describe the problem (or idea)
![screenshot 35](https://user-images.githubusercontent.com/39333058/48978378-c7c15480-f0d0-11e8-90c8-ec88d962f8f9.png)

We can move the **Download PNG** and **View GIF** buttons onto the same line as the **Save Sequence** button for better user interface.

## Solution
This would look better on the site.
![quick buttons bar](https://user-images.githubusercontent.com/39333058/48978342-52558400-f0d0-11e8-9b59-80f286a2944b.jpg)

### Please show us where to look

https://sequencer.publiclab.org

### What's your PublicLab.org username?
oorjit_chowdhary

### Browser, version, and operating system
Chrome, Windows 10

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by HarshKhandeparkar** [comment]
Can I work on this?

**Comment by oorjitchowdhary** [comment]
Sounds good!

**Comment by HarshKhandeparkar** [comment]
@tech4GT I didn't get what you said. Could you please elaborate?

**Comment by oorjitchowdhary** [comment]
He meant to say that the Download button shouldn't be moved as it downloads the image of the particular step... 
But we can move the View GIF button as it shows the whole process... 

By doing this, we won't disrupt the layout

**Comment by tech4GT** [comment]
I mean you can shift the button `View gif` to the side of `Save sequence` and maybe give them the same color too. The download button is specific to the step so it is better suited on the side only.

**Comment by HarshKhandeparkar** [comment]
OK Got It!

**Comment by HarshKhandeparkar** [comment]
I'm facing some issue. The download PNG button adds a crop step now and the step doesn't even work.

![png-btn-img-seq](https://user-images.githubusercontent.com/34770591/50304274-8a749a80-04b5-11e9-881b-e7fbb56db5bb.gif)

**Comment by HarshKhandeparkar** [comment]
The previous black step was also created the same way. The only files I've touched are index.html and demo.css. @publiclab/reviewers please help.

**Comment by HarshKhandeparkar** [comment]
update: The step works

![crop-works](https://user-images.githubusercontent.com/34770591/50304955-6f0a8f00-04b7-11e9-805c-673a9c6d5c74.gif)

**Comment by HarshKhandeparkar** [comment]
Should I open a PR or can we discuss this issue here?

**Comment by tech4GT** [comment]
Sure go ahead you can open a pull request! :)
