### ISSUE TITLE
Add 'Take a photo' as another option for initial load image step

### ISSUE THREAD

**Issue by oorjitchowdhary** [publiclab/image-sequencer#494]
### Please describe the problem (or idea)
We can add another button -  **Take a photo** as an alternative to the **Choose file** in the initial load image step.

> What did you expect to see that you didn't?

![screenshot 36](https://user-images.githubusercontent.com/39333058/48978530-c002af80-f0d2-11e8-9de3-fe68a7ef36a2.jpg)
A **'take a photo'** button will basically open the camera of the user device, click a picture 📸  and then load it in the initial image load step.
### Please show us where to look

https://sequencer.publiclab.org

### What's your PublicLab.org username?
oorjit_chowdhary
### Browser, version, and operating system
Chrome, Windows 10
****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by aashna27** [comment]
I am working on this.
