### ISSUE TITLE
Description text above quick buttons bar doesn't reset after adding a new module

### ISSUE THREAD

**Issue by oorjitchowdhary** [publiclab/image-sequencer#495]
### Please describe the problem (or idea)
When we choose a new `module` from the drop-down, the description text above the quick buttons bar changes but after adding that `module` it doesn't revert back to the default text.

> What did you expect to see that you didn't?

![imagesequencergooglechrome](https://user-images.githubusercontent.com/39333058/48978736-2a691f00-f0d6-11e8-8949-84a5a3870751.gif)

### Please show us where to look

https://sequencer.publiclab.org
### What's your PublicLab.org username?
oorjit_chowdhary
### Browser, version, and operating system
Chrome, Windows 10

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by VibhorCodecianGupta** [comment]
@tech4GT done at #574
