### ISSUE TITLE
Add a 'Start a new sequence' button

### ISSUE THREAD

**Issue by oorjitchowdhary** [publiclab/image-sequencer#496]
### Please describe the problem (or idea)
Add a `start a new sequence` button in the header which when clicked, opens a new page 📄  for editing a new picture. The output of this button could either be loaded on the same tab or be opened in a new tab. 
> What did you expect to see that you didn't?

![screenshot 37](https://user-images.githubusercontent.com/39333058/48978876-99477780-f0d8-11e8-9414-92c615298fe5.jpg)

### Please show us where to look

https://sequencer.publiclab.org

### What's your PublicLab.org username?
oorjit_chowdhary
### Browser, version, and operating system
Chrome, Windows 10

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by jywarren** [comment]
This is great, and perhaps a first step could be some brainstorming about
what the UI could look like!

**Comment by oorjitchowdhary** [comment]
@jywarren @gauravano I think I'd like to work on this after I complete #491

**Comment by jywarren** [comment]
that'd be great! I think we may want to do some sketching -- consider using
a mockup program or a document like this one:

https://docs.google.com/presentation/d/1TCZoTfuhamRVrUak8aDgqJAwSgyhRtZg2Pgacl2_4zc/edit?usp=slides_home&ths=true

to experiment a bit with how it ought to look!
