### ISSUE TITLE
Add toggle button next to step name

### ISSUE THREAD

**Issue by JonathanXu1** [publiclab/image-sequencer#498]
This issue is a sub-issue of #487 , which is to be broken down into smaller issues.

So in the image-sequencer, each step has a config panel on the left, as shown below:
![image](https://user-images.githubusercontent.com/22998430/49045019-9a8ea800-f19d-11e8-8aad-c3f1bcbbae92.png)

What we want to do is to add a toggle-able "collapse" button next to step name (like "load-image") to hide image, description (leaving just the line and the title), like shown in the Photoshop rendering below.

![collapse](https://user-images.githubusercontent.com/22998430/49045407-e8f07680-f19e-11e8-92bd-3b9df9011ce0.png)

### Please show us where to look

http://sequencer.publiclab.org/examples/#steps=

### What's your PublicLab.org username?

JonathanXu1

### Browser, version, and operating system

Firefox63, Windows 10

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by kevinzluo** [comment]
I'd like to work on this.

**Comment by JonathanXu1** [comment]
@jywarren are all the sub tasks now available for codein?

**Comment by kevinzluo** [comment]
I think only the ones tagged with `gci-candidate` are available. I just did this task because I saw it last night and thought I could help out (though if anyone wants to give me  credit I'm not complaining :grin:). I am still waiting for [this task](https://github.com/publiclab/leaflet-environmental-layers/issues/73) to be added to the dashboard.

**Comment by jywarren** [comment]
We can add any subtasks, we'd love to!
