### ISSUE TITLE
Add resize module to list of quick buttons

### ISSUE THREAD

**Issue by JonathanXu1** [publiclab/image-sequencer#499]
This issue is a sub-issue of #487 , which is to be broken down into smaller issues.

In the image-sequencer, there are a list of quick-buttons so the user can add commonly-used layers quickly:
![image](https://user-images.githubusercontent.com/22998430/49045726-d460ae00-f19f-11e8-854f-530eb752ba31.png)

What we want to do is to add another quick-add button for the resize functionality. Here's the todo for this task:

- [ ] Find a suitable icon on font-awesome and link it here **make sure it's from the v4.5 icon set!**
- [ ] Add the icon in the appropriate button style in examples/index.html.
![image](https://user-images.githubusercontent.com/22998430/49046043-da0ac380-f1a0-11e8-8325-c07bcfbeea15.png)
- [ ] Keep in mind the proper syntax for data-value, which can be checked by navigating to the proper component in src/modules. It is lowercase

### Please show us where to look

http://sequencer.publiclab.org/examples/#steps=

### What's your PublicLab.org username?

JonathanXu1

### Browser, version, and operating system

Firefox63, Windows 10

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by jywarren** [comment]
great work!!

**Comment by Harshithpabbati** [comment]
Was this a open issue?? Can i work on it??

**Comment by HarshKhandeparkar** [comment]
Go ahead @Harshithpabbati

**Comment by Harshithpabbati** [comment]
![resize](https://user-images.githubusercontent.com/43822585/52900275-e93a6400-3219-11e9-9f77-dfac1eb30651.png)
@HarshKhandeparkar I am almost done with it.But i cant get the image on the resize module.Can you help me out??

**Comment by HarshKhandeparkar** [comment]
@Hashithpabbati you will have to use some fontawesome icon. Choose an appropriate icon from [here](https://fontawesome.com/v4.7.0/icons/)

**Comment by HarshKhandeparkar** [comment]
Oh wait, the image you provided didn't load for me. Sorry, I though you were asking something else. Can you please open a pr or give me a link to your branch? Btw you have to change the `examples/lib/intermediateHtmlStepUi.js` file too. @Harshithpabbati

**Comment by Harshithpabbati** [comment]
> Oh wait, the image you provided didn't load for me. Sorry, I though you were asking something else. Can you please open a pr or give me a link to your branch? Btw you have to change the `examples/lib/intermediateHtmlStepUi.js` file too. @Harshithpabbati

Yeah i made the change in the intermediateHtmlStepUi.js

**Comment by HarshKhandeparkar** [comment]
Are you going to open a PR? Or atleast provide me a link to the branch so that I can help you in troubleshooting.

**Comment by Harshithpabbati** [comment]
fine i will open the pr jst wait a min
