### ISSUE TITLE
image cropping module

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#5]
A module which crops images according to passed width and height values.

**Comment by ccpandhare** [comment]
What if we made it interactive?
Accepting width and height params from users is impractical, isn't it?

**Comment by jywarren** [comment]
I don't think so -- it could be specified in the setup() stage, on the
commandline, perhaps passed into addStep(), or set via the HTML user
interface, as you suggest.

**Comment by ccpandhare** [comment]
I have done this. Will send a PR soon.

**Comment by ccpandhare** [comment]
I have done this. Will send a PR soon.

**Comment by ccpandhare** [comment]
Added. PR #8

**Comment by ccpandhare** [comment]
I haven't implemented a demo for the module yet.
So on the demo page (not in the module) cropping occurs at default values (0,0,50%,50%).
Will add a method to accept input from the user soon.
