### ISSUE TITLE
Make sliders for range values touch-draggable

### ISSUE THREAD

**Issue by JonathanXu1** [publiclab/image-sequencer#500]
This issue is a sub-issue of #487 , which is to be broken down into smaller issues.

As you can see in the link below, the image sequencer can take range values for many adjustments. What we would need to do is to make sliders that are touch-draggable  (similar to the slider for brightness) in steps such as contrast (below brightness). 

Since this page uses the Bootstrap library, I'd highly recommend you check out https://seiyria.com/bootstrap-slider/ to build your sliders with bootstrap.

TODO:

- [ ] Add touch-draggable slider for each range input
- [ ] Ensure all sliders are stylistically uniform

### Please show us where to look

http://sequencer.publiclab.org/examples/#steps=brightness{brightness:100},contrast{contrast:70}
![image](https://user-images.githubusercontent.com/22998430/49046420-14289500-f1a2-11e8-9d74-c7874c6b08a2.png)

### What's your PublicLab.org username?

JonathanXu1

### Browser, version, and operating system

Firefox63, Windows 10

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by aashna27** [comment]
would work on this.

**Comment by Divy123** [comment]
Can I please work on this issue?

**Comment by aashna27** [comment]
Actually I was working on this.

**Comment by tech4GT** [comment]
@aashna27 @Divy123 Maybe you guys can collaborate on this one! Aashna can you drop a link to the branch you are working on? Thanks! :)

**Comment by HarshKhandeparkar** [comment]
This is working right now. Closing this. Can reopen if needed.
