### ISSUE TITLE
Documentation of MODULES is incomplete

### ISSUE THREAD

**Issue by oorjitchowdhary** [publiclab/image-sequencer#506]
### Please describe the problem (or idea)
MODULES.md is complete.
It has information only about 3 modules which are:-
* Crop Module
* FisheyeGI
* Colormap

We can add information about the other modules as well so it is a complete file.
Also, when someone adds a new module, he/she could also add info about it here.

This could be a good **documentation** issue for newcomers or maybe frequent contributors too.
@publiclab/mentors what say? 😄 
### Please show us where to look
https://github.com/publiclab/image-sequencer/blob/main/docs/MODULES.md

### What's your PublicLab.org username?
oorjit_chowdhary
### Browser, version, and operating system
Chrome, Windows 10
****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by oorjitchowdhary** [comment]
@jywarren @aashna27 @Paarmita @Rishabh570

**Comment by jywarren** [comment]
this would be good but I wonder if documentation may focus on the info.json
files of each module. Would it be possible to add more documentation there,
rather than compiled into one place? Or perhaps there should be a short
documentation in the info.json (and the description shown on the demo) but
it could provide a link to the MODULES.md file on the web, to read a
longer-form documentation there?

**Comment by oorjitchowdhary** [comment]
@jywarren I found the doc with only three modules so I pointed it out.. 
Yes, I think providing a link to MODULES.md would be better.. It'd be a neat and clean way of organizing our repo and describing the modules too

**Comment by Divy123** [comment]
@oorjitchowdhary Can I please take up this issue?

**Comment by tech4GT** [comment]
Sure divy!😁
