### ISSUE TITLE
Brightness slider is not going all the way

### ISSUE THREAD

**Issue by tech4GT** [publiclab/image-sequencer#507]
<img width="1147" alt="screen shot 2018-11-30 at 11 52 27 am" src="https://user-images.githubusercontent.com/25617855/49272119-716c6100-f496-11e8-80e5-28097c7f0197.png">
The brightness slider is not going all the way for full values.

**Comment by oorjitchowdhary** [comment]
Yes @tech4GT.. Even I encountered this problem.. But I was unable to work out the solution.. This must be css error right?
