### ISSUE TITLE
 Fix alignment of Add Step button and dropdown 

### ISSUE THREAD

**Issue by CodeSarthak** [publiclab/image-sequencer#511]
Fix alignment of add step button and the dropdown besides at at http://sequencer.publiclab.org/examples/#steps=

> What happened just before the problem occurred? Or what problem could this idea solve?

It requires simple changes in the html/css code of Image Sequencer repository 

> What did you expect to see that you didn't?

they should be in same line i.e. aligned.

### Please show us where to look

http://sequencer.publiclab.org/examples/#steps=

### Browser, version, and operating system

Windows 10, Google Chrome

****

## Thank you!

**Comment by CodeSarthak** [comment]
![alignment](https://user-images.githubusercontent.com/24937677/49325870-8a951080-f56f-11e8-8385-4316ed69c631.PNG)

**Comment by Rishabh570** [comment]
@CodeSarthak This is resolved in [this](https://github.com/publiclab/image-sequencer/pull/501) I guess...

**Comment by gauravano** [comment]
Closing this issue as already solved as pointed by @Rishabh570. Thanks!
