### ISSUE TITLE
Command for installation is wrong in the readme.

### ISSUE THREAD

**Issue by Rishabh570** [publiclab/image-sequencer#514]
## First Timers Only
Hi, this is a first-timers-only issue. This means this has been worked to make it more legible to folks who either haven't contributed to our codebase before or even folks who haven't contributed to open source before.

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!

### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

The command for installing dependencies is wrong in the `README.md` file, below is the screenshot showing the line to be corrected...

![screenshot from 2018-12-01 22-18-52](https://user-images.githubusercontent.com/25483260/49330637-475e9000-f5b7-11e8-8a3e-30abcec4b6af.png)

> What did you expect to see that you didn't?

Instead of `sudo npm setup` it should be `sudo npm run setup`.

DIFF
```DIFF
- You can set up a local environment to test the UI with `sudo npm setup` followed by `npm start`
+ You can set up a local environment to test the UI with `sudo npm run setup` followed by `npm start` 
```

### Please show us where to look

https://github.com/publiclab/image-sequencer/blob/main/README.md#unix-based-platforms

### What's your PublicLab.org username?

> This can help us diagnose the issue:

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by oorjitchowdhary** [comment]
Can i fix this?

**Comment by oorjitchowdhary** [comment]
I kinda already made a pull request as it was a very small issue.. So should I close it to welcome a newcomer or let it be as is... 😢

**Comment by oorjitchowdhary** [comment]
Ok I closed it down... Any newcomer may solve this. 😄

**Comment by jywarren** [comment]
That's kind of you, Oorjit, thank you!!!

**Comment by lwahlnayar** [comment]
Newcomer here. Has this issue already been taken care of, or can I go for it? Already made a pull request =)

**Comment by oorjitchowdhary** [comment]
No this hasn't been solved.. You can solve this one

**Comment by oorjitchowdhary** [comment]
Wait a min.. I think @momomen solved it

**Comment by oorjitchowdhary** [comment]
@lwahlnayar You can try other `first-timers-only` or `fto-candidate` issues
