### ISSUE TITLE
Show spinner icon while gif is generating

### ISSUE THREAD

**Issue by tsparksh** [publiclab/image-sequencer#516]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### Problem

After clicking on "View GIF" while Gif is generating we can not see spinner icon. 
![image](https://user-images.githubusercontent.com/17945250/49725783-2117af00-fc9f-11e8-9ff1-86f9149fe0ff.png)

### 📋Solution

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [examples/demo.js](https://github.com/publiclab/image-sequencer/blob/main/examples/demo.js) in the image-sequencer repository (press the little pen Icon) and edit the line as shown below.

Below is a "diff" showing in red (and a -) which lines to remove, and in green (and a +) which lines to add:
```DIFF
$('.js-view-as-gif').on('click', function(event) {
    // Prevent user from triggering generation multiple times
    if (isWorkingOnGifGeneration) return;

    isWorkingOnGifGeneration = true;

    var button = event.target;
    button.disabled = true;
+   button.innerHTML='<i class="fa fa-circle-o-notch fa-spin"></i>'

...

          button.disabled = false;
+         button.innerHTML='View GIF';
          isWorkingOnGifGeneration = false;
        }
      });
    }
    catch(e) {
      console.error(e);
      button.disabled = false;
+     button.innerHTML = 'View GIF';
      isWorkingOnGifGeneration = false;

    }
  });
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

**Comment by thesparks** [comment]
#487

**Comment by gauravano** [comment]
@publiclab/image-sequencer-guides please review the task details. Thanks!

**Comment by Rishabh570** [comment]
@thesparks It can be converted into a `fto` issue if you provide the DIFF of required changes...it will help a newcomer :)
Pinging @publiclab/image-sequencer-guides

**Comment by thesparks** [comment]
@Rishabh570, I'm not sure that I completely understood what you mean 

> DIFF of required changes

If I understand correctly, then I need to add this? My English is poor, sorry

> ### Solution
> Add spinner after clicking on "View GIF" while Gif is generating.
> You need to change this file `image-sequencer/examples/index.html`

**Comment by Rishabh570** [comment]
@thesparks What I was saying is you can show what lines to add and what lines to remove in order to achieve what the issue is about...
For example, if you want to change the word `good` to `best` in some file, the DIFF will look like...

![screenshot from 2018-12-05 18-13-19](https://user-images.githubusercontent.com/25483260/49514253-86435d00-f8b9-11e8-8f8b-1874303d591f.png)

which will render this,

```DIFF
- good
+ best
```

**Comment by thesparks** [comment]
@Rishabh570, Thank you! Is it okey now?

**Comment by Rishabh570** [comment]
@thesparks Looks good :tada:

**Comment by thesparks** [comment]
@Rishabh570, so can you accept task now?

**Comment by Rishabh570** [comment]
Oh...Sure :+1:

**Comment by lohitha02** [comment]
I Would like to claim this issue.

**Comment by HarshKhandeparkar** [comment]
Go ahead!
