### ISSUE TITLE
segmented-colormap module

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#52]
we can use PixelManipulation, and copy this directly from Infragram.org (https://infragram.org/sandbox/):

https://github.com/publiclab/infragram-js/blob/master/public/infragram.js#L88-L114

that method returns a new function which maps an incoming value (0-255) to an outgoing value, and can be run on each pixel. 

Colormap functions are based on a nested array:

https://github.com/publiclab/infragram-js/blob/master/public/infragram.js#L212-L214

```js
var c = segmented_colormap([[0, [0, 0, 255], [38, 195, 195]], [0.5, [0, 150, 0], [255, 255, 0]], [0.75, [255, 255, 0], [255, 50, 50]]]);
c(0) // => [0, 0, 255]
```

then we can make lots of different segmented_colormaps! Gradient colormaps too, but later; this is simpler for now. 

![screenshot 2017-07-08 at 2 05 29 pm](https://user-images.githubusercontent.com/24359/27988035-8b9f28ce-63e6-11e7-9389-c8971593e153.png)

Also the Fastie colormap:

```
colormap_fastie = segmented_colormap([[0, [255, 255, 255], [0, 0, 0]], [0.167, [0, 0, 0], [255, 255, 255]], [0.33, [255, 255, 255], [0, 0, 0]], [0.5, [0, 0, 0], [140, 140, 255]], [0.55, [140, 140, 255], [0, 255, 0]], [0.63, [0, 255, 0], [255, 255, 0]], [0.75, [255, 255, 0], [255, 0, 0]], [0.95, [255, 0, 0], [255, 0, 255]]]);
 ```

**Comment by ccpandhare** [comment]
Added in #57!
