### ISSUE TITLE
input text is too close to edges

### ISSUE THREAD

**Issue by bhavayAnand9** [publiclab/image-sequencer#530]
### Please describe the problem (or idea)
As described in this [comment](https://github.com/publiclab/image-sequencer/pull/510#issuecomment-443931221), due to the form-class in demo.css the fields in text input are now too close to the edges.

#### What happened just before the problem occurred? Or what problem could this idea solve?
using .form-control[type="range"] might solve the problem

> What did you expect to see that you didn't?

Too close:

![image](https://user-images.githubusercontent.com/24359/51060628-5aa14a00-15be-11e9-8d79-a0060ed49b28.png)

OK:

![](https://user-images.githubusercontent.com/44309027/49411399-616eae80-f72e-11e8-9e93-5dc51afb4117.png)

### Please show us where to look
https://github.com/publiclab/image-sequencer/blob/main/examples/demo.css#L45

### What's your PublicLab.org username?
bhavayanandcse

> This can help us diagnose the issue:

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by kevinzluo** [comment]
The changes should be made here:
https://github.com/publiclab/image-sequencer/blob/2161d58e501c0436d0e7cb420ca45114ece464ba/examples/demo.css#L45-L47

DIFF:
```diff
- .form-control {
+ .form-control[type="range"] {
     padding: 0px 0px; 
  } 
```

**Comment by bhavayAnand9** [comment]
@jywarren It's a month old issue and very easy to fix. Can you assign it a fto or first-timers-tag? Thanks

**Comment by jywarren** [comment]
Done! 

****

This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://code.publiclab.org/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

**Comment by sashadev-sky** [comment]
I will double check @kevinzluo's solution and repost this as a FTO in the next few hours :) @jywarren @bhavayAnand9

**Comment by sashadev-sky** [comment]
@bhavayAnand9 @kevinzluo @jywarren I think this issue may be outdated as the UI looks like this now:
[http://sequencer.publiclab.org/examples/#steps=contrast{}](http://sequencer.publiclab.org/examples/#steps=contrast{})
<img width="972" alt="screen shot 2019-01-16 at 12 11 15 am" src="https://user-images.githubusercontent.com/41092741/51227938-73925e00-1924-11e9-8d89-76f0c31bef26.png">

Please confirm.

**Comment by bhavayAnand9** [comment]
@sashadev-sky  other modules like crop which uses text inputs instead of range based have still this issue.
![screenshot 2019-01-16 at 16 58 55](https://user-images.githubusercontent.com/34943807/51248157-4d68ce80-19b5-11e9-867c-0dab99dfafff.png)

**Comment by sashadev-sky** [comment]
@bhavayAnand9 Sorry I missed that! I went through a few other ones and they were converted to the new UI so I figured they all might be. Is there a reason we changed some and not others? 

Would it be preferable to change all of them to the new UI for consistency? If so, I can open up FTOs regarding that. If not, I will open for the recommended edit for the current UI.

**Comment by bhavayAnand9** [comment]
@sashadev-sky I don't think we can change all modules because some modules like white-balance can take input from 0-40k so it'll be difficult to adjust that input on a slider. I guess slider method is more suitable with modules having one input and having a range between 1-100. What do you think?

**Comment by sashadev-sky** [comment]
@bhavayAnand9 good point! I don't think it matters how many inputs there are just that the range is small enough to be slider friendly as you mentioned. I will open an FTO for your recommended CSS change :)

**Comment by sashadev-sky** [comment]
@bhavayAnand9 My branch is updated but I think there might be something wrong with my setup. Can you please advise? I have never used grunt before but I ran _grunt serve_ and the _demo.css_ file I am seeing in the Network panel of Chrome dev tools seems to be an old version... it doesn't have a lot of the styles on it

 for me it is showing:
<img width="582" alt="screen shot 2019-01-18 at 6 57 22 am" src="https://user-images.githubusercontent.com/41092741/51387468-1c42e800-1af4-11e9-97fc-998b83bcbd87.png">

**Comment by bhavayAnand9** [comment]
Haha! You had forked a wrong repo. You forked it from [jywarren/image-sequencer](https://github.com/jywarren/image-sequencer) instead of [publiclab/image-sequencer](https://github.com/publiclab/image-sequencer). Jywarren's repo is 159 commits behind.

**Comment by bhavayAnand9** [comment]
@sashadev-sky  Haha! You had forked a wrong repo. You forked it from [jywarren/image-sequencer](https://github.com/jywarren/image-sequencer) instead of [publiclab/image-sequencer](https://github.com/publiclab/image-sequencer). Jywarren's repo is 159 commits behind.

**Comment by jywarren** [comment]
oh no! Yes, i am recently usually updating only my feature branches...
sorry!!!

**Comment by sashadev-sky** [comment]
@bhavayAnand9 :see_no_evil: :see_no_evil:
I will fix this and open after the weekend

**Comment by bhavayAnand9** [comment]
Thanks!

**Comment by sashadev-sky** [comment]
Closing this issue as I have opened an FTO from it #692
