### ISSUE TITLE
Make Fisheye-gl module compatible with nodejs

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#542]
This module uses webgl, which isn't available in Node, so let's try to use one of these libraries to make this possible:

https://github.com/publiclab/image-sequencer/tree/main/src/modules/FisheyeGl

This lib is a pure-JavaScript implementation of OpenGL, so it could work on servers without a GPU: https://github.com/Overv/JSGL

This one, i believe, would just make the GPU accessible to Node, so is less useful but still OK: https://github.com/stackgl/headless-gl

This could then open up the possibility of making a perspective-distort module based on:

https://github.com/jywarren/webgl-distort

**Comment by Divy123** [comment]
Is this issue still open? I would like to work upon it.

**Comment by jywarren** [comment]
Oh this would be really cool!

**Comment by Divy123** [comment]
@jywarren I was going through with the first link as provided above by you but I found that there was no method for taking an image as an input and always requires an html 'div' to work with.
So can you please guide me on this?

**Comment by jywarren** [comment]
Ah, you mean JSGL? Hmm. Would it be possible to run it in `phantomjs` even in NodeJS - using a div still but not needing a browser? Maybe there's some questions/docs about that in the repo issues?

**Comment by Divy123** [comment]
As of now I saw `phantomjs` development is suspended. So, cool, I will find a way to figure it out.
Thanks @jywarren .

**Comment by jywarren** [comment]
Oh really? Is it because of chrome headless?

**Comment by Divy123** [comment]
@jywarren Its because they are receiving less contributions these days. So I guess we should not rely on it. Also I explored JSDOM for this but it requires Node v8 or newer.

**Comment by Divy123** [comment]
@jywarren  @tech4GT  Sorry this issue is taking too much time but I would like to mention that almost all the libraries or modules I saw for this are using node v6+ .
So if we can change out travis can be configured to work with node v6+.
Would like to know your opinion please.

**Comment by jywarren** [comment]
Hm, sure, want to open a travis.yml change PR?

**Comment by Divy123** [comment]
Ya sure.

**Comment by Divy123** [comment]
while I was working with fisheyegl module , I found that requiring fisheyegl in node.js says FisheyeGl is not defined.
`module.exports = function DoNothing(options,UI) {

  var output;

  require('fisheyegl');`
This is the code from Module.js inside fisheyegl module and FisheyeGl is not available.
Any suggestions @jywarren @tech4GT ?

**Comment by Divy123** [comment]
`module.exports = function DoNothing(options,UI) {

  var output;

  require('fisheyegl');`
This is the code from fisheyegl Module.js.
Here requiring fisheyegl is not giving any results that is FisheyeGl is not defined.
Any suggestions @jywarren @tech4GT ?

**Comment by aashna27** [comment]
@Divy123 please give me sometime I ll search on this and then will let you know.

**Comment by Divy123** [comment]
Thanks @aashna27 .
@jywarren I have made some temporary changes to the fisheyegl.js file in src folder in fisheyegl module for fisheye correction.
Please have a look
[https://dpaste.de/H3Kf](url)
What I am stuck at is I am using gl and I think it does not support gl.texImage2D function.
Any suggestions?

**Comment by Divy123** [comment]
Also I have tries using node-canvas apart from jsdom but that too does not support webGl.
Can you please  help me @jywarren ?

**Comment by HarshKhandeparkar** [comment]
Can be discussed in #316

**Comment by HarshKhandeparkar** [comment]
#216 is pinned and discusses the same thing
