### ISSUE TITLE
Tests for more modules; starting with QR code module jsqr

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#546]
We are starting to grow this library substantially and could really use more tests for specific modules. One example is that this pull request is trying to update `jsqr` but we don't test that module, so we don't know if that update breaks the module: #532 

The test could look something like this one, and be in the same folder; we could use a data-url encoded QR code as test data, and confirm that we get the correct data out of the module!

Here's the module code itself:

https://github.com/publiclab/image-sequencer/tree/main/src/modules/DecodeQr

Once this is done, we could move on to each other module. This would be a great repeat first-timers-only issue!

****

This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://code.publiclab.org/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

**Comment by VibhorCodecianGupta** [comment]
@jywarren I'm on this! 
Would love to know if we already have some packages in IS to compare images or their base64 encodings, was thinking of testing the actual functioning of modules against benchmark images.

**Comment by Mridul97** [comment]
@jywarren @VibhorCodecianGupta We don't have any such package in IS already, was writing the test of brightness module #624 , so there is one issue coming while creating a way of image comparison, the module is returning the output as undefined. Please have a look!

![ss_41](https://user-images.githubusercontent.com/21158457/51089229-ce468100-178f-11e9-9d5a-cd5d92329bea.jpg)

**Comment by jywarren** [comment]
> compare images or their base64 encodings

Sorry, yes we do actually, although we don't use it enough!

`looks-same`:

https://github.com/publiclab/image-sequencer/blob/81719a9e139e2a144219d354522f8cdf31d55dd3/test/modules/image-manip.js#L33-L37

**Comment by jywarren** [comment]
Sorry took me a few days, i'm a bit behind!

**Comment by VibhorCodecianGupta** [comment]
@jywarren looks great. I'll get on to writing some tests right away!

**Comment by Mridul97** [comment]
@VibhorCodecianGupta I was also working on adding tests, can we collaborate on this one, maybe you can create tests for some modules and I will create for others, Just a suggestion. :smiley:

**Comment by VibhorCodecianGupta** [comment]
@Mridul97 sounds nice! I think you were working on the brightness module, right? I'll pick up a couple others for the time being, and make a PR. We can proceed accordingly!

**Comment by Mridul97** [comment]
Sounds good! Yes, I am working on the brightness module!

**Comment by aashna27** [comment]
@VibhorCodecianGupta @Mridul97 can you specify the modules you are writing tests for ? I would write for the others then.

**Comment by VibhorCodecianGupta** [comment]
@jywarren added tests at #748 for brightness, invert and contrast modules. `image-manip` had some code which was buggy and wasn't being used. One of them was the QR code module testing, which was not functioning because the module itself is buggy in the first place. Removed those tests.
