### ISSUE TITLE
Add Step button and select fields not inline 

### ISSUE THREAD

**Issue by avsingh999** [publiclab/image-sequencer#547]
### Please describe the problem (or idea)

![pub3](https://user-images.githubusercontent.com/25536022/50054112-b49c2480-0164-11e9-82af-1d9344601d72.png)

### Please show us where to look

http://sequencer.publiclab.org...

### What's your PublicLab.org username?
singhav
> This can help us diagnose the issue:

### Browser, version, and operating system
chrome Ubuntu 18.04 LTS
> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by jywarren** [comment]
I think this may have been fixed in the latest main branch... Would you
mind testing it out? Thank you!

**Comment by avsingh999** [comment]
yes, you are right I will close this and
thank you for inform me : )
