### ISSUE TITLE
GIF generation is not working correctly

### ISSUE THREAD

**Issue by tech4GT** [publiclab/image-sequencer#557]
Gif generation is picking up the images produced in the thumbnails too!(brightness, contrast, saturation, rotate and crop). 
We just want the step outputs in the gif and not these preview images.
cc @jywarren @Mridul97

**Comment by HarshKhandeparkar** [comment]
@tech4GT, in which file is the gif generation done?

**Comment by HarshKhandeparkar** [comment]
I actuallu found it in demo.js

**Comment by tech4GT** [comment]
https://github.com/publiclab/image-sequencer/blob/d5aac98a29c5d8e115a90b5b25265fe05c18db51/examples/demo.js#L96-L168

**Comment by tech4GT** [comment]
Yeah go ahead @HarshKhandeparkar :)
