### ISSUE TITLE
The value below the slider does not updates with slider's movements

### ISSUE THREAD

**Issue by Mridul97** [publiclab/image-sequencer#564]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

The value below the slider does not updates with slider's movements.

![pop](https://user-images.githubusercontent.com/21158457/50528263-43208680-0b13-11e9-9885-ea6899222145.gif)

### Please show us where to look

https://github.com/publiclab/image-sequencer/blob/main/examples/lib/defaultHtmlStepUi.js

### What's your PublicLab.org username?
Mridul97
> This can help us diagnose the issue:

### Browser, version, and operating system
Chrome, Windows 8.1
> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

cc @jywarren  @tech4GT

**Comment by Mridul97** [comment]
I would like to work on this issue!

**Comment by aashna27** [comment]
> I would like to work on this issue!

could you please check it again because it is updating.

**Comment by Mridul97** [comment]
@aashna27 I have checked it till the last commit, is any currently open pull request solving this issue?

**Comment by aashna27** [comment]
> @aashna27 I have checked it till the last commit, is any currently open pull request solving this issue?

i checked it on the hosted one, it was working there. No i dont think so .

**Comment by Mridul97** [comment]
Yes It is working fine on the gh-pages branch but it is not working on the main branch. Any of the latest commits must have caused this error
