### ISSUE TITLE
Map types in `info.json` files to valid HTML types

### ISSUE THREAD

**Issue by HarshKhandeparkar** [publiclab/image-sequencer#570]
### Please describe the problem (or idea)

Input types in some module **info.json** files are not valid html input types. This makes typing number type values inconvenient and invalid values can be submitted. Types like **integer** and **string** should be replaced with **number**, **range** or **string**.

https://github.com/publiclab/image-sequencer/blob/611016b022b22d1f89247e7b13f7650e1b65f2c7/src/modules/Rotate/info.json#L6

### Possible Fixes

Add a new function in `examples/lib` which maps different types to valid HTML types

## Thank you!

**Comment by VibhorCodecianGupta** [comment]
@HarshKhandeparkar what values would `htmlType` assume? Given that the `type` property would be float, integer etc

**Comment by HarshKhandeparkar** [comment]
`htmlType` can be generalised. **integer**, **float** can both use **number** or **range**. **percentage**, **color** etc. can be **string**.

**Comment by HarshKhandeparkar** [comment]
@tech4GT @jywarren is this issue good? Is this being fixed in some other issue?

**Comment by Mridul97** [comment]
If no one is working on this issue, can I take up this issue?

**Comment by HarshKhandeparkar** [comment]
Absolutely. That will be awesome!

**Comment by Mridul97** [comment]
@HarshKhandeparkar we cannot keep htmltype to be Number for input type float because it will not allow us to enter values like 1.5. So what should we keep htmltype when input type is float?

**Comment by HarshKhandeparkar** [comment]
@Mridul97 range will be good for float type inputs

**Comment by HarshKhandeparkar** [comment]
@Mridul97 if you are taking up https://github.com/publiclab/image-sequencer/issues/628 then can I work on this?

**Comment by Mridul97** [comment]
@HarshKhandeparkar Actually I am almost done with this one, opening a pr!

**Comment by HarshKhandeparkar** [comment]
Hmm actually even I had worked on this. Should we collab?

**Comment by HarshKhandeparkar** [comment]
Tell me your branch name. We will compare our changes. I will open a pr to your branch. Lets merge our changes.

**Comment by Mridul97** [comment]
Branch name is htmltypes, I just opened a pr #633.

**Comment by HarshKhandeparkar** [comment]
Look at my branch `htmlType-in-info-files` I have done many more other changes.

**Comment by Mridul97** [comment]
There are multiple to see changes like this becomes a bit inefficient, you can see my changes here #633.

**Comment by HarshKhandeparkar** [comment]
I have opened a pr to your branch. Please check it out. Also please `git merge upstream/main`

**Comment by HarshKhandeparkar** [comment]
https://github.com/Mridul97/image-sequencer/pull/2/

**Comment by jywarren** [comment]
Hi, I'd like to suggest a slightly different approach, i'm sorry I didn't earlier but the rate of contribution is making my inbox a bit wild, apologies!

What if we maintain a utility function which maps the `type` to an `htmlType`, so that we can be more specific than `htmlType` (for reasons you've outlined here!) while not further complicating the `info.json` files, and not making the process of adding a new module any more complex? 

We could create `/src/util/inputTypeConversion.js` perhaps... with some internal mapping with an assoc. array, like:

```js
types = {
  'string': 'input',
  'text': 'textarea',
  'range': ...
}
```

And the util module could provide a method like:

```js
inputTypeConversion.typeToHtmlType('string');
```

What do you think of this?

**Comment by jywarren** [comment]
I appreciate all your work on this! I think it's a great idea. Thanks for considering my suggestion.

**Comment by HarshKhandeparkar** [comment]
@jywarren The idea you suggested is cool but same type of input can have more than one htmlType like e.g. 'integer' can have both 'range' and 'number' as input. What can we do in that case?

**Comment by HarshKhandeparkar** [comment]
@jywarren I'll open a new PR

**Comment by HarshKhandeparkar** [comment]
New pr https://github.com/publiclab/image-sequencer/pull/674

**Comment by jywarren** [comment]
ah, actually wouldn't the lookup would go from both range and number to
integer, and not the other way?

**Comment by HarshKhandeparkar** [comment]
@jywarren I think your rebase caused some problem in the pr and no changes were made. Any thoughts? I will probably open a new pr by force pushing from local. I still have the changes there. Thanks

**Comment by jywarren** [comment]
Oh sorry! Yes please do.

**Comment by HarshKhandeparkar** [comment]
Ok will do in a few minutes
