### ISSUE TITLE
Improving buttons for smaller screens

### ISSUE THREAD

**Issue by VibhorCodecianGupta** [publiclab/image-sequencer#582]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

The buttons `save sequence` and `view gif` are too wide and have no margin at all in mobile and tablet views. They even flow out of the div, and hence out of the device screen. This is undesirable, buttons should change their shape according to the device.

![screen shot 2018-12-31 at 10 33 56 pm](https://user-images.githubusercontent.com/29275810/50567761-d3a6d300-0d6e-11e9-9e2b-3787ba3958a6.png)

![screen shot 2018-12-31 at 10 34 28 pm](https://user-images.githubusercontent.com/29275810/50567762-d3a6d300-0d6e-11e9-96b6-188f1b4761f5.png)

> What did you expect to see that you didn't?

Well-aligned and spaced buttons

### Please show us where to look

http://sequencer.publiclab.org

> This can help us diagnose the issue:

Observe the mobile/tablet view

### Browser, version, and operating system

Chrome/Safari; OSX 10.13

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by jywarren** [comment]
Hmm, are they block buttons? Perhaps just normal `btn` class from Bootstrap
would work better?

**Comment by VibhorCodecianGupta** [comment]
@jywarren yes, this can be achieved using `btn-block` as well, but the white `panel` behind the two buttons doesn't adjust it's size, and additional css might be required there (which I haven't figured out yet). Example: 

![screen shot 2019-01-03 at 11 22 20 am](https://user-images.githubusercontent.com/29275810/50625056-57b5b200-0f4b-11e9-802c-77d002f76363.png)

**Comment by VibhorCodecianGupta** [comment]
@jywarren #583 however, takes care of the white panel background as well

**Comment by VibhorCodecianGupta** [comment]
@jywarren #583 however, takes care of the white panel background as well, which looks prettier IMO. Thoughts?

**Comment by jywarren** [comment]
OK, would you like to close this and solve over there? Thanks!

**Comment by VibhorCodecianGupta** [comment]
@jywarren sure, I'll close this and update the PR :)
