### ISSUE TITLE
Add "(local)" to locally stored modules

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#591]
It's possible to save a sequence locally, and have it appear in the Add Step menu (see   https://github.com/publiclab/image-sequencer/pull/587). Let's be sure any we add there are marked with ` (local)` in their name so people know which are locally stored an which are built-in.

**Comment by Mridul97** [comment]
@jywarren I would love to work on this issue!

**Comment by VibhorCodecianGupta** [comment]
@jywarren I'd like to work on this. I understand the part where it'll be better to label the locally saved steps in the sequence `(local)`. I reckon when the user clears cache or reloads the application and sees the saved sequence, it should display a (local) to demark it as already saved in the browser, and any steps added further after which are not saved should not show the (local) mark right? 
The part I don't understand is, what do you mean by `built-in` ?

**Comment by Mridul97** [comment]
I think this issue has an easy fix, when a user enters the name of the sequence to be saved, we can append '(local)' to the name, so now the sequence will be saved as 'userGivenName (local)' This can be done before calling 'sequencer.saveSequence()' function! I would like to solve this!

**Comment by Mridul97** [comment]
Something like this: 

![ss_38](https://user-images.githubusercontent.com/21158457/50591554-51292b00-0eb6-11e9-91e3-044750d03337.jpg)

**Comment by VibhorCodecianGupta** [comment]
@Mridul97 Or instead of displaying `(local)` in the drop-down, we can append it to the title of the step, probably a side text or something.
For example, I save a sequence with two steps, reload the page, and it shows (local) in front of the two steps that I saved. All the subsequent steps added, before saving the next sequence, will not have the (local) tag. Will post a screenshot once I reach home or better understanding

**Comment by jywarren** [comment]
Ah, i see. we would yes probably need to not just save it in the dropdown,
but "upstream" as it's stored in localstorage, which would then be
reflected in the dropdown, right?

This would be great!

**Comment by Mridul97** [comment]
Yes, It would be stored in the local storage by the name "userGivenName (local)" and that would then appear in the dropdown!

Please see here #596 I have implemented this!

**Comment by jywarren** [comment]
Oh hi @VibhorCodecianGupta -- sorry I merged @Mridul97 's solution but we'd love your help with other issues. It's so great to have a community of collaboration on this library - it's moving so fast!!!
