### ISSUE TITLE
Hex color picker input in default HTML UI

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#597]
Some modules now are prompting for a color of input. We can accept RGBA, hex, etc, but for easier input, perhaps we can include a node library which has a simple built-in color picker? Then that could become an input type on its own!

**Comment by HarshKhandeparkar** [comment]
How about implementing color pickers on the frontend https://farbelous.io/bootstrap-colorpicker/tutorial-Basics.html

**Comment by VibhorCodecianGupta** [comment]
@HarshKhandeparkar sounds good!
We could write a util function to convert the input into RGB or HEX and then pass it to the respective module to process it. Would like to work on this.
@jywarren how does that sound?

**Comment by HarshKhandeparkar** [comment]
What I feel is that the color input is up to the user frontend and the parsing of different values `HEX` `HSLA` `RGB` should be the job of the library so instead of adding more packages, we could add frontent code and make the library conlmpatible with it. This makes the library even more useful.

**Comment by VibhorCodecianGupta** [comment]
Makes sense. Parsing would then be the only concern for IS. Nice.

**Comment by jywarren** [comment]
oh this sounds awesome!

**Comment by HarshKhandeparkar** [comment]
We also have to keep in mind that mobile phone users cannot use color pickers very efficiently.

**Comment by aashna27** [comment]
@VibhorCodecianGupta would you like some help on this?? This issue sounds interesting to me.

**Comment by VibhorCodecianGupta** [comment]
@aashna27 sure! I was thinking to provide a colour picker to all the modules requiring some sort of colour modules and since  https://farbelous.io/bootstrap-colorpicker/tutorial-Basics.html already gives us the values of the `RGBA`, we could write a custom function to pick the respective channel values and pass them into the already existing input types

**Comment by aashna27** [comment]
> 
> 
> @aashna27 sure! I was thinking to provide a colour picker to all the modules requiring some sort of colour modules and since https://farbelous.io/bootstrap-colorpicker/tutorial-Basics.html already gives us the values of the `RGBA`, we could write a custom function to pick the respective channel values and pass them into the already existing input types

How's work going @VibhorCodecianGupta please let me know what can I help you with.

**Comment by jywarren** [comment]
Harsh i think this is a great idea. 

Looking for good UIs we could use, this is nice: https://farbelous.io/bootstrap-colorpicker/tutorial-Basics.html and bootstrap-compatible:

![image](https://user-images.githubusercontent.com/24359/55291910-35003180-53b2-11e9-9eb5-9c9efbd439dd.png)

This one has lots of different options but may be more complex to install: https://casesandberg.github.io/react-color/

![image](https://user-images.githubusercontent.com/24359/55291915-506b3c80-53b2-11e9-97de-04c2ca62e0b6.png)
