### ISSUE TITLE
Compilation and testing of demo files using Grunt-concat

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#598]
Our demo HTML UI is becoming ever more complex. We should compile those files too to help reduce complexity and code organization in our examples/demo.js folder, by modifying our Gruntfile to produce `dist/image-sequencer-ui.js` and `dist/image-sequencer-ui.min.js` files.

Then we should start writing tests for the UI! They could go in `/spec/ui/` and could use Jasmine, or maybe Teaspoon? Something quite compatible with our test runners. That'll help stabilize our code now that it's growing so big and is becoming more mature! We can test that menus appear, buttons are enabled/disabled, buttons create/delete steps, and more. 

This is 2 separate tasks, but are both related to the maturity of this library. We'd love help with either or both!

**Comment by Mridul97** [comment]
@jywarren I would love to work on this!

**Comment by jywarren** [comment]
AWESOME!!!

**Comment by HarshKhandeparkar** [comment]
@jywarren @gauravano this has been fixed but was not closed since a wrong keyword `Issue` was used in the PR. Closing this.

**Comment by VibhorCodecianGupta** [comment]
@jywarren reopened this issue because:
Setting up a frontend testing harness was not addressed in the merged PR, just made a PR for the same. It entails boilerplate code testing the invocation of various UI helper methods. Further tests can be written on top of that.
