### ISSUE TITLE
Error in common modules region

### ISSUE THREAD

**Issue by aashna27** [publiclab/image-sequencer#604]
### The images in the common modules area are not appearing , this is a bug which is causing the crop image to not display and the brightness' one to be black.
> Error
![image](https://user-images.githubusercontent.com/26546120/50706582-445a3200-1084-11e9-87c2-bb54980d8691.png)

I would request someone to verify this issue and then I would like to claim it.

Thanks

**Comment by jywarren** [comment]
I think this is due to #606 -- closing unless you think there's another issue too?
