### ISSUE TITLE
Center Align Step Removed Notification

### ISSUE THREAD

**Issue by HarshKhandeparkar** [publiclab/image-sequencer#610]
### Please describe the problem (or idea)

The notification toast which appears when a step is removed is not center aligned on smaller screens.

![not-center-aligned toast](https://user-images.githubusercontent.com/34770591/50725064-d06c6800-111d-11e9-9510-a43b18e319ee.gif)

![screenshot_20190105-191448](https://user-images.githubusercontent.com/34770591/50725119-a8313900-111e-11e9-9fc5-36e457a7078a.jpg)

### Possible fixes

Instead of appending a `span`, appending a `div` with `display: flex` and `width: 100%` could solve the issue. Instead of using `$.fadeIn`, `$.animate` the opacity from `0` to `1`.

### Where to look

https://github.com/publiclab/image-sequencer/blob/107b4c22e44dd3363095104a2df51cc5b2a07597/examples/lib/defaultHtmlStepUi.js#L10-L20

https://github.com/publiclab/image-sequencer/blob/107b4c22e44dd3363095104a2df51cc5b2a07597/examples/demo.css#L204-L216

**Comment by HarshKhandeparkar** [comment]
I'm working on this.

**Comment by aashna27** [comment]
Is anyone working on this ?? Can i claim it ?

**Comment by HarshKhandeparkar** [comment]
If @Mridul97 has not started work yet then maybe you can do that?

**Comment by aashna27** [comment]
> If @Mridul97 has not started work yet then maybe you can do that?.

Is it claimed already ?

**Comment by HarshKhandeparkar** [comment]
Oh maybe I'm confused. I mixed up some other issue with this one. Sorry I don't think this is claimed 😅

**Comment by aashna27** [comment]
😆 okay !! On it..

**Comment by HarshKhandeparkar** [comment]
I remember, the notification toast was my first GCI PR this year. You were the mentor @aashna97 😊

**Comment by aashna27** [comment]
> I remember, the notification toast was my first GCI PR this year. You were the mentor @aashna27 😊

Haha yeah I remember too!! Its lovely to have you 😄

**Comment by HarshKhandeparkar** [comment]
> > I remember, the notification toast was my first GCI PR this year. You were the mentor @aashna27 blush
> 
> Haha yeah I remember too!! Its lovely to have you

I love working here too!! 😊😊

**Comment by jywarren** [comment]
😊🎉
