### ISSUE TITLE
Configure pre-commit hooks to build and add dist/*

### ISSUE THREAD

**Issue by rexagod** [publiclab/image-sequencer#611]
### Please describe the problem (or idea)
We can implement git pre-commit hooks that `grunt build` and `git add` before committing to the repository which will reduce merge conflicts and provide the new (and old) members some amount of abstraction over some unproductive and repetitive tasks.

### What happened just before the problem occurred? Or what problem could this idea solve?
Merge conflicts and Travis builds.

### Please show us where to look
[Grunt docs](https://gruntjs.com/getting-started), [git hooks](https://githooks.com/), `./Gruntfile.js`, and `./.git/hooks/pre-commit.sample`

### What's your PublicLab.org username?
rexagod

### This can help us diagnose the issue:
[Some ideas](https://github.com/publiclab/image-sequencer/issues/601#issuecomment-451640284)

### Browser, version, and operating system
Chrome, Version 71.0.3578.98 (Official Build) (64-bit), Arch

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by Mridul97** [comment]
@jywarren This seems quite interesting. I would like to work on this one!

**Comment by jywarren** [comment]
I guess I think this will be helpful, but won't solve the issue of needing
to rebase so much. One suggestion had been to actually not track /dist/ at
all, and to have maintainers do it only, and perhaps only when we `npm
publish`. Let's quickly check back in the original issue to talk through a
few more possibilities before merging this, ok? Thanks!

**Comment by HarshKhandeparkar** [comment]
Let's move the discussion to #773
