### ISSUE TITLE
weird border on right and bottom of thumbnail grid

### ISSUE THREAD

**Issue by bhavayAnand9** [publiclab/image-sequencer#615]
### Please describe the problem (or idea)
![screenshot 2019-01-06 at 14 45 52](https://user-images.githubusercontent.com/34943807/50734344-df0d5a80-11c3-11e9-9ba3-b503ca5baf60.png)

there's an excessive space on right and bottom of thumbnail grid.
 
It should be like this

![screenshot 2019-01-06 at 14 46 30](https://user-images.githubusercontent.com/34943807/50734381-4e834a00-11c4-11e9-9c1c-faf5b6555807.png)

fix:
I think it's because of overflow:scroll property on radio-group class, changing it with auto fixes the issue.

### Please show us where to look

http://sequencer.publiclab.org...

### Browser, version, and operating system
Chrome, Macos

****

**Comment by bhavayAnand9** [comment]
@tech4GT can you confirm this and maybe add the first-timer-only tag?

**Comment by HarshKhandeparkar** [comment]
I've had the same issue. Its because of the `overflow:scroll` property which was added recently. Its just the scrollbar.

**Comment by HarshKhandeparkar** [comment]
Possible fix would be to add `overflow:scroll` only on small screen sizes.

**Comment by HarshKhandeparkar** [comment]
No problems on my phone though


![screenshot_20190106-151548](https://user-images.githubusercontent.com/34770591/50734497-1aa92400-11c6-11e9-9916-4dffcea62d9d.jpg)



Desktop view:


![screenshot_20190106-151533](https://user-images.githubusercontent.com/34770591/50734502-24cb2280-11c6-11e9-962d-9bd5ca36d275.jpg)

**Comment by bhavayAnand9** [comment]
> Possible fix would be to add `overflow:scroll` only on small screen sizes.

setting overflow to `auto` does the same. It only adds scrollbar when necessary unlike `scroll` which adds it even if we don't need it.

**Comment by HarshKhandeparkar** [comment]
Do you want to fix this?

**Comment by HarshKhandeparkar** [comment]
@VibhorCodecianGupta this is linked to your PR. Do you want to fix this? It is very annoying. It is a very small fix too. Maybe its too simple for being an `fto-candidate`
