### ISSUE TITLE
thumbnails not showing upon adding a step

### ISSUE THREAD

**Issue by bhavayAnand9** [publiclab/image-sequencer#618]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

 on clicking +Add button, the toolbar appears but without thumbnails

![screenshot 2019-01-06 at 21 04 12](https://user-images.githubusercontent.com/34943807/50738222-85bf1e80-11f7-11e9-83f2-29bcb2b667cc.png)

### Please show us where to look

http://sequencer.publiclab.org...

### Browser, version, and operating system
Chrome, MacOS

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

**Comment by Divy123** [comment]
Since this one is related to a PR created by me. I will be sending a PR soon enough.
