### ISSUE TITLE
Add package-lock.json to .gitignore 

### ISSUE THREAD

**Issue by aashna27** [publiclab/image-sequencer#625]
Adding package-lock.json to .gitignore would prevent it's unnecessary commit .

****

## Thank you!

**Comment by VibhorCodecianGupta** [comment]
I think we should actually commit the lock file since they lock the version being used by the project, for any new contributor to setup and not end up installing incompatible dependencies. Thoughts? @jywarren

**Comment by aashna27** [comment]
The dependency version is locked in package.json, and package-lock.json comes everytime npm install is done . And in case of conflicts in versions in package.json and package-lock.json the version of package.json is considered so I think ignoring package-lock while commiting is okay!! 😄

**Comment by VibhorCodecianGupta** [comment]
@aashna27 https://stackoverflow.com/a/44210813 😅 
The dependency version is actually locked in `package-lock` and not `package.json`. Also, the precedence being given to `package.json` in case of conflicts in versions is exactly why lock exists, to prevent such a thing from happening :D 

Rest, admins may decide what seems fit

**Comment by HarshKhandeparkar** [comment]
When a project is initialized with `npm init` it is specifically stated that the lockfile should be commited. But there may be another way around this?

**Comment by jywarren** [comment]
We could git-ignore the lock file but on the "build process" we're
developing it could be force updated using `git add -f`, would that work?

**Comment by aashna27** [comment]
We could add it to gitignore and also prevent its creation all together,
Thoughts?
