### ISSUE TITLE
Add a util function which loads defaults from `info.json` files

### ISSUE THREAD

**Issue by HarshKhandeparkar** [publiclab/image-sequencer#628]
### Please describe the problem (or idea)

In https://github.com/publiclab/image-sequencer/pull/607 the default values for some modules were changed in the `info.json` files but subsequent changes were not made to the `module.js` files which led to issues like https://github.com/publiclab/image-sequencer/pull/616 in which the html renders the default value but the sequencer doesn't 

### Possible Solution

We could add a new util function in `src/util` directory which will load all the default values from `./info.json` file and return an object based on those. This function can be used in any `module.js` file if required like for e.g 
```
const defaults = require('../../util/getDefaults.js')();
```

This will be helpful as all the defaults can be managed from the module `info.json` files and there will be no need to manage more than a single file.

**Comment by HarshKhandeparkar** [comment]
@Mridul97 do you want to work on this? If not then I will.

**Comment by Mridul97** [comment]
Yes, I would like to work on this!

**Comment by HarshKhandeparkar** [comment]
> Yes, I would like to work on this!

Awesome!!
