### ISSUE TITLE
Initial value of brightness step is not correct

### ISSUE THREAD

**Issue by tech4GT** [publiclab/image-sequencer#630]
The initial value displayed is 175 but the image is processed like 100.
<img width="1194" alt="screen shot 2019-01-08 at 8 33 50 am" src="https://user-images.githubusercontent.com/25617855/50807437-71c30c00-1320-11e9-9d7b-f94c672ac4b2.png">

**Comment by bhavayAnand9** [comment]
@tech4GT #616

**Comment by HarshKhandeparkar** [comment]
@tech4GT https://github.com/publiclab/image-sequencer/issues/628 Mridul is going to fix this. You can close this one.

**Comment by gauravano** [comment]
Thanks for update @HarshKhandeparkar. @tech4GT feel free to reopen if needed. Thanks!
