### ISSUE TITLE
Take a photo feature not working

### ISSUE THREAD

**Issue by bhavayAnand9** [publiclab/image-sequencer#631]
### Please describe the problem (or idea)
Take a Photo feature uses `navigator.getUserMedia` which has been deprecated on Insecure origins and as localhost is treated as a secure origin so we might not see this error on localhost server but on the [website](http://sequencer.publiclab.org/examples/#steps=) it's throwing an error.

we should start using the newer method 
https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia
but I don't know if that'll work on insecure origins or not?

and I think it'll be more helpful if we console log error object instead of error string here
https://github.com/publiclab/image-sequencer/blob/main/src/ui/SetInputStep.js#L57 

### Please show us where to look

http://sequencer.publiclab.org...

### What's your PublicLab.org username?

> This can help us diagnose the issue:

### Browser, version, and operating system
Chrome, Safari MacOS

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by bhavayAnand9** [comment]
@publiclab/reviewers

**Comment by bhavayAnand9** [comment]
@jywarren @tech4GT

**Comment by HarshKhandeparkar** [comment]
I was facing the same problem too. @aashna27 ?

**Comment by aashna27** [comment]
I ll look into it and submit a pr soon 😊
