### ISSUE TITLE
New Add QR Module

### ISSUE THREAD

**Issue by HarshKhandeparkar** [publiclab/image-sequencer#632]
### Please describe the problem (or idea)

Add a new module called `Add QR` which adds a QR code to an image like for e.g at the corner.

example:

![add-qr-module](https://user-images.githubusercontent.com/34770591/50827428-6d204700-1364-11e9-8358-3bff018cc443.png)

In the above GIMP image, there is QR code at the corner which links to https://github.com/publiclab/image-sequencer

This module can take a string input and output a QR code based on that. 
Maybe this can help https://www.npmjs.com/package/qrcode

`StartingX`, `StartingY` and `size` inputs can be added in a followup later for image placement. As a simple module, this could add a QR code only to the bottom right corner.

### Uses

This module can be used to add a link to an image for maybe profile pictures or even adverts.

**Comment by lakshyabatman** [comment]
@HarshKhandeparkar ,  you meant  placing QR code in image linking to Public Labs github profile, right?

**Comment by HarshKhandeparkar** [comment]
That was just an example l. What i meant was that it can take any text input and place a qr code. For example a link

**Comment by lakshyabatman** [comment]
Yeah, it is cool! I'll start working on it.

**Comment by HarshKhandeparkar** [comment]
Awesome!!

**Comment by Divy123** [comment]
Is this issue still open @HarshKhandeparkar ?
I would like to work on it.

**Comment by HarshKhandeparkar** [comment]
@Divy123 if @lakshyabatman has not started working on this yet then sure.

**Comment by Divy123** [comment]
@HarshKhandeparkar I have started working on the module.
Just one thing if you can help me out with image manipulation part.
I have got the qr code image data-uri then how should I attach the same to the original image.
thanks

**Comment by HarshKhandeparkar** [comment]
@Divy123 you can use [get-pixels](https://github.com/scijs/get-pixels) to get an ndarray from a data-uri. Then you can replace pixels in the original image with the pixels in the ndarray. I don't know anything about resizing the image though. An example of getpixels can be tound [here](https://github.com/HarshKhandeparkar/image-sequencer/blob/1787ccd29732aa08c06655001c789d23ba0ee8d2/src/modules/FlipImage/Module.js) where I have duplicated the original image.

**Comment by Divy123** [comment]
Thanks for your help.
I will go through it. 😁
