### ISSUE TITLE
Webgl-distort library module

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#64]
Thinking ahead again (so, lower priority) but it'd be great to integrate the `webgl-distort` library:

https://github.com/jywarren/webgl-distort

This, like `fisheyegl`, uses WebGL canvas. 

It probably needs to be packaged up for compatibility with `require` or something, but it is also on NPM:

https://www.npmjs.com/package/webgl-distort

**Comment by ccpandhare** [comment]
Adding this to the list of module candidates in CONTRIBUTING.md for now!

**Comment by jywarren** [comment]
Merging into https://github.com/publiclab/image-sequencer/issues/1021
