### ISSUE TITLE
Intermediate step UI adds more than once

### ISSUE THREAD

**Issue by HarshKhandeparkar** [publiclab/image-sequencer#640]
### Please describe the problem (or idea)

When a step is inserted between two steps, the new form that appears is appended more than once if the button is clicked more than once 

![screenshot_20190109-230559](https://user-images.githubusercontent.com/34770591/50917388-67f5f180-1463-11e9-801e-2c51fb1cbbe9.jpg)

![screenshot_20190109-230616](https://user-images.githubusercontent.com/34770591/50917397-6cbaa580-1463-11e9-90ac-265a0b514cf4.jpg)

### Browser, version, and operating system
Chrome 71, android 8

****

## Thank you!

**Comment by aashna27** [comment]
@HarshKhandeparkar its working fine on localhost. Would you mind checking it there ?

**Comment by HarshKhandeparkar** [comment]
@jywarren I tried clearing the cache I get the same error.

**Comment by HarshKhandeparkar** [comment]
The error is only on `gh-pages` maybe?
