### ISSUE TITLE
Load Image step has no insert step button

### ISSUE THREAD

**Issue by HarshKhandeparkar** [publiclab/image-sequencer#644]
### Please describe the problem (or idea)

> What happened just before the problem occurred? 

All the steps have an `+add` button which lets the user insert a step in betwee ln but the initial `load image` step does not.
There should be a button in that step too which lets the user add a step to the start of the sequence.

![screenshot_20190110-181650](https://user-images.githubusercontent.com/34770591/50969413-6defdf00-1504-11e9-91c7-d28e00b0eaeb.jpg)

![screenshot_20190110-181655](https://user-images.githubusercontent.com/34770591/50969429-79dba100-1504-11e9-821f-b3f2713ace4e.jpg)

Please note: This is a screenshot from the `gh-pages` branch on sequencer.publiclab.org

**Comment by aashna27** [comment]
@jywarren what do you think ??

**Comment by jywarren** [comment]
Isn't load image always the first module, so it'd have the Add Step box initially? Maybe that's why it didn't have it. Maybe we need to do it but make sure it doesn't show redundantly when there's only 1 step?

**Comment by aashna27** [comment]
> 
> 
> Isn't load image always the first module, so it'd have the Add Step box initially? Maybe that's why it didn't have it. Maybe we need to do it but make sure it doesn't show redundantly when there's only 1 step?

I am not really sure if it should have "add" button.

**Comment by HarshKhandeparkar** [comment]
> > Isn't load image always the first module, so it'd have the Add Step box initially? Maybe that's why it didn't have it. Maybe we need to do it but make sure it doesn't show redundantly when there's only 1 step?
> 
> I am not really sure if it should have the "add" button.

I think it should as no step can be added in between step 1 i.e. load-image and step 2

**Comment by Harshithpabbati** [comment]
do i need to just add the add button in it?? I guess there is no use on adding it

**Comment by HarshKhandeparkar** [comment]
@Harshithpabbati the add button is to insert a new step between the image and the current first step

**Comment by Harshithpabbati** [comment]
oh ok. Can i work on this???

**Comment by HarshKhandeparkar** [comment]
yes sure!

**Comment by Harshithpabbati** [comment]
I am almost done with I had a small problem as the add button is not disabled at the load-image
![insert](https://user-images.githubusercontent.com/43822585/52939626-ac41af00-338a-11e9-967f-30331a2fe348.png)

**Comment by Harshithpabbati** [comment]
Can anyone help me out

**Comment by HarshKhandeparkar** [comment]
Fixed
