### ISSUE TITLE
CLI NOT WORKING

### ISSUE THREAD

**Issue by tech4GT** [publiclab/image-sequencer#645]
I am getting this error in the CLI
<img width="1147" alt="screen shot 2019-01-10 at 8 00 10 pm" src="https://user-images.githubusercontent.com/25617855/50975003-7e0ebb00-1512-11e9-9fa3-20505430c0aa.png">

cc @Mridul97 @jywarren

**Comment by HarshKhandeparkar** [comment]
Does the `drawRectangle` module work in browser on localhost ?

**Comment by jywarren** [comment]
Hi, I believe this was addressed in
https://github.com/publiclab/image-sequencer/issues/637, but does it still
not work?

What concerns me is that the CLI failure appeared in Travis, but did not
trigger a Travis failure:

https://travis-ci.org/publiclab/image-sequencer/jobs/477001494#L1713

Can we:

1. confirm if the fix worked, and fix it if not
2. change the title of this issue to "CLI failure not causing Travis fail"
and address that issue as well?

Thank you!

**Comment by jywarren** [comment]
Thank you, I'd really appreciate that!

**Comment by jywarren** [comment]
OK, closing this and opening a new one for why a CLI error didn't trigger a Travis failure! 

Moving to https://github.com/publiclab/image-sequencer/issues/659

Thanks, all!

**Comment by tech4GT** [comment]
Glad to know this was fixed! :smile:

**Comment by HarshKhandeparkar** [comment]
This has been fixed. Closing this
