### ISSUE TITLE
'let' not allowed outside strict mode - error

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#646]
Travis shows an error in the logs, here:

https://travis-ci.org/publiclab/image-sequencer/jobs/477803581#L830-L834

```
/home/travis/build/publiclab/image-sequencer/src/ImageSequencer.js:135
    let progressObj, index = 0;
    ^^^
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
```

But it doesn't fail - i'd like to address both issues, getting Travis to actually report a failure in this case, AND then resolving it -- probably with adding strict mode?

**Comment by jywarren** [comment]
Related to #645

**Comment by Divy123** [comment]
I would like to work upon it.

**Comment by gauravano** [comment]
Go ahead @Divy123!

**Comment by Divy123** [comment]
@jywarren @tech4GT I tested it by creating a test that uses a simple  assignment using 'let' and the test still passed without any errors.
Hence I don't think there is a problem with our image-sequencer code itself.
Also when I went through [https://node.green/](url), it should fail the test.
Would like to know your opinion on this.

**Comment by Divy123** [comment]
Any opinions @jywarren .Also since the tests for node 4 has been  removed, we should close this issue.

**Comment by HarshKhandeparkar** [comment]
No longer relevant.
