### ISSUE TITLE
Adding blend module at unavailable offset always shows loading.

### ISSUE THREAD

**Issue by Divy123** [publiclab/image-sequencer#648]
### Please describe the problem (or idea)
On adding Blend module, if the step at offset is not available it always shows loading
>One Possible solution:
I think output produced can be made same as input in case of unavailable offset and a notification can be shown for offset unavailable.

### Please show us where to look
[https://github.com/publiclab/image-sequencer/blob/main/src/modules/Blend/Module.js](url)

**Comment by Divy123** [comment]
@jywarren @tech4GT  I would like to work upon this.

**Comment by jywarren** [comment]
oh please do, that would be great!

**Comment by HarshKhandeparkar** [comment]
@Divy123 wasn't this fixed when notify was implemented? Can this be closed? If yes then please do so. Thanks.

**Comment by Divy123** [comment]
Ya this is fixed. Thanks!!
