### ISSUE TITLE
Planning interface architecture

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#65]
Just to kick this off, i had some thoughts:

Each module should have a default interface, which perhaps just doesn't do anything. But we should be able to add an interface, and connect up:

* `onAdd` or `onSetup` - runs when the module is added - can be used to create/append HTML 
* `onTrigger` or `onDraw` - runs when the module is run
* `beforeDraw` vs. `afterDraw`? These could display for example a spinning icon when a process starts, and hide the spinner on completion. Alternately, we could also use `onComplete`.
* we should make some methods available to any HTML features we construct inside `onSetup` -- maybe pass in some methods like `onSetup(stuff)`

**Comment by jywarren** [comment]
I actually think we may want to create an extremely minimal "simple" html interface first to prove out our architectural decisions and also make it easy for people to understand how an interface can be implemented. Then circle back for a more awesome interface as a second step. What do you think?

**Comment by jywarren** [comment]
Like maybe the simplest just displays the images in div, no more. 

Also, let's think carefully about designing this so that the interface code may eventually be spun out into a separate module.

**Comment by ccpandhare** [comment]
Okay! All this sounds great! Just a few thoughts here:
* Shouldn't the modules be independant of the implementation (i.e. the UI/FrontEnd Code)?
* We also have support for NodeJS. So what will the above methods as mentioned by you do in NodeJS?
* What I had in mind was a module called "UserInterface.js" (Just like Image Sequencer had, initially.). whenever an image is drawn, `UserInterface` is informed. Then It produces the necessary HTML Elements, or the NodeJS output. Basically all the methods above as you said, just that they connect to `UserInterface` and that modules themselves don't handle any HTML.
* Also, users should be able to make their own UI as per their requirements, so they Can implement Image Sequencer in their projects, right? So shouldn't image sequencer act like an API? Taking instructions from the user and returning the output so they can use it the way they want.

What do you think about all this?

**Comment by ccpandhare** [comment]
I do agree to the fact that we should have a basic, but rigid UI in the beginning, and then develop it furtyher.

>I actually think we may want to create an extremely minimal "simple" html interface first to prove out our architectural decisions and also make it easy for people to understand how an interface can be implemented. Then circle back for a more awesome interface as a second step. What do you think?

**Comment by jywarren** [comment]
Just brainstorming here -- What about a class called ModuleInterface, where
it's not in the module code but an instance is created and attached to each
separate module?

**Comment by ccpandhare** [comment]
That sounds great! 👍

**Comment by jywarren** [comment]
Had another thought on this -- the most basic version of the demo interface could just insert a default `options` object into a textarea, and allow people to just edit it directly in text. This isn't a friendly UI, but it very clearly explains what the UI allows you to do with regard to options. What do you think? 

So a demo UI could: 

1. display the options parameter object for editing
2. display the image after the step is run
3. show a button to re-run the whole sequence at the bottom of the sequence

**Comment by ccpandhare** [comment]
By `options`, do you mean the options in this syntax:
```js
sequencer.addSteps('nodule-name',options)
```
If yes, then I agree with all you've said!

**Comment by jywarren** [comment]
Yep!

**Comment by ccpandhare** [comment]
Please see #67

**Comment by jywarren** [comment]
Ok, I think we should implement an example (maybe all examples?) Using the new UI system. Then link to the examples to show how the UI may be hooked up. What do you think?

**Comment by ccpandhare** [comment]
Yes I think that is a good way to show how to use the UI!

**Comment by ccpandhare** [comment]
Made the FisheyeGl Demo with the new interface.
It can be seen at https://ccpandhare.github.io/image-sequencer/examples/fisheyegl

**Comment by ccpandhare** [comment]
I think we are done with this, closing the issue now! :-)
