### ISSUE TITLE
use require() in index.js to source from /src/cli/

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#658]
The `index.js` file in the root directory runs the CLI interface. But the CLI code is a bit long now, and could be easier to read. Let's break it up into a few different files kept in `/src/cli/` and use `require()` to access them from `index.js`. This will result in cleaner and easier to read code. 

Personally I like this type of task! It can be pretty fun to tidy things up. The CLI tests should help us ensure this is done properly, too. We'd love some help!

**Comment by VibhorCodecianGupta** [comment]
@jywarren PR incoming!

**Comment by VibhorCodecianGupta** [comment]
@jywarren using strict mode is always good, as you mentioned in the PR, let's do it!
However, is the let based error affecting this PR too? I don't think it is...

**Comment by VibhorCodecianGupta** [comment]
@jywarren also, if we'd like to fix the `let` issue in Travis, let's replace it with `var` for now, because using the `strict` mode requires a lot of other things to be taken care of, which I think is best to pursue in a separate issue. A new issue could be created dedicated to introducing the strict scope in js files. For simplicity though, I'd suggest merging #665 without a major overhaul

**Comment by jywarren** [comment]
Oh ok great!

On Jan 12, 2019 6:04 PM, "Vibhor Gupta" <notifications@github.com> wrote:

@jywarren <https://github.com/jywarren> also, if we'd like to fix the let
issue in Travis, let's replace it with var for now, because using the strict
mode requires a lot of other things to be taken care of, which I think is
best to pursue in a separate issue. A new issue could be created dedicated
to introducing the strict scope in js files. For simplicity though, I'd
suggest merging #665 <https://github.com/publiclab/image-sequencer/pull/665>
without a major overhaul

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/publiclab/image-sequencer/issues/658#issuecomment-453787727>,
or mute the thread

**Comment by VibhorCodecianGupta** [comment]
Shall I then? Replace the `let` with `var`?

**Comment by jywarren** [comment]
yes, let's do that. Thanks.

On Jan 12, 2019 6:18 PM, "Vibhor Gupta" <notifications@github.com> wrote:

Shall I then? Replace the let with var?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/publiclab/image-sequencer/issues/658#issuecomment-453788539>,
or mute the thread

**Comment by VibhorCodecianGupta** [comment]
@jywarren done!

**Comment by VibhorCodecianGupta** [comment]
@jywarren is there more work to be done here or is this mergeable for now?

**Comment by VibhorCodecianGupta** [comment]
@jywarren is #665 mergeable?
