### ISSUE TITLE
CLI error did not trigger a Travis failure

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#659]
In #645 we noticed a bug in the CLI version broke that interface - the bug appeared in Travis but did not cause Travis to fail, unfortunately, so we didn't notice it!

The original error was fixed, but actually there seems to be a new one in the CLI, here:

https://travis-ci.org/publiclab/image-sequencer/jobs/478649385#L644-L658

We should ensure that the CLI tests actually detect and report a failure in Travis. @Mridul97 you mentioned you may be interested in working on this one? Thanks!

**Comment by Mridul97** [comment]
@jywarren Yes, I would like to give this one a try!

**Comment by VibhorCodecianGupta** [comment]
@HarshKhandeparkar yes, I fixed them. So Travis is not catching the syntax errors then I presume?

**Comment by HarshKhandeparkar** [comment]
@VibhorCodecianGupta your PR tests are failing because of many reasons but that line 1710 fails in every PR but the overall test does not fail.

**Comment by VibhorCodecianGupta** [comment]
@HarshKhandeparkar I fixed my PR which was failing because of a parsing error. I noticed the line 1710 failing and another similar error (which is now gone because of the fix) that of using `let` outside the `strict` scope. Which is why I was wondering whether it's just Syntax errors that Travis is not catching, but apparently not, as https://travis-ci.org/publiclab/image-sequencer/jobs/478709461#L1710 is too.

**Comment by HarshKhandeparkar** [comment]
@VibhorCodecianGupta what about https://travis-ci.org/publiclab/image-sequencer/jobs/478484508? The build is not failing even though error is thrown.

**Comment by VibhorCodecianGupta** [comment]
That is exactly what I'm saying 😆 
I thought it was for all syntax errors like it is in this one 
> @VibhorCodecianGupta what about https://travis-ci.org/publiclab/image-sequencer/jobs/478484508? The build is not failing even though error is thrown.

but apparently it isn't as can be seen here
> The original error was fixed, but actually there seems to be a new one in the CLI, here:
https://travis-ci.org/publiclab/image-sequencer/jobs/478649385#L644-L658

**Comment by HarshKhandeparkar** [comment]
> That is exactly what I'm saying 
> I thought it was for all syntax errors like it is in this one
> 
> > @VibhorCodecianGupta what about https://travis-ci.org/publiclab/image-sequencer/jobs/478484508? The build is not failing even though error is thrown.
> 
> but apparently it isn't as can be seen here
> 
> > The original error was fixed, but actually there seems to be a new one in the CLI, here:
> > https://travis-ci.org/publiclab/image-sequencer/jobs/478649385#L644-L658
> 
> So the issue is somewhere else

LOL :laughing: I thought you were saying something else.

**Comment by HarshKhandeparkar** [comment]
How about dropping support for node 6? It doesn't support the spread operator and throws an error but travis doesn't fail though. Maybe we have to run `set -e` which will terminate script with a non-0 if any commands which are run inside the script exit with non zero.

**Comment by jywarren** [comment]
+1 to both of these, i think they're fine; can you test out the -e in a PR?
Thank you!

**Comment by HarshKhandeparkar** [comment]
Hmm, i'll try.

**Comment by jywarren** [comment]
Linking to #1550 and https://github.com/publiclab/image-sequencer/issues/1113 !

**Comment by jywarren** [comment]
Fixed in #1718
