### ISSUE TITLE
NodeJS Binary Output

### ISSUE THREAD

**Issue by ccpandhare** [publiclab/image-sequencer#66]
We should allow users on NodeJS to save output to actual binary files!
Agree?
Some gitignored directory like `./output/` could be used for the same

**Comment by jywarren** [comment]
That'd be cool! Although we should just save to the same directory unless
there's a specified destination directory -- and we can look back at this
when we try a commandline interface. +1!

**Comment by ccpandhare** [comment]
Okay!
