### ISSUE TITLE
Module step not getting displayed

### ISSUE THREAD

**Issue by VibhorCodecianGupta** [publiclab/image-sequencer#666]
### Please describe the problem (or idea)

The modules are not getting displayed, this is a bug introduced after implementing the toggle-able collapse for modules.

Screenshot:
![screen shot 2019-01-12 at 9 29 09 pm](https://user-images.githubusercontent.com/29275810/51075438-52760700-16b1-11e9-841b-fe45d27ec813.png)

Upon inspection, this bug has been introduced in e5d26815d7e02310a6463f48240c4027b3e4bce3
****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by VibhorCodecianGupta** [comment]
@jywarren @aashna27 can you guys reproduce this one?

**Comment by aashna27** [comment]
Yeah that's cause of a bootstrap styling, on the bootstrap class that makes the display for collapse class be none, it will get fixed soon.

**Comment by VibhorCodecianGupta** [comment]
@aashna27 yes, I just caught that. You can push the fix if you have the time, or I'll do it whenever I'm free :D

**Comment by HarshKhandeparkar** [comment]
I think you can close this one as @Mridul97 is fixing this.

**Comment by aashna27** [comment]
Mridul has already made a pr.

**Comment by VibhorCodecianGupta** [comment]
Okay! didn't notice. Is there a dedicated issue for this? If this is a duplicate, let's close this. If not, let's keep this up?
#651 is fixing this

**Comment by HarshKhandeparkar** [comment]
@VibhorCodecianGupta maybe mridul can change their pr to link to this issue?

**Comment by VibhorCodecianGupta** [comment]
Sounds good. 
@Mridul97

**Comment by Mridul97** [comment]
Cool! I will do that!
