### ISSUE TITLE
Bootstrap Panel UI for steps

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#673]
Following up on a lot of changes from the past week; I am thinking of how we could integrate a lot of the buttons and features into a better and more coherent design using Bootstrap Panels:

https://getbootstrap.com/docs/3.3/components/#panels-heading

Maybe like this?

![image](https://user-images.githubusercontent.com/24359/51141420-39876600-1817-11e9-9e2a-1822a0ba57de.png)

I /think/ this would work:

```html
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Module name <span class="caret"></span></h3>
        <a class="pull-right btn btn-xs btn-default"><span class="fa fa-trash" aria-hidden="true"></span></a>
    </div>

    <div class="panel-body"></div>

    <div class="panel-footer">
        <a class="btn btn-sm btn-default">Save</a><a class="pull-right btn btn-sm btn-default">
        <span class="fa fa-plus" aria-hidden="true"></span> Insert module</a>
    </div>
</div>
```

This may also give us more flexibility to add more tools and such as the project gets more complex.

**Comment by Mridul97** [comment]
@jywarren I would like to work on this! :smile:

**Comment by jywarren** [comment]
haha ok! Let's try to get our pull request backlog down a bit first,
however. Thanks though, this is exciting!!!

**Comment by Mridul97** [comment]
@jywarren I have caught up with pull request backlog! :smiley:

**Comment by Mridul97** [comment]
@jywarren Sure! I will work on this!

**Comment by Harshithpabbati** [comment]
Was anyone working on this ?? Or can i work on it??

**Comment by jywarren** [comment]
Oh please, that would be super!

**Comment by Harshithpabbati** [comment]
@jywarren can you say me what to add in the panel???

**Comment by jywarren** [comment]
I think we can just put everything that's currently in a step into each pane:

![image](https://user-images.githubusercontent.com/24359/53761808-6b6e8d80-3e94-11e9-9f8a-972a8a02980c.png)

**Comment by Harshithpabbati** [comment]
![bootstrappanel](https://user-images.githubusercontent.com/43822585/53808125-73ebc480-3f77-11e9-8226-ead6ab8cdf40.png)
@jywarren was this ok???

**Comment by Harshithpabbati** [comment]
But still i have to make many things. I just want to know any changes for now.

**Comment by jywarren** [comment]
Basically yes! Although module name could be replaced by the actual module
name, and there's some alignment and spacing issues. But looking good!

**Comment by Harshithpabbati** [comment]
yeah i will make the css properties at the last and will change the name of the module.

**Comment by Harshithpabbati** [comment]
@jywarren we need a new panel for every module right??

**Comment by HarshKhandeparkar** [comment]
Yes

**Comment by HarshKhandeparkar** [comment]
@Harshithpabbati can you open a PR? We can discuss all the changes there.

**Comment by Harshithpabbati** [comment]
Few things needed to be implemented then i will open a pr.

**Comment by HarshKhandeparkar** [comment]
Cool! You can share the next screenshot directly in the PR.

**Comment by Harshithpabbati** [comment]
Yeah for sure!!
