### ISSUE TITLE
Wrong command in PR template.

### ISSUE THREAD

**Issue by Divy123** [publiclab/image-sequencer#676]
### Please describe the problem (or idea)
Current PR template suggests using  ` rake test` but it should be `npm test`.
### Please show us where to look
https://github.com/publiclab/image-sequencer/blob/main/.github/PULL_REQUEST_TEMPLATE.md

**Comment by HarshKhandeparkar** [comment]
@Divy123 this is a good fto-candidate. Can you please add that label and format the issue based on https://github.com/publiclab/plots2/blob/master/.github/ISSUE_TEMPLATE/first-timers-issue-template.md?

**Comment by Divy123** [comment]
@jywarren  please review.

**Comment by HarshKhandeparkar** [comment]
@Divy123 there are only 2 or 3 open first timer issues right now. One of them is being fixed. This is a very good first timers issue. Can you close your pr and let somebody else fix this?

**Comment by Divy123** [comment]
I completely agree with you @HarshKhandeparkar .
That is why I have created one more first-timer-issue.
I realized that there are very less first-timers so I have created this one.
Let this one go as I had already done the work.
Will contribute by opening such f-t issues in future as well.

**Comment by jywarren** [comment]
great thinking, folks! Thanks!
