### ISSUE TITLE
Remove logs in console.

### ISSUE THREAD

**Issue by Divy123** [publiclab/image-sequencer#678]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [$FILENAME]($BRANCH_URL) in the `$REPO` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://publiclab.github.io/community-toolbox/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
$DIFF
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). 

### Problem description:
There are logs in console which are not needed.
> What happened just before the problem occurred? Or what problem could this idea solve?
There are logs in console which are not needed.

> What to expect after resolving the issue?
See a clear console.

###  File to look
[demo.js](https://github.com/publiclab/image-sequencer/blob/main/examples/demo.js)
### What's your PublicLab.org username?
divy123

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by HarshKhandeparkar** [comment]
@Divy123 good but can you please update the format based on the template?

**Comment by Divy123** [comment]
Actually I formatted the template as somethings were not required.

**Comment by himanshuc3** [comment]
Is the UserInterface file not being used anymore? It does not have any logic besides showing console logs.

**Comment by VibhorCodecianGupta** [comment]
@himanshuc3 it logs the steps the sequencer takes during the process. Is it a good idea to remove them just yet? Let's confirm with @jywarren first?

**Comment by HarshKhandeparkar** [comment]
@VibhorCodecianGupta how about adding a verbose mode?

**Comment by jywarren** [comment]
I think the user interface file is designed to be an overridable minimal
reference implementation of the UI code which can be replaced by a more
complex UI. We could add comments to say this explicitly?

**Comment by HarshKhandeparkar** [comment]
@jywarren how about adding a config file of some sort but in a different issue as we are browserifying and refactoring the code anyways. Maybe close this one and find some better but complex solution?

**Comment by puranik9** [comment]
Is this still up for grabs? First timer here

**Comment by HarshKhandeparkar** [comment]
@puranik9 welcome! Can you please wait for @jywarren's approval? If sir says that this issue is good to go, then you can grab it. In the meanwhile, you can search through other issues to find some other first timer only(if any) and see if that interests you. You can also get yourself acquainted with the codebase. Thanks!

**Comment by HarshKhandeparkar** [comment]
Updated the issue based on https://github.com/publiclab/image-sequencer/issues/678#issuecomment-455369262

**Comment by HarshKhandeparkar** [comment]
Updated again as there are no logs in intermediateHtmlStepUi.js

**Comment by himanshuc3** [comment]
@HarshKhandeparkar I've removed the console logs from demo.js.

**Comment by HarshKhandeparkar** [comment]
@himanshuc3 please do the changes suggested in your PR
