### ISSUE TITLE
Should Node-Canvas be used?

### ISSUE THREAD

**Issue by ccpandhare** [publiclab/image-sequencer#68]
I know, we've had this discussion about node-canvas earlier, but since quite a lot of algorithms are based on canvas, Do you think we should include `node-canvas` in image sequencer anyway?

**Comment by jywarren** [comment]
I think only if there's additional optimization we can offer - like a
reusable canvas to save memory, or a compatibility fallback. Otherwise it
may make the lib unnecessarily heavy. What do you think?

**Comment by ccpandhare** [comment]
Yes, I was thinking about it. I don't think we need canvas. We need WebGL contexts actually.

I found this on NPM:
[gl | Headless WebGL Context in Node.js](https://www.npmjs.com/package/gl)

What do you think about this?

**Comment by ccpandhare** [comment]
Actually that may not be a very good idea, since it is still under development, also, `node-canvas` has less dependancies (3) than `gl` (6)...

I guess we still need to think about this more...

**Comment by jywarren** [comment]
Yeah, we can wait a bit. But we could also just require `phantomjs` to do this, perhaps? In any case let's wait a bit for now; does `node-canvas` or `phantomjs` provide WebGL?

**Comment by ccpandhare** [comment]
Node-canvas doesn't provide WebGL as far as I know, PhantomJS doesn't intend to support WebGL since it's a headless browser, and supporting WebGL would require an OpenGL capable system - and PhantomJS would no longer remain self contained. (Source: phantomjs)

Other npm modules like the one I have stated above provides WebGL ports.
