### ISSUE TITLE
Switch to npm for gifshot

### ISSUE THREAD

**Issue by vrk99** [publiclab/image-sequencer#687]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update**: the file [package.json](https://github.com/publiclab/image-sequencer/blob/main/package.json) as following: 
Add the line : **"gifshot": "^0.4.5",** after the **"get-pixels": "~3.3.0",** line

- [ ] **Delete** the following file [gifshot.js](https://github.com/publiclab/image-sequencer/blob/main/examples/gifshot.js)

- [ ] 📝 **Update**: the file [index.html](https://github.com/publiclab/image-sequencer/blob/main/examples/index.html) as following: 
Change line 28 from **<script src="gifshot.js" type="text/javascript"></script>** to **<script src="../node_modules/gifshot/dist/gifshot.min.js" type="text/javascript"></script>**

[See this page](https://publiclab.github.io/community-toolbox/#r=all) for some help in taking your first steps!

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

**Comment by vrk99** [comment]
@publiclab/is-reviewers 
Can you review this issue and add the labels. Thank You

**Comment by gauravano** [comment]
Thanks for opening FTO @vrk99!

**Comment by atsutton** [comment]
Hello -- I'd love to handle this for my first issue. Is that possible?

**Comment by HarshKhandeparkar** [comment]
@atsutton welcome! You can go ahead and resolve this one. You can ask any queries here too!

**Comment by ihabmhadi** [comment]
It is smoe thing ican not understand
