### ISSUE TITLE
Create Histogram Module

### ISSUE THREAD

**Issue by ccpandhare** [publiclab/image-sequencer#69]
Also, don't you think that the steps after histogram should use the output from the step BEFORE histogram?
It doesn't quite make sense to apply a module on the "histogram" output.
So what we can do is, the histogram module shows the histogram of the image but passes on ITS INPUT as its output to OTHER modules.

Similarly for the QR Code module?

**Comment by jywarren** [comment]
Yeah, perhaps we should wait on this a bit. It seems almost like a use case external to `image-sequencer`, as useful as it is.

**Comment by ccpandhare** [comment]
You did talk about "Terminating Modules" long ago in #13, I think that can actually be made a thing!
Like we can provide histograms for any image in a sequence, when demanded by the user!
A histogram in the middle of a sequence doesn't make much sense, but one as an on-demand side chain does!

```
load-image ──> module-1 ──> module-2 ──> module-3
                  │                         │
              histogram                 histogram
```

**Comment by jywarren** [comment]
+1

On Wed, Jul 26, 2017 at 10:38 PM, Chinmay Pandhare <notifications@github.com

**Comment by ccpandhare** [comment]
We shouldn;t use the

**Comment by ccpandhare** [comment]
We shouldn't use the `Plotly` one right?
As far as I remember it was slow (#13)

**Comment by tech4GT** [comment]
@jywarren i was reading up on this and I think I can make this work! I was thinking maybe we can overlay the histogram on the bottom of the image itself, what say?
So histogram can be a meta module which calculates the histogram and overlays it onto the image.

**Comment by jywarren** [comment]
Cool!

**Comment by jywarren** [comment]
Maybe we can set where the overlay goes?

**Comment by tech4GT** [comment]
@jywarren please have a look at #354 I have made a basic module for this there.
One thing I can't decide on is whether to make this a meta-module or to include the overlay code in histogram module only, what do you think @jywarren ?

**Comment by tech4GT** [comment]
I guess we can do something having a module which generates the histogram and then have a separate meta-module `histogram-overlay`

**Comment by jywarren** [comment]
👍🏽 good thinking!

**Comment by tech4GT** [comment]
Closing this one now! 🎉

**Comment by jywarren** [comment]
🙌
