### ISSUE TITLE
Input text is too close to edges

### ISSUE THREAD

**Issue by sashadev-sky** [publiclab/image-sequencer#692]
## First Time?

This is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/image-sequencer/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

## The problem

After updating some of our modules to have sliders instead of text input fields, some of the styling we provided for the sliders overwrote the styling for the text input fields as well. This resulted in all of our input fields having their padding removed.

For ex: [http://sequencer.publiclab.org/examples/#steps=crop{}](http://sequencer.publiclab.org/examples/#steps=crop{})

<img width="819" alt="screen shot 2019-01-20 at 11 26 23 pm" src="https://user-images.githubusercontent.com/41092741/51453079-6225c900-1d0b-11e9-8323-adf8dcd2e437.png">

## Solution

We will make our css declaration more specific so that it only removed padding on sliders:

On the demo.css page, for the below declaration add the attribute selector `[type="range"]` to the class selector `.form-control` so that it no longer effects the text input fields.

https://github.com/publiclab/image-sequencer/blob/17d79c4b44c5e5b8f7f8b4574a783d5b87cdf871/examples/demo.css#L45-L47

Thanks!!

## Steps to Fix
 
- [ ] Claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] Fork the repository and set it up locally following the main repo README instructions [https://github.com/publiclab/image-sequencer/blob/main/README.md](https://github.com/publiclab/image-sequencer/blob/main/README.md)
 - [ ] Create a new feature branch with a unique name descriptive to the issue
- [ ] Try to fix the issue following the steps above, but even before you're done, you can:
  commit your changes to your branch and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] Reference this issue in your pull request body
- [ ] Once you submit your pull request, an additional checklist will be provided for getting it merged

##  💬   Get help
If you need any help - here are some options: 

- Comment below
- Join our gitter chat at https://gitter.im/publiclab/publiclab

**Comment by nic-og** [comment]
Hi, I'd like to handle this for my first issue. Is that possible?

**Comment by sashadev-sky** [comment]
@nic-og Yes, we would love your help! Thank you :+1:
