### ISSUE TITLE
Center Cropped Image

### ISSUE THREAD

**Issue by HarshKhandeparkar** [publiclab/image-sequencer#698]
### Please describe the problem (or idea)

After an image is cropped it is aligned to the top left corner. Instead, it can be centered.

> What happened just before the problem occurred? Or what problem could this idea solve?

![screenshot from 2019-01-22 11-32-01](https://user-images.githubusercontent.com/34770591/51515388-7b2c9800-1e39-11e9-9b2d-9d03367c6f6d.png)

### Possible FTO

This is a potential `first-timers-only` issue. If you are new to the community, then you can reformat this issue into a first timer only issue and mention `@publiclab/is-reviewers` to add the label. If you have contributed to Image Sequencer before, then you can resolve this one as a second-time contribution.

##### HTML (this is where the img element is)

https://github.com/publiclab/image-sequencer/blob/17d79c4b44c5e5b8f7f8b4574a783d5b87cdf871/examples/lib/defaultHtmlStepUi.js#L33-L36

#### Possible fixes.

A bootstrap class or some CSS can be used to center the image

### Please show us where to look

http://sequencer.publiclab.org...

### What's your PublicLab.org username?

> This can help us diagnose the issue:

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by harsh1599** [comment]
Hey! I would llke to work on this.

**Comment by HarshKhandeparkar** [comment]
@harsh1599 go ahead! you can resolve this as a 2nd time contribution to get acquainted with the codebase

**Comment by harsh1599** [comment]
We want the thumbnail to be in the center right?

**Comment by harsh1599** [comment]
![screenshot from 2019-01-22 22-42-37](https://user-images.githubusercontent.com/33490577/51552736-3f282000-1e97-11e9-81de-75655fe4894c.png)
Is this the desired result?

**Comment by HarshKhandeparkar** [comment]
@harsh1999 it looks good but can you center it vertically?

**Comment by HarshKhandeparkar** [comment]
Btw what is the name of the icon pack you are using? Looks pretty cool. Sorry for going off topic 😜

**Comment by harsh1599** [comment]
It's called hicolor-icon-theme I guess..I'm not really sure..coz it came preinstalled with ubuntu and I'm a beginner so I'm not really aware of any icon themes.

**Comment by HarshKhandeparkar** [comment]
> It's called hicolor-icon-theme I guess..I'm not really sure..coz it came preinstalled with ubuntu and I'm a beginner so I'm not really aware of any icon themes.

Oh I guess it is the new community theme which comes preinstalled. I haven't tried that before. Thanks anyways. Also please try to center the image vertically. @harsh1599

**Comment by harsh1599** [comment]
Hey! I tried really hard..but I am unable to center it vertically as the "col-md-8" class spans vertically only as much as the image does and I am not able to find how to stretch the div vertically..it would be great if you could suggest something @HarshKhandeparkar

**Comment by HarshKhandeparkar** [comment]
> Hey! I tried really hard..but I am unable to center it vertically as the "col-md-8" class spans vertically only as much as the image does and I am not able to find how to stretch the div vertically.. I even tried using flexbox, but it won't work..it would be great if you could suggest something @HarshKhandeparkar

Ok. I'm not as good st CSS. Maybe @aashna27 can help?

**Comment by akshaygupta533** [comment]
Can I work on this? The vertical alignment part.

**Comment by HarshKhandeparkar** [comment]
@akshaygupta533 if @harsh1999 wants then you two can collaborate.

**Comment by harsh1599** [comment]
I try one last time..is this the desired output
![screenshot from 2019-01-23 19-28-03](https://user-images.githubusercontent.com/33490577/51611394-26764380-1f45-11e9-9f5f-8ee2838c1563.png)

**Comment by HarshKhandeparkar** [comment]
@harsh1999 awesome. Just make sure it works on all screen sizes. @akshaygupta533 maybe you can work on some other issue?

**Comment by HarshKhandeparkar** [comment]
Also please make sure this works for all crop sizes.

**Comment by HarshKhandeparkar** [comment]
@harsh1999 you can open a pr and we can discuss this there.

**Comment by akshaygupta533** [comment]
On inspecting the img element, the style attribute is empty even though "max-width=100%" is added in code. I am running a local environement. Any idea why this is the case?

**Comment by HarshKhandeparkar** [comment]
Please click the clear cache button. Also you will have to run `grunt
build` if js files are changed

On 23-Jan-2019 7:53 PM, "Akshay Gupta" <notifications@github.com> wrote:

On inspecting the img element, the style attribute is empty even though
"max-width=100%" is added in code. I am running a local environement. Any
idea why this is the case?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/publiclab/image-sequencer/issues/698#issuecomment-456819326>,
or mute the thread

**Comment by harsh1599** [comment]
Done @HarshKhandeparkar

**Comment by Harshithpabbati** [comment]
can I work on this??

**Comment by HarshKhandeparkar** [comment]
@Harshitpabbati there is an open pr fixing this. Maybe you can try fixing some other issue?

**Comment by Harshithpabbati** [comment]
It looks ready to merge :+1: 
Awesome work @harsh1599
