### ISSUE TITLE
Use of socket.io for two people to work on same image simultaneously(Long Term)

### ISSUE THREAD

**Issue by Divy123** [publiclab/image-sequencer#718]
This feature involves two people to edit the same image by using web sockets which can be a good use case for collaborative image-sequencing.

**Comment by VibhorCodecianGupta** [comment]
I don't fully understand the use case of this.
The sequencer provides the ability to save the chained sequences already. If for example, user A wants to edit an image a certain way, they can create a sequence and export it to user B who can then edit the same by chaining more modules. Would there be a need to create sequences via web sockets?

**Comment by Divy123** [comment]
So the point is suppose there are two users who want to create a sequence of image by applying different effects simultaneously working for some project(lets say).
Won't that be better that we provide that sharing included in our image-sequencer itself which can save the time of both else they would open some external sharing medium and do all this stuff.
Suppose the users have to do this very frequently which can actually waste a lot of time using external source of sharing.
So by this  the things can be made quite handy.

**Comment by VibhorCodecianGupta** [comment]
Hmm. @jywarren thoughts?
I still feel using a socket for this sake might be overkill. Something, like allowing sending your created and saved sequences over file-sharing networks or emails etc, would be cooler. Let's brainstorm on this and see what comes up.

**Comment by Divy123** [comment]
Sure let's see .
Also I would be happy with your collaboration on this.
Thanks😄

**Comment by jywarren** [comment]
This is really interesting... I actually want to suggest that we consider
something like this for
https://github.com/publiclab/Leaflet.DistortableImage

Or for https://github.com/publiclab/mapknitter which uses the above lib.
Any interest in something like that?

**Comment by HarshKhandeparkar** [comment]
@jywarren can you please provide some info about leaflet.distortableimage and mapknitter? Also what part of those libraries are similar to this issue?

**Comment by jywarren** [comment]
Ah just noting that it's a very strong use case for sockets because there's
strong interest in simultaneous editing there. Whereas here that would be
interesting but perhaps also not a core goal of the library. Thanks!!

**Comment by Divy123** [comment]
Thanks @jywarren. 
I would be really happy to contribute towards the same 
Could you please guide me how should I proceed?
Using websockets to implement this feature is quite awesome.

**Comment by Divy123** [comment]
@jywarren can you please help me out with this?

**Comment by Divy123** [comment]
No problem @jywarren . Happy journey :smile:

**Comment by jywarren** [comment]
Hi! Please check out these ideas I've written out at greater length!

https://publiclab.org/wiki/gsoc-ideas#MapKnitter+Synchronous+Editing

**Comment by jywarren** [comment]
Related to https://github.com/publiclab/mapknitter/issues/300

**Comment by Harshithpabbati** [comment]
Does anyone working on it??? I am really interested in taking it to work. Can I ??

**Comment by HarshKhandeparkar** [comment]
Harshith this is an advanced issue. Also please not that this is a long term one which means that it is not our main priority as of now. If you are ok with it then you can start brainstorming rather than opening a straight PR. Thanks!

**Comment by Harshithpabbati** [comment]
@HarshKhandeparkar yeah sure. I made a similar app where we can chat with other one who comes to the same room.So i was really interested in making it out .
Thanks

**Comment by HarshKhandeparkar** [comment]
Go ahead

**Comment by Harshithpabbati** [comment]
shall i work on it or else wait for sometime??

**Comment by HarshKhandeparkar** [comment]
@jywarren @publiclab/is-reviewers what are your thoughts?

**Comment by Divy123** [comment]
This issue turned out to be more helpful in case of https://github.com/publiclab/Leaflet.DistortableImage .
So its not of much consideration here .
You may give it a try there. 
Thanks.

**Comment by jywarren** [comment]
Hi - I think this is a bit complex of a use case to think about, in part because it could require a server to track changes. I suggested that people interested in sockets work might look at another Public Lab project where we're more likely to tackle this sooner, as it's a higher priority. 

I'd recommend looking at the "simultaneous multi-user UI, like Google docs" section of https://github.com/publiclab/mapknitter/issues/300 if you're interested. 

I think we could continue brainstorming here, but we'd have to really map out how it'd work and what'd be required and since we're already going to be doing that sooner for mapknitter, I thought that's a place we could prototype this idea a bit. Thanks!

**Comment by Harshithpabbati** [comment]
I made an web app using socket.io. I will host it in something like heroku and send you the link.See it and say what changes should i make in it .what do you say??

**Comment by Harshithpabbati** [comment]
Checkout this link https://afternoon-lake-15004.herokuapp.com/
Thanks

**Comment by Harshithpabbati** [comment]
@publiclab/is-reviewers what do you say???

**Comment by jywarren** [comment]
Hi, all, so, after discussing and such, I think I'll close this and we can focus on use of sockets in other projects. Thank you!
