### ISSUE TITLE
Add New Modules To The Docs

### ISSUE THREAD

**Issue by HarshKhandeparkar** [publiclab/image-sequencer#719]
### Please describe the problem (or idea)

Some of the new modules which were added recently are not added to the `docs/modules.md` file.

- [ ] [Dither](https://github.com/publiclab/image-sequencer/blob/main/src/modules/Dither/info.json)
- [ ] [DrawRectangle](https://github.com/publiclab/image-sequencer/blob/main/src/modules/DrawRectangle/info.json)
- [ ] [PaintBucket](https://github.com/publiclab/image-sequencer/blob/main/src/modules/PaintBucket/info.json)
- [ ] [WhiteBalance](https://github.com/publiclab/image-sequencer/blob/main/src/modules/WhiteBalance/info.json)
- [ ] [Tint](https://github.com/publiclab/image-sequencer/blob/main/src/modules/Tint/info.json)
- [ ] [Threshold](https://github.com/publiclab/image-sequencer/blob/main/src/modules/Threshold/info.json)
- [ ] [FlipImage](https://github.com/publiclab/image-sequencer/blob/main/src/modules/FlipImage/info.json)

Current [modules.md](https://github.com/publiclab/image-sequencer/blob/main/docs/MODULES.md)

### Files to look into
- **info.json**: All the modules listed above link to their info.json files. You will get information about the modules there. You have to change these files to add a new property `docs-link` which is a link to their docs in the modules.md file.
- **modules.md**: The modules.md file linked above should be changed and docs to all modules should be added there.

#### Optional
All the module info.json files have linked directly to the modules.md file but the link does not link to the part that concerns the module.
https://github.com/publiclab/image-sequencer/blob/c445070937a9eb069745ced983f210b2f16da40b/src/modules/Channel/info.json#L12

Optionally add a link to the part of the modules.md file which documents the module.
For e.g. the following link links to the docs for channel module

https://github.com/publiclab/image-sequencer/blob/main/docs/MODULES.md#channel-module

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by harsh1599** [comment]
I would like to work on this..

**Comment by HarshKhandeparkar** [comment]
You can go ahead and resolve this but if you can resolve some other issue
then consider leaving this one for a first time

**Comment by HarshKhandeparkar** [comment]
@harsh1599 if you have already started work then you can go ahead and open a PR. Thanks! 😊

**Comment by harsh1599** [comment]
Okay I'll take up another one

**Comment by HarshKhandeparkar** [comment]
😊

**Comment by HarshKhandeparkar** [comment]
@harsh1599 actually you can resolve this one as this is going to give you knowledge about the modules. So if you are interested then you can solve this one

**Comment by harsh1599** [comment]
Sure..I'll solve this

**Comment by HarshKhandeparkar** [comment]
:+1:

**Comment by harsh1599** [comment]
I'm a bit confused. Everything is present in the info.json file right? Like I need to just specify the options and the what they all do right?@HarshKhandeparkar

**Comment by HarshKhandeparkar** [comment]
@harsh1599 the docs file is added so that people can go through it easily instead of going through all the info files. Also, people who don't have knowledge about JSON can read it.

**Comment by HarshKhandeparkar** [comment]
@harsh1599 the info files may not have all the information you might have to add some info of your own sometimes. Even examples can be added.

**Comment by lohitha02** [comment]
Hello, Can I work on this issue?

**Comment by HarshKhandeparkar** [comment]
Go ahead!

**Comment by HarshKhandeparkar** [comment]
Please note that I have added two new modules to the list above. Thanks!

**Comment by lohitha02** [comment]
So I have to add the links to all the six modules that you've mentioned above right?

**Comment by HarshKhandeparkar** [comment]
Yes. You don't just have to add links. You also have to document the modules which is the main purpose of this issue.

**Comment by lohitha02** [comment]
From where can I get the information about the above mentioned modules?

**Comment by lohitha02** [comment]
@HarshKhandeparkar  please review my pr I've linked all the modules that concerns the part of the module

**Comment by lohitha02** [comment]
@HarshKhandeparkar I've done it can you please review it and let me know if I have to make any changes.

**Comment by HarshKhandeparkar** [comment]
@lohitha a new FlipImage was added recently can you also add that to the docs?

**Comment by lohitha02** [comment]
@HarshKhandeparkar what about replacecolor module?

**Comment by HarshKhandeparkar** [comment]
You can document it
