### ISSUE TITLE
Buttons going out of their parent element in mobile view

### ISSUE THREAD

**Issue by gauravano** [publiclab/image-sequencer#725]
Hi, while testing the mobile-view for checking. Noted that buttons "Save Sequence" and "view Gif" are going out of their parent element as seen in the image below:

![buttons_out](https://user-images.githubusercontent.com/20878070/51872716-778c9a00-2380-11e9-9bde-284dc7cc6ea0.png)

cc @publiclab/is-reviewers I think, this can be converted to FTO, feel free to edit the issue as required. Thanks!

**Comment by rexagod** [comment]
@gauravano You may close this now. I've made one here #726.

**Comment by gauravano** [comment]
Thanks @rexagod for opening a FTO :smiley:
