### ISSUE TITLE
Adjust buttons respective to viewport

### ISSUE THREAD

**Issue by rexagod** [publiclab/image-sequencer#726]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/PublicLab.Editor/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update**: Currently the buttons specified [here](https://github.com/publiclab/image-sequencer/issues/725) are not responsive due to the fact that their widths have been defined in `px` or pixels. You need to set the **widths** of both of these buttons to `35%` so that they can adjust accordingly. Changes that need to made are located in `demo.css` file.
https://github.com/publiclab/image-sequencer/blob/c445070937a9eb069745ced983f210b2f16da40b/examples/demo.css#L134-L138
https://github.com/publiclab/image-sequencer/blob/c445070937a9eb069745ced983f210b2f16da40b/examples/demo.css#L143-L147

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there.

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

**Comment by VibhorCodecianGupta** [comment]
@gauravano @rexagod I already tried something like this previously, check [this commit](https://github.com/publiclab/image-sequencer/pull/583/commits/522aa979fa1cdb457b3e27288399cbfcb1d1ddbd) out.

adding media queries and removing `min-width` solves this issue, but discussions with @jywarren on that PR concluded in not going for complex CSS manipulations, please check the PR for reference.

**Comment by gauravano** [comment]
@jywarren should we close this one then?

**Comment by rexagod** [comment]
Hey @VibhorCodecianGupta! I really don't think there's anything complex here. The widths are just being converted to a dynamic proportion here that inherit the parent's width. Changing `250px` to `35%` is all that needs to be done here, no media queries, no min-width removal. This in my opinion is one of the simplest solutions for this issue, but if there's some fault in it though that I may not be seeing, please feel free to close this issue. Thanks!

**Comment by HarshKhandeparkar** [comment]
@rexagod @VibhorCodecianGupta I'm adding the label for now. Don't relly know if this should be closed

**Comment by jywarren** [comment]
I mainly meant we should try to focus on a slight overhaul of this UI area - i opened an issue for it today! #735 But this is also fine as a shorter term solution! 👍

**Comment by ananyaarun** [comment]
May i work on this issue , if it is still valid ? @jywarren

**Comment by gauravano** [comment]
Hi @ananyaarun, actually the PR #735 is solved but the branch `gh-pages` still needs to be updated with the commit so let's wait for the push to the branch to see if this issue is solved or not. I guess @IgorWilbert can confirm too? Thanks!

**Comment by Harshithpabbati** [comment]
can i work on this issue @jywarren

**Comment by jywarren** [comment]
Hi, all, i believe this is resolved now and will close this accordingly. Perhaps some other Image Sequencer community members would be willing to help @Harshithpabbati and @ananyaarun find a new issue to work on? Thanks all!
