### ISSUE TITLE
Minor Fix required in CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by Yugandhartripathi** [publiclab/image-sequencer#727]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you :gift_heart: 

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/PublicLab.Editor/labels/help-wanted) issues. Thanks!

## :thinking: What you will need to know.
Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### Problem
![image](https://user-images.githubusercontent.com/32102845/51910498-63cf4b00-23f5-11e9-912f-a3493734a056.png)

### :clipboard:  Step by Step
- [ ] :raising_hand_woman: Claim this issue: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!
- [ ]  :memo: Update: open [CODE_OF_CONDUCT.md file](https://github.com/publiclab/image-sequencer/blob/main/CODE_OF_CONDUCT.md) in edit mode and go to the problem line(line 46) underlined with red in above image and add a blank space between "###" and "The" .
### After Update preview should look like this 
![image](https://user-images.githubusercontent.com/32102845/51909385-80b64f00-23f2-11e9-8d0a-3f28efb941d1.png)
- [ ] :floppy_disk: Commit your changes
- [ ] :twisted_rightwards_arrows: Start a Pull Request. There are two ways how you can start a pull request:
1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there.
- [ ]  :checkered_flag: Done Ask in comments for a review :)

### :thinking::question: Questions?
Leave a comment below. I would be happy to help you out !

### Is someone else already working on this?
We encourage you to **link to this issue by mentioning the issue # in your pull request**, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

**Comment by HarshKhandeparkar** [comment]
Thanks, @Yugandhartripathi. Also can you please link to the code of conduct file in the PR body where it is mentioned.

**Comment by Yugandhartripathi** [comment]
@HarshKhandeparkar Thanks for adding the tag, added line number and link to the code of conduct file.

**Comment by dav1d337** [comment]
Hi, can i do this?

**Comment by HarshKhandeparkar** [comment]
Go ahead

**Comment by Chimdiya1** [comment]
Can I still do this?

**Comment by HarshKhandeparkar** [comment]
@Chimdiya1 @dav1d337 has already opened a PR. You can try resolving one of [these](https://github.com/publiclab/image-sequencer/labels/fto-candidate) or [these](https://github.com/publiclab/image-sequencer/labels/first-timers-only) if it is not taken up
