### ISSUE TITLE
Detect and parse any input syntax type (string, obj) in addSteps, replaceImage methods

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#731]
I noticed that `sequencer.addSteps('invert,ndvi')` doesn't work because it doesn't recognize and parse the string. We should detect commas and pre-filter the input using `sequencer.importString()` so that we can simply pass multiple steps in via `addSteps()`

This shouldn't be too hard, and we can add this as an example to the README too, where actually we don't show the use of string syntax -- we can demonstrate in a new subsection:

```

Use string syntax (see below) to add multiple steps and configurations quickly by passing a string to `sequencer.addStep()`:

...example...

```

This'd be a really nice refinement!

**Comment by jywarren** [comment]
Just a note that:

1. `addSteps()` and `insertSteps()` share an implementation, so we'd best make this improvement work for both.
2. any of the input types listed in https://github.com/publiclab/image-sequencer#string-syntax ought to still return the sequencer object itself, so that the methods can be chained, like `sequencer.addSteps().run()`

Thanks!

**Comment by jywarren** [comment]
And actually we should check that there's a test for their chainability -- i think there is, if I remember right!

**Comment by VibhorCodecianGupta** [comment]
Hmm. Working on this!

**Comment by jywarren** [comment]
Awesome!!

**Comment by jywarren** [comment]
I just linked to this from https://github.com/publiclab/leaflet-tile-filter/issues/3 because once this is complete we should be able to vastly improve that use case! Thanks @VibhorCodecianGupta !
