### ISSUE TITLE
Provide example of JSON style steps syntax in README

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#732]
In the docs here: https://github.com/publiclab/image-sequencer#string-syntax

we describe how a steps object can be passed in:

```
sequencer.importJSON(obj) //Imports the given sequence of JSON steps into sequencer
```

But we don't describe the formatting. I think there is an example in the tests, we can link to and/or quote in the docs. We should have a brief section below the string syntax section in the docs showing an example of the object syntax!

Also, we should ensure `addSteps()` can also accept a command JSON object too, as in #731 -- that could be a nice follow-up!

**Comment by Divy123** [comment]
I would like to work upon this issue.

**Comment by Divy123** [comment]
@jywarren just one thing that by saying 'command JSON object' does that mean JSON object from command line?

**Comment by jywarren** [comment]
or in the JS console on a webpage. I think there are examples of this in
the tests, just not in the README!
