### ISSUE TITLE
Change style of "take a photo" button

### ISSUE THREAD

**Issue by IgorWilbert** [publiclab/image-sequencer#733]
### Please describe the problem (or idea)
I thought it would be interesting to apply some style in these buttons, so that they match the buttons below. If you agree, I'll turn this into a **FTO Issue**, it is a one line of code change. Changing the "Browse.." button is not so simple, since it uses the default `input type="file"` tag. I'd have to either use a CSS file, make extensive changes in the HTML using CSS or make it from scratch using actual buttons.

#### Before 
![salvar](https://user-images.githubusercontent.com/42987854/52006131-8e330e00-24b2-11e9-9a5f-3a3f78431dcb.JPG)

#### After 
![after](https://user-images.githubusercontent.com/42987854/52006153-9db25700-24b2-11e9-9947-5e65e10dab77.JPG)

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by jywarren** [comment]
This sounds great!
