### ISSUE TITLE
New design layout for Save and Add areas

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#735]
I'd like to reorganize the Save and Add boxes a bit, because they're a bit confusing, i think. 

![image](https://user-images.githubusercontent.com/24359/52079470-a31baa00-2563-11e9-9687-2aae5c09fcdd.png)

Brainstorming some issues:

1. the difference between Save sequence and Save image may be confusing
2. we should have a place to output the whole string syntax of the current sequencer, besides just the URL bar
3. maybe View Gif and Download PNG should be near each other since they're kind of similar?
4. We should highlight the most common actions and de-emphasize ones that are a bit more obscure, maybe?

What about something like this?

![image](https://user-images.githubusercontent.com/24359/52079728-3228c200-2564-11e9-971a-1d05fa913566.png)

Love to hear ideas and input!

**Comment by IgorWilbert** [comment]
Great ideas @jywarren ! If you have no rush, I'd like to work on this. I could create a PR and update it as the ideas come up in this discussion.

**Comment by HarshKhandeparkar** [comment]
@IgorWilbert go ahead!

**Comment by jywarren** [comment]
That'd be awesome!
