### ISSUE TITLE
Runkit.com demo

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#74]
low priority, but kind of interesting -- i think this is currently still waiting for the newly published npmjs module to update, but could/should work? 

https://runkit.com/jywarren/image-sequencer

Nice to give people a Node demo sandbox to work with :-)

**Comment by ccpandhare** [comment]
Yes, It should work!

**Comment by ccpandhare** [comment]
There's a small problem here:
https://runkit.com/embed/epjvm3wepv8c
```
TypeError: ImageSequencer is not a function
```

**Comment by ccpandhare** [comment]
Is this still waiting for npmjs to update?

**Comment by jywarren** [comment]
yeah i dunno why it's stuck... i reported the module missing again.

On Wed, Jul 26, 2017 at 10:07 PM, Chinmay Pandhare <notifications@github.com

**Comment by ccpandhare** [comment]
I realized we have the same issue as in [fisheyegl/#17](https://github.com/jywarren/fisheyegl/issues/17)
We are requiring in `./dist/image-sequencer.js` which returns an empty object `{}`. That is why the RunKit isn't working.

While testing we usually do `require('./src/ImageSequencer.js')` and not `require('./dist/ImageSequencer.js')`. The latter returns an empty object, the former returns the intended Image Sequencer function.

**Comment by ccpandhare** [comment]
Is there a workaround for this such that browserify produces a file which can be both used in Browser as well as required in Node?

**Comment by jywarren** [comment]
hmm, i'm not sure... can you do a check for window, and instantiate
accordingly? Or perhaps we need to append a separately wrapped version for
node usage?

On Wed, Jul 26, 2017 at 11:01 PM, Chinmay Pandhare <notifications@github.com

**Comment by ccpandhare** [comment]
I already am instantiating according to the presence of `window`. That's why :
* `./src/ImageSequencer.js` can be required in Node.js
* `./dist/image-sequencer.js` can be run in Browser

Maybe this has to do with the way Browserify handles everything, I am not sure...

**Comment by ccpandhare** [comment]
What would happen if we changed `package.json` to:
```js
...
main: "src/ImageSequencer.js"
...
```
?

Whoever is using npm will be `require()`-ing Image Sequencer, so it should work for everyone...
Is `./dist/image-sequencer.js` supposed to be served by npm, or by a CDN?

**Comment by jywarren** [comment]
I was just thinking the same thing. Let's try it! You can npm require a
branch directly via a URL from an upstream package.json to test it out.

**Comment by ccpandhare** [comment]
Yes I have tried it! It works!
```
npm i git+https://github.com/ccpandhare/image-sequencer.git#npm
```

**Comment by jywarren** [comment]
Super. Merge a PR with that package.json and bump the version number, and
let's try runkit again. :-)

**Comment by ccpandhare** [comment]
I have merged the PR ( #84 ).
I don't have publish privileges, So I can't bump the version, so I request you to publish the new version!
It must work this time :-)

**Comment by jywarren** [comment]
OK, i published but then noticed #84 failed tests? Can you figure that out? 

https://www.npmjs.com/package/image-sequencer

Thanks!

**Comment by ccpandhare** [comment]
![screenshot_ -](https://user-images.githubusercontent.com/20787612/28687169-372cf34e-732b-11e7-8633-795daf05d80d.jpg)
I don't think #84 failed tests, It's just that I merged the PR before the TravisCI build completed.

**Comment by ccpandhare** [comment]
I checked TravisCI. #84 had passed. The build didn't fail, I think the "cross" is shown on the commit in #84 because I merged it in before the TravisCI build completed.

**Comment by jywarren** [comment]
Ah ok!

**Comment by ccpandhare** [comment]
https://runkit.com/embed/hvtvir55gm5v

It works now!

**Comment by ccpandhare** [comment]
Closing this issue.

**Comment by jywarren** [comment]
Great, can you add this to the README too?
