### ISSUE TITLE
Next steps on UI testing

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#740]
https://github.com/publiclab/image-sequencer/pull/720 implemented UI tests, which is GREAT. Let's make a list of next steps:

* [x] build out some actual test assertions
* [x] connect it to the Travis output: https://travis-ci.org/publiclab/image-sequencer/jobs/487565932, see below

So `npm test-ui` should run it:

https://github.com/publiclab/image-sequencer/blob/3081dccf19114d8e7e814a66a791e691a17523c4/package.json#L8-L9

Let's add that to `.travis.yml`:

https://github.com/publiclab/image-sequencer/blob/3081dccf19114d8e7e814a66a791e691a17523c4/.travis.yml#L14

What else?

**Comment by jywarren** [comment]
Opened a PR!

**Comment by VibhorCodecianGupta** [comment]
@jywarren #791 adds ui test script to travis, and configures code coverage as well.

**Comment by jywarren** [comment]
amazing!

**Comment by jywarren** [comment]
This is looking good now -- I'm going to close it but if we come up with other ideas on how to test and stabilize the UI code, that'd be great too!
