### ISSUE TITLE
select module box with a search option  

### ISSUE THREAD

**Issue by bhavayAnand9** [publiclab/image-sequencer#747]
### Please describe the problem (or idea)
As our list of modules is increasing it'll be getting difficult to find a particular module from the select box. So I think it'll be more convenient if we add a search option.

imagine you just know the module name so instead of searching for the module in that list we can start typing and filtering out that module from the list.

### Please show us where to look
something like this...
https://codepen.io/tipdub/full/AXJpKj
https://codepen.io/Rio517/full/NPLbpP

http://sequencer.publiclab.org...

### What's your PublicLab.org username?

> This can help us diagnose the issue:

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by HarshKhandeparkar** [comment]
@bhavayAnand9 is there any lib which can provide help here?

**Comment by Divy123** [comment]
I think this can be done by a simple search function and I would love to implement it.

**Comment by bhavayAnand9** [comment]
https://select2.org/searching
https://developer.snapappointments.com/bootstrap-select/
https://selectize.github.io/selectize.js/

But I aslo think we should consider doing it with jquery or vanilla js.
@Divy123 we'd love your help but let's first get a go signal from @jywarren

**Comment by Divy123** [comment]
Sure @bhavayAnand9 .

**Comment by Divy123** [comment]
@jywarren should I proceed with vanilla js?

**Comment by jywarren** [comment]
Cool, the https://selectize.github.io/selectize.js/ options of "groups"
looks good!

**Comment by Divy123** [comment]
Thanks I will proceed with this.

**Comment by Divy123** [comment]
![ezgif com-gif-maker 1](https://user-images.githubusercontent.com/31225007/52427652-5ff2a580-2b26-11e9-807f-8dfd677a93c8.gif)
