### ISSUE TITLE
Pixel Manipulation and GIFs

### ISSUE THREAD

**Issue by ccpandhare** [publiclab/image-sequencer#75]
Thanks to #73, GIFs are fully supported by PixelManipulation!

But It doesn't really work as expected. I inverted the following GIF using IS :

![ani-pm-hammer](https://user-images.githubusercontent.com/20787612/28542412-a9c34a88-70d9-11e7-8868-b66bb82ba062.gif)

This is the result:

![gif](https://user-images.githubusercontent.com/20787612/28542439-c03734d2-70d9-11e7-818e-e0e2d5b2b014.gif)

It doesn't apply to all frames, I guess. Also, now the GIF doesn't play infinitely. It just plays once.
(Try opening the image in a browser tab and then `Cmd+Shift+R` or `Ctrl+Shift+R`)

**Comment by ccpandhare** [comment]
Also, some other modules don't work with GIFs yet. Like the Crop Module.

**Comment by HarshKhandeparkar** [comment]
Hello, @jywarren shall I work on this?

**Comment by mgroovyank** [comment]
claim

**Comment by jywarren** [comment]
Hi all! We'd love help wherever you're interested. Thanks!

**Comment by keshav234156** [comment]
**UPLOADED ON GCI**

**Comment by SidharthBansal** [comment]
Published

**Comment by HarshKhandeparkar** [comment]
I have claimed this task. PR Coming soon :rocket:
