### ISSUE TITLE
Display RGB values when hovering over images

### ISSUE THREAD

**Issue by aashna27** [publiclab/image-sequencer#751]
### Displaying rgb values when hovering over images to provide imagedate

 This is a new feature and can be really interesting to implement

### where to look

http://sequencer.publiclab.org...

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by aashna27** [comment]
This seems really interesting and is a breakout from #197, I would like to go forward with it , but having searched a little I found the canvas approach, ie using canvas Api for each image and getting imagedata from it. I would request some views if it would be appropriate to go forward with it? I will also look for some other alternatives, not through with the search. Thanks!!

**Comment by jywarren** [comment]
here this would likely become part of the default UI code, so using Canvas
is OK. Thanks!

**Comment by Divy123** [comment]
@aashna27 can you please elaborate the use case of the issue?
