### ISSUE TITLE
Add code coverage

### ISSUE THREAD

**Issue by dojutsu-user** [publiclab/image-sequencer#774]
1. Code coverage might be good addition to show the percentage of code tested.
2. A `codecov` badge can be added to the `README`.

https://codecov.io/ can be used for this.

**Comment by Divy123** [comment]
I think this can be great to implement.
This can help us a lot to write tests and and know our code coverage.
@jywarren thoughts? 
If okay, I would love to implement this one.
Thanks @dojutsu-user for opening this issue.

**Comment by jywarren** [comment]
this would be fantastic, would you be interested in opening a PR for this?

**Comment by Divy123** [comment]
Sure I will be opening a PR soon..

**Comment by jywarren** [comment]
Also noting: https://docs.codeclimate.com/docs/travis-ci-test-coverage could work for this...

and I believe this is needed? https://libraries.io/npm/codeclimate-test-reporter

**Comment by jywarren** [comment]
Also linking to https://github.com/publiclab/image-sequencer/pull/929/files!
