### ISSUE TITLE
Allow Image Sequencer to load images locally and via HTTP requests in Browser

### ISSUE THREAD

**Issue by ccpandhare** [publiclab/image-sequencer#78]
Image Sequencer requires DataURI input when in Browser mode.
I think we should allow local images and AJAX images via XHR Requests too.

**Comment by jywarren** [comment]
What would the syntax be? Thanks!

**Comment by ccpandhare** [comment]
No syntax updates... Just an internal update to loadImages. Now users will
be able to load external images (local or otherwise) using loadImage() on
browsers.

**Comment by jywarren** [comment]
Ok!

**Comment by jywarren** [comment]
Maybe an example in the readme can illustrate that?

**Comment by ccpandhare** [comment]
Yes, sure. I am still working on this. So once I am done with this, I shall add an example to the README.md
