### ISSUE TITLE
Split README.md into README.md and CONTRIBUTING.md

### ISSUE THREAD

**Issue by ccpandhare** [publiclab/image-sequencer#79]
Now that Image Sequencer has been published to npm, I think the `README.md` should only consist of Usage instructions and all the development notes should be in `CONTRIBUTING.md`.
Am I right in thinking so?
Also because `README.md` has become very long over the time.

Should README.md have a small navigation or "jump to..." section?

**Comment by jywarren** [comment]
sure! Great.
