### ISSUE TITLE
Problem with the rotate module.

### ISSUE THREAD

**Issue by Harshithpabbati** [publiclab/image-sequencer#798]
### When we set the angle of rotation to 0 degrees.Though it rotates 90 degrees
![rotate](https://user-images.githubusercontent.com/43822585/53103151-10af6a80-3553-11e9-9791-10ff039991c3.png)
Problem with rotate module.

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by aashna27** [comment]
thanks for this issue, awesome !! 😄
