### ISSUE TITLE
Adding a reset feature.

### ISSUE THREAD

**Issue by Harshithpabbati** [publiclab/image-sequencer#799]
### Making a reset button.Which makes it to reset to the most recent change in the sequence
![reset](https://user-images.githubusercontent.com/43822585/53104619-b49a1580-3555-11e9-871d-735487d27cdd.png)

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by gauravano** [comment]
@publiclab/is-reviewers what do you think about this idea?

**Comment by HarshKhandeparkar** [comment]
@Harshithpabbati can you please elaborate on this?

**Comment by Harshithpabbati** [comment]
If we made a change which we don't want in that sequence and want to do it again then we have to delete the step and start doing it again.But by adding this feature we can reset it in the step so that it will be very convenient for everyone to use this.
Thanks.

**Comment by HarshKhandeparkar** [comment]
Do you mean like an undo?

**Comment by Harshithpabbati** [comment]
Yeah exactly!!

**Comment by HarshKhandeparkar** [comment]
IS already has the ability to add/remove steps or insert steps or do whatever you want really. Any value in between the sequence can be tweaked(which is why it has got its name). What kind of undo do you mean specifically?

**Comment by Harshithpabbati** [comment]
See if i want to make a some saturation of some extent and i made a wrong thing.Then i need to delete the step and start making the step so instead of it if I have the reset button it will be easy to solve it

**Comment by HarshKhandeparkar** [comment]
Harshith you don't have to delete the step, all you have to do is tweak the values and press the apply button and all the succeeding steps will also change. If you want to change a step, you can delete it and insert a different step there. Is there something else which is not achievable by doing this? Or am I saying something wrong?

**Comment by Harshithpabbati** [comment]
Yeah I mean the same we need to delete and make the other step instead of it.It will be convenient to have a reset button according to me.Lets have some others review
@publiclab/is-reviewers what do you say about it??

**Comment by HarshKhandeparkar** [comment]
What I meant to say is that you don't have to delete a step if you want to tweak values. You only have to delete a step if if you want to change the core step like change a crop step to saturation. Instead a good idea would be to add a replaceStep functionality(if it doesn't exist already). What do you say?

**Comment by Harshithpabbati** [comment]
Hello 
@publiclab/is-reviewers what do you feel about it???

**Comment by aashna27** [comment]
@Harshithpabbati I think there is some difference of opinion , why dont you give an example to show , how reset would be more friendly, than changing the values. As far as I understand , I think that a reset would undo the most recent change , so suppose you made a brightness of 120 , and then you make it 150 ,and press `reset` so it will take you to 120. 

So basically what I think is that a `reset` on a module wont show much effect as the user can easily make it 120 manually but yeah if we consider `crop` module say for example, wherein there are many inputs, so instead of manually switching to last change a `reset` would simplify the process!!

**Comment by Harshithpabbati** [comment]
@aashna27 I mean for modules like crop when we make a change in it.For example: I want to crop the picture to size x and i cropped it to some size y .Now i have to delete it and start it again for the particular step. So if we have a reset feature then image switches to the recent change.

**Comment by aashna27** [comment]
No you wont need to delete it, you can do it on the current one only , ie change the values and changes would be made.

**Comment by Harshithpabbati** [comment]
Oh ok fine sorry for the issue.

**Comment by jywarren** [comment]
Hi @Harshithpabbati i like the brainstorming here. I think this is something we could think more about and discuss, so thank you for opening it. UI design is hard and we need to think about these things regularly as we work, or we'll miss good ideas. In this case, it looks like people feel that it's not needed, but we might revisit in the future and this kind of discussion is good. So thanks!
