### ISSUE TITLE
Had a problem with crop module.

### ISSUE THREAD

**Issue by Harshithpabbati** [publiclab/image-sequencer#800]
### When we open the crop module directly after the load-image and delete it.
Then the following thing is happening
![crop](https://user-images.githubusercontent.com/43822585/53106301-bfa27500-3558-11e9-935e-75d2280072c9.png)

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by VibhorCodecianGupta** [comment]
I can't reproduce this. #623 addressed this issue. Are you sure you rebased?

**Comment by aashna27** [comment]
the error does exist, I ll see if I can fix it
