### ISSUE TITLE
Issue with saturation

### ISSUE THREAD

**Issue by Harshithpabbati** [publiclab/image-sequencer#801]
### When we open the saturation then the images are turning to a black screen. 

![saturation](https://user-images.githubusercontent.com/43822585/53107165-7c490600-355a-11e9-80d4-2095d57805bb.png)

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by VibhorCodecianGupta** [comment]
Again, I can't reproduce this. Looks like in the screenshot a previous implementation of contrast is being served. Try clearing your cache and try again. The module loads with a 70 parameter by default with the range from 0-100.

**Comment by aashna27** [comment]
I have refereced the pr that was open to this issue . Thanks 👍
