### ISSUE TITLE
Select crop feature

### ISSUE THREAD

**Issue by niravasher** [publiclab/image-sequencer#805]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

> What did you expect to see that you didn't?
What if I want to start cropping at a random location and want to finish at a random location?

### Please show us where to look
http://sequencer.publiclab.org/examples/#steps=

### What's your PublicLab.org username?
niravasher

### Browser, version, and operating system
windows 10 with ubuntu subsystem

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

@jywarren

**Comment by HarshKhandeparkar** [comment]
Welcome to the community! Could you please elaborate on this issue?

**Comment by niravasher** [comment]
I want to crop and have a small portion of the image and I don't exactly know the xy coordinates of that rectangle, hence there should some functionality to press the mouse and drag it till you reach the point where you want to stop and that portion gets selected and its start and stop coordinates are displayed automatically on the left

**Comment by HarshKhandeparkar** [comment]
Oh cool but I think there is an already open issue addressing this. Please make sure that this is not a duplicate. Thanks!

**Comment by niravasher** [comment]
Could you please reference it here @HarshKhandeparkar ??

**Comment by HarshKhandeparkar** [comment]
Ok I'll check.

**Comment by HarshKhandeparkar** [comment]
I think #796 is very similar to this. After that has been implemented, a user can select two pixels by clicking. Both issues are very similar but they mention different modules. Can they be merged into one general issue somehow which will improve the UX?

**Comment by niravasher** [comment]
Yes, both of them are quite similar

**Comment by HarshKhandeparkar** [comment]
Sorry you had to face some trouble. Would you like to try solving one of the currently open issues?
