### ISSUE TITLE
Change the "improve this tool" button.

### ISSUE THREAD

**Issue by Harshithpabbati** [publiclab/image-sequencer#810]
### Change the improve this tool button to primary.
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/PublicLab.Editor/labels/help-wanted) issues. Thanks!
###  What you will need to know.
Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

###  Step by Step
* [ ]  :raising_hand_woman: **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!
* [ ]  :memo: **Update**: All that needs to be done is replace this line
* [image-sequencer/examples/index.html]
      
           Line 214
                   <a class="btn btn-default" href="https://github.com/publiclab/image-sequencer">View the code</a>
  with this line
 `<a class="btn btn-primary" href="https://github.com/publiclab/image-sequencer">View the code &raquo;</a>`
* [ ]  :floppy_disk: **Commit** your changes
* [ ]  :twisted_rightwards_arrows: **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.
2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there.

* [ ]  :checkered_flag: **Done** Ask in comments for a review :)

###  Questions?
Leave a comment below!

### Is someone else already working on this?
We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

**Comment by Harshithpabbati** [comment]
Can someone label it as a First Timers Issue

**Comment by Harshithpabbati** [comment]
@publiclab/is-reviewers

**Comment by HarshKhandeparkar** [comment]
Harshith, in github MD, emojis are inserted by putting the ID between two colons `:` e.g. `:checkered_flag:`. Thanks!

**Comment by marieram** [comment]
Can I work on this?

**Comment by HarshKhandeparkar** [comment]
Go ahead 😊

**Comment by 88pawankumarjha** [comment]
Can I work on this?

**Comment by Harshithpabbati** [comment]
Sorry there is already an open pr.
Thanks
