### ISSUE TITLE
Improve the Ui of Image-Sequencer

### ISSUE THREAD

**Issue by Harshithpabbati** [publiclab/image-sequencer#818]
## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by Harshithpabbati** [comment]
@publiclab/is-reviewers what do you say about it???

**Comment by HarshKhandeparkar** [comment]
Harshith there is an open issue addressing this. #708. I'm also kind of working on it. Check [this](https://harshkhandeparkar.github.io/image-sequencer/) out.

**Comment by Harshithpabbati** [comment]
cool!! That really good!!

**Comment by Harshithpabbati** [comment]
why didn't they implemented it???

**Comment by HarshKhandeparkar** [comment]
There's no need for this issue. Please close it. #708 is enough. We can discuss everything there.

**Comment by HarshKhandeparkar** [comment]
It wasn't implemented since it is a huge  change

**Comment by HarshKhandeparkar** [comment]
Currently I am working on refactoring the ui code. Almost done with it but I'm not getting time to complete it.
