### ISSUE TITLE
Only Allow Https Connection

### ISSUE THREAD

**Issue by HarshKhandeparkar** [publiclab/image-sequencer#819]
### Please describe the problem (or idea)

Currently sequencer.publiclab.org has an SSL certificate but it can run without https as well. If no https:// is included in the URL, then an insecure connection is opened. We have to always redirect to the https page.

### Possible Fix

Create a function which checks the page URL. If the URL doesn't contain https, then it should redirect to `https://rest-of-the-url`. Run this function before the sequencer is loaded.

E.g. 
`http://sequencer.publiclab.org#step={}` should be redirected to `https://sequencer.publiclab.org#steps={}`

### Any Other Ideas?
If you have any other ideas then please let us know. We can discuss those below.

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by HarshKhandeparkar** [comment]
@publiclab/is-reviewers can this be an `fto-candidate` ?

**Comment by gauravano** [comment]
I have added the label but let's see in the PR if the load time is noticed.

**Comment by jywarren** [comment]
Great idea! I think in one of our repos we actually have a redirect... can't remember which though!

**Comment by Divy123** [comment]
Love to work upon it .Thanks

**Comment by HarshKhandeparkar** [comment]
Awesome!!

**Comment by jywarren** [comment]
I was able to turn on this setting in the gh-pages configuration! I think we can close now, thanks for the great idea!
