### ISSUE TITLE
Demos rework + starter module rethink

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#82]
Now that we have a UI system, I'd like to take the "starter module" idea from the previous demo, and start by plugging it into the new sequencer code. 

This is the first step in getting a demo that runs on the new code. But do you think we should package up the selector more than including it in the demo code? I had originally seen it as a kind of "special module" but if it really doesn't fit into the architecture, we can just provide it in something like `demo/initial-image.js`

**Comment by ccpandhare** [comment]
Sorry, I am not able to get you here... What is a "starter module" ?
Are you taking about the initial step on every image, `load-image` ?

**Comment by jywarren** [comment]
Sorry, I'm talking about the older system which had a pseudo-module to
"start the sequencer": https://jywarren.github.io/image-sequencer/

**Comment by ccpandhare** [comment]
Yes, I remember. And we had discussed how that's not a good idea so now we no longer use the pseudo module. I will redo the demos using the new UI System.

**Comment by jywarren** [comment]
right. agreed. But I'm thinking we can move that code into the demo code
outside the library itself, since there's some good convenient UI there,
the ability to select or drag/drop to activate the demo. Sound all right?

On Wed, Jul 26, 2017 at 10:22 PM, Chinmay Pandhare <notifications@github.com

**Comment by ccpandhare** [comment]
I have already started on that!
The FisheyeGl has been now rewritten using the UI methods

**Comment by ccpandhare** [comment]
Is anything remaining as far as this issue is concerned?

**Comment by jywarren** [comment]
I guess perhaps it could be a good idea to show/describe how one of the demos (with a drag/select interface for choosing an image) can be adapted to use different steps. 

I guess I wanted to know if we could make a new demo very similar to the old demo at https://jywarren.github.io/image-sequencer/ -- one where you can choose different modules to add to the sequence, and it makes a vertical chain of them on the page. I know we've talked about this a few times in different ways but now that we have the "standard" UI do you think this demo is possible? 

Then we can finally replace the demo links on the README and the main repo description.

**Comment by ccpandhare** [comment]
Demo has been reworked! Shall add it to the README.md when #92 gets merged :-)
Closing this issue then!
