### ISSUE TITLE
Unwanted scrollbars in x direction

### ISSUE THREAD

**Issue by niravasher** [publiclab/image-sequencer#820]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?
Scrollbars in the x direction

### Please show us where to look
http://sequencer.publiclab.org/examples/#steps=

### What's your PublicLab.org username?
niravasher

### Browser, version, and operating system
windows 10 with ubuntu subsystem

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!
![screenshot 34 _li](https://user-images.githubusercontent.com/32176296/53352578-08876e80-3949-11e9-8a75-3e33ed255883.jpg)

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by niravasher** [comment]
Will shift steps to a bit left and also set the width as per required

**Comment by aashna27** [comment]
I understand the scrollbar doesnt look good , but I guess it is for if we need to add more modules as quick ones, maybe in future, so adjusting width again and again seems pointless.That's why a scrollbar provides a quick solution for now, and maybe later this can be changed. Thoughts?

**Comment by niravasher** [comment]
There is a width set for a class name row which doesn't allow to increase the width beyond the point. As per your suggestion, one of the modules that is already existing is the resize module. The maximum resize that I can do is 125%, if I try to do it beyond that it simply doesn't work because of the max-width property. So the scrollbar can be removed. And I am just shifting the elements towards the left and not trying to hide anything on overflow. There are also elements relative to each other, hence more edits need to be done @aashna27

**Comment by Harshithpabbati** [comment]
@niravasher we need the scroll bar for smaller screens.

**Comment by niravasher** [comment]
Nopes @Harshithpabbati we don't need scroll bar for smaller screens as the image goes below the input options and is fit correctly on the screen.

**Comment by Harshithpabbati** [comment]
I mean for the quick modules.If we increase the size of the box then it will look weird in small screens

**Comment by Harshithpabbati** [comment]
If we have the scrollbar then we can add many more quickbuttons to access easily.

**Comment by niravasher** [comment]
The scrollbar isn't going anywhere, i am just shifting elements to a bit left, so that initially there is no scrollbar visible. If there is anything that goes out of the window, the scrollbar will appear automatically.

**Comment by HarshKhandeparkar** [comment]
Scrollbars do not exist anymore. If someone sees these scrollbars then please report here or reopen this issue. Current version of IS is available here https://harshithpabbati.github.io/image-sequencer
