### ISSUE TITLE
Issue with flip-image.

### ISSUE THREAD

**Issue by Harshithpabbati** [publiclab/image-sequencer#826]
### Image flips in different way.
It flips vertically when we flip it horizontally and even same with the vice-versa.

**Comment by HarshKhandeparkar** [comment]
Harshith the button was disabled since the image is flipped vertically by default.

**Comment by Harshithpabbati** [comment]
@HarshKhandeparkar No!!!. When it is flipped vertically then see the text it should be flipped right???
![flipimg](https://user-images.githubusercontent.com/43822585/53693171-c3d55a80-3dc2-11e9-8495-cea453117c24.png)

**Comment by Harshithpabbati** [comment]
Cool!! sorry for it.
And there was another issue you when we flip it vertically then it's flipping horizontally and same for the vice-versa.

**Comment by HarshKhandeparkar** [comment]
The input is for the axis. The image is flipped ON THE selected axis. Which means that the image is flipped vertically ie on the x-axis when the horizontal input is selected and the image is flipped on the vertical axis(y-axis) ie. It is flipped horizontally when the vertical input is selected.

I think this can be closed

**Comment by HarshKhandeparkar** [comment]
Your PR can be a standalone.
