### ISSUE TITLE
Image Diff based testing

### ISSUE THREAD

**Issue by ccpandhare** [publiclab/image-sequencer#83]
Check image similarity using [image-diff](https://www.npmjs.com/package/image-diff)

**Comment by jywarren** [comment]
we don't need to include it in the library itself; it could just be included in the test suite and under devDependencies.

https://github.com/publiclab/image-sequencer/blob/master/CONTRIBUTING.md#module-candidates -- had several diff modules.

**Comment by ccpandhare** [comment]
I seem to have hit a roadblock here.
None of the npm image-diff modules have DataURL support

**Comment by jywarren** [comment]
ugh! And probably too much cost to convert and then run. I think this may
be lower priority than other issues, but perhaps we could consider what it
would take to file a new dataUrl feature on one of the more active libs.

**Comment by ccpandhare** [comment]
Yes, I agree. I shall open an issue and post the link here.

**Comment by ccpandhare** [comment]
https://github.com/uber-archive/image-diff/issues/57

**Comment by ccpandhare** [comment]
https://github.com/gemini-testing/looks-same
This works on buffers as well.

**Comment by ccpandhare** [comment]
But it works only for PNG images

**Comment by ccpandhare** [comment]
Implemented it for PNG images for now at #89
