### ISSUE TITLE
Completion Of `$step` helper method

### ISSUE THREAD

**Issue by HarshKhandeparkar** [publiclab/image-sequencer#833]
### scopeQuery
I have an open PR #710 which refactors the UI code by adding a new helper method called `scopeQuery` which returns a *scoped* `jQuery` object(here it is assigned to a variable called `$step`) which only searches elements inside a given scope(DOM element). This method itself is complete but needs a test and needs to be documented.

### Tests
The helper method is awesome and can shorten the UI code significantly but it should have a test which checks if it works properly so that the UI code doesn't break. I don't have much experience with jasmine(which is used to test UI code). If someone can add the test for me then it would be really great.

### Documentation
Such a useful helper method should definitely get the attention of the contributors. It should be documented in the [CONTRIBUTING.md](https://github.com/publiclab/image-sequencer/blob/main/CONTRIBUTING.md) file. If someone can do that as well, it would be great!

### I Need Help
I am very busy and I want to get my PR merged but it should not be incomplete. If some contributor(s) can help me with the testing and documentation then I would be really grateful. All the information about this method can be found in the PR #710. If you are going to contribute to the tests then you can merge my branch into yours.
### Break Me Up
This issue consists of two parts i.e. documentation and testing. Those two things are different enough from each other to deserve a dedicated issue for each. If you would like to break this issue into two separate ones it that would be helpful as well. Alternatively you can also solve one or both of these issues without breaking them up. Just let us know down in the discussion (comments).

##### Separated Issues:
- [x] Testing
- [x] Documentation (#885)

##### Resolved Issues
- [x] Testing
- [x] Documentation

##### Open PRs
- [x] Main PR (#710)
- [x] Tests (#710)
- [x] Documentation (#916)

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by HarshKhandeparkar** [comment]
@jywarren @publiclab/is-reviewers new issue for testing and docs for `$step` now open!

**Comment by HarshKhandeparkar** [comment]
I guess the documentation part can be an `fto`.

**Comment by HarshKhandeparkar** [comment]
@Harshithpabbati if you want to split up both the issues or any one, please note that the documentation issue should be formatted into a `first-timers-only` and the testing part can be a normal issue. If you want to solve the testing part, you can do that but please leave the docs part to a newcomer. Thanks.

**Comment by HarshKhandeparkar** [comment]
@Harshithpabbati? Are you going to break this issue up?

**Comment by Harshithpabbati** [comment]
Sorry I am traveling back to my home. So i can't work at this time.

**Comment by HarshKhandeparkar** [comment]
Ok np.

**Comment by HarshKhandeparkar** [comment]
@mgroovyank would you like to work on any one(or both) part(s) of this issue?

**Comment by HarshKhandeparkar** [comment]
Documentation issue open #885

**Comment by HarshKhandeparkar** [comment]
@jywarren docs pr done #916.

**Comment by Divy123** [comment]
I would like to work upon writing the UI tests for it.

**Comment by HarshKhandeparkar** [comment]
Thanks! Do you need any information about it?

**Comment by Divy123** [comment]
I will be exploring a bit and then discuss here,🙂

**Comment by HarshKhandeparkar** [comment]
Ok.😊

**Comment by Divy123** [comment]
@HarshKhandeparkar there are some things that are breaking out the code maybe, can you have a look at them. It was a huge PR and congrats for the merge.

@jywarren maybe we can revert the changes here now, and once we can have the things fixed we can remerge .

**Comment by Divy123** [comment]
1) This is the error currently in the console:
![Screenshot from 2019-06-25 16-07-23](https://user-images.githubusercontent.com/31225007/60091942-5ed3b500-9763-11e9-9dca-950c90bf83ba.png)

Also just one thing more that also due  to $step method not available in intermediateHtmlui.js

2). Also after refreshing the page, the url is correct but the steps inside url are not getting loaded.

3). I figured it out and what's happening is inside, defaultHtmlStepUi.js:
```js
if (step.linkElements[index].contains(imgthumbnail))
        step.linkElements[index].href = step.imgElement.src;
    }
```
at the time of checking the condition, step.linkElements[index] is unavailable, maybe some async stuff here.

@HarshKhandeparkar maybe we can get this fixed here and @jywarren if we can have a revert so that we can have the code cleanup issue go on and once this gets fixed we can continue but again great work Harsh.

**Comment by HarshKhandeparkar** [comment]
What is broken?

**Comment by Divy123** [comment]
Right now, the inserStep button is not working and showing this error. Also, I am seeing this error, in the console on starting up the server .
You can have a look at the screenshot I sent above to have a better understanding.
Hope that helps

**Comment by HarshKhandeparkar** [comment]
I am pretty sure that $step is available in the intermediateHtmlStepUi.js. Maybe a recent commit broke this.

**Comment by HarshKhandeparkar** [comment]
Can you tell which line throws the not defined error by expanding it?

**Comment by Divy123** [comment]
@HarshKhandeparkar its line 273 of defaultHtmlStepUi.js :
```js
if (step.linkElements[index].contains(imgthumbnail))
        step.linkElements[index].href = step.imgElement.src;
    }
```
and step method is not working in line 92 in IntermediateHtmlStepUi.js where its showing $step is not defined.

**Comment by HarshKhandeparkar** [comment]
Ok ty. I will look into this but I won't be able to push anything today.
And we don't have to revert this. Reverting just creates a new PR, does not
react directly. I will open a new PR.

**Comment by Divy123** [comment]
Actually, I was suggesting a revert so that I can work on things till then as I was to work upon the same functionality and I won't be able to work without it done. Is that ok to you?

**Comment by HarshKhandeparkar** [comment]
Ypu can locally revert. Reverting globally will cause problems to my branch
and pushing again will be a problem.

**Comment by Divy123** [comment]
Since I am also going to work on UI, so it would be better if I work on the latest code.

**Comment by HarshKhandeparkar** [comment]
If it is reverted globally, I won't be able to rebase my branch becuase
rebasing will delete the code. Oh wait, fo you know a fix for this? You can
directly push that fix or use it as a workaround locally. (I have done this
many times)

**Comment by Divy123** [comment]
Actually, I don't have the fix now and working without the fix may lead to issues later .

**Comment by HarshKhandeparkar** [comment]
Ok . As you say. Let's wait for @jywarren's thoughts on this.

**Comment by Divy123** [comment]
Ya sure!!
Thanks a lot @HarshKhandeparkar

**Comment by jywarren** [comment]
How complex is the fix? We haven't pushed this to the live demo yet... would it be something we can patch relatively quickly?

**Comment by Divy123** [comment]
I am not sure on this. Maybe @HarshKhandeparkar can help on this..
Also till that I am on halt as I also have to work on things built over that functionality.
So for the time being, I will discuss with aashna on the UI testing..

**Comment by jywarren** [comment]
Can you merge a short-term commenting-out of the line that causes the
error, or reverting just that line? Many lines from this code were just
shortening from more verbose commands and we could just switch back to the
longer forms until this is fixed?

**Comment by Divy123** [comment]
Ok trying it now!!

**Comment by Divy123** [comment]
I tried it and on reverting the complete intermediate file gave me the correct result.
@jywarren do you want me to send a PR for that?

**Comment by jywarren** [comment]
Sure! That would be great. And if you want to add explanatory comment and
perhaps even leave in the commented out previous line so we are super clear
this is a temporary fix. And - can you bump the 0.0.x version in your PR so
we can release it as a patch as per semver.org ? Thanks!

**Comment by Divy123** [comment]
Can you please explain a bit on the bump part?
I am totally unaware of that.

**Comment by jywarren** [comment]
Ah, sorry - just change the version number in /package.json by one
"patch-level" interval, so increasing from 3.5.0 to 3.5.1 -- this signals
to dependencies that /use/ image-sequencer that we are releasing a bugfix!
https://semver.org has explanation of this versioning scheme which is known
as "semantic versioning" -- 0.x.0 denotes a new feature that does not break
or change any existing functionality, and x.0.0 denotes a breaking change
(a major release) which will require refactoring by "downstream" libraries
that use this one. So we're just doing a "patch-level" release, which
affects 0.0.x. Does that make sense?

**Comment by Divy123** [comment]
Yes and thanks a lot for this great information.

**Comment by HarshKhandeparkar** [comment]
I think this can be closed.
cc @Divy123 @jywarren
