### ISSUE TITLE
Bug in UI in button alignment ( for small screens )

### ISSUE THREAD

**Issue by subhahu123** [publiclab/image-sequencer#836]
### Please describe the problem (or idea)

![screenshot-sequencer publiclab org-2019 03 05-23-21-14](https://user-images.githubusercontent.com/34541684/53825954-85e05e00-3f9d-11e9-85eb-25603727e5e8.png)

Download button  and clear all steps are not on the same line

**Comment by HarshKhandeparkar** [comment]
Nice catch! I think they can be aligned one below the other. What arey your thoughts?

**Comment by subhahu123** [comment]
> Nice catch! I think they can be aligned one below the other. What arey your thoughts?

We can use media query css

**Comment by subhahu123** [comment]
> Nice catch! I think they can be aligned one below the other. What arey your thoughts?

this project ui should be redegisned like
it should have a sidebar with all its features and view of image on the right page or view
it will really look like editor something

**Comment by HarshKhandeparkar** [comment]
Check this out https://harshkhandeparkar.github.io/image-sequencer/

**Comment by HarshKhandeparkar** [comment]
#708 #825

**Comment by HarshKhandeparkar** [comment]
The button UI has changed ever since this was opened. Closing
