### ISSUE TITLE
Create `first-timers-only` issues for newcomers

### ISSUE THREAD

**Issue by HarshKhandeparkar** [publiclab/image-sequencer#842]
Hi everyone!

We, at Public Lab, are known for welcoming new contributors into the Open Source world but a number of times, newcomers were not able to find `first-timers-only` issues to start their journey or face troubles making their first contribution with us. 

Reasons being:
1. Lack of `first-timers-only` issues
2. Struggle in finding a good issue to start and lack of enough support?

We are working on both of the above aspects to support and help the maximum number of people to take their first step in their OSS journey with us, through our various [projects](https://github.com/publiclab/) but we need more support for this. So, this is a call to all the Public Lab members to try and create a first-timers-issue for someone who wants to start their journey and waiting for an FTO being assigned to them.

If you are interested in creating `first-timers-only` issue, follow these instructions:
1. Browse through the publiclab.org and see if there's a bug which can be easily solved.

2. Solve this issue but don't create a PR this time, instead create an FTO issue.

3. Click on this [link](https://github.com/publiclab/image-sequencer/issues/new) to start creating a new issue.

4. We follow a specific template for FTO issues, so copy the template from [here](https://github.com/publiclab/plots2/blob/master/.github/first-timers-issue-template.md).

5. Edit the issue body to add the goal of the issue, code snippet required, file to be updated, add screenshots(if required). Don't add code snippet required to solve in case, the issue just requires minor HTML or CSS change or equivalent.

6. Add a catchy and relevant title to the issue but don't include "FTO", "first-timers-only" or equivalent in the title.

7. Get the issue you just created labeled by mentioning @publiclab/reviewers or @publiclab/is-reviewers. 

- If you have labeling privileges, feel free to do so yourself but ensure that you have used FTO template. 

- If you are not able to mention the above-mentioned teams and don't have labeling privileges, then drop a line in Gitter channel - https://gitter.im/publiclab/publiclab or mention @jywarren @tech4GT and any one of us will surely follow-up with you. You can also mention any other member, you can think of with labeling privileges.

###### note: all of the members of [publiclab/is-reviewers](https://github.com/orgs/publiclab/teams/is-reviewers/members) team have labelling rights.

8. It's time to invite a new contributor to your issue. If there are unchecked names in the below list, then those people are still looking for FTO issue to start with, so mention them in your FTO by writing - `This issue is created for @[contributor-name]. Thanks!` 

Also, if you see, a new contributor is looking for an issue, feel free to point them to your FTO. 

### **fto-candidate** Issues

These are issues which can become good `first-timers-only` issues but have to be reformatted using the fto issue [template](https://github.com/publiclab/plots2/blob/master/.github/first-timers-issue-template.md). If you feel like reformatting any of [these](https://github.com/publiclab/image-sequencer/labels/fto-candidate), please feel free to do so. Please let us know if you are going to reformat the issue in the issue comments and link to the new issue in the comments of the original issue and this issue. You can mention `@publiclab/is-reviewers` to get the new issue labeled and then the old issue closed.

### Contributors looking for `first-timers-only` (FTO) issues

- [x] @mgroovyank (#874)
- [x] @An0u (#894)
- [ ] @Jaya738
- [x] @hodbadger (#885)
- [x] @vaarigupta (#898)
- [x] @teisenhower (#992)
- [ ] @ElenaG518
- [ ] @edwd42
- [ ] @rmcorre 
- [x] @Michaellin250 (#884)
- [ ] @scheleon
- [x] @irasanchez(#951)
- [ ] @konolga
- [ ] @garg3133
- [ ] @jmauriciowebdev
- [ ] @freerangeandy
- [ ] @amreshk005

**To first-time contributors:** If you are looking for FTO and want your name to be added to the above list then, feel free to comment below to show your interest. If you are looking for working on specific language/framework, mention that too in your comment.

**To Public Lab members who have comment edit privileges:** Please add names of newcomers who have shown into for FTO in below comments. Also, add the names of other newcomers who are looking for FTO and shown their interest by commenting on other issues.

Currently open [`first-timers-only`](https://github.com/publiclab/image-sequencer/labels/first-timers-only) and [`fto-candidate`](https://github.com/publiclab/image-sequencer/labels/fto-candidate) issues in **image-sequencer** repo.

#### See also #879

For any query, feel free to ask below or at Public Lab gitter channel - https://gitter.im/publiclab/publiclab

****

#### Thank you!

cc @jywarren @publiclab/reviewers @publiclab/is-reviewers @tech4GT

Original issue template by @gauravano  

_Sent from my OnePlus3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_ 

_Sent from my OnePlus3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Harshithpabbati** [comment]
Good idea!! We need new contributers..

**Comment by HarshKhandeparkar** [comment]
@Harshithpabbati would you mind breaking up #833 ?

**Comment by Harshithpabbati** [comment]
What should I do ?? Documentation ??

**Comment by HarshKhandeparkar** [comment]
Any one or both or you can even solve one of those(if you want). Thanks.

**Comment by HarshKhandeparkar** [comment]
But I think the documentation part should be split up into a new first-timers-only

**Comment by Divy123** [comment]
One suggestion I have already opened up an issue regarding documentation.
So you could do the other part.
Documentation needs a considerable change so I woulkd like to discuss upon it.
Thanks.

**Comment by Harshithpabbati** [comment]
ok @Divy123

**Comment by Divy123** [comment]
@jywarren Please look into issue #753 as it may greatly enhance the ease of understanding codebase making it much easier for new contributors to participate.

Also please review #251, it needs to be merged urgently as with merging PR's every time the code has to be enhanced. Also I will be updating README.md if the changes are ok to you.
Thanks

**Comment by HarshKhandeparkar** [comment]
Divy123 we were talking about the documentation part of #833

**Comment by Divy123** [comment]
Oh! proceed with it all the best.
But since it is a pinned issue I want to up raise the overasll doc as well.
Thanks and great work @HarshKhandeparkar

**Comment by Harshithpabbati** [comment]
Created an first timers issue https://github.com/publiclab/image-sequencer/issues/846

**Comment by HarshKhandeparkar** [comment]
Harshith, thanks for your enthusiasm and help and the issue of course. But the issue has to based on the fto template. Please reformat it and add the label later. Thanks and apologies as you have to take trouble.

**Comment by Harshithpabbati** [comment]
Done with that @HarshKhandeparkar

**Comment by HarshKhandeparkar** [comment]
Awesome!!

**Comment by HarshKhandeparkar** [comment]
@mgroovyank shall I add your name to this list? There are currently 0 fto issues open but there are some fto-candidate issues.

**Comment by HarshKhandeparkar** [comment]
@mgroovyank welcome! Your name has been added :tada:. I have a few questions that you can answer if you like:

- What programming language are you good at/like? (JS, HTML, CSS, something else?)

- Do you have experience with GitHub?
- If JS is your cup of tea, what framework/package/environment are you comfortable with?(nodejs, some specific nodejs package, libs like jquery or frameworks like react)
- Are you good at ruby? You can check out [plots2](https://github.com/publiclab/plots2) which is another project of publiclab.

#### Thank You!

**Comment by HarshKhandeparkar** [comment]
Opened a new fto #874. @mgroovyank this one is for you but if you don't want to solve it then it will be assigned to someone else. Do not worry as new ones are yet to come. I have some ideas for better ftos. You can either solve this one or wait for another one. Thank you!

**Comment by An0u** [comment]
I'm looking for first-time issues to solve ;)

**Comment by HarshKhandeparkar** [comment]
@An0u Welcome! You have come to the right place. Your name has been added to the list !!:tada:

**Comment by HarshKhandeparkar** [comment]
Hello! Newcomers can see issue #879 also to find a bug and get the bug formatted as an FTO(first timers only issue). This new FTO will be reserved for the one who finds the bug. Thank you!

@An0u

**Comment by HarshKhandeparkar** [comment]
@Jaya738 welcome!! Your name has been added!

**Comment by Jaya738** [comment]
@HarshKhandeparkar  
please guide me what to do next

**Comment by HarshKhandeparkar** [comment]
You will have to wait until an issue is created. I am going to create atleast one tonight. This one will be reserved for you and will create another one for @An0u. Sorry for the delay but I'm busy and cannot create issues right now. If someone else creates an issue for you before I do you claim that one. No problem. Thanks!

**Comment by HarshKhandeparkar** [comment]
@Jaya738 you can, instead of waiting for me to open an issue, go and see this one #879

**Comment by HarshKhandeparkar** [comment]
Opened an issue for you @Jaya738 in #884. Go ahead and try to resolve it. We will be ready to provide any kind of help.

**Comment by HarshKhandeparkar** [comment]
Opened an issue #885 for @An0u. Go ahead and try to resolve it. We will be ready to provide any kind of help.

**Comment by HarshKhandeparkar** [comment]
If @Jaya738 and @An0u want to exchange issues which are assigned to them, they can provided that both agree. Thanks!

**Comment by hodbadger** [comment]
I'd like to help with documentation if there's an open issue.

**Comment by HarshKhandeparkar** [comment]
Yes there is. #885

**Comment by HarshKhandeparkar** [comment]
@vaarigupta welcome! Your name has been added. You will be assigned soon.

**Comment by vaarigupta** [comment]
@HarshKhandeparkar  I want to contribute as FTO on HTML , CSS , Javascript. How can I start contributing?

**Comment by vaarigupta** [comment]
> @vaarigupta welcome! Your name has been added. You will be assigned soon.

thanks a lot .I am an outreachy applicant and excited to work for public lab

**Comment by HarshKhandeparkar** [comment]
Great! We don't have any ftos right now but many are to come. Btw do you have experience with git? If yes, you can try to solve the fto-candidate issues if you can or else wait for an fto. Thanks.

**Comment by HarshKhandeparkar** [comment]
@vaarigupta opened an fto #898. This one is for you. Go ahead and resolve it. 😊

**Comment by vaarigupta** [comment]
@HarshKhandeparkar  Ya thanks I will look into it and ask if I get stuck meanwhile.

**Comment by Divy123** [comment]
Hello everyone in the discussion here who are here to grab some issues.
Just want to express that you can always ask @publiclab/is-reviewers or any of the contributors from ourselves for any help you need from us.
You people are awesome and thanks for helping us improve the  project through your contributions.

**Comment by HarshKhandeparkar** [comment]
We, @publiclab/is-reviewers are always ready to help in case you get stuck. Thanks for your important contributions which improve this project! 😊

**Comment by HarshKhandeparkar** [comment]
@teisenhower welcome! Your name has been added :tada:!

**Comment by HarshKhandeparkar** [comment]
You will have to wait until an fto is created. Thanks.

**Comment by HarshKhandeparkar** [comment]
In the meanwhile, you can browse other repos.

**Comment by teisenhower** [comment]
@HarshKhandeparkar **Thank you!**

**Comment by ElenaG518** [comment]
Hello! I am interested in being added to the list of FTO contributors.  Thanks!

**Comment by gauravano** [comment]
Hi @ElenaG518, added your name and we'll ping you soon with an FTO. Thanks!

**Comment by edwd42** [comment]
Hi, please add me to the FTO list above.  I just started learning Ruby on Rails, but my others are MERN stack, Python, Java, MySQL

**Comment by HarshKhandeparkar** [comment]
@edwd42 are you good with JavaScript? If yes, i will add your name here. If you sre learning ruby on rails, go and get your name added to the list here https://github.com/publiclab/plots2/issues/4963. This is our most famous repository, it is a runy on rails project.

**Comment by HarshKhandeparkar** [comment]
Oh ok, you know MERN stack which means you should know JS. Adding your name here.

**Comment by edwd42** [comment]
Thanks @HarshKhandepakar!  JS is fine, but was hoping to get some issue for Ruby on Rails.

**Comment by edwd42** [comment]
I see @HarshKhandepakar I am now on two lists - this one above, and publiclab/plots2#4963.  Prefer #4963 if that's more for ruby on rails.

**Comment by HarshKhandeparkar** [comment]
Hello and welcome!
You can solve both if you want.
1. It's HarshKhandeparkar you forgot to put an 'r' in 'parkar' at the end.
2. This is a js and html/css lib, no ruby on rails.
3. Plots2 is a ruby on rails lib with some CSS/HTML/JS for normal DOM behavior but the backend is ruby on rails.
4. You can contribute to both or add your names in both the lists. No problem. I can also remove your name from this list if you want.

**Comment by edwd42** [comment]
Hi @HarshKhandeparkar  Thanks for the welcoming.  I greatly appreciate your help.  First, sorry about the spelling error.  I am happy to work and contribute on both.  JS is my first language, and Ruby on Rails is a new project I'm starting.  
So, yea, waiting for my first issue.
Thanks and have a great day!

**Comment by rmcorre** [comment]
Hi HarshKhandeparkar,
Please add me to the FTO list. 
Thanks

**Comment by gauravano** [comment]
Hi @rmcorre, added your name to the above list. Thanks!

**Comment by Michaellin250** [comment]
Can you add me to the list? I want to get started with open source contributions.

**Comment by sashadev-sky** [comment]
@Michaellin250 added!

**Comment by HarshKhandeparkar** [comment]
@Jaya738 has not replied. His issue has been reassigned to @Michaellin250

**Comment by HarshKhandeparkar** [comment]
@scheleon welcome! your name has been added.

**Comment by HarshKhandeparkar** [comment]
@Harshithpabbati do you have any ideas for an fto?

**Comment by Harshithpabbati** [comment]
#951 I will reformat it to fto issue.

**Comment by HarshKhandeparkar** [comment]
:+1:

**Comment by Divy123** [comment]
#959 can also be seen.

**Comment by Divy123** [comment]
#992 is up here.

**Comment by irasanchez** [comment]
Hey there, may I be added to the list? I am familiar with CSS, HTML, and JavaScript (vanilla, nodejs, React) and am looking for more practice in real projects. Thanks!

**Comment by Harshithpabbati** [comment]
@irasanchez you can start your contributions with this issue #951

**Comment by konolga** [comment]
Hi, please add me to the FTO list.

**Comment by Harshithpabbati** [comment]
@konolga added your name. You will be assigned with an issue.
Thanks

**Comment by aashna27** [comment]
A new fto added https://github.com/publiclab/image-sequencer/issues/1084 please have a look and proceed.

**Comment by garg3133** [comment]
Hey there, can you please add my name to the FTO list. Thanks!

**Comment by HarshKhandeparkar** [comment]
@jmauriciowebdev your name has been added. You can try to solve #894 btw.

**Comment by HarshKhandeparkar** [comment]
@jmauriciowebdev your name has been added. You can try to solve #894 btw.

**Comment by jywarren** [comment]
Hi @HarshKhandeparkar or @publiclab/is-reviewers would you be able to open an FTO for  @freerangeandy ? I'll add him to the list!

**Comment by aashna27** [comment]
There is a new fto issue #1167 @freerangeandy please have a look !

**Comment by amreshk005** [comment]
Hey there, can you please add my name to the FTO list.

**Comment by HarshKhandeparkar** [comment]
Done. You can search for existing ones though.

**Comment by Tanish0019** [comment]
@HarshKhandeparkar Can you add me to the FTO list. I can work with HTML, CSS, JavaScript and Python. Thank you :)
