### ISSUE TITLE
Add the link of the image sequencer in the footer.

### ISSUE THREAD

**Issue by Harshithpabbati** [publiclab/image-sequencer#846]
Hi, this is a first-timers-only issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you :gift_heart: 

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!

:thinking: What you will need to know.
Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

:clipboard: Step by Step
  :raising_hand_woman: Claim this issue: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

  :memo: Update: All that needs to be done is replace this line
image-sequencer/examples/index.html

Line 211 in
``` 
 This is an open source toolkit which you can help add to and improve on <a href="https://github.com/">Github</a>
```
with this line
```
 This is an open source toolkit which you can help add to and improve on <a href="https://github.com/publiclab/image-sequencer/issues">Github</a>
```
Line 202 in
``` 
 Post a link to this and ask help from other community members on <a href="https://github.com/publiclab/image-sequencer/issues">PublicLab.org</a>
```
with this line
```
 Post a link to this and ask help from other community members on <a href="https://github.com/publiclab/image-sequencer/issues/new">PublicLab.org</a>
```
Line 205 in 
```
<a class="btn btn-primary" href="https://github.com/publiclab/image-sequencer/issues">Ask a question &raquo;</a>
```

with this line
```
<a class="btn btn-primary" href="https://github.com/publiclab/image-sequencer/issues/new">Ask a question &raquo;</a>
```
  :floppy_disk: Commit your changes

  :twisted_rightwards_arrows: Start a Pull Request. There are two ways how you can start a pull request:

If you are familiar with the terminal or would like to learn it, here is a great tutorial on how to send a pull request using the terminal.

You can also edit files directly in your browser and open a pull request from there.

  :checkered_flag: Done Ask in comments for a review :)
:thinking::question: Questions?
Leave a comment below!

Is someone else already working on this?
We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. If someone seem stuck, offer them some help! Otherwise, take a look at some other issues you can help with. Thanks!

Thanks!!!

**Comment by HarshKhandeparkar** [comment]
Harshith, sorry but the issue has to strictly have the fto template. Please reformat it.

**Comment by Harshithpabbati** [comment]
oh fine i will do it.

**Comment by maks-ostashkevich** [comment]
Hello.

I'm trying to complete these changes and make a pull request.
Not able to run "npm test", I've done "npm install", then "npm start", it started to work according to "Gruntfile.js", then, after performing some checks, it's stuck on: "Running "watch" task. Waiting...", not running "test".

Also, do I have to make a separate branch for the project?

**Comment by Harshithpabbati** [comment]
Yeah create a new branch for every new issue.
Exactly what do you  get ?? I mean the error.

**Comment by maks-ostashkevich** [comment]
"Running "watch" task. Waiting..." - this is an output.

After "npm start" it (Gruntfile.js performing) makes several operations, like "browserify", "uglify", then it opens the project main page on localhost, and it's stuck after that, and it does not pass the tests (does not show tests passing).

"npm test" outputs some issue, connected with "TEST" (I've removed all the files and now trying to create a branch), I haven't saved it.

**Comment by Harshithpabbati** [comment]
Yup go to the localhost:3000 after pressing npm start.

**Comment by Harshithpabbati** [comment]
To build dist files you need to run grunt uglify and grunt browserify.

**Comment by maks-ostashkevich** [comment]
Ok, I have to be a collaborator to create a branch?
How can I become it?

**Comment by Harshithpabbati** [comment]
You need to fork it and then you have to clone it.

**Comment by maks-ostashkevich** [comment]
Ok.

**Comment by HarshKhandeparkar** [comment]
@maks-ostashkevich hello! You don't have to run npm test offline. You just have to commit your changes and open a pull request. If there are any problems in the code, the reviewers will know as travis will run the tests online.
 Secondly, to view your changes live, the gruntfile will run the watch task, this means that as soon as you save a file it will build the dist files. To view the changes in the browser (which will be open with localhost:3000 in a tab) you have to click on the `clear offline cache-image-sequencer-static-v3` link which will be right at the end of the page. This will reload the browser and your changes will be live. Thanks!

**Comment by HarshKhandeparkar** [comment]
In this task, since you are only changing index.html file you don't have to build any dist files, you can commit index.html and leave everything aside. You can open a PR and we can review it and ask for any changes (if required) there. Thanks.

**Comment by maks-ostashkevich** [comment]
@HarshKhandeparkar Ok, thank you, now I will try to do this way.

**Comment by HarshKhandeparkar** [comment]
@maks-otashkevich awesome. If you have any other queries, feel free to ask. Otherwise, you can open a pr.

**Comment by maks-ostashkevich** [comment]
@HarshKhandeparkar I've made the changes on the fork, I have to push them now to the fork from my local repository? Cannot figure out, how to do this.

**Comment by maks-ostashkevich** [comment]
@HarshKhandeparkar I've already solved the problem, using "git push origin main".

**Comment by HarshKhandeparkar** [comment]
You have to first create a remote. A remote is essentially a nickname to a link. A link to a github repository. You can create a new remote by using git. When you fork a repository, a remote to the main repository is traditionally called `upstream` and a remote to your online fork ia called `origin`. Origin should be created automatically. You can create upstream by running 
```console
user@pc~: git remote add upstream https://github.com/publiclab/image-sequencer.git
```
You don't need upstream yet but you can create it if you want. To commit your changes, you can do
```console
user@pc~: git add . # stages all the files
user@pc~: git commit - m "some descriptive message" # commit it
user@pc~: git push # push it to origin
```
You will be prompted to type your password and username. Thanks.

**Comment by HarshKhandeparkar** [comment]
By default git will push to origin `git push` will push to origin, the next two arga are optional. And please note that in `git add .` the `.` is important.

**Comment by maks-ostashkevich** [comment]
Ok, will remember this.

I created a fork, then made changes, "add"-ed them, made "commit", then "push"-ed to my fork with "git push origin main" - is this also correct or I still have to do operations that you've described?

**Comment by HarshKhandeparkar** [comment]
All you have to do in the future is add -> commit -> push and Done!
