### ISSUE TITLE
Rework UI Handling

### ISSUE THREAD

**Issue by ccpandhare** [publiclab/image-sequencer#85]
@jywarren you were once suggesting changes in the UI module. I thought upon them, and find them really interesting. Also, the current system has forward compatibility issues (Adding new features to it is really complicated. The code quality isn't very good). I have been working on the new model, with a much cleaner syntax and code and working on it all day. Will create a PR when ready.

Some takeaway features are:
* User defined variables : Users can define a variable for any step. This can be used to store the reference of an HTML Element, for further use in the other events (Like you suggested earlier) .
    ```js
        sequencer.setUI(
            onSetup: function(step){
                step.image = document.createElement('img'); // create a user defined variable step.image
                step.image.setAttribute( 'id', 'IS-'+step.ID ); // access the default variable step.ID
                ... // append to DOM and other stuff
            },
            onComplete: function(step){
                step.src = step.output;
            },
            onRemove: function(step){
                step.remove();
            },
        );
* Unified variables : Earlier there were too many unnecessary variables and objects in the picture : `options`, `identity`, etc. Now all come under the same banner `steps`. This brings in clarity and helps maintain code, and is good for new contributors!
* Easier to understand and more User Friendly.

I am sorry, the "Bootstrapping Phase" doesn't seem to end very soon, major functionality changes happening every day... :(

**Comment by jywarren** [comment]
:-) that's OK -- you're doing really well, thinking through usage and these
improvements are great. Let's just not forget to start wrapping up along a
reasonable timeline for SoC -- and getting our demos and such working. I'd
even like to consider making a demo that's a complete replacement for
Infragram.org and FisheyeGL -- with the extra HTML UI those two have.

Thanks!

On Fri, Jul 28, 2017 at 10:30 PM, Chinmay Pandhare <notifications@github.com

**Comment by ccpandhare** [comment]
Yes, you are right. We have to follow a timeline. I shall stick to it.

Now that the new version of FisheyeGl has been published, I can re-implement the FisheyeGL Module!

**Comment by jywarren** [comment]
+1!

**Comment by ccpandhare** [comment]
"Rework UI Handling" has actually solved a few things for us!
* Modules can give any number of output(s) to the user
* User can send in inputs to the module
* It is much cleaner

**Comment by ccpandhare** [comment]
This is similar to Metadata. Except that the metadata is stored per "step" and not per "module-name"

**Comment by jywarren** [comment]
Ah ok! That does make sense.

**Comment by ccpandhare** [comment]
> I'd even like to consider making a demo that's a complete replacement for Infragram.org and FisheyeGL -- with the extra HTML UI those two have.

A FisheyeGl-like demo has been created. (PR #62)
It can be previewed at https://ccpandhare.github.io/image-sequencer/examples/fisheyegl

**Comment by ccpandhare** [comment]
The link is https://ccpandhare.github.io/image-sequencer/examples/fisheye and not https://ccpandhare.github.io/image-sequencer/examples/fisheyegl, sorry for that.

**Comment by ccpandhare** [comment]
I think this part is over and we are now onto #87 for UI development, So I am closing this issue.
