### ISSUE TITLE
IS Nightly

### ISSUE THREAD

**Issue by HarshKhandeparkar** [publiclab/image-sequencer#857]
@jywarren @publiclab/is-reviewers how about creating an IS nightly website where daily builds are pushed? The page can be updated everyday after all the PRs of that day are merged. It will be different from the sequencer.publiclab.org website since only stable versions are pushed there. This will help users find bugs in the latest code easily and be like beta testers without having to clone the repo and do all the things the developers do. This can be like an end user feedback form. What are your thoughts??

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by jywarren** [comment]
Hi, I think this is a cool idea; we might start with weekly to make it a
bit easier? Would we run it from another account's github pages? And could
there be some automation to help this go smoother? For example, who would
do the updating? Would they have to run a script each day?

Thanks for this cool idea!

**Comment by HarshKhandeparkar** [comment]
How about runing it on jywarren/image-sequencer? Can you update it yourself?

**Comment by jywarren** [comment]
I don't think i could keep up -- i'm already struggling a bit to stay
current. This is one reason I thought of an automated solution. Or if
someone wants to volunteer?

**Comment by HarshKhandeparkar** [comment]
It can be hosted on maybe sequencer.beta.publiclab.org and since prs are not merged everyday, it can be updated when they are. What do you say? Can you do that? Just merging gh-pages with main every night??

**Comment by HarshKhandeparkar** [comment]
Is there a bot who can help?

**Comment by HarshKhandeparkar** [comment]
I would have been more than happy to volunteer but I will be busy as I have mentioned many times bfore.

**Comment by HarshKhandeparkar** [comment]
There is a way to automate this....

Does PL have a server which runs 24hrs?

**Comment by HarshKhandeparkar** [comment]
@subhahu123 do you have any good ideas for this?

**Comment by HarshKhandeparkar** [comment]
@Harshithpabbbati

**Comment by Harshithpabbati** [comment]
Yeah !!

**Comment by HarshKhandeparkar** [comment]
Do you know some way to do this auto updating? A bit maybe?

**Comment by Harshithpabbati** [comment]
I will check through this.

**Comment by Harshithpabbati** [comment]
Or else I can volunteer for this to update them.

**Comment by HarshKhandeparkar** [comment]
Oh Awesome. You can ask @jywarren about that. Thank you.

**Comment by HarshKhandeparkar** [comment]
Do you use linux btw? @Harshithpabbati

**Comment by Harshithpabbati** [comment]
Yeah.

**Comment by HarshKhandeparkar** [comment]
I can write a script for you if you want. You can type `update-is` in the terminal and it will do everything for you and finally ask for your github username. Shall I do that. It won't be very difficult.

**Comment by Harshithpabbati** [comment]
Ok thanks for that!!

**Comment by HarshKhandeparkar** [comment]
Cool. Should it be `update-is` or something else?

**Comment by Harshithpabbati** [comment]
Make it update-is no prob.

**Comment by HarshKhandeparkar** [comment]
Ok. The script is really easy actually.

```bash
#!/bin/bash
set -e

if [ -d ~/.is ];
then
  pushd ~/.is
  rm -R ~/.is/*

  git clone https://github.com/Harshithpabbati/image-sequencer.git

  pushd image-sequencer/
  git checkout gh-pages
  git merge -f upstream/main
  npm run setup
  grunt browserify
  grunt uglify
  git add .
  git add -f node_modules/
  git commit -m "update"
  git push

else
  mkdir ~/.is
  update-is
fi
```

This will ask for your username and password.

You can create a directory named `bin` in your home folder `/home/[username]/`

**Comment by Harshithpabbati** [comment]
Thanks @harshkhandeparkar

**Comment by HarshKhandeparkar** [comment]
I have edited the comment. Please read it again

**Comment by Harshithpabbati** [comment]
@HarshKhandeparkar hey did you renamed it as is ???

**Comment by HarshKhandeparkar** [comment]
Renamed what?

**Comment by Harshithpabbati** [comment]
Getting an error when i tried to run it.

**Comment by HarshKhandeparkar** [comment]
Can you please tell me the error?

**Comment by Harshithpabbati** [comment]
![update](https://user-images.githubusercontent.com/43822585/54492248-e3a06e80-48ea-11e9-9fdd-51612d193158.png)
see this.

**Comment by HarshKhandeparkar** [comment]
Sorry for that. I have updated the comment again.

**Comment by HarshKhandeparkar** [comment]
Btw you dont have to `cd image-sequencer`

**Comment by HarshKhandeparkar** [comment]
Another update. Just enhanced the script.

**Comment by HarshKhandeparkar** [comment]
Reposting full script


```bash
#!/bin/bash
set -e

if [ -d ~/.is ];
then
  pushd ~/.is

  if [ -d ~/.is/image-sequencer/ ];
  then
    rm -r ~/.is/*
  else
    git clone https://github.com/Harshithpabbati/image-sequencer.git

    pushd ~/.is/image-sequencer/
    git checkout gh-pages
    git fetch upstream
    git merge -f upstream/main
    npm run setup
    grunt browserify
    grunt uglify
    echo "beta.sequencer.publiclab.org" > CNAME
    git add .
    git add -f node_modules/
    git commit -m "update"
    git push

    popd 
    popd
  fi
else
  mkdir ~/.is
  update-is
fi
```

**Comment by Harshithpabbati** [comment]
Done !! Thanks :+1:

**Comment by HarshKhandeparkar** [comment]
Cool!

**Comment by Harshithpabbati** [comment]
but i can't get the node modules .

**Comment by HarshKhandeparkar** [comment]
I can't see a gh-pages branch in your fork.

**Comment by HarshKhandeparkar** [comment]
Please initialize github pages for your fork in the repo settings.

**Comment by Harshithpabbati** [comment]
It's not working.

**Comment by HarshKhandeparkar** [comment]
Error?

**Comment by Harshithpabbati** [comment]
no. I made it but the changes were not done. I am doing it manually now.

**Comment by HarshKhandeparkar** [comment]
Have you initialised GitHub pages?

**Comment by HarshKhandeparkar** [comment]
You will see something like this in the settings of your fork

![Screenshot_20190317-200048__01](https://user-images.githubusercontent.com/34770591/54492798-7af0cc00-48c1-11e9-8427-8d34809748a1.jpg)

**Comment by Harshithpabbati** [comment]
yeah.

**Comment by Harshithpabbati** [comment]
It's done !!!. See this https://harshithpabbati.github.io/image-sequencer/examples/#steps=

**Comment by HarshKhandeparkar** [comment]
Totally awesome!!

**Comment by HarshKhandeparkar** [comment]
@jywarren Harshithpabbati has agreed to volunteer. We have managed to automate the process. We have even changed the CNAME to `beta.sequencer.publiclab.org` can we host his `gh-pages` on beta.sequencer.publiclab.org?

**Comment by HarshKhandeparkar** [comment]
@Harshithpabbati can you document this somewhere?

**Comment by Harshithpabbati** [comment]
@harshkhandeparkar what should I do?? I mean documentation.

**Comment by Harshithpabbati** [comment]
Should I write the process what we want to do??

**Comment by HarshKhandeparkar** [comment]
We can just add a line linking to this website once it is hosted on beta.sequencer.publiclab.org.

You can update this whenever you get time. Try to do this daily after all the prs are merged. Since the timezones do not match, you can update at any time of the day. No need to update if no prs have been merged.

Thanks a ton!!

**Comment by Harshithpabbati** [comment]
Ha ok. I have a how to link it to beta.sequencer.publiclab.org???

**Comment by HarshKhandeparkar** [comment]
You can add a line to the CONTRIBUTING.md file or add a link in the webpage footer or both. But lets wait for @jywarren's thoughts on this and lets wait to get this hosted on beta.sequencer.publiclab.org. The full link will have `https://` i.e. `https://beta.sequencer.publiclab.org`

**Comment by HarshKhandeparkar** [comment]
@Harshithpabbati wherever your main clone of image-sequencer is on your pc, it will not be touched. You can run this command from any directory and your main clone will not get affected and nothing will change on your system. You can run the command as many times as you want.

**Comment by Harshithpabbati** [comment]
Yeah I know it.

**Comment by HarshKhandeparkar** [comment]
When we get permission to host on beta.sequencer.publiclab.org, opening harshithpabbati.github.io/image-sequencer will redirect to that. You probably don't have to do anything. @jywarren will give you further instructions and provide permissions to the domain. You just have to update your gh-pages. Maybe the main stable website sequencer.publiclab.org can be updated every month? Any thoughts on this? Improvements? Other ideas? Finishing touches?

**Comment by Harshithpabbati** [comment]
Yeah it's fine :)

**Comment by Harshithpabbati** [comment]
@harshkhandeparkar I runned it but it is not working .

**Comment by Harshithpabbati** [comment]
I mean there is no change in gh-pages

**Comment by Harshithpabbati** [comment]
![terminal](https://user-images.githubusercontent.com/43822585/54508131-c0b59f00-496a-11e9-8638-39b7c6c9b7c0.png)
see this I was not asked with github username and password.

**Comment by HarshKhandeparkar** [comment]
Ok I guess the remote has to be adder manually. Wait a min. I will change that.

**Comment by HarshKhandeparkar** [comment]
Reposted 
```bash
#!/bin/bash
set -e

if [ -d ~/.is ];
then
  pushd ~/.is

  if [ -d ~/.is/image-sequencer/ ];
  then
    rm -r ~/.is/*
  else
    git clone https://github.com/Harshithpabbati/image-sequencer.git

    pushd ~/.is/image-sequencer/
    git checkout gh-pages
    git remote add upstream https://github.com/publiclab/image-sequencer.git
    git fetch upstream
    git merge -f upstream/main
    npm run setup
    grunt browserify
    grunt uglify
    echo "beta.sequencer.publiclab.org" > CNAME
    git add .
    git add -f node_modules/
    git commit -m "update"
    git push

    popd 
    popd
  fi
else
  mkdir ~/.is
  update-is
fi
```

**Comment by Harshithpabbati** [comment]
![check](https://user-images.githubusercontent.com/43822585/54509178-ae3d6480-496e-11e9-998a-13b8c64674cc.png)
see this @HarshKhandeparkar

**Comment by HarshKhandeparkar** [comment]
Type y and hit enter

**Comment by HarshKhandeparkar** [comment]
A small change, now it will not ask for anything.
```bash
#!/bin/bash
set -e

if [ -d ~/.is ];
then
  pushd ~/.is

  if [ -d ~/.is/image-sequencer/ ];
  then
    rm -rf ~/.is/*
  else
    git clone https://github.com/Harshithpabbati/image-sequencer.git

    pushd ~/.is/image-sequencer/
    git checkout gh-pages
    git remote add upstream https://github.com/publiclab/image-sequencer.git
    git fetch upstream
    git merge -f upstream/main
    npm run setup
    grunt browserify
    grunt uglify
    echo "beta.sequencer.publiclab.org" > CNAME
    git add .
    git add -f node_modules/
    git commit -m "update"
    git push

    popd 
    popd
  fi
else
  mkdir ~/.is
  update-is
fi
```

**Comment by Harshithpabbati** [comment]
Everytime when i run this. It is cloning again.

**Comment by HarshKhandeparkar** [comment]
It has to clone again to make sure that no old changes conflict with the latest version. Myabe the branch was changed somehwere else, but the local was not changed. So it clones everytime.

**Comment by Harshithpabbati** [comment]
![css](https://user-images.githubusercontent.com/43822585/54511618-81417f80-4977-11e9-8ef3-c0dc29336dfb.png)
See the css @HarshKhandeparkar

**Comment by HarshKhandeparkar** [comment]
I think@aashna27 is fixing this issue.

**Comment by HarshKhandeparkar** [comment]
Great! Edge detect PR changes have been added.

**Comment by HarshKhandeparkar** [comment]
Another small change. Sorry @Harshithpabbati
```bash
#!/bin/bash
set -e

if [ -d ~/.is ];
then
  pushd ~/.is

  if [ -d ~/.is/image-sequencer/ ];
  then
    rm -rf ~/.is/*
  else
    git clone https://github.com/Harshithpabbati/image-sequencer.git

    pushd ~/.is/image-sequencer/
    git checkout gh-pages
    git remote add upstream https://github.com/publiclab/image-sequencer.git
    git fetch upstream
    git merge -f upstream/main
    npm run setup
    grunt browserify
    grunt uglify

    if [ ! -f CNAME ];
    then
      touch CNAME
    fi
    echo "beta.sequencer.publiclab.org" > CNAME

    git add .
    git add -f node_modules/
    git commit -m "update"
    git push

    popd 
    popd
  fi
else
  mkdir ~/.is
  update-is
fi
```

**Comment by Harshithpabbati** [comment]
@jywarren what do you say ???

**Comment by jywarren** [comment]
Oh my goodness so much happened in this thread. 😅

This looks great. I'll repoint beta.x and perhaps we can do a few things
next:

1. if the script is confirmed to be working, could we make it into a Grunt
or npm task?
2. maybe icarito can set this up for us in Jenkins as a regular task once
we test it out a bit

Thanks!

**Comment by HarshKhandeparkar** [comment]
This is not a js script but instead it is a bash script which runs on the pc and also it is specific for harshith's account. It clones **his** repo and checks out gh-pages and merges with main, builds dist, force commits node_modules and pushes to **his** gh-pages by asking for a password.

So what it does is it clones the repo in a hidden folder on **his** pc's home folder (in linux) and does all of the processing/updating there.

**Comment by jywarren** [comment]
For sure, but npm scripts don't need to be JS - they can run shell scripts
too. Would it be possible to adapt it to take inputs or otherwise detect
your github username/branch etc? Thanks! Just trying to think how we'd
adapt this for a bot to use, for example.

**Comment by HarshKhandeparkar** [comment]
Can a bot have repos?

**Comment by Harshithpabbati** [comment]
Yeah we can take input and can make it run.

**Comment by Harshithpabbati** [comment]
Oh yah the bot can't have the repo 😅

**Comment by Harshithpabbati** [comment]
<code>
#!/bin/bash
echo Enter your username.
read username
set -e

if [ -d ~/.is ];
then
  pushd ~/.is

  if [ -d ~/.is/image-sequencer/ ];
  then
    rm -rf ~/.is/*
  else
    git clone https://github.com/$username/image-sequencer.git

    pushd ~/.is/image-sequencer/
    git checkout gh-pages
    git remote add upstream https://github.com/publiclab/image-sequencer.git
    git fetch upstream
    git merge -f upstream/main
    npm run setup
    grunt browserify
    grunt uglify

    if [ ! -f CNAME ];
    then
      touch CNAME
    fi
    echo "beta.sequencer.publiclab.org" > CNAME

    git add .
    git add -f node_modules/
    git commit -m "update"
    git push

    popd 
    popd
  fi
else
  mkdir ~/.is
  update-is
fi

**Comment by Harshithpabbati** [comment]
<code>
#!/bin/bash
set -e

echo Enter your username.
read username
if [ -d ~/.is ];
then
  pushd ~/.is

  if [ -d ~/.is/image-sequencer/ ];
  then
    rm -rf ~/.is/*
  else
    git clone https://github.com/$username/image-sequencer.git

    pushd ~/.is/image-sequencer/
    git checkout gh-pages
    git remote add upstream https://github.com/publiclab/image-sequencer.git
    git fetch upstream
    git merge -f upstream/main
    npm run setup
    grunt browserify
    grunt uglify

    if [ ! -f CNAME ];
    then
      touch CNAME
    fi
    echo "beta.sequencer.publiclab.org" > CNAME

    git add .
    git add -f node_modules/
    git commit -m "update"
    git push

    popd 
    popd
  fi
else
  mkdir ~/.is
  update-is
fi
</Code>

**Comment by Harshithpabbati** [comment]
I will repost this such that everyone can use this .

**Comment by HarshKhandeparkar** [comment]
@jywarren does PL have a server which runs 24x7??

**Comment by jywarren** [comment]
Yes we do!

**Comment by jywarren** [comment]
I also use my own `publish to gh-pages` script, fwiw:

```
git checkout main
git pull publiclab main
git checkout gh-pages
git merge main -m 'merge from main'
git push publiclab gh-pages
git checkout main
npm install
```

**Comment by jywarren** [comment]
Also, i just released the latest to https://sequencer.publiclab.org and pointed beta.sequencer.publiclab.org to https://harshithpabbati.github.io/image-sequencer/!

**Comment by Harshithpabbati** [comment]
@jywarren check the url beta.sequencer.publiclab.org i cant get it.

**Comment by jywarren** [comment]
ah, you need to add a CNAME file!

**Comment by Harshithpabbati** [comment]
Where should i add it in gh-pages branch ??

**Comment by jywarren** [comment]
That's right!

**Comment by HarshKhandeparkar** [comment]
Hello harshith, the last revision of the script I made actually creates the CNAME file and also points to beta.sequencer.publiclab.org. Please change your script locally.
Reposting
```bash
#!/bin/bash
set -e

if [ -d ~/.is ];
then
  pushd ~/.is

  if [ -d ~/.is/image-sequencer/ ];
  then
    rm -rf ~/.is/*
  else
    git clone https://github.com/Harshithpabbati/image-sequencer.git

    pushd ~/.is/image-sequencer/
    git checkout gh-pages
    git remote add upstream https://github.com/publiclab/image-sequencer.git
    git fetch upstream
    git merge -f upstream/main
    npm run setup
    grunt browserify
    grunt uglify

    if [ ! -f CNAME ];
    then
      touch CNAME
    fi
    echo "beta.sequencer.publiclab.org" > CNAME

    git add .
    git add -f node_modules/
    git commit -m "update"
    git push

    popd 
    popd
  fi
else
  mkdir ~/.is
  update-is
fi
```

**Comment by HarshKhandeparkar** [comment]
Hey harshith, would you mind posting the update script somewhere on github so I can propose cahnges whenever needed? When we add the dist files to gitignore, the script will have to be changed, if anything breaks, I can open a pr and then you can pull the latest script when ot gets updated. Would you mind putting it on github?

**Comment by Harshithpabbati** [comment]
Ok where should I keep it ?? In my repos??

**Comment by HarshKhandeparkar** [comment]
Anywhere you like. Just tell me where. Thanks.😊

**Comment by Harshithpabbati** [comment]
Fine i will create a repo and I will send you the link.

**Comment by subhahu123** [comment]
@HarshKhandeparkar please check this out 
https://community-toolbox-kiwxvw.stackblitz.io/ ( angular version ) ( not completed)

**Comment by HarshKhandeparkar** [comment]
@Harshithlabbati a new pr was juet merged! Please run the script. Also please make sure that you have the latest version that I had posted. It adds the CNAME file to the branch. Let's see if beta.sequencer.publiclab.org redirects.

**Comment by Harshithpabbati** [comment]
Yeah it's redirecting :+1:

**Comment by HarshKhandeparkar** [comment]
I will close this issue in a pr where this is documented in README.md file. @jywarren I noticed that the description of this repo has the link http://sequencer.publiclab.org can it be changed to have https?

**Comment by jywarren** [comment]
Yes that'd be great but I also set it up to force https now.

**Comment by Harshithpabbati** [comment]
Do I need to document about beta.sequencer.publiclab.org

**Comment by Harshithpabbati** [comment]
Ok I am done with the script.

**Comment by HarshKhandeparkar** [comment]
I will do the documentation

**Comment by Harshithpabbati** [comment]
Ok fine thanks.

**Comment by jywarren** [comment]
Hi @harshithpabbati @HarshKhandeparkar shall we place this script in a `/scripts/` folder in the repository? Thanks!

**Comment by HarshKhandeparkar** [comment]
The core script is in my repo `HarshKhandeparkar/Update-is` and the github action is in Harshith's repo. We can definitely migrate the script but that won't change Harshith's github action.

**Comment by harshithpabbati** [comment]
Yes @jywarren, we can do that.
