### ISSUE TITLE
add some css transitions dropdown

### ISSUE THREAD

**Issue by avsingh999** [publiclab/image-sequencer#858]
### Please describe the problem (or idea)
If we can add some CSS transition It would be better UI.we can see in this gif.
 but if we can some transition. example in plots 2 https://github.com/publiclab/plots2/issues/4688
![pub5](https://user-images.githubusercontent.com/25536022/54471891-4e1bb680-47e6-11e9-8882-22ae55470787.gif)

> What happened just before the problem occurred? Or what problem could this idea solve?

> What did you expect to see that you didn't?

### Please show us where to look

http://sequencer.publiclab.org...

### What's your PublicLab.org username?
singhav
> This can help us diagnose the issue:

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by HarshKhandeparkar** [comment]
We can use jquery collapse method. CSS is not required. Cool idea!

**Comment by avsingh999** [comment]
@HarshKhandeparkar yes that's cool Idea!.and it would be better for first timer.
thanks : )

**Comment by HarshKhandeparkar** [comment]
Sorry but this has to be formatted.

**Comment by HarshKhandeparkar** [comment]
Done in #875
