### ISSUE TITLE
Add transition on button or clicking effect like ( translateY )

### ISSUE THREAD

**Issue by subhahu123** [publiclab/image-sequencer#859]
### Please describe the problem (or idea)

on hovering button shows some effects
but on activating it there is no effect or visual effect

add transition or animation on button when someone click it
To show the effect that the button has been clicked

**Comment by HarshKhandeparkar** [comment]
How about waves effect used in android? It is used in the materialize renderer in #825

Live demo [here](https://harshkhandeparkar.github.io/image-sequencer) (marked as new UI)

**Comment by HarshKhandeparkar** [comment]
What is github tab and ribbon feature?

**Comment by subhahu123** [comment]
> How about waves effect used in android? It is used in the materialize renderer in #825
> 
> Live demo [here](https://harshkhandeparkar.github.io/image-sequencer) (marked as new UI)

we can do that also

**Comment by subhahu123** [comment]
> What is github tab and ribbon feature?

i mean u r making a navigation tab for github which is not required as ur just navigating to github website
instead of it use github ribbon like fork me

**Comment by HarshKhandeparkar** [comment]
Oh that is under devel, lets discuss it in #825

**Comment by subhahu123** [comment]
> Oh that is under devel, lets discuss it in #825

Like 
![download](https://user-images.githubusercontent.com/34541684/54472339-ffbde600-47ec-11e9-9f1b-02b682157022.jpeg)

**Comment by HarshKhandeparkar** [comment]
Let's keep this issue to the point and discuss this stuff in the pr #825

**Comment by subhahu123** [comment]
should we open a issue for this
@HarshKhandeparkar

**Comment by HarshKhandeparkar** [comment]
Issue for what? The ribbon? Sure

**Comment by subhahu123** [comment]
y

**Comment by gauravano** [comment]
@HarshKhandeparkar your PR is handling this issue?

**Comment by HarshKhandeparkar** [comment]
No. Not for bootstrap.

**Comment by HarshKhandeparkar** [comment]
Bootstrap button has click effects.
