### ISSUE TITLE
Minify the JS  ( production )

### ISSUE THREAD

**Issue by subhahu123** [publiclab/image-sequencer#861]
####     Refer    #837 

Currently website use non-minifed JS file for serving
instead of it , we should use minified JS to decrease the size 
and for increasing the performance

**Comment by HarshKhandeparkar** [comment]
The js is minified already. Or are you suggesting something else?

**Comment by subhahu123** [comment]
@HarshKhandeparkar  No it is not ( according to me)
![Screenshot_2019-03-16_12-56-22](https://user-images.githubusercontent.com/34541684/54472228-18c59780-47eb-11e9-9424-f5c25118f4e8.png)

**Comment by HarshKhandeparkar** [comment]
We use non minified file since in dev mode, minification takes very long. Is there a way to include minified for prod and normal for dev? Like somehow mark it as prod or dev?

**Comment by subhahu123** [comment]
i think yes 
does we using same website for both prod and dev

**Comment by subhahu123** [comment]
> We use non minified file since in dev mode, minification takes very long. Is there a way to include minified for prod and normal for dev? Like somehow mark it as prod or dev?

what is the link for prod mode website

**Comment by HarshKhandeparkar** [comment]
We use the same website for prod. We just host it on gh-pages branch.

**Comment by HarshKhandeparkar** [comment]
Link is https://sequencer.publiclab.org

**Comment by HarshKhandeparkar** [comment]
Yes it uses non minified as it is the same code

**Comment by subhahu123** [comment]
> Link is https://sequencer.publiclab.org

they are same

**Comment by HarshKhandeparkar** [comment]
It is present on a different branch which is updated less frequently.

**Comment by subhahu123** [comment]
i think should main two branch 
one for main
one for dev

**Comment by subhahu123** [comment]
> It is present on a different branch which is updated less frequently.

they should be in sync

**Comment by HarshKhandeparkar** [comment]
The main branch can be main. But in gh-pages branch, the code can be changed but @jywarren is so busy that he cannot update the gh-pages branch to the latest version let alone changing the code.

**Comment by HarshKhandeparkar** [comment]
It was last updated ~20d ago
