### ISSUE TITLE
Add procfile for heroku deploy

### ISSUE THREAD

**Issue by subhahu123** [publiclab/image-sequencer#862]
### Please describe the problem (or idea)

adding procfile so that anyone can deploy this to heroku also

**Comment by gauravano** [comment]
I think we don't need to cover this as anyone who would be interested in deploying over the heroku would go the extra mile.

Let's have @publiclab/is-reviewers opinion on this one.

Thanks!

**Comment by Harshithpabbati** [comment]
Yup. I feel the same.

**Comment by HarshKhandeparkar** [comment]
Even me. Adding more files will only make the repo look messy. Also heroku is not the only service where people can deploy. Anyways, if someone wants to deploy the app to any service, they will have to make some or the other change. They will atleast have to make it compatible with the service. 

So closing this one. Feel free to open if necessary.

**Comment by HarshKhandeparkar** [comment]
Even me. Adding more files will only make the repo look messy. Also heroku is not the only service where people can deploy. Anyways, if someone wants to deploy the app to any service, they will have to make some or the other change. They will atleast have to make it compatible with the service. 

So closing this one. Feel free to open if necessary.
