### ISSUE TITLE
Saturation Module not working correctly

### ISSUE THREAD

**Issue by mgroovyank** [publiclab/image-sequencer#868]
### Please describe the problem (or idea)

When you add the saturation module then instead of displaying the image with 0.5 saturation value it displays a black image.

![Screenshot (3)](https://user-images.githubusercontent.com/40556224/54489267-7bdd2a00-48d0-11e9-98f2-00430831316f.png)

**You can see it here:**

https://sequencer.publiclab.org/examples/#steps=saturation{}

**Comment by HarshKhandeparkar** [comment]
Hello. Thanks for the catch but this has been already fixed but not uploaded to sequencer.publiclab.org website. Closing this. Thank you!

**Comment by HarshKhandeparkar** [comment]
Hello. Thanks for the catch but this has been already fixed but not uploaded to sequencer.publiclab.org website. Closing this. Thank you!

**Comment by mgroovyank** [comment]
@HarshKhandeparkar  Thanks for update. 
I don't know if this is important. But Have a look at these two links.
Is the difference of default parameter in the two links okay?

https://github.com/jywarren/image-sequencer/blob/main/src/modules/Saturation/info.json
https://github.com/publiclab/image-sequencer/blob/main/src/modules/Saturation/info.json

**Comment by HarshKhandeparkar** [comment]
Oh don't look at jywarren/image-sequencer. It is old. The whole repo has been shifted to publiclab/image-sequencer and jywarren's fork is around 200 commits behind. Thank you.

**Comment by HarshKhandeparkar** [comment]
Would you like to solve some first-timers-only issue? You haven't contributed before right?

**Comment by mgroovyank** [comment]
@HarshKhandeparkar  Yeah I will do it.

**Comment by HarshKhandeparkar** [comment]
@mgroovyank shall I add your name to the list in #842? There are currently 0 fto issues open but there are some fto-candidate issues

**Comment by mgroovyank** [comment]
@HarshKhandeparkar  yes please add my name. Thank you.
