### ISSUE TITLE
Custom UI for modules

### ISSUE THREAD

**Issue by ccpandhare** [publiclab/image-sequencer#87]
We discussed on #62 that modules should provide their own basic UI. This can be done by creating a wrapper UI module which requires in the actual module and also contains the UI elements.

What do we mean by a basic UI? A basic UI could just mean `<input type="text" />` elements for all input fields or a slider as in FIsheyeGl. It's not very clear as to what should be done - or what the purpose is.

What are our expectations from the module in terms of UI? What UI Elements should it return? Ideally, Image Sequencer is supposed to have multiple steps, and not one entire page for just one step (Which has been the case for the demos I have recently made). 

This is why I thought that the module can return the elements that it wants, but again the positioning and styling will highly depend on the implementation (one-step, multi-step, multi-image, et cetra.) , so it is really hard to expect the module to return a fit-all UI which can simply be injected into the front end code.

I think still a little clarity is needed on this front.

**Comment by jywarren** [comment]
Hi, Chinmay - i guess that we should try to prototype this. What if we build one around the `threshold` module that has a single slider to set the threshold, and perhaps one other, and then make a demo that uses both of these UIs to present a 2-step example?

**Comment by jywarren** [comment]
But also -- if you can list out some of your questions to narrow this down, that's also a good next step. Thanks!!!

**Comment by ccpandhare** [comment]
This was implemented in #92 
Now modules have an `info.json` which spcifies what inputs they take, their defaults, their min/max values, etc. Documentations also added. This can be used to create UIs!

Do you think this is complete or can be improved upon? If it looks complete, I shall close the issue

**Comment by jywarren** [comment]
This looks super. Close!
