### ISSUE TITLE
Does not redirect HTTP traffic to HTTPS: Chrome Audits

### ISSUE THREAD

**Issue by Divy123** [publiclab/image-sequencer#870]
### Please describe the problem (or idea)
The chrome audit reports of LightHouse in Chrome Dev tools states that the webpage does not redirect HTTP traffic to HTTPS which means that insecure HTTP traffic is not sent to HTTPS.

For reference:

![Screenshot from 2019-03-18 00-06-01](https://user-images.githubusercontent.com/31225007/54496119-ac918380-4911-11e9-999b-220374970543.png)

A link to the LightHouse docs:

https://developers.google.com/web/tools/lighthouse/audits/http-redirects-to-https

**Comment by Divy123** [comment]
@jywarren your thoughts upon this?

**Comment by HarshKhandeparkar** [comment]
There is an open issue #819.

**Comment by HarshKhandeparkar** [comment]
I think this can be closed as that one proposes a fix rather than an issue
