### ISSUE TITLE
Images should be optimized : LightHouse effect

### ISSUE THREAD

**Issue by Divy123** [publiclab/image-sequencer#872]
I think we can use [imagemin](https://github.com/imagemin/imagemin) to minimize our images.
@jywarren what do you think upon it?

**Comment by HarshKhandeparkar** [comment]
Does imagemin do a lossy compression?

**Comment by Divy123** [comment]
Well I think yes.

Minify images seamlessly:says minmatch docs.

**Comment by HarshKhandeparkar** [comment]
Lossy compression means that the edges and other less important parts of images are decreased in resolution. I think this should not be done to IS as the images have to be high res and their quality should be preserved. Tools like imagemin can be used on landing page kind of sites where most of the images are real life photos and compression would not make much of a difference. But this gave me a new idea. How about a module which compresses/minifies images?

**Comment by Divy123** [comment]
@HarshKhandeparkar Totally agree!!
May I work on this module and what do you think should we use imagemin for this?

**Comment by HarshKhandeparkar** [comment]
You can work on that module for sure!! Do you want to open a new issue or edit this one?

**Comment by Divy123** [comment]
Ya I am editing this one.

**Comment by Divy123** [comment]
Creating a new one.

**Comment by jywarren** [comment]
This is an awesome idea for a module.
