### ISSUE TITLE
Add Dropdown Transitions

### ISSUE THREAD

**Issue by HarshKhandeparkar** [publiclab/image-sequencer#874]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.
Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

**To Do**: Add a nice transition effect to the step collapse using bootstrap collapse plugin.

### 📋 Step by Step
- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [defaultHtmlStepUi js](https://github.com/publiclab/image-sequencer/blob/main/examples/lib/defaultHtmlStepUi.js) in the `image-sequencer` repository (press the little pen Icon) and edit the line as shown below. 

Change this code
https://github.com/publiclab/image-sequencer/blob/e1a113cde183a620eaa9bb0fd0c37520178eb84a/examples/lib/defaultHtmlStepUi.js#L158-L161

[See this page](https://publiclab.github.io/community-toolbox/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
    $(step.ui.querySelector(".toggle")).on("click", () => {
      $(step.ui.querySelector('.toggleIcon')).toggleClass('fa-caret-up').toggleClass('fa-caret-down');
- $(step.ui.querySelectorAll(".cal")).toggleClass("collapse");
+ $(step.ui.querySelectorAll(".step")).collapse('toggle');
    });
```
- [ ] 💾 **Commit** your changes.

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review
### Please keep us updated
💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?
🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by HarshKhandeparkar** [comment]
@mgroovyank do you want to solve this? This will be reserved to you for the next 2 days. If you don't reply, ths can be assigned to someone else. But don't worry as new issues will be opened soon.
If someone wants to solve a first-timers-only issue but this one is taken up, join the discussion and add your name to the list in #842.

**Comment by An0u** [comment]
I'd like to take this one up if it becomes available

**Comment by mgroovyank** [comment]
@HarshKhandeparkar I am doing this. Thank you.

**Comment by HarshKhandeparkar** [comment]
@mgroovyank awesome!! @An0u your name has been added to the list in #842

**Comment by mgroovyank** [comment]
@HarshKhandeparkar  I have sorted it out. The code you provided didn't worked. 
So I've opened another pull request with changes that work.
#880 
Sorry I can't provide you any GIF.
