### ISSUE TITLE
Document separate "build" from "minify/uglify" tasks in grunt

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#875]
@publiclab/is-reviewers this was suggested already but we didn't follow-up, so I'm opening a new issue for it. It seems this exists now, but it's not well documented.

Copying in the last note from that issue via @HarshKhandeparkar on this distinct issue:

> Yes. Definitely. I think the gruntfile should be revised. Its very messy as of now. The ui dist files are not built in the build task. All the targets of a task are mentioned whereas the whole taskname can be used. Like instead of adding browserify:dist browserify:js uglify:dist uglify:js to the build task, browserify ulgify is enough. Etc. Can somebody open a new issue for that or do taht directly?

So, I think we currently have:

1. `grunt build` - just do everything below
2. `grunt browserify` - just generate `dist/image-sequencer.js`
3. `grunt uglify - minify `dist/image-sequencer.js` to `dist/image-sequencer.min.js`

Is this correct? I believe we could also better show building UI files, so instead of current `grunt browserify:js` it should be `grunt browserify:ui`?

https://github.com/publiclab/image-sequencer/blob/main/Gruntfile.js#L56

Let's especially make it clear to people that:

1. you don't need to submit /dist/ files (as per #601) in PRs
2. while developing you don't need to run full `grunt build` but only `grunt browserify`?

Is this correct?

**Comment by jywarren** [comment]
Reopening just so we can add better documentation to newcomers using this! (and oldcomers since it changed 😄 )

**Comment by HarshKhandeparkar** [comment]
Fixed in #897
