### ISSUE TITLE
Cursor doesn't change to pointer on link

### ISSUE THREAD

**Issue by mgroovyank** [publiclab/image-sequencer#878]
The cursor when hovered on the link - _Clear offline cache image-sequencer-static-v3_  doesn't changes to a pointer, instead it remains a text type cursor.

![Screenshot (12)](https://user-images.githubusercontent.com/40556224/54507074-97dedb00-4965-11e9-8177-82d307da46ea.png)

The cursor when hovered on the link should change to a pointer(or hand).

You can have a look here at:
https://sequencer.publiclab.org/examples/

**Comment by HarshKhandeparkar** [comment]
Hello. Thanks for the issue but there is already an issue which suggests to change the link to a button and a pr already solves it. Sorry but this can be closed.
