### ISSUE TITLE
npm audit and dependabot

### ISSUE THREAD

**Issue by HarshKhandeparkar** [publiclab/image-sequencer#882]
### Please describe the problem (or idea)
I installed lodash recently in a pr where I had removed it by mistake and the version that was installed was 6 patches ahead of the old one. Also when I installed it, I found that npm audit showed 5 critical warnings. Is dependabot working properly ? Also I feel like npm audit fixes should be done to IS deps.

cc @jywarren @tech4GT @publiclab/is-reviewers
****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by jywarren** [comment]
I'm not sure exactly how the two systems track. But I'd love to accept a PR
that's the result of running `npm audit` -- then maybe we can get ahead of
dependabot, even?

**Comment by HarshKhandeparkar** [comment]
I am busy right now. If someone else wante to work, they can but of nobody claime it for the next few weeks, I will fix it. (Once my exams are over).

**Comment by gauravano** [comment]
No hurry @HarshKhandeparkar. All the best for exams!
