### ISSUE TITLE
Weekly Community Check-in #14 - "Let's complete them."

### ISSUE THREAD

**Issue by Harshithpabbati** [publiclab/image-sequencer#883]
Hi everyone!!!

We all at Public Lab  :balloon:  - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. The goal of our Community Check-In is for every community member to share something about their work from the past week and about their current week's goal :dart: . You are also welcome to share fun-fact :smile: , new ideas  :bulb: , your learning goals :ballot_box_with_check: .

If you're new here, welcome :balloon:, and please comment a Hello message below, we love to work with you. If you're looking for new issues, please try some of our first-timers-only issues.

We're SO EXCITED to have your help!

Is there anything, you would like to share with us from last week's work? What is your plan for this week?

If you have not planned yet, just leave a Hello! so that we know that you are in sync with us :arrows_clockwise: and doing well!

As always, if you're waiting for a review, or if you're stuck, you can request help here, leave a comment on your issue with @publiclab/reviewers mentioned, or ask the community in our Gitter chatroom :open_hands: .
### Gitter
Gitter is an active chatroom in our community and we'll be sending weekly reminders about check-ins there. Be sure to sign up there for these updates or just to join the conversation page .

### This Week's Theme
Let's complete the issues which needs rebase and let the community grow. I guess everyone know how to pull a pr to check it locally or else see this
<code>git fetch repo pull/pr-number/head:new-branch-name</code>
Let's rebase and solve the issues where the contributer is not active.

### Summer of Code
@jywarren has started a brainstorming post for the ideas page for Summer of Code 2019 -It would be best to get some ideas into the discussion from the fellow community member before time. People have been brainstorming already - let's do it together!
https://publiclab.org/notes/warren/01-02-2019/brainstorming-for-summer-of-code-2019
And this is the official idea’s page:
https://publiclab.org/wiki/gsoc-ideas

### Software Contributors Survey
This survey is conducted on a yearly basis to improve our experience.
https://goo.gl/forms/4VVMO8dOijRj6BUA3
The form will remain open until early March, but don't wait to respond! This one’s for us!

### Outreachy
If you're a Outreachy aspirant and looking forward to spending your summer with us working on UI improvements of https://publiclab.org, then check out https://github.com/publiclab/plots2/issues/5022 and call for Outreachy proposals is also open -https://publiclab.org/notes/gauravano/03-12-2019/call-for-outreachy-2019-proposals so do start your proposal early! 

### Welcoming First Timers
Check out issues #842 in image-sequencer and https://github.com/publiclab/plots2/issues/4963 if you are a first timer who is in search of an issue to start your open source journey. You are always welcome!

cc
@mohitRJranjan @milaaraujo @kevinzluo @Rishabh570 @sashadev-sky @geekychaser @shubhscoder @sidntrivedi012 @SidharthBansal @cesswairimu @stefannibrasil @ViditChitkara @tech4GT @mridulnagpal @IshaGupta18 @CoderJolly @namangupta01 @sagarpreet-chadha @Souravirus @MayankKashyap @siaw23 @ryzokuken @icarito @steviepubliclab, @ebarry, @jywarren, @sagarpreet-chadha, @JonathanXu1, @uzorjchibuzor, @eli6, @rexagod, @dinaelhanan, @dependabot[bot], @oorjitchowdhary, @wanzulfikri, @mohitRJranjan @publiclab/mentors @publiclab/image-sequencer-guides @publiclab/leaflet-environmental-layers-guides @Paarmita @publiclab/reviewers @Divy123 @bhavayAnand9 @Mridul97 @avsingh999 @romanrodriguez @Dhiraj240 @codeIriss @rishabhc32 @chirag-singhal @IgorWilbert @dhruvgupta167 @vrk99 @pdurbin @HarshKhandeparkar @aashna27 @Harshithpabbati @marieram @swiatek7 @kaunair
@niravasher 

Thanks and keep contributing! Contributing to Public Lab means contributing to the Environment.

People who did the check-ins-
Gaurav Sachdeva (@gauravano )
Sidharth Bansal (@SidharthBansal)
Cess (@cesswairimu )
Harman Jolly (@CoderJolly )
Rishabh Rawat (@Rishabh570 )
Sasha Boginsky (@sashadev-sky)
Rishabh Kr Bothra (@geekychaser)
Shubham Sangamnerkar (@shubhscoder)
Siddhant N Trivedi(@sidntrivedi012)
Isha Gupta (@IshaGupta18)
Gaurav Sachdeva (@gauravano)
Harshith Pabbati (@Harshithpabbati)
Gaurav Sachdeva
Harshith Pabbati (@Harshithpabbati)

Have a great week everyone :balloon: :tada: :sparkler:

**Comment by HarshKhandeparkar** [comment]
@Saurabh19126848_twitter @dhruvgupta167 @marieram @swiatek7 @kaunair @gauravano @publiclab/reviewers @publiclab/is-reviewers @publiclab/community-reps

**Comment by HarshKhandeparkar** [comment]
@subhahu123 @An0u @Jaya738 @mgroovyank 

@shreyateeza 
@TANGL3SIT3S
@nazeem1988
@karunagoyalk
@Nirvikalpa108
@cassianoblonski
@EngrEric
@Anjalizi
@GettyOrawo
@coderbeetle
@corbettbw
@govindjeevan
@gautamig54
@daddyjab
@emestabillo
@letnewKid
@srujana121
@jazdao
@ChinwenduSilvia
@aggarwal19
@Jenniline
@madelinejones
@helenatxu
@richa031
@fabsar
@kuja24
@megha070 
@Aarabhi2017 
@Manvi07
@siddhishree
@CubikMan47
@Julius26
@VinneyJ

These are some newcomers. Welcome!!

**Comment by jywarren** [comment]
Thanks for posting, @Harshithpabbati !!! Great job!

**Comment by madeofhuman** [comment]
Hi, guys! I'm happy we're all still here and contributing, and a huge welcome to the newcomers (you're going to love it here!)

Goals for the week:

  * [ ] 1. Close out my last PR from last week and work on three new issues
  * [ ] 2. Create two first-timer-only issues
  * [ ] 3. Provide guidance to others (and learn) by reviewing at least two PRs
  * [ ] 4. Finalise and submit my Outreachy internship application.

Looking forward to everybody being more awesome than we were last week 😸 🕺 🍾

**Comment by ebarry** [comment]
This week i will be closing the Survey down, so if you haven't filled it in, here's the link https://github.com/publiclab/plots2/issues/4614

I am also working on setting up an evaluation plan for our upcoming education work in the Gulf Coast.

**Comment by divyabaid16** [comment]
Hi everyone!
My last week had been quite productive and I wish the same for this week too.

**My goals for this week**
1. Find some more bugs and report them in form of issues.
2. Work on some more issues and submit PR for the same.
3. Create my outreachy proposal.

And yes, I must say that this community is beginner friendly.

**Comment by ananyaarun** [comment]
Hi everyone !!
The last few days were amazing considering the amount i got to learn!! Looking forward to a great week ahead :)
My goals for this week are:
- Work on some more issues and bugs
- Make a few FTO issues
- Finalize and submit my outreachy application
- Continue to help and learn from the community :smiley:  

Good luck everyone !!

**Comment by emestabillo** [comment]
Hi folks! It’s been awesome finding this community! Everyone is so active and helpful 🙂

First - My first PR got merged (Huzzah!)

For this week:
1. I hope to help out/review a pending PR, and 
2. Find another issue to tackle

Have a good rest of the week to all! 🌞

**Comment by IshaGupta18** [comment]
Hey Everyone! Really great to see so many people coming in and expanding our community! I am learning so much from all of us!

Plans for this week:

1. Help out more, with PRs and issues.
2. Help out first-timers more in understanding the codebase and collaborate with them.
 
Make the proposals better and complete.
I would love it if you guys give some feedback on my GSoC proposal here:

https://publiclab.org/notes/IshaGupta18/03-04-2019/gsoc-proposal-sensor-data-upload-and-display-library?_=1551722861#

Any review is appreciated!

Cheers everyone! :tada:

**Comment by niravasher** [comment]
Hello contributors, glad to see so many people here. My goals for this week are
1) Finish my issue and work on new issues in image sequencer
2) Start working on mapknitter
3) Complete my GSOC proposal
Good luck to everyone

**Comment by jywarren** [comment]
Hi, everyone! I'm hoping this week to close out some long-running bugs on our different projects. Any help with this would be appreciated! You can find bugs and try to help document them, find relevant code links, that sort of thing at these addresses:

* "priority" bugs: https://github.com/publiclab/plots2/labels/priority
* all bugs (lots!) https://github.com/publiclab/plots2/labels/bug

It's so wonderful to see everyone here, we truly appreciate your work and love having you all as part of the community! 🎉

**Comment by kaunair** [comment]
Hey everyone! I'm hoping to get a little more active on publiclab from this week!
I have been getting my hands dirty on a bit of CI lately, also configured coveralls for mapknitter :smile: 
My aims for this week:
* Improve test coverage for mapknitter
* Try to set up dangerbot
* Finish my gsoc proposal

Have fun everyone!

**Comment by jywarren** [comment]
@kaunair special thanks for that Coveralls issue!!!!

**Comment by gauravano** [comment]
Anyone interested in opening check-in for next week? Let's open this time in mapknitter. Thanks!

**Comment by CoderJolly** [comment]
Yup !!

**Comment by gauravano** [comment]
@CoderJolly please open check-in at mapknitter and you can refer https://github.com/publiclab/plots2/blob/master/doc/CHECKINS.md for details. Thanks!

**Comment by CoderJolly** [comment]
Sunday evening would be good ?

**Comment by gauravano** [comment]
Yes!

**Comment by CoderJolly** [comment]
> Yes!

Any theme ?

**Comment by HarshKhandeparkar** [comment]
New check-in https://github.com/publiclab/mapknitter/issues/447
