### ISSUE TITLE
Fix Typo In EdgeDetect Module

### ISSUE THREAD

**Issue by HarshKhandeparkar** [publiclab/image-sequencer#884]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/image-sequencer/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.
Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

**To Do**: Fix a typo in EdgeDetect module source code which doesn't affect functionality but is better to be fixed.

### 📋 Step by Step
- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [Module.js](https://github.com/publiclab/image-sequencer/blob/main/src/modules/EdgeDetect/Module.js) in the `image-sequencer` repository (press the little pen Icon) and edit the line as shown below. 

Change `options.hystereis` to `options.hysteresis`
Here

https://github.com/publiclab/image-sequencer/blob/c6457323ccb19297553dedbac7f5caf39e00a078/src/modules/EdgeDetect/Module.js#L10

And here

https://github.com/publiclab/image-sequencer/blob/c6457323ccb19297553dedbac7f5caf39e00a078/src/modules/EdgeDetect/Module.js#L30
[See this page](https://publiclab.github.io/community-toolbox/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

On line 10
```diff
-  options.hystereis = options.hysteresis || defaults.hysteresis;
+  options.hysteresis = options.hysteresis || defaults.hysteresis;
```

And on line 30
```diff
-      pixels = require('./EdgeUtils')(pixels, options.highThresholdRatio, options.lowThresholdRatio, options.hystereis);
+      pixels = require('./EdgeUtils')(pixels, options.highThresholdRatio, options.lowThresholdRatio, options.hysteresis);
```
- [ ] 💾 **Commit** your changes
- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review
### Please keep us updated
💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?
🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by HarshKhandeparkar** [comment]
This issue is reserved for@Jaya738. You can resolve this at anytime and take as much time as you want but please let us know that you are working on this. Sorry for the delay and thank you!

**Comment by HarshKhandeparkar** [comment]
If a newcomer wants to solve an issue, they can get their name added to the list in #842

**Comment by Michaellin250** [comment]
Can I work on this issue?

**Comment by HarshKhandeparkar** [comment]
Go ahead!

**Comment by scheleon** [comment]
Is this issue assigned? I would love to work on it
