### ISSUE TITLE
Error: Cannot read property 'options' of undefined

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#888]
I'm seeing this on the latest main branch, when clicking a quick-add module: https://sequencer.publiclab.org/examples/

```
image-sequencer.js:68615 Uncaught TypeError: Cannot read property 'options' of undefined
    at Object.modulesInfo (image-sequencer.js:68615)
    at Object.selectNewStepUi (image-sequencer-ui.js:294)
    at HTMLDivElement.<anonymous> (image-sequencer-ui.js:83)
    at HTMLDivElement.dispatch (jquery.min.js:2)
    at HTMLDivElement.y.handle (jquery.min.js:2)
```

**Comment by jywarren** [comment]
I think we could do a few things here; 

1. let's move all `/examples/lib/` into `/src/ui/`
2. let's make a test for clicking the previews and confirming a step is added, [in this test](https://github.com/publiclab/image-sequencer/tree/main/test/spec/insertPreview.spec.js)
3. let's give the preview buttons unique CSS classes like `preview-step preview-step-resize` so we can more easily write the test.

**Comment by jywarren** [comment]
But I can't find where the previews onClick events are connected up... that's what I want to write a test for and fix...

**Comment by VibhorCodecianGupta** [comment]
@jywarren the quick-add modules are the modules on the widget that we can add on a single click, right? I can't seem to reproduce the issue. Is there a screenshot?

**Comment by jywarren** [comment]
That's right. I'll try uploading one later today! @Harshkhandeparkar do you
see it running normally?

**Comment by VibhorCodecianGupta** [comment]
I was able to reproduce the issue. Tricky, this one. Trying to backtrack.

**Comment by jywarren** [comment]
Thanks Vibhor!!!

**Comment by jywarren** [comment]
Publishing 3.0.1 now! @Divy123 @HarshKhandeparkar @publiclab/is-reviewers @VibhorCodecianGupta @tech4GT - thank you!!!

**Comment by Divy123** [comment]
Feeling great to be a part of this. :heart: 
Thanks a lot @jywarren @tech4GT @HarshKhandeparkar for helping out always .
