### ISSUE TITLE
ImageSequencer Mobile App 

### ISSUE THREAD

**Issue by HarshKhandeparkar** [publiclab/image-sequencer#890]
### Please describe the problem (or idea)
How about creating a mobile app for IS. We can use react native maybe? Should this be amrked as long term?

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by HarshKhandeparkar** [comment]
@publiclab/is-reviewers

**Comment by tech4GT** [comment]
Harsh, Actually we already have a PWA and I don't think we really need a native mobile app since most of our processing is happening in javascript anyway.

**Comment by HarshKhandeparkar** [comment]
I tried adding IS to homescreen but it didn't seem to work as expected. The browser has to be open in the background for some reason.

**Comment by HarshKhandeparkar** [comment]
I think native will also increase performance on mobile phones with less processing power.

**Comment by Divy123** [comment]
@HarshKhandeparkar @tech4GT Just noting here something regarding lighthouse
![pwa](https://user-images.githubusercontent.com/31225007/54598761-3c911380-4a5f-11e9-8665-741fe3766858.png)
I think this can be settled out by mior UI fixes and can be a good fto.

**Comment by gauravano** [comment]
Any updates here? @Divy123 are you working on fixing on those minor fixes? Thanks!

**Comment by HarshKhandeparkar** [comment]
I think the minor fixes can be addressed in a separate issue. They are not related to this issue.

**Comment by jywarren** [comment]
I think these seem to be solved, as I just installed it!
