### ISSUE TITLE
Selectize is not responsive

### ISSUE THREAD

**Issue by HarshKhandeparkar** [publiclab/image-sequencer#891]
### Please describe the problem (or idea)
The module search box added by @Divy123 using selectizeJs is not responsive on small screens
![Screenshot_20190319-180250](https://user-images.githubusercontent.com/34770591/54606353-823fe300-4a43-11e9-804a-09072a99472e.jpg)

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by jywarren** [comment]
Oh whoops thanks Harsh you're too fast!!! 😂🎉🙌🏽

**Comment by HarshKhandeparkar** [comment]
Duplicate of #892
