### ISSUE TITLE
Add step selector too narrow on mobile view

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#892]
The new selector is awesome! I just noticed that on my phone it's a bit narrow. Should be a quick fix!

**Comment by jywarren** [comment]
![Screenshot_20190319-083528](https://user-images.githubusercontent.com/24359/54606808-2feeca00-4a23-11e9-8b7d-0f2254333b06.png)

**Comment by HarshKhandeparkar** [comment]
Duplicate.

**Comment by HarshKhandeparkar** [comment]
Closed the other one

**Comment by Divy123** [comment]
I think the issue can be made a FTO.
What do you think @jywarren @HarshKhandeparkar ?

**Comment by jywarren** [comment]
Sounds great!!

**Comment by HarshKhandeparkar** [comment]
Needs reformat

**Comment by Divy123** [comment]
Yup doing ..

**Comment by Divy123** [comment]
@HarshKhandeparkar do I have to add first timers issue template here?

**Comment by HarshKhandeparkar** [comment]
Yes

**Comment by HarshKhandeparkar** [comment]
Or open a new issue

**Comment by HarshKhandeparkar** [comment]
Opening a new one would be better. Be sure to notify about it in issue #842

**Comment by Divy123** [comment]
Sure. So closing this one.
cc @jywarren

**Comment by HarshKhandeparkar** [comment]
Fto #894
