### ISSUE TITLE
Add step selector too narrow on mobile view

### ISSUE THREAD

**Issue by Divy123** [publiclab/image-sequencer#894]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/image-sequencer/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

**To Do**: Make the step selector dropdown and add step button responsive.

#### To Fix
![Screenshot_20190327-153954__01__01__01](https://user-images.githubusercontent.com/34770591/55068019-bedd9100-5078-11e9-962f-0bdaf0a88138.jpg)

You can have a look [here](https://beta.sequencer.publiclab.org) for reference.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [examples/index.html](https://github.com/publiclab/image-sequencer/blob/main/examples/index.html) in `image-sequencer` repository (press the little pen Icon) and edit the line as shown below.

[See this page](https://publiclab.github.io/community-toolbox/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

Diff yet to be added.

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there.

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

**Comment by HarshKhandeparkar** [comment]
If a newcomer wants to solve an issue but cannot find one, they can get their name added to the list in #842

**Comment by Divy123** [comment]
Thanks @HarshKhandeparkar

**Comment by HarshKhandeparkar** [comment]
This issue is reserved for @An0u

**Comment by HarshKhandeparkar** [comment]
@Divy123 @Harshithpabbati @aashna27 can this issue be solved by using bootstrap flex grid? The step selector can be given a class of `.col-sm-12 .col-md-8` and the add step btn `.col-sm-12 .col-md-4`. Is this possible? Also changing selectize dist file directly isn't advisable. Also selectize is actually included through node modules, so no question about editing dist.

**Comment by Harshithpabbati** [comment]
I guess we can override them.

**Comment by HarshKhandeparkar** [comment]
@aashna27 what are your views on this?

**Comment by HarshKhandeparkar** [comment]
> I guess we can do it.

So shall we edit the issue?

**Comment by Harshithpabbati** [comment]
@HarshKhandeparkar I just tried it now but we need to even change the width of the button so we have to change in it's own css.

**Comment by HarshKhandeparkar** [comment]
I don't think we need to change the width. Did you try the col classes?

**Comment by Harshithpabbati** [comment]
Yeah I tried it.

**Comment by Harshithpabbati** [comment]
@HarshKhandeparkar I just tried to change the width of the option and then now it's ok even with the small screens.

**Comment by Harshithpabbati** [comment]
![xs](https://user-images.githubusercontent.com/43822585/55063550-32de6000-509e-11e9-8632-90192a094a89.png)
See this is what it's happening even if I use col-xs.

**Comment by HarshKhandeparkar** [comment]
Do you have a screenshot?

**Comment by HarshKhandeparkar** [comment]
It is happening **because** you are using col-xs. Try adding only `.col-sm-12` class.

**Comment by HarshKhandeparkar** [comment]
Please note that the columns have to be eirect children of a `.row`

**Comment by Harshithpabbati** [comment]
Yeah they are in that row div.

**Comment by Harshithpabbati** [comment]
Oh okay we want them in different lines right???

**Comment by HarshKhandeparkar** [comment]
```html
<div class="row">
  <div class="col-sm-12">
    <div>
       <!-- step selector markup -->
    </div>
  </div>
  <div class="col-sm-12">
    <div>
       <!-- add step btn markup -->
    </div>
  </div>
</div>
```

**Comment by Harshithpabbati** [comment]
@harshkhandeparkar i did the same thing

**Comment by HarshKhandeparkar** [comment]
How is it not working then? It should work...

**Comment by Harshithpabbati** [comment]
![ch](https://user-images.githubusercontent.com/43822585/55065374-bbaacb00-50a1-11e9-984a-e7e4998c0b55.png)

**Comment by Harshithpabbati** [comment]
It's because of the custom width of the selectize.

**Comment by HarshKhandeparkar** [comment]
The add step btn should have full sized....

**Comment by Harshithpabbati** [comment]
May be even that have a particular width

**Comment by HarshKhandeparkar** [comment]
It shouldn't...

**Comment by HarshKhandeparkar** [comment]
Try giving it a style width=100%

**Comment by Harshithpabbati** [comment]
In demo.css it is having max-width:500px; thats the reason.

**Comment by HarshKhandeparkar** [comment]
Oh. Remove that and try...

**Comment by aashna27** [comment]
I am sorry, a little busy for 2 days I ll get back with a suggestion after
that.

**Comment by HarshKhandeparkar** [comment]
@jmauriciowebdev you can try this one.

**Comment by HarshKhandeparkar** [comment]
fixed
