### ISSUE TITLE
There's a problem with exportBin

### ISSUE THREAD

**Issue by tech4GT** [publiclab/image-sequencer#899]
<img width="1079" alt="Screen Shot 2019-03-20 at 5 59 39 PM" src="https://user-images.githubusercontent.com/25617855/54684330-070d2880-4b3a-11e9-906b-2a097172ccaa.png">
cc @jywarren @HarshKhandeparkar @Divy123

**Comment by Divy123** [comment]
Looking into it.

**Comment by Divy123** [comment]
I am unable to see the image variable declared in the whole file.

**Comment by tech4GT** [comment]
Hmm, never mind I found it.

**Comment by Divy123** [comment]
What have you found out?

**Comment by tech4GT** [comment]
Pushing in a fix now, please be careful to test the project via all the clients in the future, we don't want broken code on npm right.

**Comment by tech4GT** [comment]
it should be "image" not image

**Comment by Divy123** [comment]
Ya that should work!!

**Comment by Divy123** [comment]
Actually I think there is a confusion.
I never changed anything in this file.
So this problem might be existing from some earlier parts.
@tech4GT

**Comment by tech4GT** [comment]
That's okay, I did not mean you broke something, just wanted to say it's good practice to test for all clients before pushing to npm.

**Comment by Divy123** [comment]
Thanks for always helping and guiding.
I will be writing a workflow for webgl shim issue there.
Please help there to create a right workflow on things as majority of the hinderances have been figured out.

**Comment by jywarren** [comment]
Thanks all! Was there a test we might write to protect this in the future?

We're also still seeing an error on addsteps in the demo, I wanted to try
to fix that but also add a test to protect it as well. Now that we have
test suites for all clients as well as UI, we can get much higher test
coverage and this sort of thing will happen less. Thanks again!

**Comment by Divy123** [comment]
Can you tell which kind of error in addSteps, the responsiveness one?

**Comment by tech4GT** [comment]
Hi jeff, I redid the import-image using another instance of sequencer to load the image. If that’s okay we can merge and publish to npm since the current code is not working on CLI

**Comment by tech4GT** [comment]
Btw import-image is now working in node.

**Comment by Divy123** [comment]
Can you please elaborate on why the CLI part is not working @tech4GT ?
I mean what are the issues?

**Comment by jywarren** [comment]
Awesome can u bump the version number?

The addsteps error is here:
https://github.com/publiclab/image-sequencer/issues/888

Thanks!
