### ISSUE TITLE
Add Step via HTML ui in demo errors in PixelManipulation

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#9]
As described in #6, in comments, after merging #6, I still got:

```js
Uncaught TypeError: Cannot read property 'src' of undefined
    at PixelManipulation (image-sequencer.js:184462)
```

on this line: https://github.com/publiclab/image-sequencer/blob/master/src/modules/PixelManipulation.js#L17

when adding a new step via the HTML ui. But then when I drop a new image into the `image-select` UI, all steps run correctly. 

This may have to do with `sequencer.run()`

**Comment by rackstar17** [comment]
sequencer.run() expects an image parameter 
file - dist/image-sequencer.js line -184165 

```
function run(image) {
    if (image) steps[1].draw(image);
    else steps[0].draw();
  }
```

So maybe it's not catching the image and that's why showing undefined error

I might be wrong since I just started looking at the codebase 
What do you think @jywarren ?

**Comment by jywarren** [comment]
I was trying to make it so that you could pass an image in via run(image)
but that you could also just trigger it by sending an empty run call if the
imageselect module exists. But I think it could be better thought through
-- I don't like how imageselect is "special", you know? It breaks the
rules. Maybe imageselect is really part of the HTML UI, and not a module?

**Comment by ccpandhare** [comment]
@jywarren  Yes, I too believe that image-select shouldn't be treated as a module, and be a part of HTML UI.

For now, I have fixed the issue by declaring a global variable document.sequencer_image.
I think we should come up with a better solution.

PR #12

**Comment by ccpandhare** [comment]
We have shifted quite a lot from this code, and this issue is fixed, so closing this issue.
