### ISSUE TITLE
Quick buttons are not working.

### ISSUE THREAD

**Issue by Harshithpabbati** [publiclab/image-sequencer#902]
### Please show us where to look
https://beta.sequencer.publiclab.org

**Comment by Harshithpabbati** [comment]
@jywarren @publiclab/is-reviewers major issue 😅

**Comment by HarshKhandeparkar** [comment]
I saw it as well

**Comment by HarshKhandeparkar** [comment]
Oy brightness works. Weird 😕

**Comment by Harshithpabbati** [comment]
Yeah !!!

**Comment by jywarren** [comment]
Yes, we found this already but I haven't had time to look into it, it is quite a major issue! Any help appreciated! https://github.com/publiclab/image-sequencer/issues/888

**Comment by jywarren** [comment]
Thank you!!!
