### ISSUE TITLE
WelcomeBot mention is-reviewers

### ISSUE THREAD

**Issue by HarshKhandeparkar** [publiclab/image-sequencer#903]
### Please describe the problem (or idea)

First time contributors who are not publiclab members cannot mention is-reviewers. Only organisation members can. How about adding welcomebot to the organisation and let it mention is-reviewers in the newPRWelcomeComment?

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by HarshKhandeparkar** [comment]
@jywarren @publiclab/is-reviewers

**Comment by jywarren** [comment]
Sure, do you want to try it out by editing /.github/config.yml ?

**Comment by Harshithpabbati** [comment]
Easy way is directly mentioning it in the pr will it work ???

**Comment by jywarren** [comment]
i think we have to test -- but i believe it'll run from the PR where you
change config.yml, so we can test it before merging!

I can't seem to add welcome [bot] to our team but could be since it's an
app it has privileges already?

**Comment by Harshithpabbati** [comment]
I am saying can we add the line publiclab/is-reviewers directly in the pr template so that when we send it we will be called what do you say will it work????

**Comment by HarshKhandeparkar** [comment]
I don't think it will work since the pr author will still be a first timer.

**Comment by Harshithpabbati** [comment]
Why was the welcome bot not working here ???

**Comment by HarshKhandeparkar** [comment]
When was it not working?

**Comment by Harshithpabbati** [comment]
It's working right then we just need to add a line in config.yml isn't it???

**Comment by HarshKhandeparkar** [comment]
Yes but we are not sure if it will be able to mention is-reviewers. We can try adding to both the pr template and the config.yml. Can someone do that?

**Comment by Harshithpabbati** [comment]
Fine i will do it.

**Comment by Harshithpabbati** [comment]
Let's test it for once.
