### ISSUE TITLE
Black and White

### ISSUE THREAD

**Issue by niravasher** [publiclab/image-sequencer#912]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?
We could have a module that can convert colorful images into black and white

### Please show us where to look
https://publiclab.org/image-sequencer

### What's your PublicLab.org username?
niravasher

### Browser, version, and operating system
windows 10 with subsystem for ubuntu

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by niravasher** [comment]
Hey, @jywarren @HarshKhandeparkar is there any module which already does this? If yes please close the issue.

**Comment by HarshKhandeparkar** [comment]
Nirav do you mean greyscale images? If yes, colormap already does that.

**Comment by HarshKhandeparkar** [comment]
We also have a pure black and white module, threshold. So shall this be closed?
