### ISSUE TITLE
cursor should change into pointer

### ISSUE THREAD

**Issue by subhahu123** [publiclab/image-sequencer#913]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before.**

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you `gift_heart`

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!

### What you will need to know.
Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### Please describe the problem (or idea)

![Peek 2019-03-21 22-07](https://user-images.githubusercontent.com/34541684/54768689-b541cc80-4c25-11e9-8ce8-faa8f7f651ce.gif)

![Peek 2019-03-21 22-11](https://user-images.githubusercontent.com/34541684/54768951-4d3fb600-4c26-11e9-8136-d9ccc21aa290.gif)

**Comment by subhahu123** [comment]
@jywarren  @Harshithpabbati  @HarshKhandeparkar  @publiclab/reviewers  
please review

**Comment by HarshKhandeparkar** [comment]
We are going to change the cache link to a button. You can exclude that gif.

**Comment by Harshithpabbati** [comment]
What is the problem in save button ???

**Comment by subhahu123** [comment]
> What is the problem in save button ???

not save button it''s `save as png` dropdown
@Harshithpabbati

**Comment by Harshithpabbati** [comment]
Ok!!!

**Comment by subhahu123** [comment]
@Harshithpabbati @HarshKhandeparkar  add first-timers-only label

**Comment by Harshithpabbati** [comment]
Make it into first timers issue format @subhahu123

**Comment by subhahu123** [comment]
> Make it into first timers issue format @subhahu123


What format ????

**Comment by Harshithpabbati** [comment]
Check this for sample.
https://github.com/publiclab/image-sequencer/issues/898
You should even add the code for first timers issues.

**Comment by HarshKhandeparkar** [comment]
@subhahu123 you will have to include the diff and the step by step process etc.

**Comment by rohithGoudM** [comment]
Can I take this up..?

**Comment by subhahu123** [comment]
> Can I take this up..?

go ahead

**Comment by HarshKhandeparkar** [comment]
Sure!

**Comment by rohithGoudM** [comment]
What shall I do now...?

**Comment by HarshKhandeparkar** [comment]
I have reviewed your pr. the other reviewers will also review it soon.
