### ISSUE TITLE
Problem with add step button

### ISSUE THREAD

**Issue by Harshithpabbati** [publiclab/image-sequencer#918]
### Add step button looks like this when we add the new step between the two steps

![button](https://user-images.githubusercontent.com/43822585/54829422-62771c00-4cdc-11e9-8373-0937b26b04a1.png)

### Please show us where to look

https://beta.sequencer.publiclab.org

### Browser, version, and operating system
 Chrome(latest version) ,Linux 
## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by HarshKhandeparkar** [comment]
Addressed in #655 check out #919 for reference.
