### ISSUE TITLE
Selectize isn't working on "insert step"

### ISSUE THREAD

**Issue by Harshithpabbati** [publiclab/image-sequencer#919]
### When we append new step between the two steps then the selectize step is not working to select the modules.
![button](https://user-images.githubusercontent.com/43822585/54829741-11b3f300-4cdd-11e9-9390-f71ac302be3e.png)

### Please show us where to look

https://beta.sequencer.publiclab.org

### Browser, version, and operating system
Chrome(latest version) and Linux

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by HarshKhandeparkar** [comment]
Actually this and #918 are related. I think the selectize box is rendered inside the addStep button.

**Comment by Harshithpabbati** [comment]
May be lets check it.

**Comment by HarshKhandeparkar** [comment]
I will address it in #655

**Comment by HarshKhandeparkar** [comment]
I am almost done with it locally. Will push in a few days
