### ISSUE TITLE
Add Coveralls test coverage tracking

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#920]
This could be instead of #230 which we didn't get working...

https://docs.coveralls.io/javascript

I've added the REPO_TOKEN to Travis already! This would be great to help track how thorough our tests are. Any help appreciated!

**Comment by Divy123** [comment]
Its already opened here @jywarren  #774 .
I am involving this one is my soc idea. So can we put that hold on till then?

**Comment by jywarren** [comment]
Well, please do include it in your proposal, but I think we prefer not to
hold back work before the summer; otherwise we would 'get stuck' between
GSoC applications opening and the start of summer work. But don't worry, we
will consider everything like this when we review applications, and if
someone else solves it it won't be held against you. Thank you!

**Comment by Divy123** [comment]
Thanks @jywarren.
I will soon start on this as soon as possible.

**Comment by jywarren** [comment]
Linking to #635 too

**Comment by jywarren** [comment]
We now have codecov! #1014
