### ISSUE TITLE
Offer warning before generating preview "quick-add steps" on very large images

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#922]
Uploading a big image (actually like any image from a smartphone camera 😂 📸 🤳 ) stalls out the sequencer because of the preview images. A few ideas:

1. we could not generate previews for the small steps if the image size is over a certain threshold, instead showing a message `Generating previews for images this large may take a while. _Do it anyways_?` so it can be overridden...
2. do we generate the preview resize once, then pass it to each preview step, or do we generate it multiple times from the original image? 
3. make resizing images faster with optimization of the resize module?

Just thinking how we could smooth this out a bit!

**Comment by Harshithpabbati** [comment]
https://sharp.pixelplumbing.com/en/stable/

**Comment by Harshithpabbati** [comment]
Coverting larger images to friendly image formats. What do you say about it???

**Comment by HarshKhandeparkar** [comment]
@jywarren I had mentioned about it in #955.
Also I think the images **have to be** downsclaes for the previews.

On my phone, the phone takes 15secs to even show the image in the load-image step and takes atleast 1.5 min to generate the previews. Then I actually saw the resolution, 3480x4610 and my phone is 3yrs old. 

Without downscaling the imgs, the previews will just stop the page.

**Comment by jywarren** [comment]
Agreed! Ok, let's start by not running the preview generation on big images
then? We can pursue other options once we do this. Are you interested in
working on this one? Thanks!!!

**Comment by aashna27** [comment]
I am pursuing this , adding this in my proposal.

**Comment by HarshKhandeparkar** [comment]
@aashna27 please have a look at the discussion in #955. Try to adding an option to stop previews altogether, if you want/can/have time. Thanks.

**Comment by jywarren** [comment]
Noting for the preview refactor, we could add an intermediate sequencer object before passing to generatePreview:

https://github.com/publiclab/image-sequencer/blob/0eb3f263f921c888cc0ec0cc33e42c2fd7e59a47/examples/lib/insertPreview.js#L1-L3

We could do it just before passing the image to this iterator: 

https://github.com/publiclab/image-sequencer/blob/440c3e0ad0ab081bdcc7dfff0d000f52a0902035/examples/lib/insertPreview.js#L47-L49
