### ISSUE TITLE
A small bug in UI

### ISSUE THREAD

**Issue by subhahu123** [publiclab/image-sequencer#924]
### Please describe the problem (or idea)

![download (1)](https://user-images.githubusercontent.com/34541684/54865398-218a1080-4d8b-11e9-806d-5422e351ec6b.png)

**Comment by subhahu123** [comment]
@Harshithpabbati  @HarshKhandeparkar  @publiclab/is-reviewers  please review

**Comment by HarshKhandeparkar** [comment]
Oh good. I was going to open an issue but didn't get time.

**Comment by HarshKhandeparkar** [comment]
@rohithGoudM do you want to solve this issue?

**Comment by rohithGoudM** [comment]
Yes,
I'm working on it
