### ISSUE TITLE
Add codecov.yml for tests coverage

### ISSUE THREAD

**Issue by subhahu123** [publiclab/image-sequencer#928]
### Please describe the problem (or idea)

site: https://codecov.io/

**Comment by HarshKhandeparkar** [comment]
Check out #920

**Comment by subhahu123** [comment]
> Check out #920

i know but they both are different This does not require any token only install its package and run it for generating report

**Comment by HarshKhandeparkar** [comment]
So which one should be kept? Is there any need for keeping both?

**Comment by subhahu123** [comment]
> So which one should be kept? Is there any need for keeping both?

i know only about codecov and it's very good

**Comment by Divy123** [comment]
@subhahu123 please have alook here. #774 
Involving this in my soc idea.

**Comment by Divy123** [comment]
Duplicate Issue.
