### ISSUE TITLE
Minified distribution version

### ISSUE THREAD

**Issue by ccpandhare** [publiclab/image-sequencer#93]
`./dist/image-sequencer.js` is a very large file. Maybe we should add a minified version too, apart from it : `./dist/image-sequencer.min.js`

What do you think?

**Comment by jywarren** [comment]
+1!

**Comment by ccpandhare** [comment]
Adding the FTO label!

Description:

We are using grunt for distribution. This task essentially requires one to add a new module to the Gruntfile `./Gruntfile.js` in the "build" task.

Currently the "build" task only browserifies the code.

- Find a new grunt module to minify JavaScript files and add it to the devDependancies in `package.json`
- Add this to the registered Grunt task "build"
- The configuration should be such that the module minifies the `./dist/image-sequencer.js` generated by browserify in the task "build" in-place.

Does this look good, @jywarren?

**Comment by jywarren** [comment]
Hi, @ccpandhare -- take a look at this guide: https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors

Part of the key of FTOs is that they have a welcoming intro, they describe the "problem" or current state, and the "solution" or intended changes. Then they use a checklist to lay out exactly what steps will be needed to solve the issue. 

The hope is that people will go through these steps and "learn how to contribute" through the process. Then they can tackle an issue with some deeper problem solving, next. 

So if you'd like to do some as FTOs and leave some others as next steps, that could work. As you've laid out above, it's /almost/ an FTO but maybe for now it could be marked as `help-wanted` (a more general request for help). I think a mix of `help-wanted` and `first-timers-only` is good. `help-wanted` issues ensure that there's something for people to try once they've finished a FTO. 

@publiclab/soc - take a look at these suggestions -- they're applicable to all your projects!

**Comment by ccpandhare** [comment]
Thanks for your input, shall do!

**Comment by ccpandhare** [comment]
Closing this and adding another FTO regarding this. Thanks!
