### ISSUE TITLE
X and Y inputs in Resize module.

### ISSUE THREAD

**Issue by Harshithpabbati** [publiclab/image-sequencer#933]
### Please show us where to look

https://beta.sequencer.publiclab.org

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by Harshithpabbati** [comment]
@jywarren @publiclab/is-reviewers I would like to work on this.

**Comment by HarshKhandeparkar** [comment]
There is an open issue and an open pr for this.

**Comment by HarshKhandeparkar** [comment]
Pr #571 issue #464

**Comment by jywarren** [comment]
But we'd love help on that issue, thanks!!!

**Comment by Harshithpabbati** [comment]
Adding X and Y options that's it right ???

**Comment by jywarren** [comment]
Yes, adding a new type of input that let's the user select x and y by
clicking!

**Comment by Harshithpabbati** [comment]
So in a simple way cropping it and then resizing the image isn't it.
