### ISSUE TITLE
Demo site doesn't work

### ISSUE THREAD

**Issue by HarshKhandeparkar** [publiclab/image-sequencer#948]
### Please describe the problem (or idea)
The current beta demo site doesn't work.

![Screenshot_20190327-005856](https://user-images.githubusercontent.com/34770591/55027688-c7dd4c80-4ffd-11e9-818c-2b01f920837d.jpg)

It is stuck in this state.

### Please show us where to look

https://beta.sequencer.publiclab.org

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by HarshKhandeparkar** [comment]
@publiclab/is-reviewers I think there is an error in the console but I cannot see that on my phone. Can someone post a screenshot of the error?

**Comment by Harshithpabbati** [comment]
When I tried to update the demo site then I got a message that github can have a max of 50 mb files but only the node modules files are about 70mb may be that was the error I guess.

**Comment by Harshithpabbati** [comment]
But the push was done successfully.

**Comment by HarshKhandeparkar** [comment]
Oh, that might be the issue. But why are the node_modules so big?

**Comment by Harshithpabbati** [comment]
I don't know 🤔

**Comment by HarshKhandeparkar** [comment]
Ok i will open a pr to update-is to only push reqd node Modules

**Comment by HarshKhandeparkar** [comment]
The problem was that the dist has to be force pushed but it wasn't. It will be fixed in https://github.com/Harshithpabbati/Update-is/issues/5

**Comment by Harshithpabbati** [comment]
Done !!! Now it's working.
