### ISSUE TITLE
Webcam preview moves to the side.

### ISSUE THREAD

**Issue by Harshithpabbati** [publiclab/image-sequencer#951]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/image-sequencer/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

**To Do**: Making the webcam preview responsive.

#### To Fix
The file to be looked into is:
https://github.com/publiclab/image-sequencer/blob/main/examples/index.html
```diff
-  <video  id="video" width="400" height="300" style="display:none"></video>
+  <video  id="video" width="100%" height="100%" style="display:none"></video>
```
You can have a look [here](https://beta.sequencer.publiclab.org) for reference.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [examples/index.html](https://github.com/publiclab/image-sequencer/blob/main/examples/index.html) in `image-sequencer` repository (press the little pen Icon) and edit the line as shown below.

[See this page](https://publiclab.github.io/community-toolbox/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

Diff yet to be added.

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there.

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

**Comment by Harshithpabbati** [comment]
@harshkhandeparkar I will try to reformat this to fto

**Comment by Harshithpabbati** [comment]
May be today night or tommorow, I have last exam tomorrow.

**Comment by Harshithpabbati** [comment]
@HarshKhandeparkar made this an FTO

**Comment by Sanscripter** [comment]
Hey, can I claim this issue?

**Comment by Harshithpabbati** [comment]
Yeah you can. :)

**Comment by Sanscripter** [comment]
@Harshithpabbati Hey I made the change to the html but when I run it locally, even after I `grunt build` , the stays the same. Is there something I'm missing about the process?

**Comment by Harshithpabbati** [comment]
Can you share a screenshot.?

**Comment by Sanscripter** [comment]
Actually I think I managed it. Just made the pull request.
