### ISSUE TITLE
Configure First Timers Bot

### ISSUE THREAD

**Issue by HarshKhandeparkar** [publiclab/image-sequencer#952]
### Please describe the problem (or idea)
Configure [First-Timers](https://probot.github.io/apps/first-timers/) probot to automate the process of creating FTO issues.

### To Do
Create the following files.
* /.github/first-timers.yml
* /.github/fto-issue-template.md (can be renamed)

For reference.
* [plots2/.github/first-timers.yml](https://github.com/publiclab/plots2/blob/master/.github/first-timers.yml)
* [plots2/.github/first-timers-issue-template.md](https://github.com/publiclab/plots2/blob/master/.github/first-timers-issue-template.md)

Setup first timers probot app. Has to be done by @jywarren.

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by HarshKhandeparkar** [comment]
@jywarren @publiclab/is-reviewers

**Comment by HarshKhandeparkar** [comment]
@jywarren I have requested the installation of first timers bot on image-sequencer.
cc @publiclab/is-reviewers

**Comment by HarshKhandeparkar** [comment]
Oh great! If it actually works then we can close this but I think the template and config.yml is yet to be added?

**Comment by HarshKhandeparkar** [comment]
The template is a bit different from what we use normally

**Comment by HarshKhandeparkar** [comment]
Also can we change its logo?

**Comment by Harshithpabbati** [comment]
@HarshKhandeparkar we can't change the profile image as it is a registered github app.
