### ISSUE TITLE
Grid overlay 

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#954]
We're looking to do a small use case with some NASA folks and they wanted to simply overlay a grid over an image, and we should be able to do that pretty simply with IS. 

[I gave it a try here.](https://sequencer.publiclab.org/examples/#steps=import-image{url:data%3Aimage%2Fpng%3Bbase64%2CiVBORw0KGgoAAAANSUhEUgAABDoAAAMiCAYAAACPD6PBAAAACXBIWXMAAAsTAAALEwEAmpwYAAAKT2lDQ1BQaG90b3Nob3AgSUNDIHByb2ZpbGUAAHjanVNnVFPpFj333vRCS4iAlEtvUhUIIFJCi4AUkSYqIQkQSoghodkVUcERRUUEG8igiAOOjoCMFVEsDIoK2AfkIaKOg6OIisr74Xuja9a89%2BbN%2FrXXPues852zzwfACAyWSDNRNYAMqUIeEeCDx8TG4eQuQIEKJHAAEAizZCFz%2FSMBAPh%2BPDwrIsAHvgABeNMLCADATZvAMByH%2Fw%2FqQplcAYCEAcB0kThLCIAUAEB6jkKmAEBGAYCdmCZTAKAEAGDLY2LjAFAtAGAnf%2BbTAICd%2BJl7AQBblCEVAaCRACATZYhEAGg7AKzPVopFAFgwABRmS8Q5ANgtADBJV2ZIALC3AMDOEAuyAAgMADBRiIUpAAR7AGDIIyN4AISZABRG8lc88SuuEOcqAAB4mbI8uSQ5RYFbCC1xB1dXLh4ozkkXKxQ2YQJhmkAuwnmZGTKBNA%2Fg88wAAKCRFRHgg%2FP9eM4Ors7ONo62Dl8t6r8G%2FyJiYuP%2B5c%2BrcEAAAOF0ftH%2BLC%2BzGoA7BoBt%2FqIl7gRoXgugdfeLZrIPQLUAoOnaV%2FNw%2BH48PEWhkLnZ2eXk5NhKxEJbYcpXff5nwl%2FAV%2F1s%2BX48%2FPf14L7iJIEyXYFHBPjgwsz0TKUcz5IJhGLc5o9H%2FLcL%2F%2Fwd0yLESWK5WCoU41EScY5EmozzMqUiiUKSKcUl0v9k4t8s%2BwM%2B3zUAsGo%2BAXuRLahdYwP2SycQWHTA4vcAAPK7b8HUKAgDgGiD4c93%2F%2B8%2F%2FUegJQCAZkmScQAAXkQkLlTKsz%2FHCAAARKCBKrBBG%2FTBGCzABhzBBdzBC%2FxgNoRCJMTCQhBCCmSAHHJgKayCQiiGzbAdKmAv1EAdNMBRaIaTcA4uwlW4Dj1wD%2FphCJ7BKLyBCQRByAgTYSHaiAFiilgjjggXmYX4IcFIBBKLJCDJiBRRIkuRNUgxUopUIFVIHfI9cgI5h1xGupE7yAAygvyGvEcxlIGyUT3UDLVDuag3GoRGogvQZHQxmo8WoJvQcrQaPYw2oefQq2gP2o8%2BQ8cwwOgYBzPEbDAuxsNCsTgsCZNjy7EirAyrxhqwVqwDu4n1Y8%2BxdwQSgUXACTYEd0IgYR5BSFhMWE7YSKggHCQ0EdoJNwkDhFHCJyKTqEu0JroR%2BcQYYjIxh1hILCPWEo8TLxB7iEPENyQSiUMyJ7mQAkmxpFTSEtJG0m5SI%2BksqZs0SBojk8naZGuyBzmULCAryIXkneTD5DPkG%2BQh8lsKnWJAcaT4U%2BIoUspqShnlEOU05QZlmDJBVaOaUt2ooVQRNY9aQq2htlKvUYeoEzR1mjnNgxZJS6WtopXTGmgXaPdpr%2Bh0uhHdlR5Ol9BX0svpR%2BiX6AP0dwwNhhWDx4hnKBmbGAcYZxl3GK%2BYTKYZ04sZx1QwNzHrmOeZD5lvVVgqtip8FZHKCpVKlSaVGyovVKmqpqreqgtV81XLVI%2BpXlN9rkZVM1PjqQnUlqtVqp1Q61MbU2epO6iHqmeob1Q%2FpH5Z%2FYkGWcNMw09DpFGgsV%2FjvMYgC2MZs3gsIWsNq4Z1gTXEJrHN2Xx2KruY%2FR27iz2qqaE5QzNKM1ezUvOUZj8H45hx%2BJx0TgnnKKeX836K3hTvKeIpG6Y0TLkxZVxrqpaXllirSKtRq0frvTau7aedpr1Fu1n7gQ5Bx0onXCdHZ4%2FOBZ3nU9lT3acKpxZNPTr1ri6qa6UbobtEd79up%2B6Ynr5egJ5Mb6feeb3n%2Bhx9L%2F1U%2FW36p%2FVHDFgGswwkBtsMzhg8xTVxbzwdL8fb8VFDXcNAQ6VhlWGX4YSRudE8o9VGjUYPjGnGXOMk423GbcajJgYmISZLTepN7ppSTbmmKaY7TDtMx83MzaLN1pk1mz0x1zLnm%2Beb15vft2BaeFostqi2uGVJsuRaplnutrxuhVo5WaVYVVpds0atna0l1rutu6cRp7lOk06rntZnw7Dxtsm2qbcZsOXYBtuutm22fWFnYhdnt8Wuw%2B6TvZN9un2N%2FT0HDYfZDqsdWh1%2Bc7RyFDpWOt6azpzuP33F9JbpL2dYzxDP2DPjthPLKcRpnVOb00dnF2e5c4PziIuJS4LLLpc%2BLpsbxt3IveRKdPVxXeF60vWdm7Obwu2o26%2FuNu5p7ofcn8w0nymeWTNz0MPIQ%2BBR5dE%2FC5%2BVMGvfrH5PQ0%2BBZ7XnIy9jL5FXrdewt6V3qvdh7xc%2B9j5yn%2BM%2B4zw33jLeWV%2FMN8C3yLfLT8Nvnl%2BF30N%2FI%2F9k%2F3r%2F0QCngCUBZwOJgUGBWwL7%2BHp8Ib%2BOPzrbZfay2e1BjKC5QRVBj4KtguXBrSFoyOyQrSH355jOkc5pDoVQfujW0Adh5mGLw34MJ4WHhVeGP45wiFga0TGXNXfR3ENz30T6RJZE3ptnMU85ry1KNSo%2Bqi5qPNo3ujS6P8YuZlnM1VidWElsSxw5LiquNm5svt%2F87fOH4p3iC%2BN7F5gvyF1weaHOwvSFpxapLhIsOpZATIhOOJTwQRAqqBaMJfITdyWOCnnCHcJnIi%2FRNtGI2ENcKh5O8kgqTXqS7JG8NXkkxTOlLOW5hCepkLxMDUzdmzqeFpp2IG0yPTq9MYOSkZBxQqohTZO2Z%2Bpn5mZ2y6xlhbL%2BxW6Lty8elQfJa7OQrAVZLQq2QqboVFoo1yoHsmdlV2a%2FzYnKOZarnivN7cyzytuQN5zvn%2F%2FtEsIS4ZK2pYZLVy0dWOa9rGo5sjxxedsK4xUFK4ZWBqw8uIq2Km3VT6vtV5eufr0mek1rgV7ByoLBtQFr6wtVCuWFfevc1%2B1dT1gvWd%2B1YfqGnRs%2BFYmKrhTbF5cVf9go3HjlG4dvyr%2BZ3JS0qavEuWTPZtJm6ebeLZ5bDpaql%2BaXDm4N2dq0Dd9WtO319kXbL5fNKNu7g7ZDuaO%2FPLi8ZafJzs07P1SkVPRU%2BlQ27tLdtWHX%2BG7R7ht7vPY07NXbW7z3%2FT7JvttVAVVN1WbVZftJ%2B7P3P66Jqun4lvttXa1ObXHtxwPSA%2F0HIw6217nU1R3SPVRSj9Yr60cOxx%2B%2B%2Fp3vdy0NNg1VjZzG4iNwRHnk6fcJ3%2FceDTradox7rOEH0x92HWcdL2pCmvKaRptTmvtbYlu6T8w%2B0dbq3nr8R9sfD5w0PFl5SvNUyWna6YLTk2fyz4ydlZ19fi753GDborZ752PO32oPb%2B%2B6EHTh0kX%2Fi%2Bc7vDvOXPK4dPKy2%2BUTV7hXmq86X23qdOo8%2FpPTT8e7nLuarrlca7nuer21e2b36RueN87d9L158Rb%2F1tWeOT3dvfN6b%2FfF9%2FXfFt1%2Bcif9zsu72Xcn7q28T7xf9EDtQdlD3YfVP1v%2B3Njv3H9qwHeg89HcR%2FcGhYPP%2FpH1jw9DBY%2BZj8uGDYbrnjg%2BOTniP3L96fynQ89kzyaeF%2F6i%2FsuuFxYvfvjV69fO0ZjRoZfyl5O%2FbXyl%2FerA6xmv28bCxh6%2ByXgzMV70VvvtwXfcdx3vo98PT%2BR8IH8o%2F2j5sfVT0Kf7kxmTk%2F8EA5jz%2FGMzLdsAAAAgY0hSTQAAeiUAAICDAAD5%2FwAAgOkAAHUwAADqYAAAOpgAABdvkl%2FFRgAAFg9JREFUeNrs27GNGEEMBME55Z8z3%2FgABHnaRlUEA5oNcPt1%2B7%2FZZ5999tlnn3322WefffbZZ5999v113%2FfASAAAAIB%2FohjZZ5999tlnn3322WefffbZZ599z%2B%2F7MwAAAIAIoQMAAADIEDoAAACADKEDAAAAyBA6AAAAgAyhAwAAAMgQOgAAAIAMoQMAAADIEDoAAACADKEDAAAAyBA6AAAAgAyhAwAAAMgQOgAAAIAMoQMAAADIEDoAAACADKEDAAAAyBA6AAAAgAyhAwAAAMgQOgAAAIAMoQMAAADIEDoAAACADKEDAAAAyBA6AAAAgAyhAwAAAMgQOgAAAIAMoQMAAADIEDoAAACADKEDAAAAyBA6AAAAgAyhAwAAAMgQOgAAAIAMoQMAAADIEDoAAACADKEDAAAAyBA6AAAAgAyhAwAAAMgQOgAAAIAMoQMAAADI%2BLadMwAAAAAlZ5999tlnn3322WefffbZZ5999tn3%2Bj6vKwAAAECG0AEAAABkCB0AAABAhtABAAAAZAgdAAAAQIbQAQAAAGQIHQAAAECG0AEAAABkCB0AAABAhtABAAAAZAgdAAAAQIbQAQAAAGQIHQAAAECG0AEAAABkCB0AAABAhtABAAAAZAgdAAAAQIbQAQAAAGQIHQAAAECG0AEAAABkCB0AAABAhtABAAAAZAgdAAAAQIbQAQAAAGQIHQAAAECG0AEAAABkCB0AAABAhtABAAAAZAgdAAAAQIbQAQAAAGQIHQAAAECG0AEAAABkCB0AAABAhtABAAAAZAgdAAAAQIbQAQAAAGQIHQAAAECG0AEAAABkfNvOGQAAAICSs88%2B%2B%2Byzzz777LPPPvvss88%2B%2B%2Bx7fZ%2FXFQAAACBD6AAAAAAyhA4AAAAgQ%2BgAAAAAMoQOAAAAIEPoAAAAADKEDgAAACBD6AAAAAAyhA4AAAAgQ%2BgAAAAAMoQOAAAAIEPoAAAAADKEDgAAACBD6AAAAAAyhA4AAAAgQ%2BgAAAAAMoQOAAAAIEPoAAAAADKEDgAAACBD6AAAAAAyhA4AAAAgQ%2BgAAAAAMoQOAAAAIEPoAAAAADKEDgAAACBD6AAAAAAyhA4AAAAgQ%2BgAAAAAMoQOAAAAIEPoAAAAADKEDgAAACBD6AAAAAAyhA4AAAAgQ%2BgAAAAAMoQOAAAAIEPoAAAAADKEDgAAACBD6AAAAAAyvm3nDAAAAEDJ2WefffbZZ5999tlnn3322Wefffa9vs%2FrCgAAAJAhdAAAAAAZQgcAAACQIXQAAAAAGUIHAAAAkCF0AAAAABlCBwAAAJAhdAAAAAAZQgcAAACQIXQAAAAAGUIHAAAAkCF0AAAAABlCBwAAAJAhdAAAAAAZQgcAAACQIXQAAAAAGUIHAAAAkCF0AAAAABlCBwAAAJAhdAAAAAAZQgcAAACQIXQAAAAAGUIHAAAAkCF0AAAAABlCBwAAAJAhdAAAAAAZQgcAAACQIXQAAAAAGUIHAAAAkCF0AAAAABlCBwAAAJAhdAAAAAAZQgcAAACQIXQAAAAAGUIHAAAAkCF0AAAAABlCBwAAAJAhdAAAAAAZ37ZzBgAAAKDk7LPPPvvss88%2B%2B%2Byzzz777LPPPvte3%2Bd1BQAAAMgQOgAAAIAMoQMAAADIEDoAAACADKEDAAAAyBA6AAAAgAyhAwAAAMgQOgAAAIAMoQMAAADIEDoAAACADKEDAAAAyBA6AAAAgAyhAwAAAMgQOgAAAIAMoQMAAADIEDoAAACADKEDAAAAyBA6AAAAgAyhAwAAAMgQOgAAAIAMoQMAAADIEDoAAACADKEDAAAAyBA6AAAAgAyhAwAAAMgQOgAAAIAMoQMAAADIEDoAAACADKEDAAAAyBA6AAAAgAyhAwAAAMgQOgAAAIAMoQMAAADIEDoAAACADKEDAAAAyBA6AAAAgAyhAwAAAMgQOgAAAICMb9s5AwAAAFBy9tlnn3322WefffbZZ5999tlnn32v7%2FO6AgAAAGQIHQAAAECG0AEAAABkCB0AAABAhtABAAAAZAgdAAAAQIbQAQAAAGQIHQAAAECG0AEAAABkCB0AAABAhtABAAAAZAgdAAAAQIbQAQAAAGQIHQAAAECG0AEAAABkCB0AAABAhtABAAAAZAgdAAAAQIbQAQAAAGQIHQAAAECG0AEAAABkCB0AAABAhtABAAAAZAgdAAAAQIbQAQAAAGQIHQAAAECG0AEAAABkCB0AAABAhtABAAAAZAgdAAAAQIbQAQAAAGQIHQAAAECG0AEAAABkCB0AAABAhtABAAAAZAgdAAAAQIbQAQAAAGQIHQAAAEDGt%2B2cAQAAACg5%2B%2Byzzz777LPPPvvss88%2B%2B%2Byzz77X93ldAQAAADKEDgAAACBD6AAAAAAyhA4AAAAgQ%2BgAAAAAMoQOAAAAIEPoAAAAADKEDgAAACBD6AAAAAAyhA4AAAAgQ%2BgAAAAAMoQOAAAAIEPoAAAAADKEDgAAACBD6AAAAAAyhA4AAAAgQ%2BgAAAAAMoQOAAAAIEPoAAAAADKEDgAAACBD6AAAAAAyhA4AAAAgQ%2BgAAAAAMoQOAAAAIEPoAAAAADKEDgAAACBD6AAAAAAyhA4AAAAgQ%2BgAAAAAMoQOAAAAIEPoAAAAADKEDgAAACBD6AAAAAAyhA4AAAAgQ%2BgAAAAAMoQOAAAAIEPoAAAAADKEDgAAACDj23bOAAAAAJScffbZZ5999tlnn3322WefffbZZ9%2Fr%2B7yuAAAAABlCBwAAAJAhdAAAAAAZQgcAAACQIXQAAAAAGUIHAAAAkCF0AAAAABlCBwAAAJAhdAAAAAAZQgcAAACQIXQAAAAAGUIHAAAAkCF0AAAAABlCBwAAAJAhdAAAAAAZQgcAAACQIXQAAAAAGUIHAAAAkCF0AAAAABlCBwAAAJAhdAAAAAAZQgcAAACQIXQAAAAAGUIHAAAAkCF0AAAAABlCBwAAAJAhdAAAAAAZQgcAAACQIXQAAAAAGUIHAAAAkCF0AAAAABlCBwAAAJAhdAAAAAAZQgcAAACQIXQAAAAAGUIHAAAAkCF0AAAAABlCBwAAAJDxbTtnAAAAAErOPvvss88%2B%2B%2Byzzz777LPPPvvss%2B%2F1fV5XAAAAgAyhAwAAAMgQOgAAAIAMoQMAAADIEDoAAACADKEDAAAAyBA6AAAAgAyhAwAAAMgQOgAAAIAMoQMAAADIEDoAAACADKEDAAAAyBA6AAAAgAyhAwAAAMgQOgAAAIAMoQMAAADIEDoAAACADKEDAAAAyBA6AAAAgAyhAwAAAMgQOgAAAIAMoQMAAADIEDoAAACADKEDAAAAyBA6AAAAgAyhAwAAAMgQOgAAAIAMoQMAAADIEDoAAACADKEDAAAAyBA6AAAAgAyhAwAAAMgQOgAAAIAMoQMAAADIEDoAAACADKEDAAAAyBA6AAAAgAyhAwAAAMj4tp0zAAAAACVnn3322WefffbZZ5999tlnn3322ff6Pq8rAAAAQIbQAQAAAGQIHQAAAECG0AEAAABkCB0AAABAhtABAAAAZAgdAAAAQIbQAQAAAGQIHQAAAECG0AEAAABkCB0AAABAhtABAAAAZAgdAAAAQIbQAQAAAGQIHQAAAECG0AEAAABkCB0AAABAhtABAAAAZAgdAAAAQIbQAQAAAGQIHQAAAECG0AEAAABkCB0AAABAhtABAAAAZAgdAAAAQIbQAQAAAGQIHQAAAECG0AEAAABkCB0AAABAhtABAAAAZAgdAAAAQIbQAQAAAGQIHQAAAECG0AEAAABkCB0AAABAhtABAAAAZAgdAAAAQIbQAQAAAGR8284ZAAAAgJKzzz777LPPPvvss88%2B%2B%2Byzzz777Ht9n9cVAAAAIEPoAAAAADKEDgAAACBD6AAAAAAyhA4AAAAgQ%2BgAAAAAMoQOAAAAIEPoAAAAADKEDgAAACBD6AAAAAAyhA4AAAAgQ%2BgAAAAAMoQOAAAAIEPoAAAAADKEDgAAACBD6AAAAAAyhA4AAAAgQ%2BgAAAAAMoQOAAAAIEPoAAAAADKEDgAAACBD6AAAAAAyhA4AAAAgQ%2BgAAAAAMoQOAAAAIEPoAAAAADKEDgAAACBD6AAAAAAyhA4AAAAgQ%2BgAAAAAMoQOAAAAIEPoAAAAADKEDgAAACBD6AAAAAAyhA4AAAAgQ%2BgAAAAAMoQOAAAAIEPoAAAAADK%2BbecMAAAAQMnZZ5999tlnn3322WefffbZZ5999r2%2Bz%2BsKAAAAkCF0AAAAABlCBwAAAJAhdAAAAAAZQgcAAACQIXQAAAAAGUIHAAAAkCF0AAAAABlCBwAAAJAhdAAAAAAZQgcAAACQIXQAAAAAGUIHAAAAkCF0AAAAABlCBwAAAJAhdAAAAAAZQgcAAACQIXQAAAAAGUIHAAAAkCF0AAAAABlCBwAAAJAhdAAAAAAZQgcAAACQIXQAAAAAGUIHAAAAkCF0AAAAABlCBwAAAJAhdAAAAAAZQgcAAACQIXQAAAAAGUIHAAAAkCF0AAAAABlCBwAAAJAhdAAAAAAZQgcAAACQIXQAAAAAGUIHAAAAkCF0AAAAABnftnMGAAAAoOTss88%2B%2B%2Byzzz777LPPPvvss88%2B%2B17f53UFAAAAyBA6AAAAgAyhAwAAAMgQOgAAAIAMoQMAAADIEDoAAACADKEDAAAAyBA6AAAAgAyhAwAAAMgQOgAAAIAMoQMAAADIEDoAAACADKEDAAAAyBA6AAAAgAyhAwAAAMgQOgAAAIAMoQMAAADIEDoAAACADKEDAAAAyBA6AAAAgAyhAwAAAMgQOgAAAIAMoQMAAADIEDoAAACADKEDAAAAyBA6AAAAgAyhAwAAAMgQOgAAAIAMoQMAAADIEDoAAACADKEDAAAAyBA6AAAAgAyhAwAAAMgQOgAAAIAMoQMAAADIEDoAAACADKEDAAAAyBA6AAAAgIxv2zkDAAAAUHL22WefffbZZ5999tlnn3322Weffa%2Fv87oCAAAAZAgdAAAAQIbQAQAAAGQIHQAAAECG0AEAAABkCB0AAABAhtABAAAAZAgdAAAAQIbQAQAAAGQIHQAAAECG0AEAAABkCB0AAABAhtABAAAAZAgdAAAAQIbQAQAAAGQIHQAAAECG0AEAAABkCB0AAABAhtABAAAAZAgdAAAAQIbQAQAAAGQIHQAAAECG0AEAAABkCB0AAABAhtABAAAAZAgdAAAAQIbQAQAAAGQIHQAAAECG0AEAAABkCB0AAABAhtABAAAAZAgdAAAAQIbQAQAAAGQIHQAAAECG0AEAAABkCB0AAABAhtABAAAAZAgdAAAAQMa37ZwBAAAAKDn77LPPPvvss88%2B%2B%2Byzzz777LPPvtf3eV0BAAAAMoQOAAAAIEPoAAAAADKEDgAAACBD6AAAAAAyhA4AAAAgQ%2BgAAAAAMoQOAAAAIEPoAAAAADKEDgAAACBD6AAAAAAyhA4AAAAgQ%2BgAAAAAMoQOAAAAIEPoAAAAADKEDgAAACBD6AAAAAAyhA4AAAAgQ%2BgAAAAAMoQOAAAAIEPoAAAAADKEDgAAACBD6AAAAAAyhA4AAAAgQ%2BgAAAAAMoQOAAAAIEPoAAAAADKEDgAAACBD6AAAAAAyhA4AAAAgQ%2BgAAAAAMoQOAAAAIEPoAAAAADKEDgAAACBD6AAAAAAyhA4AAAAgQ%2BgAAAAAMoQOAAAAIOPbds4AAAAAlJx99tlnn3322WefffbZZ5999tln3%2Bv7vK4AAAAAGUIHAAAAkCF0AAAAABlCBwAAAJAhdAAAAAAZQgcAAACQIXQAAAAAGUIHAAAAkCF0AAAAABlCBwAAAJAhdAAAAAAZQgcAAACQIXQAAAAAGUIHAAAAkCF0AAAAABlCBwAAAJAhdAAAAAAZQgcAAACQIXQAAAAAGUIHAAAAkCF0AAAAABlCBwAAAJAhdAAAAAAZQgcAAACQIXQAAAAAGUIHAAAAkCF0AAAAABlCBwAAAJAhdAAAAAAZQgcAAACQIXQAAAAAGUIHAAAAkCF0AAAAABlCBwAAAJAhdAAAAAAZQgcAAACQIXQAAAAAGUIHAAAAkPFtO2cAAAAASs4%2B%2B%2Byzzz777LPPPvvss88%2B%2B%2Byz7%2FV9XlcAAACADKEDAAAAyBA6AAAAgAyhAwAAAMgQOgAAAIAMoQMAAADIEDoAAACADKEDAAAAyBA6AAAAgAyhAwAAAMgQOgAAAIAMoQMAAADIEDoAAACADKEDAAAAyBA6AAAAgAyhAwAAAMgQOgAAAIAMoQMAAADIEDoAAACADKEDAAAAyBA6AAAAgAyhAwAAAMgQOgAAAIAMoQMAAADIEDoAAACADKEDAAAAyBA6AAAAgAyhAwAAAMgQOgAAAIAMoQMAAADIEDoAAACADKEDAAAAyBA6AAAAgAyhAwAAAMgQOgAAAIAMoQMAAADIEDoAAACADKEDAAAAyPi2nTMAAAAAJWefffbZZ5999tlnn3322WefffbZ9%2Fo%2BrysAAABAhtABAAAAZAgdAAAAQIbQAQAAAGQIHQAAAECG0AEAAABkCB0AAABAhtABAAAAZAgdAAAAQIbQAQAAAGQIHQAAAECG0AEAAABkCB0AAABAhtABAAAAZAgdAAAAQIbQAQAAAGQIHQAAAECG0AEAAABkCB0AAABAhtABAAAAZAgdAAAAQIbQAQAAAGQIHQAAAECG0AEAAABkCB0AAABAhtABAAAAZAgdAAAAQIbQAQAAAGQIHQAAAECG0AEAAABkCB0AAABAhtABAAAAZAgdAAAAQIbQAQAAAGQIHQAAAECG0AEAAABkCB0AAABAhtABAAAAZHzbzhkAAACAkrPPPvvss88%2B%2B%2Byzzz777LPPPvvse32f1xUAAAAgQ%2BgAAAAAMoQOAAAAIEPoAAAAADKEDgAAACBD6AAAAAAyhA4AAAAgQ%2BgAAAAAMoQOAAAAIEPoAAAAADKEDgAAACBD6AAAAAAyhA4AAAAgQ%2BgAAAAAMoQOAAAAIEPoAAAAADKEDgAAACBD6AAAAAAyhA4AAAAgQ%2BgAAAAAMoQOAAAAIEPoAAAAADKEDgAAACBD6AAAAAAyhA4AAAAgQ%2BgAAAAAMoQOAAAAIEPoAAAAADKEDgAAACBD6AAAAAAyhA4AAAAgQ%2BgAAAAAMoQOAAAAIEPoAAAAADKEDgAAACBD6AAAAAAyhA4AAAAgQ%2BgAAAAAMr5t5wwAAABAydlnn3322WefffbZZ5999tlnn332vb7P6woAAACQIXQAAAAAGUIHAAAAkCF0AAAAABlCBwAAAJAhdAAAAAAZQgcAAACQIXQAAAAAGUIHAAAAkCF0AAAAABlCBwAAAJAhdAAAAAAZQgcAAACQIXQAAAAAGUIHAAAAkCF0AAAAABlCBwAAAJAhdAAAAAAZQgcAAACQIXQAAAAAGUIHAAAAkCF0AAAAABlCBwAAAJAhdAAAAAAZQgcAAACQIXQAAAAAGUIHAAAAkCF0AAAAABlCBwAAAJAhdAAAAAAZQgcAAACQIXQAAAAAGUIHAAAAkCF0AAAAABlCBwAAAJAhdAAAAAAZQgcAAACQIXQAAAAAGd%2B2cwYAAACg4GcAp0RkwwwYONEAAAAASUVORK5CYII%3D},overlay{})

This is not the most efficient, but it ought to work. Not sure what's going on though -- i guess it's not preserving the alpha layer when doing overlay?

Weird because it seems like the code is correct:

https://github.com/publiclab/image-sequencer/blob/8ad171ee561bffea80029e407d521e973bbebddf/src/modules/Overlay/Module.js#L42-L56

Any help appreciated!!!

**Comment by HarshKhandeparkar** [comment]
Hello! Can you explain a bit more? What is secondImagePixels?

**Comment by Harshithpabbati** [comment]
@jywarren see this 
![grid](https://user-images.githubusercontent.com/43822585/55278377-8ae0c500-5331-11e9-869a-48aee677e596.png)

**Comment by Harshithpabbati** [comment]
@jywarren what do you say about it.

**Comment by Harshithpabbati** [comment]
Is this the one which you asked for???

**Comment by jywarren** [comment]
Oh this looks really nice! Actually i hadn't meant we needed a new module
(although maybe we could make a meta module) but this does look awesome. I
had meant to just document the bugs I found with trying to do this with
existing modules! Did you make a new module?

**Comment by Harshithpabbati** [comment]
Yeah a new module with canvas.

**Comment by Harshithpabbati** [comment]
Was this useful ???

**Comment by jywarren** [comment]
Yeah i think it could be... did you want to open a PR? Thanks!

**Comment by Harshithpabbati** [comment]
Yeah I will open it tommorow. I will make few changes and open a pr.

**Comment by jywarren** [comment]
awesome!

**Comment by HarshKhandeparkar** [comment]
We already have grid overlay
