### ISSUE TITLE
Compositing/Canvas-resize module

### ISSUE THREAD

**Issue by tech4GT** [publiclab/image-sequencer#961]
The goal of this module in conjunction with overlay is to combine images.

**Comment by tech4GT** [comment]
@jywarren Any ideas for this one? I was thinking maybe the module can take the final dimensions of the image and the overlay location for the image on the canvas?
Or do you think we should do % increase?? Keen to hear your take.

**Comment by jywarren** [comment]
Let's just do pixel dimensions to start with, not percentages. Yes, i think
width, height of final size, and x,y position so we know where the output
of the previous step would be placed on this new canvas. What do you think?

**Comment by tech4GT** [comment]
Sure! Sounds good. I’ll start this up.
