### ISSUE TITLE
GSoC Forum.

### ISSUE THREAD

**Issue by niravasher** [publiclab/image-sequencer#963]
Hello,
It's peak time for GSoC proposals. So you may have many doubts to ask and would possibly don't find any place to ask. You can ask your doubt's here!!
All the best for your proposals :smile:
We hope many contributions from you.
Thanks

**Comment by niravasher** [comment]
1) What exactly should I write for the text overlay module that is already completed

**Comment by niravasher** [comment]
2) GPU.js : a javascript library for enhanced graphics and resolution. Currently @Divy123 and @HarshKhandeparkar are working on this, so I don't know what modifications have to be done while the GSoC timeline

**Comment by Divy123** [comment]
@niravasher I am currently focusing on Webworkers and WebAssembly for my proposal.
Also if you want I can help you out in webGL issue which I have explored and Varun is getting to it.
You can explore webGL issue, I will try to help you get it done and other issues like shader refactoring etc. Also you can have a look at another idea involving real-world use cases  one.

Also text overlay module is already solved, so you can proceed with some other ones.

@jywarren request you to include some more ideas as some of them are already solved.

Thanks

**Comment by niravasher** [comment]
3) We can't change dist/bootstrap.css . I am not sure if changing demo.css and demo-old.css will increase the performance drastically. So I think we are left with minifying js files but we are already using dist for it. So how can we go further with this issue?

**Comment by niravasher** [comment]
4) In the ideas list, there are three points. Text Overlay module, performance, and gallery of real world. Do I have to choose any one of them or two or all the three?

**Comment by HarshKhandeparkar** [comment]
>  a javascript library for enhanced graphics and resolution. Currently @Divy123 and @HarshKhandeparkar are working on this, so I don't know what modifications have to be done while the GSoC timeline

Hi! I am working on gpu.js and it won't be big change. Also is @Divy123 working on this? I didn't know that. Please clarify. This will probably be my last contribution in the next 2 yrs(i will be busy for 2 yrs) so I want to work on it myself.
Gpu.js is not used for enhanced graphics and resolution but for faster speed(performance). I like working in that field and I'm almost done with that. Only thing is that gpu.js isn't supported in nodejs but it will get the support soon and I will open a pr then.

#### Thank You

**Comment by HarshKhandeparkar** [comment]
Please note that I am not participating in GSoC(im not eligible for that).

**Comment by Divy123** [comment]
@HarshKhandeparkar I am not working on gpu.js but on webworkers and webassembly.
Also exploring various libraries that can help us in webgl.
Thanks a lot @HarshKhandeparkar for your outstanding contributions.

**Comment by jywarren** [comment]
And just to clarify - we are perfectly OK with pursuing multiple
optimization strategies at once -- parallel tracks will let us pick and
choose pros and cons since some will work better for some scenarios and
others for other scenarios. Thank you all so much!

**Comment by niravasher** [comment]
@jywarren do you require a switch to GPU.js just to change the speed. I think the modules are fast enough and do not take much time to load.

**Comment by tech4GT** [comment]
Hello @niravasher We are looking at more computationally intensive modules, specifically edge detect. In the future we might have more modules like that.

**Comment by HarshKhandeparkar** [comment]
* when used with hysteresis.

**Comment by niravasher** [comment]
@HarshKhandeparkar @jywarren  correct me if I am wrong GSoC 2019 the only module to be shifted to GPGPU is edgeDetect

**Comment by niravasher** [comment]
In issue #849 you mentioned to change the entire pixelManipulation API to be dependent on GPU. So I thought all the modules are to be shifted to GPU @HarshKhandeparkar

**Comment by HarshKhandeparkar** [comment]
1. changePixel func runs the same task on each pixel.
2. Convolution runs the same task on each module. Wr have 3 modules which convolve a kernel over an image, edgeDetect, blur, convolution

All of these can benefit from gpu.js

**Comment by HarshKhandeparkar** [comment]
Btw, I am going to do this myself so try finding some other issue/idea to add to your proposal. Sorry.

**Comment by niravasher** [comment]
Ok, In the list of real world cases since the particle filtration module is completed, I will make blob region detection module

**Comment by jywarren** [comment]
Hi all - just to mention, we have in the past had multiple people working on the same project in collaboration, either breaking it into 2 parts, or supporting one another, so this is not a problem. Second, we are exploring several parallel tracks for speeding up performance across many different modules; some solutions will work better for some modules, others for different modules. So we are also OK with exploring different optimization paths at the same time -- and the new speed benchmarking code is intended to help us evaluate what speeds up by how much!

Thank you!

**Comment by niravasher** [comment]
Ok, also any ideas about how will we go about the canvas resize module?? @HarshKhandeparkar @jywarren @tech4GT @Divy123

**Comment by HarshKhandeparkar** [comment]
@niravasher do you have any other doubts or should this be closed?

**Comment by niravasher** [comment]
Let it remain for some more time please.

**Comment by HarshKhandeparkar** [comment]
Np. You can keep it open for as long as you like.

**Comment by Harshithpabbati** [comment]
Leave it. So that someone who have doubt about GSoC can ask here.

**Comment by HarshKhandeparkar** [comment]
So should we change the issue name to like GSoC forum?

**Comment by HarshKhandeparkar** [comment]
Also change the issue body?

**Comment by Harshithpabbati** [comment]
Yeah do it.

**Comment by HarshKhandeparkar** [comment]
I don't have time. Can you do that? Also there is no rush. We can do it later whenever we get time but if you have time right now, please do. Thanks.

**Comment by niravasher** [comment]
Do YPAE06 feature in images means the image below?????
![polyshaper](https://user-images.githubusercontent.com/32176296/55460701-3f1f6b80-5610-11e9-9ea2-434248944870.png)

**Comment by HarshKhandeparkar** [comment]
What is YPAE06?

**Comment by niravasher** [comment]
I don't exactly know the fullform. It was in one of the issues. I searched this on internet. I found many results like these polygonal images

**Comment by HarshKhandeparkar** [comment]
Can you please drop a link to the issue?

**Comment by niravasher** [comment]
https://github.com/publiclab/image-sequencer/issues/165

**Comment by HarshKhandeparkar** [comment]
The isue also links to a demo.

**Comment by niravasher** [comment]
It shows me WEBRTC not available. Can i do something?

**Comment by niravasher** [comment]
Infact all the modules show this

**Comment by HarshKhandeparkar** [comment]
It needs a webcam. Try it on ur phone.

**Comment by niravasher** [comment]
I am getting a blue line for all the ideas. It is not loading somehow I think

**Comment by HarshKhandeparkar** [comment]
Try askimg @jywarren or @tech4GT

**Comment by niravasher** [comment]
Also how do we test the modules that are not supported for browsers???

**Comment by HarshKhandeparkar** [comment]
Which modules are not supported for browsers?

**Comment by aashna27** [comment]
@niravasher I tested for text overlay module which works only in browser, https://github.com/publiclab/image-sequencer/pull/943 you can have an idea from here.

**Comment by aashna27** [comment]
Yeah I believe there is one, don't exactly remember which one it was.

**Comment by niravasher** [comment]
I found a module online, compress-image. The functioning was only on CLI.

**Comment by niravasher** [comment]
Thanks @aashna27 , found what I was looking for

**Comment by niravasher** [comment]
There is an issue open in the image sequencer https://github.com/publiclab/image-sequencer/issues/962 . This is the regarding making the geotiff module. I don't have mapknitter installed right now and very little time left with submitting the proposal, could somenone please explain me exactly what to do tn this issue? @jywarren @Harshithpabbati @HarshKhandeparkar , @tech4GT you have opened the issue, can you please help me with this?? @Divy123 do you have any idea on this??

**Comment by tech4GT** [comment]
Hi @niravasher Actually I would be working on that pretty soon, So it is a part of this new mapknitter exporter process that we are building over at https://github.com/publiclab/image-sequencer-app
You can get a bird's eye view about this in this issue https://github.com/publiclab/mapknitter/issues/298

If you would like to help out on that you can read more about geotiff in general and more specifically how we can make one in image sequencer. :smile:
cc @jywarren

**Comment by VibhorCodecianGupta** [comment]
@tech4GT is https://github.com/publiclab/image-sequencer-app an active GSoC project this year? Looks really cool. Could you point me to the prerequisites and future roadmaps for the project? Would love to explore

**Comment by tech4GT** [comment]
I'm not sure about gsoc. I think @jywarren might be able to clarify.
