### ISSUE TITLE
Unordered list of modules

### ISSUE THREAD

**Issue by lohitha02** [publiclab/image-sequencer#969]
The list of the modules have broken out we must arrange it back to normal.

![Screenshot from 2019-04-01 20-25-19](https://user-images.githubusercontent.com/43813629/55337663-be038f80-54bc-11e9-94f6-72631b12ede0.png)

And this is how it looks like 

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by gauravano** [comment]
Hey @lohitha02, would you be solving this or should this be offered as a FTO? Thanks!

**Comment by HarshKhandeparkar** [comment]
@Divy123 might be able to convert this to an fto(probably). Does selectize have an option for ordering options?

**Comment by Harshithpabbati** [comment]
@lohitha02 try to check it once again because I can't reproduce the bug.
check these for reference.
https://sequencer.publiclab.org/examples/#steps=
https://beta.sequencer.publiclab.org/examples/#steps=

**Comment by HarshKhandeparkar** [comment]
Actually there is bo bug in it.

**Comment by Harshithpabbati** [comment]
@HarshKhandeparkar Sorry I edited it and deleted your comment.

**Comment by HarshKhandeparkar** [comment]
The modules are ordered alphabetically instead. Earlier they were ordered how they are ordered in modules.js file. Also the More Modules option which was added at the end.

**Comment by Harshithpabbati** [comment]
Yeah even now every module in module.js is in alphabetical order right???

**Comment by Harshithpabbati** [comment]
I guess she has the older version of IS as she doesn't have the selectize option.

**Comment by Divy123** [comment]
Yes that's the case.
They are arranged alphabetically, so I don't think there is a need to do anything here.

**Comment by HarshKhandeparkar** [comment]
No the modules aren't in alphabetical order.

**Comment by HarshKhandeparkar** [comment]
The most common ones are first.

**Comment by Divy123** [comment]
Let me have a look.

**Comment by Harshithpabbati** [comment]
No. I guess just the more modules option is not in order.

**Comment by HarshKhandeparkar** [comment]
Well it doesn't matter for the modules. We have to atleast fix the more modules option.

**Comment by gauravano** [comment]
Actually, they seem sorted now

**Comment by HarshKhandeparkar** [comment]
Yes they are. But we need to do something to the more modules option.

**Comment by Harshithpabbati** [comment]
Yup making that to the last option.

**Comment by HarshKhandeparkar** [comment]
Instead, can we make it a placeholder?

**Comment by Harshithpabbati** [comment]
Yeah lets remove the option and make it as a value.

**Comment by lohitha02** [comment]
> Hey @lohitha02, would you be solving this or should this be offered as a FTO? Thanks!

We can make this as an FTO :)

**Comment by Divy123** [comment]
Sure! Making this an fto!!

**Comment by HarshKhandeparkar** [comment]
Be sure to use first timers bot.
