### ISSUE TITLE
Service Worker is not working properly

### ISSUE THREAD

**Issue by subhahu123** [publiclab/image-sequencer#972]
### Please describe the problem (or idea)

Checkout out the developer tools you will see an error in application tab
Service worker is showing error 
And when you make it offline and try to reload  it  , not working

**Comment by subhahu123** [comment]
@Harshithpabbati  @HarshKhandeparkar  @gauravano  @publiclab/reviewers  please review

**Comment by HarshKhandeparkar** [comment]
Fixed in #976
