### ISSUE TITLE
Input from saturation module.

### ISSUE THREAD

**Issue by harshithpabbati** [publiclab/image-sequencer#973]
### Why does it append different type of inputs to take the level.
![Screenshot_20190402-002839](https://user-images.githubusercontent.com/43822585/55352833-688caa00-54df-11e9-9405-2bd999b0d9e8.jpg)
See it is giving the bar and even the integer format for taking input.

**Comment by HarshKhandeparkar** [comment]
Just check if it is a browser problem

**Comment by Harshithpabbati** [comment]
No I am using chrome updated version.

**Comment by HarshKhandeparkar** [comment]
I think the panel ui broke it?

**Comment by HarshKhandeparkar** [comment]
Didn't happen before

![saturation](https://user-images.githubusercontent.com/34770591/55429225-9b4ea500-55a8-11e9-8d93-691568da94a8.png)

**Comment by HarshKhandeparkar** [comment]
Sorry, wrong screenshot

**Comment by Harshithpabbati** [comment]
It wasn't by UI i guess.

**Comment by Harshithpabbati** [comment]
It's happening only few times.

**Comment by HarshKhandeparkar** [comment]
Can you please check if there is any error log?

**Comment by Harshithpabbati** [comment]
Sorry I am using mobile. I can't do it now.

**Comment by HarshKhandeparkar** [comment]
Ok np. Let's check it out tmrw.

**Comment by HarshKhandeparkar** [comment]
GN.

**Comment by Harshithpabbati** [comment]
GN

**Comment by Divy123** [comment]
@Harshithpabbati can you elaborate a bit here on what the issue is?

**Comment by Harshithpabbati** [comment]
See the input method. We are having two types in the same module one time we are getting the input box and other time a bar.

**Comment by Harshithpabbati** [comment]
Check the input method in the image which I provided.

**Comment by HarshKhandeparkar** [comment]
Fixed elsewhere
