### ISSUE TITLE
 Document Does Not Have A Meta Description

### ISSUE THREAD

**Issue by Divy123** [publiclab/image-sequencer#978]
### Please describe the problem (or idea)
The Lighthouse says that the document does not have a meta description 
> What happened just before the problem occurred? Or what problem could this idea solve?

For SEO, we should add desciption to the head of our index.html.
Example https://developers.google.com/web/tools/lighthouse/audits/description

**Comment by Harshithpabbati** [comment]
We have it right?

**Comment by gauravano** [comment]
We have meta tag only. Refer https://github.com/publiclab/leaflet-environmental-layers/pull/130. Also, @Divy123 would you like to work on this one?

Thanks!

**Comment by Divy123** [comment]
Thanks Gaurav! Would love to work upon it.
Will send a PR soon.

**Comment by Divy123** [comment]
@jywarren @gauravano this is something I am going to add as a meta description.
<meta name="Description" content="Image Sequencer is an image editing tool that creates a new downloadble image at each step.It works in browser and supports both node and CLI.">
<meta name="Keywords" content="image editing downloadable browser node CLI">
What do you think upon this?

**Comment by Divy123** [comment]
@jywarren please have a look.
This is a small but a very important change. Would send a PR as soon as possible then.
