### ISSUE TITLE
Drag to select crop UI is broken

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#987]
#205 added this nice interface for cropping -- drag selection -- and #229 was supposed to build on this. However it seems broken now -- 

![image](https://user-images.githubusercontent.com/24359/55590189-35753100-5700-11e9-8999-4e6a750f672b.png)

Looks like we're running `imgAreaSelect` on `imgEl` here:

https://github.com/publiclab/image-sequencer/blob/0e7323efa928972bfa26fd360bc616402b3e9957/src/modules/Crop/Ui.js#L74-L77

But `sequencer.steps[1].imgElement` doesn't return anything anymore.  It's supposed to be set here:

https://github.com/publiclab/image-sequencer/blob/985c67847e135806d99798f6f62cf7d7926e971f/examples/lib/defaultHtmlStepUi.js#L71

And `$("a img.img-thumbnail");` still returns elements, so that /should/ work...

Did I break it here? 

https://github.com/publiclab/image-sequencer/pull/960/files#diff-8fab943ef984aa24b7a63cbe4442daeaR71

Would love help fixing this! Then we should write a UI test for it -- send a click event to the image, and ensure that a selection box appears.

**Comment by VibhorCodecianGupta** [comment]
Looking into this and other relevant crop module issues.
