### ISSUE TITLE
Please Help Me

### ISSUE THREAD

**Issue by HarshKhandeparkar** [publiclab/image-sequencer#988]
@jywarren I wanted to tell you something important. My exams will end on 15th April. I will start proper contributions after that. My last day will be 13th May after which I won't be able to contribute for 2 yrs. Could you please try to merge my currently open prs(except ui code refactor) before 15th April. I have also undertaken the task of gpu acceleration and gif manipulation. These are relatively easy tasks but I cannot complete them right now. So please try to merge my open prs before 15th april so that I can work on the remaining ones.
Also I will add tests for modules as I had promised you.

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by HarshKhandeparkar** [comment]
@jywarren @publiclab/is-reviewers please see this. Sorry if opening an issue was inappropriate.

**Comment by jywarren** [comment]
Hello @HarshKhandeparkar!!! No worries, and sorry to tag you on anything that stressed you out. Our very best wishes for your exams, and we'll take a look at your open PRs today. 

https://github.com/publiclab/image-sequencer/pulls/HarshKhandeparkar

**Comment by HarshKhandeparkar** [comment]
Thanks a ton for your help @jywarren. I am extremely grateful. :heart:

**Comment by Divy123** [comment]
@HarshKhandeparkar please tell in case you need any kind of help.
Would be lot more than happy to help you.
