### ISSUE TITLE
Make the API Documentation using Swagger

### ISSUE THREAD

**Issue by ccpandhare** [publiclab/image-sequencer#99]
I realized that Image Sequencer has grown a lot already and there is a need of clear documentations. I found a framework [Swagger](https://swagger.io/) which is meant to manage API development. We can write clearer documentation using Swagger.

There are a few alternatives too such as [DapperDox](https://dapperdox.io/) and [ReDoc](https://github.com/Rebilly/ReDoc)

What do you think about all this @jywarren ?

**Comment by jywarren** [comment]
I think this is a big project, and maybe we could make a well-documented
issue for it, and propose breaking it into smaller parts that can be done
one at a time? But I like how you're thinking about it.

**Comment by HarshKhandeparkar** [comment]
#753

**Comment by HarshKhandeparkar** [comment]
#753
