### ISSUE TITLE
Bugs in Text overlay module

### ISSUE THREAD

**Issue by lohitha02** [publiclab/image-sequencer#990]
Text overlay is working only for the first step
![Screenshot from 2019-04-05 14-11-05](https://user-images.githubusercontent.com/43813629/55615342-d91c1b00-57ac-11e9-9d65-2c030e05e97e.png)

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by Divy123** [comment]
I would love to work on this.
