### ISSUE TITLE
Unordered list of modules

### ISSUE THREAD

**Issue by Divy123** [publiclab/image-sequencer#992]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/image-sequencer/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.
Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

**To Do**: There is an open pr #710 which adds a helper method called `scopeQuery` to image-sequencer demo code. You have to document it in the CONTRIBUTING.md file.

### 📋 Step by Step
- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [CONTRIBUTING.md](https://github.com/publiclab/image-sequencer/blob/main/CONTRIBUTING.md) in the `image-sequencer` repository (press the little pen Icon) and edit the line as shown below. 

Have a look here:
![fto](https://user-images.githubusercontent.com/31225007/55653806-452e6b80-580d-11e9-8d37-511a02028ecc.png)
The "More Modules" option has to be removed and rather can be a made a value for select.
The files to be looked into are:
https://github.com/publiclab/image-sequencer/blob/main/examples/demo.js
https://github.com/publiclab/image-sequencer/blob/main/examples/lib/intermediateHtmlStepUi.js
 And something to help out is :
https://stackoverflow.com/questions/21962124/how-to-set-a-value-for-a-selectize-js-input

- [ ] 💾 **Commit** your changes
- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review
### Please keep us updated
💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?
🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by teisenhower** [comment]
I'll take this one if that's ok!

**Comment by jywarren** [comment]
That'd be great, thanks!!!

**Comment by teisenhower** [comment]
Perfect! I'll get started tomorrow morning.

Thanks!

**Comment by teisenhower** [comment]
@jywarren Starting to dive into this. Just want to make sure I am on the right page. What is it you are looking to have done with this? 

Thanks!

**Comment by teisenhower** [comment]
@jywarren Hey! Making sure I am on the right page. You wanted the "More Modules" option removed from the drop down correct? So the drop down defaults to the first option "Add QR"

![moreModules](https://user-images.githubusercontent.com/47988669/55670266-52b91500-5850-11e9-8106-7396f2053cd5.png)


![moreModules2](https://user-images.githubusercontent.com/47988669/55670277-73816a80-5850-11e9-959d-0201970eb395.png)

**Comment by HarshKhandeparkar** [comment]
:+1: great work!

**Comment by teisenhower** [comment]
@HarshKhandeparkar **Thanks!** I'm hoping this is what you all were looking for!

**Comment by HarshKhandeparkar** [comment]
Yes we were kind of. One last thing, can you add a placeholder text to it?

**Comment by teisenhower** [comment]
@HarshKhandeparkar Sure! Something like this? 

![moreModulesPlaceholder](https://user-images.githubusercontent.com/47988669/55670438-433acb80-5852-11e9-94c6-bed4c2035ab0.png)

**Comment by HarshKhandeparkar** [comment]
Perfect. Can you change the placeholder text as well?

**Comment by teisenhower** [comment]
@Harshithpabbati Absolutely! What would you like it to say?

**Comment by HarshKhandeparkar** [comment]
Something like "Select A Module" or "Select Modules" or "More Modules...". Whichever you think would best fit. You can add something of your own too. Awesome work!!

**Comment by Harshithpabbati** [comment]
Change the place holder name to more modules ....

**Comment by teisenhower** [comment]
@HarshKhandeparkar Thank you! 

I changed it to "Select A Module" as that seems to best fit what the user is doing. But I can of course make it whatever. 

![placeholderUpdate](https://user-images.githubusercontent.com/47988669/55670509-41bdd300-5853-11e9-9795-3b87be3386db.png)

**Comment by HarshKhandeparkar** [comment]
Great! Are you going to open PR (pull request) now? Thanks.

**Comment by teisenhower** [comment]
Yep! I can do that now. 

Thanks!

**Comment by HarshKhandeparkar** [comment]
You can open a pr and mention me.

**Comment by teisenhower** [comment]
@HarshKhandeparkar PR Submitted

**Comment by Harshithpabbati** [comment]
@teisenhower make the capital A to small a.

**Comment by teisenhower** [comment]
@Harshithpabbati Sure no problem

@HarshKhandeparkar  Should I make this change and then submit another PR?

Thanks!

**Comment by Harshithpabbati** [comment]
Update this pr.

**Comment by HarshKhandeparkar** [comment]
You can commit to the same branch.

**Comment by teisenhower** [comment]
new commit pushed. Now a lowercase 'a'

Thanks!
