### ISSUE TITLE
Image is getting deleted after clicking enter

### ISSUE THREAD

**Issue by lohitha02** [publiclab/image-sequencer#997]
The image is getting deleted after entering the changes and click enter.
Instead the changes should get applied to the image and not get deleted.

![Screenshot from 2019-04-07 17-36-26](https://user-images.githubusercontent.com/43813629/55683294-bda34280-595b-11e9-8195-eedfec857711.png)

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by HarshKhandeparkar** [comment]
@Harshithpabbati

**Comment by HarshKhandeparkar** [comment]
Bootstrap penel problem I guess.

**Comment by Harshithpabbati** [comment]
yeah but how to override the function, I don't know how it happened.

**Comment by HarshKhandeparkar** [comment]
Is the delete button inside the form?

**Comment by Harshithpabbati** [comment]
yeah i guess.

**Comment by Harshithpabbati** [comment]
Fine i will make it correct i will change it.
