### ISSUE TITLE
Bugs in blur module 

### ISSUE THREAD

**Issue by lohitha02** [publiclab/image-sequencer#998]
The amount of gaussian blur is not changing even after changing the intensity value.

![blur](https://user-images.githubusercontent.com/43813629/55686318-51d1d180-597d-11e9-9ead-35cb0939e031.jpg)

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by HarshKhandeparkar** [comment]
I'll handle this in gpu.js PR.
